### ISSUE TITLE
Pithos fetches only part of the stream

### ISSUE THREAD

**Issue by vaibhavbhat16** [pithos/pithos#102]
Hi,
I'm facing a very weird issue. Pithos was working fine all day. All of a sudden, it started picking up only 42seconds of the stream being played and there's no audio output. I changed the songs, closed and reopened Pithos but it persists. 
The audio works fine, played songs with RhythmBox to confirm. The internet connection is also fine.
![pithosbug](https://cloud.githubusercontent.com/assets/5325553/2937712/b2fce3aa-d8c7-11e3-8419-df3ead6d56b2.png)

**Comment by gregsheremeta** [comment]
Definitely not supporting 0.3 series anymore. Thanks!
