### ISSUE TITLE
Stuck in ad-fetching loop?

### ISSUE THREAD

**Issue by patrick-brian-mooney** [pithos/pithos#106]
Over the last day or so, I've noticed that Pithos will sometimes fetch a song that I expect to be longer than a minute, but the song length is 0:42. I assume this means that an ad is being fetched instead (and I understand why Pandora represents it as a real song to Pithos). However, once the 0:42-long song starts playing, it's just silence, and then the next song is also 0:42 long. Logging into the Pandora website fixes the problem ... for a few songs.

**Comment by gregsheremeta** [comment]
Haven't heard of this happening anymore. At any rate, it was a server problem and nothing we could control.
