### ISSUE TITLE
Constant buffering

### ISSUE THREAD

**Issue by jamesdcarroll** [pithos/pithos#113]
Pithos constantly buffers songs.  Play a few seconds, buffer. Play a few seconds, buffer. Play a few seconds, buffer.  Sometimes I'll get through an entire song without it happening, but then it will do it again. 

Ubuntu 14.04
Pithos 1.0.0
Pandora One account

Tried installing via PPA instructions as well as Ubuntu Software Center with apt-get purge pithos prior to each.

**Comment by jawbonegroove** [comment]
i've also been having this problem for some time. buffering alternates between 0 and 1% indefinitely.

**Comment by BrandonDusseau** [comment]
I'm having this issue on Pithos 1.0.1 as well.

**Comment by JonathanRRogers** [comment]
I subscribed to Pandora One and am using Pithos 1.0.1 from the PPA  on Ubuntu 14.04.2 LTS. I used to have a lot of buffering pauses before #44. After that everything seemed to work great for a while. However, recently, I've been experiencing more buffering problems again.

Often, Pithos stops playing and says that it's buffering without updating the buffer fill percentage. If I take no action, it will remain in that state indefinitely AFAICT. Hitting pause and then play will result in less than a second of audio playing before Pithos goes back to the stuck buffer filling state. If I tell Pithos to skip the song or switch stations, it will load a different song and play without trouble, leading me to believe that this is primarily a problem with Pithos rather than Pandora.

**Comment by Hackswell** [comment]
My problems are similar.  It gets stuck buffering on song start.  Takes 2-5 minutes to buffer the song, but then plays the full song... until the next song's start delay.

**Comment by emmainvincible** [comment]
I am also experiencing this problem. Running latest pithos-git package from the AUR. I've found that if, at the beginning of a song, I pause and unpause, the song will play fine, though the buffering will be reported as 0% or 1% for most of the duration of the song.

**Comment by gregsheremeta** [comment]
@emmainvincible @Hackswell or anyone else interested, are you comfortable running from source?

If so, could you run this exact commit and see if it solves the problem for you? (note that it's on a fork)
https://github.com/JasonLG1979/pithos/commit/e8eab2252b539684d8375442cfc0cb27f071e676

**Comment by JasonLG1979** [comment]
I've never had buffering issues with my Pandora One account but I have 2 other non-Pandora One accounts that I use for testing. My observation is that Pandora throttles free accounts/aac streams. With a free account if you skip songs/change stations to often even if Pandora allows you to retrieve new playlists it will throttle the connection to barely a trickle(not enough to fill the buffer) Here's a video of one of my test accounts after I abused it for a while. You'll notice the network traffic is near nonexistent. Switching to one of my other accounts and the problem disappears. Note that I have a very stable 50Mbps internet connection. The solution would be either to get a Pandora One account and use the mp3 stream or have multiple free accounts that you can rotate them if you notice a buffering issue.           

https://www.youtube.com/watch?v=bc_0p32h1uw

**Comment by scottkosty** [comment]
I have a Pandora One account also. Haven't tested on a free account for a while.

Jason, does the throttling go back to normal after a while? If so, is this a matter of hours or days?

**Comment by JasonLG1979** [comment]
I'm not sure how long it takes before everything returns to normal. I'd hope no longer than 24hrs?

**Comment by JasonLG1979** [comment]
I think the general consensus is that skipping songs ticks Pandora off. Do it sparingly.

**Comment by scottkosty** [comment]
OK. So to know whether this is the underlying reason that everyone in this thread is seeing, they should test not skipping songs for a couple of days and see if the behavior goes back to normal.

The OP has a Pandora One account though. Maybe that was a different issue, or the account was not recognized as One, or the OP did many skips and that ticks Pandora off even for One accounts.

**Comment by JasonLG1979** [comment]
Even Pandora One accounts have skip limits. They're just higher than free accounts.

**Comment by JasonLG1979** [comment]
Regardless if it's not Pandora causing the problem then it's gstreamer(I don't think it's gstreamer based on network traffic) Pithos doesn't do anything very fancy when it comes to buffering. Gstreamer sends a signal when the buffer is less than 100% Pithos pauses the pipeline until the buffer reaches 100%.

**Comment by scottkosty** [comment]
Good to know. Thanks for the diagnosis!

**Comment by JasonLG1979** [comment]
I'm working with @glennimoss to improve the player logic and then Glenn's going to split the player logic out from the UI logic. In the branch on my fork I've made a few changes(for the better IMHO) eventually they may find their way into the main branch after they've been tested. If you'd like to you can check it out.

**Comment by scottkosty** [comment]
I really appreciate that work, Jason. The number of things I'm currently testing is past my normal limit so I'm going to hold off on this one.

**Comment by gregsheremeta** [comment]
1.0.2 and 1.1.0 made a change to the way pithos buffers. Can everyone affected by this please upgrade and report back?

**Comment by gregsheremeta** [comment]
> 1.0.2 and 1.1.0 made a change to the way pithos buffers. Can everyone affected by this please upgrade and report back?

Closing. Feel free to reopen if there the problem persists.

**Comment by stevekuznetsov** [comment]
Having this issue today - Pandora One account, no issues for the last two weeks. 
Running Fedora 22.

**Comment by gregsheremeta** [comment]
@stevekuznetsov (hello fellow Red-Hatter)

Can you run pithos from source with debug logging enabled and post the buffering logs when it's doing this?

```
git clone http://github.com/pithos/pithos.git
cd pithos
python3 -m pithos -vv
```

Logs will look like this:

```
INFO - pithos:start_song:463 - Starting song: index = 0
INFO - pandora:audioUrl:370 - Using audio quality highQuality: 192 mp3
DEBUG - pithos:on_gst_buffering:728 - Buffering (1%)
DEBUG - pithos:on_gst_buffering:728 - Buffering (2%)
DEBUG - pithos:on_gst_buffering:728 - Buffering (100%)
DEBUG - pithos:on_gst_buffering:738 - Buffer 100%. Song starting
DEBUG - pithos:handler:685 - Found tag "bitrate" in stream: "192000" (type: <class 'int'>)
DEBUG - pithos:handler:685 - Found tag "audio-codec" in stream: "MPEG 1 Audio, Layer 3 (MP3)" (type: <class 'str'>)
INFO - pithos:check_if_song_is_ad:711 - Not an Ad..
```

I want to see if you're just hitting underruns, or if it's something else.

**Comment by stevekuznetsov** [comment]
@gregsheremeta Hello from the Tower! I tried restarting Pithos a couple of times, then Fedora, then I got fed up and mashed the skip button maybe five times. This caused the buffering issue to go away. I wish it hadn't so I could share the logs with you - if it comes up again I will do so.

**Comment by stevekuznetsov** [comment]
@gregsheremeta After some digging I found a notice from Pandora saying I had been streaming on multiple devices - I've noticed that Pithos doesn't stop the stream when I lock my computer, so that stream had not ended before I started one on another machine. I think you may be able to close this issue again, as I'm certain the throttling was due to that: 
>If our system detects your account streaming on multiple devices at the same time, you may be notified with an audio and/or display message that pauses all active streams.

**Comment by jawbonegroove** [comment]
i'll throw some debug logs at whoever wants them. i don't think it's related to paid subscription, i've had the problem both ways.

**Comment by gregsheremeta** [comment]
@jawbonegroove yes, please post some logs. You can use a pastebin and link here.

**Comment by yku-yku** [comment]
Hi,
First of all, thank you for the application.

Ubuntu 15.04; Running pithos (1.1.1) from the src cloned today (Jun 24) from http://github.com/pithos/pithos.git
I do a lot of skips when I listen the music... And I don't think I have pandora one account.

Problem:
when I start the pithos or it goes to the next song or I skip the song, I have the pause issue that looks similar to this one. UI is showing "Buffering (0%)" and if I:
1. wait for about ~3 or 5 minutes it start the playback automatically, and Buffering message goes away.
2. press pause/play, it starts the playback immediately, but the "Buffering (0%)" message stays.

here are some logs from the following command "python3 -m pithos -vv":

INFO - pithos:start_song:516 - Starting song: index = 0
INFO - pandora:audioUrl:372 - Using audio quality mediumQuality: 64 aacplus
DEBUG - pithos:handler:761 - Found tag "datetime" in stream: "2009-03-05T11:51:13Z" (type: <class 'str'>)
DEBUG - pithos:handler:761 - Found tag "container-format" in stream: "ISO MP4/M4A" (type: <class 'str'>)
DEBUG - pithos:handler:761 - Found tag "audio-codec" in stream: "MPEG-4 AAC" (type: <class 'str'>)
DEBUG - pithos:handler:761 - Found tag "maximum-bitrate" in stream: "64000" (type: <class 'int'>)
DEBUG - pithos:handler:761 - Found tag "bitrate" in stream: "64000" (type: <class 'int'>)
DEBUG - pithos:on_gst_async_done:697 - on_gst_async_done
INFO - pithos:check_if_song_is_ad:777 - Not an Ad..
DEBUG - pithos:on_gst_buffering:796 - Buffering (9%)
DEBUG - pithos:on_gst_buffering:796 - Buffering (0%)
DEBUG - pithos:on_gst_buffering:796 - Buffering (9%)
DEBUG - pithos:on_gst_buffering:796 - Buffering (0%)
DEBUG - pithos:on_gst_buffering:796 - Buffering (9%)
DEBUG - pithos:on_gst_buffering:796 - Buffering (0%)
DEBUG - pithos:on_gst_buffering:796 - Buffering (9%)
DEBUG - pithos:on_gst_buffering:796 - Buffering (0%)
DEBUG - pithos:on_gst_buffering:796 - Buffering (9%)
DEBUG - pithos:on_gst_buffering:796 - Buffering (0%)
DEBUG - pithos:on_gst_buffering:796 - Buffering (9%)
DEBUG - pithos:on_gst_buffering:796 - Buffering (0%)
DEBUG - pithos:on_gst_buffering:796 - Buffering (9%)
DEBUG - pithos:on_gst_buffering:796 - Buffering (0%)
DEBUG - pithos:on_gst_buffering:796 - Buffering (9%)
DEBUG - pithos:on_gst_buffering:796 - Buffering (0%)
DEBUG - pithos:on_gst_buffering:796 - Buffering (9%)
DEBUG - pithos:on_gst_buffering:796 - Buffering (0%)
DEBUG - pithos:on_gst_buffering:796 - Buffering (9%)
DEBUG - pithos:on_gst_buffering:796 - Buffering (0%)
DEBUG - pithos:on_gst_buffering:796 - Buffering (9%)
DEBUG - pithos:on_gst_buffering:796 - Buffering (0%)
DEBUG - pithos:on_gst_buffering:796 - Buffering (9%)
DEBUG - pithos:on_gst_buffering:796 - Buffering (0%)
DEBUG - pithos:on_gst_buffering:796 - Buffering (9%)
DEBUG - pithos:on_gst_buffering:796 - Buffering (0%)
DEBUG - pithos:on_gst_buffering:796 - Buffering (9%)
DEBUG - pithos:on_gst_buffering:796 - Buffering (0%)
DEBUG - pithos:on_gst_buffering:796 - Buffering (9%)
DEBUG - pithos:on_gst_buffering:796 - Buffering (0%)
DEBUG - pithos:on_gst_buffering:796 - Buffering (16%)
DEBUG - pithos:on_gst_buffering:796 - Buffering (0%)
INFO - pithos:art_callback:600 - Downloaded album art for 0
INFO - pithos:art_callback:600 - Downloaded album art for 1
INFO - pithos:art_callback:600 - Downloaded album art for 2
INFO - pithos:art_callback:600 - Downloaded album art for 3
DEBUG - pithos:on_gst_buffering:796 - Buffering (9%)
DEBUG - pithos:on_gst_buffering:796 - Buffering (0%)
DEBUG - pithos:on_gst_buffering:796 - Buffering (9%)
DEBUG - pithos:on_gst_buffering:796 - Buffering (0%)
DEBUG - pithos:on_gst_buffering:796 - Buffering (9%)
DEBUG - pithos:on_gst_buffering:796 - Buffering (0%)
DEBUG - pithos:on_gst_buffering:796 - Buffering (9%)
DEBUG - pithos:on_gst_buffering:796 - Buffering (0%)
DEBUG - pithos:on_gst_buffering:796 - Buffering (9%)
DEBUG - pithos:on_gst_buffering:796 - Buffering (0%)
DEBUG - pithos:on_gst_buffering:796 - Buffering (18%)
DEBUG - pithos:on_gst_buffering:796 - Buffering (0%)
DEBUG - pithos:on_gst_buffering:796 - Buffering (0%)
DEBUG - pithos:on_gst_buffering:796 - Buffering (18%)
DEBUG - pithos:on_gst_buffering:796 - Buffering (0%)
....
and so on and so on until it starts playback at some point:
....
DEBUG - pithos:on_gst_buffering:796 - Buffering (0%)
DEBUG - pithos:on_gst_buffering:796 - Buffering (3%)
DEBUG - pithos:on_gst_buffering:796 - Buffering (0%)
DEBUG - pithos:on_gst_buffering:796 - Buffering (100%)
DEBUG - pithos:on_gst_buffering:807 - Buffer 100%. Song starting
DEBUG - pithos:handler:761 - Found tag "audio-codec" in stream: "MPEG-4 AAC" (type: <class 'str'>)
DEBUG - pithos:handler:761 - Found tag "maximum-bitrate" in stream: "64000" (type: <class 'int'>)
DEBUG - pithos:handler:761 - Found tag "bitrate" in stream: "64000" (type: <class 'int'>)
DEBUG - pithos:handler:761 - Found tag "minimum-bitrate" in stream: "84582" (type: <class 'int'>)
DEBUG - pithos:handler:761 - Found tag "audio-codec" in stream: "MPEG-4 AAC" (type: <class 'str'>)
DEBUG - pithos:handler:761 - Found tag "maximum-bitrate" in stream: "64000" (type: <class 'int'>)
DEBUG - pithos:handler:761 - Found tag "bitrate" in stream: "64000" (type: <class 'int'>)
DEBUG - pithos:handler:761 - Found tag "minimum-bitrate" in stream: "73040" (type: <class 'int'>)
DEBUG - pithos:handler:761 - Found tag "audio-codec" in stream: "MPEG-4 AAC" (type: <class 'str'>)
DEBUG - pithos:handler:761 - Found tag "maximum-bitrate" in stream: "64000" (type: <class 'int'>)
DEBUG - pithos:handler:761 - Found tag "bitrate" in stream: "64000" (type: <class 'int'>)
DEBUG - pithos:handler:761 - Found tag "minimum-bitrate" in stream: "71145" (type: <class 'int'>)
DEBUG - pithos:handler:761 - Found tag "audio-codec" in stream: "MPEG-4 AAC" (type: <class 'str'>)
DEBUG - pithos:handler:761 - Found tag "maximum-bitrate" in stream: "64000" (type: <class 'int'>)
DEBUG - pithos:handler:761 - Found tag "bitrate" in stream: "64000" (type: <class 'int'>)
DEBUG - pithos:handler:761 - Found tag "minimum-bitrate" in stream: "70801" (type: <class 'int'>)
DEBUG - pithos:handler:761 - Found tag "audio-codec" in stream: "MPEG-4 AAC" (type: <class 'str'>)
DEBUG - pithos:handler:761 - Found tag "maximum-bitrate" in stream: "64000" (type: <class 'int'>)
DEBUG - pithos:handler:761 - Found tag "bitrate" in stream: "64000" (type: <class 'int'>)
DEBUG - pithos:handler:761 - Found tag "minimum-bitrate" in stream: "67528" (type: <class 'int'>)
DEBUG - pithos:handler:761 - Found tag "audio-codec" in stream: "MPEG-4 AAC" (type: <class 'str'>)
DEBUG - pithos:handler:761 - Found tag "maximum-bitrate" in stream: "64000" (type: <class 'int'>)
DEBUG - pithos:handler:761 - Found tag "bitrate" in stream: "64000" (type: <class 'int'>)
DEBUG - pithos:handler:761 - Found tag "minimum-bitrate" in stream: "65633" (type: <class 'int'>)
DEBUG - pithos:handler:761 - Found tag "audio-codec" in stream: "MPEG-4 AAC" (type: <class 'str'>)
DEBUG - pithos:handler:761 - Found tag "maximum-bitrate" in stream: "64000" (type: <class 'int'>)
DEBUG - pithos:handler:761 - Found tag "bitrate" in stream: "64000" (type: <class 'int'>)
DEBUG - pithos:handler:761 - Found tag "minimum-bitrate" in stream: "63221" (type: <class 'int'>)
DEBUG - pithos:handler:761 - Found tag "audio-codec" in stream: "MPEG-4 AAC" (type: <class 'str'>)
DEBUG - pithos:handler:761 - Found tag "maximum-bitrate" in stream: "64000" (type: <class 'int'>)
DEBUG - pithos:handler:761 - Found tag "bitrate" in stream: "64000" (type: <class 'int'>)
DEBUG - pithos:handler:761 - Found tag "minimum-bitrate" in stream: "62876" (type: <class 'int'>)
DEBUG - pithos:handler:761 - Found tag "audio-codec" in stream: "MPEG-4 AAC" (type: <class 'str'>)
DEBUG - pithos:handler:761 - Found tag "maximum-bitrate" in stream: "64000" (type: <class 'int'>)
DEBUG - pithos:handler:761 - Found tag "bitrate" in stream: "64000" (type: <class 'int'>)
DEBUG - pithos:handler:761 - Found tag "minimum-bitrate" in stream: "59776" (type: <class 'int'>)
DEBUG - pithos:handler:761 - Found tag "audio-codec" in stream: "MPEG-4 AAC" (type: <class 'str'>)
DEBUG - pithos:handler:761 - Found tag "maximum-bitrate" in stream: "64000" (type: <class 'int'>)
DEBUG - pithos:handler:761 - Found tag "bitrate" in stream: "64000" (type: <class 'int'>)
DEBUG - pithos:handler:761 - Found tag "minimum-bitrate" in stream: "50818" (type: <class 'int'>)
DEBUG - pithos:handler:761 - Found tag "audio-codec" in stream: "MPEG-4 AAC" (type: <class 'str'>)
DEBUG - pithos:handler:761 - Found tag "maximum-bitrate" in stream: "64000" (type: <class 'int'>)
DEBUG - pithos:handler:761 - Found tag "bitrate" in stream: "64000" (type: <class 'int'>)
DEBUG - pithos:handler:761 - Found tag "minimum-bitrate" in stream: "49784" (type: <class 'int'>)

I can upload the file with more logs if needed.
How I can help? I'm a developer, but would like to have some starting point for the troubleshooting/debugging vs trying to understand the whole application and debug by myself...

Thank you.
Yura.

**Comment by gregsheremeta** [comment]
@yku-yku Thanks for the log. Pandora's servers got angry at you and are severely throttling your account. We've noticed that lots of skipping tends to induce it. And they also seem less forgiving of non-One users. According to the log, the software is working perfectly. (Well, the buffering progression could be a little nicer for AAC streams, but that's a known gstreamer issue and out of our hands.)

My advice would be to skip less, buy Pandora One, or maybe try a new account and/or proxy server.

**Comment by gregsheremeta** [comment]
Closing, since it seems no more software issues have been reported on this.

**Comment by scottkosty** [comment]
Greg, is it possible to detect if Pandora is throttling? Perhaps we could give a warning message to the user if we detect this? My guess is that we cannot detect it, but thought I'd ask nonetheless.

**Comment by gregsheremeta** [comment]
> is it possible to detect if Pandora is throttling?

There's no setting we can read from them, afaik. We could guess we're being throttled by the fact that the song takes longer than XX seconds to initially buffer.

> Perhaps we could give a warning message to the user if we detect this

Not a bad idea for a feature. @JasonLG1979 might be interested in implementing something like that.

**Comment by scottkosty** [comment]
Thanks for the quick reply Greg. I opened #222 for this.

**Comment by glennimoss** [comment]
One thing to note about the throttling: In my experimentation the they throttle you to almost exactly the playback bitrate. So if buffering were to work properly (in my opinion it doesn't) then even with throttling you shouldn't have much interruption. However due to the way buffering does work right now, it effectively takes the entire playtime of the song to fill the buffer before playback occurs.

**Comment by JasonLG1979** [comment]
> Not a bad idea for a feature. @JasonLG1979 might be interested in implementing something like that.

I really don't think it's anything that we really need to detect. If it's happening you'll know. The same rules as the web interface apply to Pithos. If you skip too many songs it pisses Pandora off and they throttle you. Just don't skip a bunch of songs especially if you're listening with a free account. If you skip WAY too many songs you'll just get plain old booted for so many hours.(just like the web interface) There's already a warning message for that. Something to the effect that you've requested too many playlists, try back later. PIthos is a frontend to Pandora they control the content and the stream It doesn't magically allow you to break Pandora's rules. If you want to be able to skip more songs pay for a Pandora One account.
