### ISSUE TITLE
Commercial advertisements on every song

### ISSUE THREAD

**Issue by AlbinoCookie** [pithos/pithos#120]
For some reason if I skip a song on a station, the next song's tittle turns into "commercial advertisements" and the song won't play, and usually one or two songs after that won't play. Using pithos 1.0.0 ubuntu 14.04.

![screenshot from 2014-07-30 21 40 26](https://cloud.githubusercontent.com/assets/1955065/3758955/b1101a8c-1853-11e4-96ed-d026c43bb505.png)

**Comment by gregsheremeta** [comment]
We're pretty sure Pandora's servers get angry when songs are skipped, and this kind of stuff happens. I've tried reaching out to Pandora developers to ask about it, but they're not interested in working with us.

When this happens, you just need to wait out the cool-down period.

Thanks!
