### ISSUE TITLE
Do not treat notification as "message"

### ISSUE THREAD

**Issue by Sammidysam** [pithos/pithos#132]
When a new song plays in Pithos, it is treated as the same kind of notification as a new chat message, i.e. when you go to the Activities menu of GNOME Shell it will display a "1 new message" prompt at the bottom that you need to select the Pithos window to remove.  This is kind of annoying, as when a new song is playing I don't feel like it is such important news as to give me a notification to go to the Pithos window.  For example, Rhythmbox does not display its new notifications as a "new message", but it still displays a notification.  It would be nice if Pithos could follow suit.  It is probably just an option to the notification creation somewhere (my guess).

I am in Fedora 20 running this package https://github.com/pithos/pithos/issues/129#issuecomment-56295859 made for Pithos 1.0.1.

**Comment by Sammidysam** [comment]
Either the new version of Fedora and subsequently GNOME or the new versions of Pithos cause this problem to not happen anymore.

**Comment by TingPing** [comment]
Yes 3.16 redid a lot of notification related UI.
