### ISSUE TITLE
Pithos keeps showing 3gp codec error.

### ISSUE THREAD

**Issue by aFoxNamedMorris** [pithos/pithos#147]
Heya. I'm on Xubuntu 14.04 64-bit. I updated Pithos to the latest from the PPA and when I start it, it logs me in, tries to load a track, then tells me I don't have a 3gp codec. I have the restricted extras, as well as a massive assortment of audio/video plugins and codecs but it still refuses to play anything. I had to downgrade to an older version for it to work again. I can grab any information you might need.

**Comment by aFoxNamedMorris** [comment]
Still having this issue. Is the project dead?

**Comment by gregsheremeta** [comment]
It's not dead. If I may be frank, you were kind of mean to the people who volunteer their time on this project, and I don't feel compelled to install Xubuntu to try to help you.

See if you get the same issue using gst-launch.
gst-launch-1.0 playbin uri=<pandora mp3 url>

Pithos may be different from most media players in that we use gstreamer playbin. The downside of that is we have no control over what plugins gstreamer asks for. For some reason it thinks it needs 3gp on your machine.

The fix will probably involve not using playbin anymore, which is a lot of work.

**Comment by aFoxNamedMorris** [comment]
Yes, looking back... I'd have kept my cool. I am truly sorry for the drama and the disrespect. I promise that I will be calm, compliant, and respectful from here on out.

**Comment by gregsheremeta** [comment]
Good man. I appreciate that. :beer:

**Comment by aFoxNamedMorris** [comment]
Since then, I passed a linux pre-certification test, and became a beta tester for two games that are working on Linux support. If I can be of any assistance, just holler. No room for my former childish tantrums in my line of work. Crazy world, huh?

**Comment by gregsheremeta** [comment]
Awesome! Beta testing games must be cool

**Comment by aFoxNamedMorris** [comment]
It's crazy. You get to watch some random bug turn everyone into a think tank, fueled by coffee, energy drinks, and all manner of problem solving insanity. It's fun, but it's hard work. I love it.

**Comment by gregsheremeta** [comment]
Try 1.0.2 and reopen if there are still issues. Thanks.

**Comment by aFoxNamedMorris** [comment]
Heya, everybody. Tried 1.0.2 and 1.0.3. Still getting the error. I forgot to mention that after closing the error dialogs, Pithos brings up another dialog that states that I should try another quality setting. Doing so doesn't seem to change anything, though. For now, I am using Pithos 0.3.17-2. I hope I can be of assistance.

**Comment by aFoxNamedMorris** [comment]
So I switched back to version 1.0.0. Seems to be working pretty well for now. I would try the newest versions, but I'm still on Xubuntu 14.04.
