### ISSUE TITLE
Add a progress bar for each playing song...

### ISSUE THREAD

**Issue by murrayf** [pithos/pithos#149]
Thanks,

Alberto.

:)

**Comment by Hackswell** [comment]
+1

**Comment by JasonLG1979** [comment]
Where would you like it put. Currently I'm pretty sure that it would have to be either in the statusbar(at the bottom) or up top by the buttons and stations combo. The tracklist is, well, a list. I don't think you can put a progressbar in a list view. But I could be wrong.

**Comment by TingPing** [comment]
I personally can't think of that ever looking good

**Comment by gregsheremeta** [comment]
If we were going to do one, I think it would go under the play button.

But, I don't think we need it. Let's keep pithos nice and light and clean.

Motion to close ...

**Comment by TingPing** [comment]
> If we were going to do one, I think it would go under the play button.
> 
> But, I don't think we need it. Let's keep pithos nice and light and clean.

Yea I agree, it doesn't add any new feature (time is already shown), would only lead to users wanting seek functionality (which doesn't belong in a radio), and just clutters the UI.

> Motion to close ...

:+1:

**Comment by gregsheremeta** [comment]
Thanks for the suggestion @murrayf !
