### ISSUE TITLE
Pithos cannot open stream to pandora with altered certificates

### ISSUE THREAD

**Issue by eimirae** [pithos/pithos#151]
There is a certificate interception server and webproxy between me and the internet. I have the intermediate certificate trusted by the system, and most every other program works (curl, wget, apt-get, etc), but pithos reports the following:

```
TypeError: Couldn't find conversion for foreign struct 'cairo.Context'                                                               
TypeError: Couldn't find conversion for foreign struct 'cairo.Context'                                                               
TypeError: Couldn't find conversion for foreign struct 'cairo.Context'                                                               
TypeError: Couldn't find conversion for foreign struct 'cairo.Context'                                                               
TypeError: Couldn't find conversion for foreign struct 'cairo.Context'                                                               
TypeError: Couldn't find conversion for foreign struct 'cairo.Context'                                                               
TypeError: Couldn't find conversion for foreign struct 'cairo.Context'                                                               
TypeError: Couldn't find conversion for foreign struct 'cairo.Context'                                                               
ERROR - pithos:on_gst_error:660 - Gstreamer error: Could not establish connection to server., gstsouphttpsrc.c(1146): gst_soup_http_src_parse_status (): /GstPlayBin:player/GstURIDecodeBin:uridecodebin0/GstSoupHTTPSrc:source:                                          
Cannot connect to destination (audio-ch1-t1-1-v4v6.pandora.com) (4), URL: http://audio-ch1-t1-1-v4v6.pandora.com/access/5602450277661214712.mp4?version=4&lid=8068101&token=AS1XUnaurfbwyFG6PnVtbozor0TGlVNkiXXFLoMXnUq3uDuM4Tl9de55Bt8ZaDsoCgl9V5MRKYbhounm4Z3NvhT8tZAaeZliZRnajDOI4hLnVxCFvi%2FDzyfskcRMmXUFxHtjLekTuuQHBlbJXYCJT6F0M3DFjt3r1ym5MW%2FX1w2o6oZpyG5jrKIm37qaOzzgtcDHlsGBsLkC6tRQAWsuxl%2FFR%2FqCfDzJC%2BfM7SlWMlAfOU2ykUMRV76GBecF5IuIk8aeaaWqx1ZRI%2FYI4%2FuTW5toAJNbNPRqtHST3E5pM1SYQGa10HRRNadVDBxlB1tDiyHPWczPYdAI%2FZ4xxR3aioLAHS1AED82oMxACLItgJXGmeUx%2FFPncA%3D%3D, 5                                                                                            
ERROR - pithos:on_gst_error:660 - Gstreamer error: Could not establish connection to server., gstsouphttpsrc.c(1146): gst_soup_http_src_parse_status (): /GstPlayBin:player/GstURIDecodeBin:uridecodebin1/GstSoupHTTPSrc:source:                                          
Cannot connect to destination (audio-sv5-t1-2-v4v6.pandora.com) (4), URL: http://audio-sv5-t1-2-v4v6.pandora.com/access/8659246403026930010.mp4?version=4&lid=8068101&token=AS1XUnaurfbwyFG6PnVtbozor0TGlVNkiXXFLoMXnUqlxDntkyreV5Ocn3UtA83rOyTzzYQlv81Rf8qtAGF1Lib%2BwKQvbdjDIIuO7j7e5tuH8tQRCj8xwSecFw6iuuZydbGOjWDuKZrJQEnLNew9JsUS4y3hACencusRRsmrEcr7YW585l9mPJ8nU6PqY0O6fTzhdTH8qvFKRAeZnuN8SZrdp9uKzTEW8wVUhIyHm86KR42SxgiYfNfCDpFSHMS0Mz63mFhHFovozgU8tImPW4zhMPdxY3EBOCuwHLDOiq8F%2B0kJy8nEXP%2BXzumL6EHyPP%2Bd0SIJ2juD7NzmHuGOxrL%2BFFZgb9SUeHX1vWKx%2Bj7n1GiTPS6%2FDQ%3D%3D, 5
ERROR - pithos:on_gst_error:660 - Gstreamer error: Could not establish connection to server., gstsouphttpsrc.c(1146): gst_soup_http_src_parse_status (): /GstPlayBin:player/GstURIDecodeBin:uridecodebin2/GstSoupHTTPSrc:source:
Cannot connect to destination (audio-ch1-t3-1-v4v6.pandora.com) (4), URL: http://audio-ch1-t3-1-v4v6.pandora.com/access/7704581475269390568.mp4?version=4&lid=8068101&token=AS1XUnaurfbwyFG6PnVtbozor0TGlVNkiXXFLoMXnUqF9%2FqogppIImzQLoinjAO%2FoB0Y0szKOB82ZdNbARNk99xtTBdaeXiQgpTyhxu8JFgGU9EcD26FqbDff8yiuGV01WeaEILqxF3C2jQ6isoErUsfrcYnBUL2Thd%2BB2TygUeF%2BnXPq0BVc3JXd3LZ0LZDESkqn0%2Fl2IQzGndTdWY2vvNqQ4rVjfwMp%2BQ0LLgX%2BrJBD3otHxuGyBOkZ0caVzxEjWZkxaHjiqt7bi9OgTkwtSaYz7d0YjbbHaAFv7QUXlHjtaJsSmJWGm2somsXKE8yp8b%2BWFZF4dCP1Kpb6Snx8k8FGm8Vr8VUsTtPKTSFCbf70fLwFaFrZw%3D%3D, 5
ERROR - pithos:on_gst_error:660 - Gstreamer error: Internal data flow error., gstbasesrc.c(2865): gst_base_src_loop (): /GstPlayBin:player/GstURIDecodeBin:uridecodebin3/GstSoupHTTPSrc:source:
streaming task paused, reason error (-5), 1
```

So it looks like it can download the song info, but as soon as it tries connecting to the server where the songs are stored, it fails.

Previously, I was able to get pianobar to work correctly by overriding the key signature with the ssl signature reported by google chrome for the url.  Using the urls above work fine in a webbrowser or with wget.

**Comment by JDougherty** [comment]
I am running into the same issue, though I'm not sure if my webproxy is doing anything with certificates (and that shouldn't matter because this is a standard http request). 

Pithos (version 1.0.1) can login to Pandora, get my stations and a playlist, but cannot actually play the songs. 

Please let me know how I can assist in debugging.

**Comment by TingPing** [comment]
>and that shouldn't matter because this is a standard http request

Exactly, so at that point I never understood what they meant.

This is an issue at a level below Pithos so finding more details would mean digging into gstreamer.
Since you are both using proxies I would just assume Pandora is getting smarter about blocking them?

**Comment by JDougherty** [comment]
I don't think this is on Pandora's side of things. I can access and stream from my browser (Chrome/Chromium) through the proxy without issue. Additionally, if I try to use `wget` on the URL that gstreamer reports it could not connect to, it is able to connect (though I do get a 400 bad request, which I expect is because I'm not passing through all the extra header information to make it seem like a legit request). Similarly, I can load the URL that gstreamer fails to connect to in Chrome/Chromium through the proxy and it works fine. 

It's only for this reason that I think it may be a pithos issue, in that it is not properly supplying proxy information to gstreamer. But to that end, I have zero experience with gstreamer.

**Comment by TingPing** [comment]
@JDougherty Ah ok. You can run something like ```GST_DEBUG=5 pithos``` to get a ton of information that may or may not be helpful.

**Comment by JDougherty** [comment]
Thanks, I've created a gist with the stdout and stderr from `GST_DEBUG =5 pithos -v` in case anyone wants to check it out: https://gist.githubusercontent.com/JDougherty/8c02bf34beb9e4dd4316/raw/pithos%20debug

Be warned, it's huge. Line 21875 is relevant, which is where pithos actually spits out the error from gstreamer. You can also find this by ctrl+F'ing for "ERROR - pithos"

On line 22351 you can see pithos skip to the next song. It looks like it takes approximately 2 minutes for gstreamer to time out. 

I'm going to try building pithos later and doing some of my own debugging, but just wanted to add this information from now. 

I think it's probably safe to modify the title of this issue, I do not believe it's related to certs.

**Comment by gregsheremeta** [comment]
Also, try `gst-launch-1.0 playbin uri=<pandora url>` instead of wget.

**Comment by JDougherty** [comment]
@gregsheremeta What kind of output or result should I expect from that? Here's the output that I see 

    jwdoughe@jwdoughe-ThinkPad-T440p ~ $ gst-launch-1.0 playbin uri=[snip for brevity]
    [1] 25933
    [2] 25934
    jwdoughe@jwdoughe-ThinkPad-T440p ~ $ Setting pipeline to PAUSED ...
    Pipeline is PREROLLING ...
    ERROR: from element /GstPlayBin:playbin0/GstURIDecodeBin:uridecodebin0/GstSoupHTTPSrc:source: Could not establish connection to server.
    Additional debug info:
    gstsouphttpsrc.c(1146): gst_soup_http_src_parse_status (): /GstPlayBin:playbin0/GstURIDecodeBin:uridecodebin0/GstSoupHTTPSrc:source:
    Cannot connect to destination (audio-sv3-t1-1-v4v6.pandora.com) (4), URL: http://audio-sv3-t1-1-v4v6.pandora.com/access/719541917958245274.mp4?version=4
    ERROR: pipeline doesn't want to preroll.
    Setting pipeline to NULL ...
    Freeing pipeline ...

    [1]-  Exit 1                  gst-launch-1.0 playbin uri=http://audio-sv3-t1-1-v4v6.pandora.com/access/719541917958245274.mp4?version=4
    [2]+  Done                    lid=36536007




This is after I've set my "http_proxy" environment variable. I suppose this implicates gstreamer, but I wanted to check if there's anything else I need to do to specify a proxy. 

I'm also trying a variation that I found on Google, I'm not sure how relevant it is, but it also doesn't seem to work at the moment ([ref](https://stuff.mit.edu/afs/athena/system/amd64_deb50/os-ubuntu-10.04/usr/share/gtk-doc/html/gst-plugins-good-plugins-0.10/gst-plugins-good-plugins-souphttpsrc.html)):

    gst-launch -v souphttpsrc location=[url]  proxy=[myproxy]

**Comment by gregsheremeta** [comment]
I'm not sure how you set the proxy using gst-launch. Assuming you do that right, and gst-launch won't play a Pandora URL that you are authenticated for -- then, yes, this means it's a gstreamer bug you're experiencing.

**Comment by JDougherty** [comment]
Got it, thanks @gregsheremeta. Do you know where I should follow up with the gstreamer folks?

**Comment by gregsheremeta** [comment]
Google tells me https://bugzilla.gnome.org/enter_bug.cgi?product=GStreamer :)

**Comment by eimirae** [comment]
fyi jdougherty, you need to quote the url after uri=.  Here is the output I am getting:

gst-launch-1.0 playbin uri="http://audio-sv5-t2-2-v4v6.pandora.com/access/7621070153022255136.mp4?version=4&lid=8068101&token=vDERV01dneUojxJZxoaZzblczh7gulhMv4b3AkAnLKI28u8w0LHBgH3hNLSiABtrwh%2Frql1imywfdcwG5FQPO7bfqqNa98GVXmKMmFWpLvS%2BlwirxVX5tRxCbDG0PGMmRQLUybKb7KGMVXozcgXkpzyVux33HuYOkVGHpqEYDONcgSwZXWCkWjw5BaS99eJPW%2FQ3esIUcD45UHCsbfBalHLYqfkuOKT9hffmVjbelV4uhIFpxc6ETXv9Hz%2F%2BtDrijFaaKDaY4ESc3UETjpREkzU4n7WMUIcfrnCHGD5fcHQP0%2BVFnXTmeTqGy%2BTAIEXYuf87T5lkWkbSl4zTTVqE6P7a%2FxKMK4vONZjvhKlVb46Io%2FA7qqI%2Bmg%3D%3D"
Setting pipeline to PAUSED ...
Pipeline is PREROLLING ...
ERROR: from element /GstPlayBin:playbin0/GstURIDecodeBin:uridecodebin0/GstSoupHTTPSrc:source: Could not establish connection to server.
Additional debug info:
gstsouphttpsrc.c(1146): gst_soup_http_src_parse_status (): /GstPlayBin:playbin0/GstURIDecodeBin:uridecodebin0/GstSoupHTTPSrc:source:
Cannot connect to destination (audio-sv5-t2-2-v4v6.pandora.com) (4), URL: http://audio-sv5-t2-2-v4v6.pandora.com/access/7621070153022255136.mp4?version=4&lid=8068101&token=vDERV01dneUojxJZxoaZzblczh7gulhMv4b3AkAnLKI28u8w0LHBgH3hNLSiABtrwh%2Frql1imywfdcwG5FQPO7bfqqNa98GVXmKMmFWpLvS%2BlwirxVX5tRxCbDG0PGMmRQLUybKb7KGMVXozcgXkpzyVux33HuYOkVGHpqEYDONcgSwZXWCkWjw5BaS99eJPW%2FQ3esIUcD45UHCsbfBalHLYqfkuOKT9hffmVjbelV4uhIFpxc6ETXv9Hz%2F%2BtDrijFaaKDaY4ESc3UETjpREkzU4n7WMUIcfrnCHGD5fcHQP0%2BVFnXTmeTqGy%2BTAIEXYuf87T5lkWkbSl4zTTVqE6P7a%2FxKMK4vONZjvhKlVb46Io%2FA7qqI%2Bmg%3D%3D
ERROR: pipeline doesn't want to preroll.
Setting pipeline to NULL ...
Freeing pipeline ...

**Comment by gregsheremeta** [comment]
closing, since this is almost certainly a gstreamer bug. thanks!
