### ISSUE TITLE
Include loved/banned song status in MPRIS track metadata

### ISSUE THREAD

**Issue by bcat** [pithos/pithos#153]
My panel (Taffybar) currently shows Pithos's currently playing song via the panel's MPRIS widget, and I'd like to tweak that widget to also show the loved-or-not status of the current song, but Pithos doesn't expose that in the song metadata. I'd like to add support for that, but I'm not sure if I should use the existing `xesam:userRating` field (http://www.freedesktop.org/wiki/Specifications/mpris-spec/metadata/#index22h4) with some mapping (e.g., 0.0 -> banned, 0.5 -> normal, 1.0 -> loved) or introduce a new `pithos:rating` field with a string value. What do you think?

**Comment by TingPing** [comment]
Yes I had planned on using the the rating field for this. I didn't really like how it maps to love/ban but it is better tan nothing.

**Comment by TingPing** [comment]
Oh also there needs to be some mapping for 'Tired' as well.

**Comment by bcat** [comment]
Does it make more sense to have a bunch of properties or a single enum-like property? (Not sure if D-Bus lets you define an enum or if enums are just emulated with magic strings/integers.) I assume a song can't be both loved and banned at the same time, but being tired is independent of the loved/banned status?

**Comment by TingPing** [comment]
Tired is independent. I think I prefer separate properties to one just taking multiple strings, If a user tries to set both True it is not the end of the world.

**Comment by TingPing** [comment]
Internally it looks like Pithos does store it as a string - https://github.com/pithos/pithos/blob/master/pithos/pandora/pandora.py#L36

**Comment by bcat** [comment]
Okay, so "tired" should definitely be its own property, and for "love" and "ban", I guess it's mainly a question of which gives a clearer interface: two bool properties or one string property. (AFAIK, MPRIS doesn't allow clients to _set_ properties, so I think that will still need to be done via the Pithos-specific API.) I'm not sure if I'll have time (it's a simple change, but I've got some work/life stuff going on right now that takes precedence), but I'm going to try and send a pull request for this over the weekend, if you wouldn't mind.

**Comment by TingPing** [comment]
>(AFAIK, MPRIS doesn't allow clients to set properties, so I think that will still need to be done via the Pithos-specific API.) 

Oh right. That sucks as I really want to deprecate that API entirely...

The changes to add the read-only stuff is trivial. So a pull-request would be great or I can do it if you don't have time. I think setting ```pithos:rating``` to the current string we already use internally would be fine.

**Comment by bcat** [comment]
Alright, cool. I'll try and throw together something as soon as I have free time, probably this weekend unless you or someone else beats me to it. :) As for the setter API, for now I can just bind a media key that calls `LoveCurrentSong` in the old/custom API, though I don't think that allows me to un-love a song that's already loved. A rating property plus being able to love a song will let me use Pithos with the player window offscreen the vast majority of the time, though, so un-loving is more of a completeness thing. :)

**Comment by bcat** [comment]
Hacking up something quick now, I don't think it makes sense to include "tired" in the metadata since Pithos appears to automatically skip a track as soon as it's marked tired. If Pithos implemented `org.mpris.MediaPlayer2.TrackList` (nice to have, but more work), then the tired bit should probably make sense to include, but IMO it should be left out until full track lists are supported (since it will always be false).
