### ISSUE TITLE
Global media buttons don't work

### ISSUE THREAD

**Issue by MarkTraceur** [pithos/pithos#156]
My keyboard has pause/play, stop, next, and previous buttons on it. "previous" doesn't make any sense in the Pandora context (maybe as a "like the last song" button?) but in any case, I'd like to be able to use those buttons to control Pithos. If nobody gets around to this, I might do it myself, but I don't know the codebase very well and I'm sure it would be quicker for someone who does (and I have quite enough projects I'm involved in...)

**Comment by TingPing** [comment]
If you use Gnome it works ootb, Other desktops require installing keybinder3.

**Comment by MarkTraceur** [comment]
@TingPing how do you recommend accomplishing that from Cinnamon on Linux Mint? I tried installing libkeybinder-3.0-dev and restarting Pithos to no effect.

**Comment by TingPing** [comment]
Debian does the package splitting thing, It is called *gir1.2-keybinder-3.0*

**Comment by TingPing** [comment]
Debian does the package splitting thing, It is called *gir1.2-keybinder-3.0*

**Comment by TingPing** [comment]
Debian does the package splitting thing, It is called *gir1.2-keybinder-3.0*

**Comment by MarkTraceur** [comment]
Installed that, restarted pithos, no dice...

**Comment by TingPing** [comment]
What does `pithos -v` say about loading media keys?
