### ISSUE TITLE
Messed up notification text

### ISSUE THREAD

**Issue by JasonLG1979** [pithos/pithos#157]
![snapshot1](https://cloud.githubusercontent.com/assets/6667703/6621629/b87139b6-c8a5-11e4-9441-24e7224adc11.png)
msg = html.escape('by {} from {}'.format(song.artist, song.album)) in notify.py should be...
msg = html.unescape('by {} from {}'.format(song.artist, song.album))

**Comment by TingPing** [comment]
I think the problem is some daemons require escaping and others do not, so this should be conditionally done.

**Comment by JasonLG1979** [comment]
Idk, could be? But I know it's jacked up in both GNOME and KDE.

**Comment by TingPing** [comment]
Can you test this:

```diff
From bd1261a01e7b1d3294a8e27560d26af14c1a5994 Mon Sep 17 00:00:00 2001
From: TingPing <tingping@tingping.se>
Date: Thu, 12 Mar 2015 17:18:17 -0400
Subject: [PATCH] notify: Only escape markup when required

Fixes #157
---
 pithos/plugins/notify.py | 7 ++++++-
 1 file changed, 6 insertions(+), 1 deletion(-)

diff --git a/pithos/plugins/notify.py b/pithos/plugins/notify.py
index cd2a113..961bcef 100644
--- a/pithos/plugins/notify.py
+++ b/pithos/plugins/notify.py
@@ -26,6 +26,7 @@ class NotifyPlugin(PithosPlugin):
 
     has_notifications = False
     supports_actions = False
+    escape_markup = False
 
     def on_prepare(self):
         if platform == 'darwin':
@@ -71,6 +72,9 @@ class NotifyPlugin(PithosPlugin):
             logging.info('Notify supports actions')
             self.supports_actions = True
 
+        if 'body-markup' in caps:
+            self.escape_markup = True
+
         if 'action-icons' in caps:
             self.notification.set_hint('action-icons', GLib.Variant.new_boolean(True))
 
@@ -113,7 +117,8 @@ class NotifyPlugin(PithosPlugin):
         else:
             self.notification.set_hint('image-data', None)
 
-        msg = html.escape('by {} from {}'.format(song.artist, song.album))
+        if self.escape_markup:
+            msg = html.escape('by {} from {}'.format(song.artist, song.album))
         self.notification.update(song.title, msg, 'audio-x-generic')
         self.notification.show()
 
-- 
1.9.5 (Apple Git-50.3)

```

**Comment by TingPing** [comment]
Oh that bypasses the formatting... one sec

**Comment by TingPing** [comment]
```diff
From cad33d8f795db5c9b3fa1f93faf5ac8ba7d99e82 Mon Sep 17 00:00:00 2001
From: TingPing <tingping@tingping.se>
Date: Thu, 12 Mar 2015 17:18:17 -0400
Subject: [PATCH] notify: Only escape markup when required

Fixes #157
---
 pithos/plugins/notify.py | 8 +++++++-
 1 file changed, 7 insertions(+), 1 deletion(-)

diff --git a/pithos/plugins/notify.py b/pithos/plugins/notify.py
index cd2a113..9bb255e 100644
--- a/pithos/plugins/notify.py
+++ b/pithos/plugins/notify.py
@@ -26,6 +26,7 @@ class NotifyPlugin(PithosPlugin):
 
     has_notifications = False
     supports_actions = False
+    escape_markup = False
 
     def on_prepare(self):
         if platform == 'darwin':
@@ -71,6 +72,9 @@ class NotifyPlugin(PithosPlugin):
             logging.info('Notify supports actions')
             self.supports_actions = True
 
+        if 'body-markup' in caps:
+            self.escape_markup = True
+
         if 'action-icons' in caps:
             self.notification.set_hint('action-icons', GLib.Variant.new_boolean(True))
 
@@ -113,7 +117,9 @@ class NotifyPlugin(PithosPlugin):
         else:
             self.notification.set_hint('image-data', None)
 
-        msg = html.escape('by {} from {}'.format(song.artist, song.album))
+        msg = 'by {} from {}'.format(song.artist, song.album)
+        if self.escape_markup:
+            msg = html.escape(msg)
         self.notification.update(song.title, msg, 'audio-x-generic')
         self.notification.show()
 
-- 
1.9.5 (Apple Git-50.3)
```

**Comment by JasonLG1979** [comment]
That seems to do the trick.

**Comment by JasonLG1979** [comment]
Easy fix. closing this issue.

**Comment by JasonLG1979** [comment]
I take that back. No dice. Still screwed up.

**Comment by JasonLG1979** [comment]
Which daemons require escaping?

**Comment by JasonLG1979** [comment]
The initial "pop up" notification doesn't display correctly but it displays correctly in the notifications list. I'm going to test this on Fedora 21 GNOME to see if it's a Ubuntu or KDE issue. Seems like someone might be lying about their notification server capabilities,lol!!!

Here's the "pop up"
![snapshot3](https://cloud.githubusercontent.com/assets/6667703/6629481/7a727b66-c8dc-11e4-9fcd-17953f4130b9.png)

Here's what I get when I view the notification later.
![snapshot4](https://cloud.githubusercontent.com/assets/6667703/6629505/a8c1e6aa-c8dc-11e4-9348-514fa372c59f.png)

**Comment by TingPing** [comment]
We should likely only be escaping <>

**Comment by JasonLG1979** [comment]
When are <> even used?

**Comment by TingPing** [comment]
>When are <> even used?

Pretty uncommon in music but its possible.

**Comment by TingPing** [comment]
It is still possible now that the `&` character is escaped when they should not be, that also would be more common in music than `<` or `>`.

**Comment by JasonLG1979** [comment]
Still doesn't look right.
![snapshot5](https://cloud.githubusercontent.com/assets/6667703/6630321/9638eab6-c8e5-11e4-87e3-de533473d4c0.png)

**Comment by JasonLG1979** [comment]
Sorry just noticed you already mentioned "&".

**Comment by TingPing** [comment]
Ah thats exactly what I mentioned, the `&` symbol. We will just have to write our own escaper. =\

**Comment by TingPing** [comment]
@JasonLG1979 Can you somehow make sure things with <> show up correctly? Because if your service is reporting it supports 'body-markup' and then does not support escaped markup...

**Comment by JasonLG1979** [comment]
I'll just throw a bogus string in there instead of the song title.

**Comment by JasonLG1979** [comment]
I replaced:
msg = 'by {} from {}'.format(song.artist, song.album)

With:
msg = 'by {} from {}'.format(" <> < Random > <> ", " <> < & > <> < Crap > <> ")

And get this...

![snapshot7](https://cloud.githubusercontent.com/assets/6667703/6630616/f642ac78-c8e8-11e4-9f47-4fc413612141.png)

Not sure if that's what you want since Random & Crap are strings?

**Comment by JasonLG1979** [comment]
I think maybe the service is lying.

**Comment by JasonLG1979** [comment]
The question is; even if a service supported markup correctly what's to gained by using it? What services absolutely require it?

**Comment by TingPing** [comment]
@JasonLG1979 Seems like your service is *not* saying they support it. Pithos escapes this in pithos.py already https://github.com/pithos/pithos/blob/master/pithos/pithos.py#L760.

**Comment by JasonLG1979** [comment]
From what I understand that just escapes the song info for the main window. It doesn't change the actual song.title, song.artist or song.album.

**Comment by TingPing** [comment]
I realized that, i was just grepping for escape().

**Comment by JasonLG1979** [comment]
The main window doesn't have anything to do with the notification service.

**Comment by JasonLG1979** [comment]
I need to read the notify spec better. Something screwy's going on.

**Comment by gregsheremeta** [comment]
Take this chat to IRC, fellas.

**Comment by JasonLG1979** [comment]
ok

**Comment by JasonLG1979** [comment]
Figured it out.
https://github.com/JasonLG1979/pithos/commit/a1cdae9bcfa6bd35009b8c50b7099edeb5b87b85

**Comment by TingPing** [comment]
@JasonLG1979 Uh, well yes clearly that cap means it supports markup but you shouldn't send invalid markup, thus it should be escaped. Whatever service could of course handle that but its an assumption that likely shouldn't be made.

**Comment by JasonLG1979** [comment]
Read the spec again.

**Comment by JasonLG1979** [comment]
The markup cap means that the server understands at least some markup and that the markup can be sent inline in the notification. Why would you send markup inline then escape it?

**Comment by JasonLG1979** [comment]
IT doesn't mean that everything must be escaped.

**Comment by JasonLG1979** [comment]
![snapshot10](https://cloud.githubusercontent.com/assets/6667703/6645233/bae17650-c988-11e4-8779-670c7887f62a.png)

Inline markup in notification. Hyperlink to Pandora song info in song title, bold text song title, italicized artist name and album title.

**Comment by TingPing** [comment]
@JasonLG1979 The song information is from an external source and thus can contain anything including `<b><stuff>The title`.

- We should be escaping this so it does not get random formatting
- We should be escaping this so the receiving end does not get invalid tags

Again, it does not matter if some daemon handles invalid tags, we cannot assume all do.

**Comment by JasonLG1979** [comment]
But the song info doesn't contain markup in it's current form. It's a plain old string. In the future if Pandora decides to change that I guess we'll have to deal with it then. Until then we can either do what we're doing and break the notifications and escape text that doesn't need escaping or we can not escape text that doesn't need escaped.

**Comment by JasonLG1979** [comment]
It comes down to this. Escape everything, all tags and special characters are rendered incorrectly. Or don't escape and tags that the notification server doesn't understand are rendered incorrectly.

**Comment by JasonLG1979** [comment]
There's a list of tags in the spec that servers are suppose to support if they report they support markup.

**Comment by TingPing** [comment]
>But the song info doesn't contain markup in it's current form.

Are you sure there has never been a song on Pandora with <> in it? We can't even know. It is an untrusted input and should be treated as such.

Since the worst case is likely not terrible in this situation it might not be the end of the world to ignore it if there are more broken implementations that can't handle escaped text than there are broken implementations that can't handle invalid tags (which we assume are rare anyway).

**Comment by JasonLG1979** [comment]
I can't say that I have, but it really doesn't matter. You're not understanding what I'm trying to tell you. Whatever you do you things your way I'll do things mine.

GNOME's notification system must be broken then because it can't handle escaped text either... On Fedora 21 GNOME escaping "&" in notifications get you "&amp;"...

**Comment by TingPing** [comment]
GNOME does not support body-markup. This codepath should not apply there at all.

**Comment by TingPing** [comment]
Huh, so it does actually..

**Comment by JasonLG1979** [comment]
I know. That's what I've been trying to tell you,lol!!! Escaping text on a notification server that supports markup borks special characters.

**Comment by TingPing** [comment]
@JasonLG1979 On gnome 3.15 I cannot reproduce at all. It behaves exactly as expected with escaped characters.

**Comment by JasonLG1979** [comment]
I'll test it out on fedora 21

**Comment by JasonLG1979** [comment]
Running Pithos from a Fedora 21 LiveUSB with GNOME 3.14 it doesn't matter if the text is escaped or not it displays identically. Write this date down becasue I may have just been wrong. I'm sorry... GNOME also doesn't seem to support markup in the notification title. I'll test on Ubuntu Unity to see what it's capable of. Looks like no one wants to follow the spec. Might be a case of sniffing the DE and than deciding what to do. Kinda like with the notification area icon.

**Comment by JasonLG1979** [comment]
Maybe something like this...
```
        if self.escape_markup:
            if os.environ['XDG_CURRENT_DESKTOP'] == 'GNOME':
                msg = 'by {} from {}'.format(song.artist, song.album)
                msg = html.escape(msg, quote=False)
                self.notification.update(song.title, msg, 'audio-x-generic')
                
            elif os.environ['XDG_CURRENT_DESKTOP'] == 'KDE':
                title = ('<a href="%s"><b>%s</b></a>' %(song.songDetailURL, song.title))
                msg = 'by {} from {}'.format(song.artist, song.album)
                self.notification.update(title, msg, 'audio-x-generic')
                
            else:
                msg = 'by {} from {}'.format(song.artist, song.album)
                self.notification.update(song.title, msg, 'audio-x-generic')            
                
        else:
            msg = 'by {} from {}'.format(song.artist, song.album)
            self.notification.update(song.title, msg, 'audio-x-generic')
```

**Comment by TingPing** [comment]
>GNOME also doesn't seem to support markup in the notification title.

Well it is called 'body-markup' :P

>Looks like no one wants to follow the spec.

So far its just KDE?

If we were to work around specific daemons we would use `Notify.get_server_info()` not the desktop.

**Comment by TingPing** [comment]
Looks like notify-osd (What Unity uses) supports body-markup but does not actually show the attributes and it correctly handles escaped markup.

**Comment by JasonLG1979** [comment]
So 3 different notification servers and 3 different sets of behaviors?

**Comment by TingPing** [comment]
@JasonLG1979 Trying KDE Plasma 5.2.0 on Kubuntu 15.04 i get the same behavior as Unity. It supports escaped versions but it doesn't actually render attributes. (at least not bold)

**Comment by JasonLG1979** [comment]
Can Plasma 5.2 do hyperlinks?

**Comment by JasonLG1979** [comment]
I don't know the point of a spec if no one follows it?

**Comment by TingPing** [comment]
@JasonLG1979 Ok, KDE actually supports everything in title and body, bold is just hard to notice on a 10x10 res VM.

**Comment by JasonLG1979** [comment]
Right on. The hyperlink thing I thought was kinda neat. To bad neither GNOME or Unity support it. I didn't expect Unity to support it because their notifications aren't clickable but I'm kinda bummed GNOME doesn't.

**Comment by TingPing** [comment]
Notifications can run 'actions' such as opening a url, so I think thats what gnome would want. We use the two button actions already.

**Comment by TingPing** [comment]
Also somewhere in the future Gnome wants to stop abusing Notifications for music players, so eventually Pithos will be using that.

**Comment by JasonLG1979** [comment]
So what are they going to do then? You can already turn notifications off in most music players if you want.

**Comment by TingPing** [comment]
They have not really done any designs on it yet, I suspect it will be an item in the top status menu and likely just make use of MPRIS so all clients work ootb. No more hacks for things like the lock panel to work.
