### ISSUE TITLE
Only Python 3+ currently supported

### ISSUE THREAD

**Issue by jamiesonbecker** [pithos/pithos#159]
import urllib.request, urllib.error, urllib.parse

Is this a big problem to solve or just a matter of adding a fix for imports.. I can submit pull requests :)

**Comment by gregsheremeta** [comment]
It's by design. Can you not use python3?

**Comment by jamiesonbecker** [comment]
No, just prefer Python 2.7. :) Perhaps a note on the wiki with regards to requirements (including pip install html, ..?) to help those who are considering a build and install. Would you entertain a backport pull request?

**Comment by gregsheremeta** [comment]
Thanks, but I don't think so since we purposely moved to python 3.

I'm curious -- if you're running pithos as an end-user, why do you care what version of python it uses?

**Comment by jamiesonbecker** [comment]
np. I'm a developer too :)

**Comment by TingPing** [comment]
The docs are pretty clear considering they list tons of python3 deps.
