### ISSUE TITLE
Proposal to change coding style

### ISSUE THREAD

**Issue by glennimoss** [pithos/pithos#161]
I generally adhere to PEP 8 standards when writing Python code, with 2 specific exceptions:

##### Indentation of 2 spaces.
I think 4 is excessive. This is of course personal taste. However I argue that when attempting to limit line length to 79 characters (as specified in PEP 8) smaller indentation reduces the frequency of multi-line statements.
##### A space after the name and before the opening parenthesis of a function definition.
When searching/grepping a source filie, this makes definitions and invocations easily distinguishable. (e.g. searching for `foo (` finds the definition, but `foo(` finds invocations.) Let me illustrate: 
```python
def foo (arg1, arg2):
  pass

# a call to foo however, has no space:
foo('bar', 'baz')
```

### Discussion
I invite discussion from all other active contributors. I do have a strong personal preference for these two items. If you don't have a strong opinion, my hope is that you can agree to using this new style. If you disagree, let's hash it out!

**Comment by glennimoss** [comment]
Oh, an additional argument for 2 space indentation. Whis is more readable?
```python
if (some_long_expressions and
    such_that_it_takes_many_lines):
    code()
    code()

# vs
if (some_long_expressions and
    such_that_it_takes_many_lines):
  code()
  code()
```

**Comment by gregsheremeta** [comment]
+1. Checking should be part of the build.

**Comment by TingPing** [comment]
I disagree with 2 spaces, however following pep8 otherwise is usually fine. Another user tried doing a mass reformat but I never was interested in merging it because I was working on other things and that changes nearly every line so I didn't feel like breaking my branches. This still applies since I have the `dev` branch that some day I want to finish (though at this rate...).

**Comment by glennimoss** [comment]
I don't think I'd want to do a mass reformat... More of a gradual transition. 




What are your reasons for disliking 2 space indentation?



—

**Comment by TingPing** [comment]
> I don't think I'd want to do a mass reformat... More of a gradual transition.

Uh there is no such thing as a gradual transition for whitespace changes in Python.

>What are your reasons for disliking 2 space indentation?

As with anything, it is mostly just opinion. I think it is too small to easily notice compared to 4. Depth is usually not much of a concern of mine, I think 80 chars is too conservative and prefer something like 100. Your example is also not very interesting to me either.

**Comment by glennimoss** [comment]
> Uh there is no such thing as a gradual transition for whitespace changes in Python.

As long as within a given block your indentation is consistent it's fine. You don't have to have to use identical indentation everywhere.

**Comment by TingPing** [comment]
>As long as within a given block your indentation is consistent it's fine. You don't have to have to use identical indentation everywhere.

Hmm. Even if technically possible that is a massive pita. Developers would have to constantly be ensuring they know the syntax of the current area and follow it as well as ensuring their editor of choice is psychic to know you want it to be wrong here and right there.

>When searching/grepping a source filie, this makes definitions and invocations easily distinguishable. (e.g. searching for foo ( finds the definition, but foo( finds invocations.)

If anything I view that as a negative; When I am searching for something I want both and `foo` might be too broad.

**Comment by glennimoss** [comment]
So then grep for `foo ?(`.

**Comment by TingPing** [comment]
>So then grep for foo ?(.

Yes completely changing everyones workflow is an option..

**Comment by glennimoss** [comment]
A change for the better ;)

Maybe we can all come to an agreement on line length. PEP 8 says 79, but I don't have strong feelings about that one. Should we make 100 the official line length for Pithos?

**Comment by gregsheremeta** [comment]
Can we just use PEP8 straight up, without changing it? Pretty sure everyone can at least agree on that.

**Comment by TingPing** [comment]
>Can we just use PEP8 straight up, without changing it? Pretty sure everyone can at least agree on that.

I do love Golangs approach. "Here is an official format tool, you will use it and be happy". PEP8 is what the community at large has agreed with and I am all for just doing that.

**Comment by glennimoss** [comment]
PEP 8 it is.
