### ISSUE TITLE
Cast to Google Chromecasts

### ISSUE THREAD

**Issue by rowland007** [pithos/pithos#162]
May not be possible due to the fact that the sender application or Google Cast application refers to a web (HTML/JavaScript) app running inside a Chrome browser on a Mac/Windows/Linux/ChromeOS desktop/laptop device (the sender device). More information about Chrome Sender App Development: https://developers.google.com/cast/docs/chrome_sender

**Comment by TingPing** [comment]
>May not be possible due to the fact that the sender application or Google Cast application refers to a web (HTML/JavaScript) app running inside a Chrome browser

Yes clearly, this has nothing to do with Pithos..

**Comment by rowland007** [comment]
Might be possible with support for external/JavaScript transcoding. Pass the Pandora API to a pseudo-browser to handle the casting.

**Comment by TingPing** [comment]
This sounds like a terrible idea. Pandora already officially supports chromecast.

**Comment by EddieRockwell** [comment]
I would love to have Pithos to have a chromecast plugin. could this be re-opened? I think the application is much better than Pandora and i've been looking to cut the audio cord between my notebook and stereo for a long time. With instructions for Chromecast (http://askubuntu.com/a/326224) and a Pithos plugin, we're set :).

If there are other optoins, please let me know.

**Comment by TingPing** [comment]
I don't have a chromecast but I recently ran into this project, it is probably the best solution: https://github.com/masmu/pulseaudio-dlna
