### ISSUE TITLE
Album Art not displayed

### ISSUE THREAD

**Issue by mdshaver81** [pithos/pithos#164]
Since the implementation of the new UI, Pithos has not displayed album art nor has it displayed "loved" labels for songs. This happens only in the two latest releases (v 1.0 and 1.01). I only use the KDE4 desktop so that is the environment it is being run in. I have tested this on Kubuntu 14.10 and OpenSuse 13.2 with the same results. I have attached a snapshot.

![snapshot1](https://cloud.githubusercontent.com/assets/11648645/6825920/fbcbe51e-d2cb-11e4-86b8-c4167524367b.png)

**Comment by TingPing** [comment]
Install `python3-gi-cairo`

Duplicate of #98

**Comment by mdshaver81** [comment]
Thanks!
