### ISSUE TITLE
Song text change/improvements?

### ISSUE THREAD

**Issue by JasonLG1979** [pithos/pithos#168]
Is there any interest in showing the codec and if the stream is Pandora One in the song text? I've got a bit of code that adds that info to the song_text. If there's no interest there's no point in doing a pull request.

Here's what it looks like.

Pandora One High Quality setting:
![p1 mp3](https://cloud.githubusercontent.com/assets/6667703/6908169/ff2a4014-d700-11e4-8bb7-0bc6db7441a7.png)

Pandora One Medium/Low Quality:
![p1 aac](https://cloud.githubusercontent.com/assets/6667703/6908195/1fb37170-d701-11e4-8411-ec3dd4d7536a.png)

Non Pandora One High Quality:
![p0 aac](https://cloud.githubusercontent.com/assets/6667703/6908220/34a9e8d4-d701-11e4-820f-66bce4181c10.png)

You get the idea.

**Comment by gregsheremeta** [comment]
I like showing the codec for sure. I'm meh on showing "Pandora One."

**Comment by JasonLG1979** [comment]
OK no problem, nix the "Pandora One." I kinda like it helps me feel I'm getting my $5 worth for the Pandora One subscription,lol!!!

**Comment by TingPing** [comment]
I always thought showing the bitrate was a bit overkill already, but thats just me.

**Comment by JasonLG1979** [comment]
OK so I'm going to count that as a total of no interest in the Pandora One message and slight interest in the codecs message. So the question is there enough interest that I should do a pull request for the codecs message?

**Comment by gregsheremeta** [comment]
Yep, I like it. TingPing has no strong opinion. So I think go for it.

If you're feeling ambitious, make it configurable (showing both the bitrate and the codec)

**Comment by JasonLG1979** [comment]
OK, if/when my last request is merged I'll do one for the codecs message. As far as being configurable goes I don't really think that's worth the effort or extra preference ui options check boxes. The fewer options the better really.

**Comment by gregsheremeta** [comment]
You can do a simultaneous PR if you use a branch. Up to you.

**Comment by JasonLG1979** [comment]
I'd rather do one at a time. I get confused easily, lol!!!!

**Comment by JasonLG1979** [comment]
And the codecs message code depends on my last request.

**Comment by JasonLG1979** [comment]
Working on this. closing it.
