### ISSUE TITLE
Change Love icon

### ISSUE THREAD

**Issue by fduraibi** [pithos/pithos#169]
Currently the "Love/Unlove" is using "gtk-about" which is the same one used for "Info". I suggest changing it to something more meaning full and different too either e.g. "gtk-apply" which is a green check mark.

Is it hard to use custom made icons? Would be great if it was a heart/broken heart for love/unlove.

Update:
I see from searching that the about icon should be a golden star, however what I get on my system is a white exclamation mark inside a blue circle!

I am in Fedora with KDE

![pithos](https://cloud.githubusercontent.com/assets/432460/6985438/578cb5e0-da01-11e4-844b-8ea2ea30ff6b.png)

**Comment by fduraibi** [comment]
I found the problem, it is KDE changing gtk apps to look like KDE with oxygen theme and icons.

**Comment by JasonLG1979** [comment]
They could use emblem-favorite it's usually either a heart or a star in most icon themes. Pithos uses stock icons which have been deprecated since version 3.10. But with the way GNOME breaks things with every release I imagine it's hard to keep up,lol!!!

**Comment by TingPing** [comment]
>Pithos uses stock icons which have been deprecated since version 3.10.

I thought we got rid of all of that usage?

**Comment by fduraibi** [comment]
You forgot these in pithos.py:
```
def song_icon(self, song):
    if song.tired:
        return Gtk.STOCK_JUMP_TO
    if song.rating == RATE_LOVE:
        return Gtk.STOCK_ABOUT
    if song.rating == RATE_BAN:
        return Gtk.STOCK_CANCEL
```

but without them i cannot tell if the song was loved or banned!

**Comment by TingPing** [comment]
Those icons will not be removed @fduraibi :P (but eventually changed from stock ones)

**Comment by TingPing** [comment]
@fduraibi Oh actually that does mean the icon over the song is still wrong right?

**Comment by JasonLG1979** [comment]
Doesn't work properly with KDE in Kubuntu 14.10 at least.
![snapshot1](https://cloud.githubusercontent.com/assets/6667703/6992736/b64e2ad2-daa1-11e4-8cf6-bca8fe4419ea.png)

**Comment by TingPing** [comment]
>Doesn't work properly with KDE in Kubuntu 14.10 at least.

You get any errors? I know the Oxygen icon theme has everything.

**Comment by fduraibi** [comment]
But it now works under Fedora 21 and KDE

![pithos](https://cloud.githubusercontent.com/assets/432460/6995283/9c3d1332-db0b-11e4-8627-7a80ca911e66.png)

**Comment by JasonLG1979** [comment]
Different versions of GNOME maybe? Idk. I'll check it out this morning after I get off work. Ubuntu also mutilates GNOME so who knows?

**Comment by TingPing** [comment]
Maybe the way Gtk looks up the current icon theme is not used by KDE.

**Comment by JasonLG1979** [comment]
I don't know but I used the python3 script from here: http://stackoverflow.com/questions/6090241/how-can-i-get-the-full-file-path-of-an-icon-name changing "my-icon-name" to "emblem-favorite" and it prints the path to the emblem-favorite icon.

**Comment by JasonLG1979** [comment]
It's got to be a bug in either the settings module that KDE-a-fies GTK apps or in the Oxygen theme it's self that ships with Kubuntu. (I also have the Kubuntu updates ppa activated/installed so there's that too.) But anyway if I set the GTK3 theme to "default" and the icon theme to GNOME for GNOME apps this is what I get:
![snapshot1](https://cloud.githubusercontent.com/assets/6667703/6997020/b941cc5c-db6f-11e4-9b14-bc87af63302d.png)

It's U-G-L-Y but the icons are there. I'll test in Kubuntu 14.04, 14.10(no updates ppa) and 15.04 and report back but my guess is you're doing it right it's a problem with Kubuntu.
