### ISSUE TITLE
A couple of possible improvements/questions.

### ISSUE THREAD

**Issue by JasonLG1979** [pithos/pithos#170]
1. As far as I can tell the only thing the tag handler is used for is determining the bitrate of the stream. Is there a specific reason why Pithos doesn't just get the bitrate from the audiourl info Pandora provides? It's what's used in the debugging messages.

2. Along similar lines 'includeTrackLength' in the station.getPlaylist method causes Pandora to provide the song duration so Gstreamer doesn't really need to be involved in that either. Again is there a reason for not using the song duration that Pandora provides? 

I have working code that uses the info provided by Pandora. The result is that the info shows up in the UI instantaneously instead of having to wait for Gstreamer to figure it out. And of course Gstreamer/Pithos has to do less.

**Comment by TingPing** [comment]
Well the information gstreamer gives is certain to be the correct value. That said I'm not sure if that is relevant. The one situation that comes to mind is ads since they are detected by being short.

**Comment by JasonLG1979** [comment]
I'm testing that now. If Pandora provides the actual duration time when it's an ad it should actually make detecting ads easier. You'd be able to actually show them as ads in the playlist since the duration info is provided by playlist.

**Comment by TingPing** [comment]
That would be nice.

**Comment by JasonLG1979** [comment]
I can't get Pandora to play a commercial even on my wife's non-Pandora One account. Anyway, if Pandora does report actual duration of commercials then the existing code should work pretty much as is. Here's a code dump of that code and some other stuff I'm experimenting with. if anyone wants to test it out. https://github.com/JasonLG1979/pithos/tree/JasonLG1979-experimental

**Comment by JasonLG1979** [comment]
Well partial success, I still can't get Pandora to play an ad but I can get it to nag me with the whole "multiple streams" message which does show up as an ad and allows me to test moving ad detection to the connection side of things so that when playlists are loaded ads should show up as ads in the playlist as ads. The question still remains if Pandora report accurate duration times for ads in a playlist aside from the "multiple streams" nag, or if it just does a switch-a-roo last minute and plays an ad instead of the originally intended song? 

Here's what the results look like for the nag. If all goes well I'd like to also replace the cover art for ads also.

![snapshot3](https://cloud.githubusercontent.com/assets/6667703/7075396/470141e4-dec7-11e4-8b81-81fb16134e3c.png)

**Comment by JasonLG1979** [comment]
Working on this stuff. Closing this.
