### ISSUE TITLE
Network buffering, doing it right?/User adjustable buffer size in preferences.

### ISSUE THREAD

**Issue by JasonLG1979** [pithos/pithos#171]
I've been reading up on network stream buffering with Gstreamer and Pithos doesn't seem to be doing it as well as it could. http://gstreamer.freedesktop.org/data/doc/gstreamer/head/manual/html/section-buffering-strategies.html seems to suggest that when buffering network streams you should start the pipeline in the paused state and wait for the async_done message before even caring if the buffer is full. Using the default buffer size also seems to be a bad idea as it seems to be way to small for the 192 kbit/s stream and to large for the 64/32 kbit/s the result is that while initially buffering the 192 stream (on Gsteamer 1.4 at least) the buffer fills and drains a couple times before playback begins. And 64/32 kbit/s streams seem to buffer more than needed. Setting the buffer size to match the stream bitrate with set_property('buffer-size') (self.player.set_property('buffer-size', 192000) for the 192 stream for example) so that it buffers 1 sec of audio before it tries to begin playback seems to work pretty good for me, but it would be nice to have a UI option to adjust the buffer size in seconds.

My experimental branch has code (among other things) that automatically adjusts the buffer-size based on stream bitrate.
https://github.com/JasonLG1979/pithos/tree/JasonLG1979-experimental

**Comment by TingPing** [comment]
>My experimental branch has code (among other things)

It would be really nice if your commits were actually well organized in multiple branches and had useful titles to actually figure out what is going on.

>but it would be nice to have a UI option to adjust the buffer size in seconds.

No reason for an option. It should "Just work".

**Comment by JasonLG1979** [comment]
It's an experimental branch. I'm not going to do pull requests from it. It's just a place for me to play around. When/if I come up with anything useful I'll do a proper branch and to requests off that.

It would also be nice if someone would review the pull request I have pending ;P

1 sec of buffer seems to "just work" for me.

**Comment by JasonLG1979** [comment]
I'm not an organized person. That's not how I work.

**Comment by JasonLG1979** [comment]
There I broke it up into more easily understandable commits.

Basically the changes are as follows:

Created a new buffer ui loop at 10fps to use during buffering to update the UI otherwise update_song_row hammers the UI with 100 updates in less then a 1/10 of a second for no good reason.

Dynamically set buffer-size according to bitrate.

Added buffering function and state statuses.

Improved buffering behavior. Start pipeline in paused state and only allow it to go to play when/after the async_done message is received.

Get bitrate and codec info from Pandora instead of Gstreamer.

**Comment by TingPing** [comment]
Very nice, In my brief usage everything is working well. Like a year ago I moved the buffer message out of the song tab into a progressbar in the statusbar, would you be interested in that?

**Comment by JasonLG1979** [comment]
Yep, I like the status bar idea a lot better. I'd still like to limit the updates to 10fps so it's easier on the CPU. 10fps seems to be enough to get the point across.

**Comment by JasonLG1979** [comment]
I think the biggest improvement is the dynamic buffer-size. With the default buffer-size the buffer fills and drains sometimes up to 3 times before playback starts. Switching back and forth between pause and play states that fast could be the cause of the random stop bug?

**Comment by JasonLG1979** [comment]
There I added your progress bar to my branch. I set a time out of 50 to equal @20fps. 10fps wasn't quite smooth enough. I also changed the message in the song text to just read "Buffering..." when it's buffering.

**Comment by JasonLG1979** [comment]
Is it possible to move the "Buffering" text to the actual progress bar?

**Comment by TingPing** [comment]
> Is it possible to move the "Buffering" text to the actual progress bar?

I just did: https://github.com/pithos/pithos/commit/58c3a64d7cc8e9ff1dc2887bad742485e6723178

**Comment by JasonLG1979** [comment]
I like that!!! I got rid of the ()'s around the percent though. I think it looks better without them. It works pretty nice. I added it to my branch.

**Comment by JasonLG1979** [comment]
I'm going to get myself banned for skipping to many song so I can see the progress bar in action,lol!!!

**Comment by TingPing** [comment]
Also ping @glennimoss since he was the last person to touch this area of code.

**Comment by JasonLG1979** [comment]
It's a metric crap ton of changes. I think I may have stepped on just about everyone's code ;P

**Comment by JasonLG1979** [comment]
It also needs to be tested on Gstreamer 1.2, the version that ships with Ubuntu 14.04. Personally for me that's about as far as I'd like to go back as far as compatibility to the most recent Ubuntu LTS.

**Comment by gregsheremeta** [comment]
@JasonLG1979 absolutely fantastic work. Running this today.

I can't believe I never looked into the buffer size -- I assumed playbin was dynamically setting the buffer size, but I guess it was not? Crazy!

Do we think 1s is enough of a buffer?

**Comment by JasonLG1979** [comment]
> absolutely fantastic work. Running this today.

Not bad for a guy who 6 months ago didn't even know what Python was huh,lol!!!

> Do we think 1s is enough of a buffer?

That is a very good question. It seems it pretty much has to be <i>at least</i> 1 sec to keep the buffer from double tapping at the beginning of a song. As far as if it's long enough that's another story. For the 32 and 64 streams I'd say probably. In Gstreamer 1.2 and 1.4 mp4/aac's are download buffered. If you look in ~/.cache you'll see the file. Buffering should only ever really happen at the beginning of the song. The same is true for Mp3's in Gstreamer 1.4. But Mp3's are <b>NOT</b> download buffered in Gstreamer 1.2. That's really the only wild card.

**Comment by JasonLG1979** [comment]
@gregsheremeta Have you had any random stop issues? Not letting it go to play until async-done seems to solve that problem for me.

**Comment by gregsheremeta** [comment]
I'm on gstreamer 1.2 mp3. I'll play around with a larger buffer over the next few days and let you know what I find out.

**Comment by gregsheremeta** [comment]
Not yet -- but it only happens for me when my system is under decent load. And I've only been running your branch for about 2 hours. So, gimme a couple days :)

**Comment by JasonLG1979** [comment]
I turned download buffering off by commenting out the line and it seemed to still work just fine but I have a very stable 50Mbps internet connection. That's why I'd like there to be and option to manually set the buffer size in the preferences UI. Not everyone has fast, stable internet.

**Comment by JasonLG1979** [comment]
It would be as simple as self.player.set_property('buffer-size', int(self.current_song.bitrate)*1000*self.buffer_size_in_seconds)

**Comment by JasonLG1979** [comment]
> I assumed playbin was dynamically setting the buffer size, but I guess it was not? Crazy!

I can't really find a definite answer in the docs for playbin but filesink's default buffer-size is 65536 bytes. playbin seems to be using the same value by default. That would account for the double tap as that's only .34133 secs of buffer at 192.

**Comment by gregsheremeta** [comment]
> That's why I'd like there to be and option to manually set the buffer size in the preferences UI. 

I'm not against it. I also have a 50mbps solid connection (soon to be 300 :D)

If we really want to avoid an option, what if you start out with say 2s, and then if you detect rampant buffering, go to 4s. I'm just picking somewhat random numbers.

**Comment by JasonLG1979** [comment]
Anything over 1 sec just delays the start of the song with no benefit. But I could write a bit of code that starts at 1 sec and uses the time it took to buffer the previous song as a multiple to determine the buffer size for the next song. If you change the buffer-size while the pipeline is buffering or playing it locks up the last time I tried.

**Comment by JasonLG1979** [comment]
The code that @glennimoss put in there to tell how long buffing takes generally says that the buffer completes for me in under 0.009 seconds. And like I said 1 sec is about 3 times the default buffer already as it is.

**Comment by JasonLG1979** [comment]
3 times at 192 anyway.

**Comment by JasonLG1979** [comment]
I messed around with the code I was talking about and it didn't really show any benefit. Anything over 1 sec is more than needed and just delays the start of the song, anything under under 1 sec causes multiple fill/drains before startup and anything under about 0.2 sec causes distortion and constant buffering throughout the song. 1 sec seems to be the sweet spot for me.

**Comment by JasonLG1979** [comment]
My vote is set it at 1 sec and leave it, if anything to stop the buffer double tap on 192. Has anyone reported problems with the default buffer-size? Namely stuttering or distortion at the beginning or throughout the song?

**Comment by TingPing** [comment]
FYI there are various tools to simulate poor connections if somebody wanted to test some reasonable ranges.

**Comment by glennimoss** [comment]
I actually have a pretty extensive refactor of the gstreamer code that I'm just finishing testing. It separates all the media playing code from the UI code. It also addresses this buffering issue by doing it in a completely different way. I'll try and get the PR submitted on Monday, probably.

**Comment by TingPing** [comment]
> It separates all the media playing code from the UI code

Oh thank god. Moving the player into its own file has been on my todo list for years :P

**Comment by JasonLG1979** [comment]
> It also addresses this buffering issue by doing it in a completely different way

Aside from dynamically setting buffer-size I followed the docs as far as I can tell.
http://gstreamer.freedesktop.org/data/doc/gstreamer/head/manual/html/section-buffering-strategies.html says:

"See how we set the pipeline to the PAUSED state first. We will receive buffering messages during the preroll state when buffering is needed. When we are prerolled (on_message_async_done) we see if buffering is going on, if not, we start playback. If buffering was going on, we start a timeout to poll the buffering state. If the estimated time to download is less than the remaining playback time, we start playback."

**Comment by glennimoss** [comment]
Yeah, even following the docs it wasn't really good enough. The problem is that the gst component that deals with the buffering reports the buffer based on how much data it's holding on to. In one side comes the http data stream, and it goes out to the play sink. The problem is the data doesn't really stick around in the buffer, so it never reports the buffer as being 100%. It seems to just bounce around from 1% to 9% (for me anyways.) The buffering logic I wrote is based off the download progress instead.

**Comment by JasonLG1979** [comment]
The buffer reports 100% for me on both formats? If a buffer works properly it should fill to 100% and then (in my case after 1 second worth of audio) begin to play. Provided the source of the buffer, either the http stream or the cached file, depending on what version of Gstreamer it should fill pretty much 1 for 1 as it's drained. As long as the input is enough to keep up with the output it should never go below 100% once it's full in theory.

**Comment by JasonLG1979** [comment]
> The buffering logic I wrote is based off the download progress instead.

By download progress do you mean the download progress of the cached file in .cache/? If so that's not going to work with the MP3 stream on Gstreamer 1.2 as it doesn't download buffer MP3's.

**Comment by JasonLG1979** [comment]
What about a ring-buffer?

**Comment by glennimoss** [comment]
It does download if you set the right options. I've tested it with both MP3 and AAC. You can look at the code when I get the PR in. 

Getting a little off-topic here, but I remember @JasonLG1979 mentioned he had some kind of VLC based backend working. My refactor makes the player component pluggable so it would be cool to incorporate both (and one day maybe more) with an option to choose between your backend provider.

**Comment by JasonLG1979** [comment]
Right on I'll check it out. What are you doing to get it to download buffer mp3s? In gstreamer 1.2(the version that comes with Ubuntu 14.04) setting the download buffer flag causes it to download buffer aac's but not mp3's. On gstreamer 1.4(Ubuntu 14.10) setting the flag does cause it to download buffer mp3's. 

As far as the vlc back end. It needs a lot of work.

**Comment by glennimoss** [comment]
I'm trying to test out the behavior of gstreamer 1.2.3 (what comes with ubuntu 14.04.) Any idea how to run against a different version of gstreamer in 14.10? I've compiled from source, messed with $LD_LIBRARY_PATH, etc., and it ALMOST works... But not quite. :P

Maybe I should just make a VM...

**Comment by JasonLG1979** [comment]
I'm for sure not an authority on the subject but my 2 cents worth says a real install of Ubuntu 14.04 would be the best to test against Ubuntu 14.04. There's nothing like the real thing,lol!!!

**Comment by JasonLG1979** [comment]
Working on this. Closing it.
