### ISSUE TITLE
Media keys don't work in Mate desktop.

### ISSUE THREAD

**Issue by rathboma** [pithos/pithos#172]
I'm using Mint 17.1 Mate edition and pressing Back/Play/Next keys does nothing. I'm installing Pithos from the Ubuntu PPA.

This is due to a namespace change in Mate vs the original Gnome namespace used in Gnome2 (and 3).

There's a discussion on the topic here - http://forums.linuxmint.com/viewtopic.php?f=47&t=102626

Not sure how hard this would be to do, but it would be great for us Mate users.

**Comment by TingPing** [comment]
Can you verify that changing these lines to mate instead of gnome works for you: [mediakeys.py#L33](https://github.com/pithos/pithos/blob/7c8b5627dce446f1c66edcd351e30f3bd4904f6c/pithos/plugins/mediakeys.py#L33)

**Comment by wscalf** [comment]
For what it's worth, making that change worked for me on Mint 18 (Sarah) MATE edition. Diff:
36,37c36,37
<             mk = bus.get_object("org.gnome.SettingsDaemon","/org/gnome/SettingsDaemon/MediaKeys")
<             mk.GrabMediaPlayerKeys(APP_ID, 0, dbus_interface='org.gnome.SettingsDaemon.MediaKeys')
---
>             mk = bus.get_object("org.mate.SettingsDaemon","/org/mate/SettingsDaemon/MediaKeys")
>             mk.GrabMediaPlayerKeys(APP_ID, 0, dbus_interface='org.mate.SettingsDaemon.MediaKeys')
