### ISSUE TITLE
Part of the About Dialog turns transparent in Ubuntu.  

### ISSUE THREAD

**Issue by JasonLG1979** [pithos/pithos#178]
In Ubuntu(15.04 at least) if you open the about dialog, after you click the "Credits" button to show the credits and then click it again part of the about window becomes transparent. It's caused by Unity's overlay scrollbar. Starting Pithos with LIBOVERLAY_SCROLLBAR=0 solves the problem. Just a heads up in case others file future bug reports on this so you can reference this report and close them.

![screenshot from 2015-04-22 18 35 42](https://cloud.githubusercontent.com/assets/6667703/7287873/92c1c4fc-e91f-11e4-820f-e38d81e9d613.png)

Feel free to close this when you guys notice it as I wouldn't expect a Unity specific fix for such a minor cosmetic bug that's clearly Ubuntu's fault.

**Comment by TingPing** [comment]
You would not believe the number of bugs mentioned in #gtk+ when it comes to the Unity scrollbars. Anyway upstreams bug tracker is on launchpad..

**Comment by JasonLG1979** [comment]
The version of Pithos in the default repo is ancient and Pithos on launchpad seems pretty much abandoned. I'm curious how one would become a maintainer of Pithos for Ubuntu so it would get a more up to date version?

**Comment by TingPing** [comment]
>Pithos on launchpad seems pretty much abandoned

I mean't their liboverlay project or whatever it is called, surely this bug applies to all Gtk3 applications.

> I'm curious how one would become a maintainer of Pithos for Ubuntu so it would get a more up to date version?

You would basically become a packager for Debian. They already have bugs open to update it, not sure whats holding it up.

**Comment by JasonLG1979** [comment]
> I mean't their liboverlay project or whatever it is called, surely this bug applies to all Gtk3 applications.

Pretty much unless you specifically patch it to deal with it. Which doesn't seem worth it. Seems kinda backwards to patch an otherwise perfectly working app to work with a dang scroll bar. They probably should just fix the scroll bar so it doesn't break apps. But they won't because it's Ubuntu. "Whatever, I do what I want!!!" lol!!!
