### ISSUE TITLE
Change up the Preferences dialog?  

### ISSUE THREAD

**Issue by JasonLG1979** [pithos/pithos#180]
Before:
![before](https://cloud.githubusercontent.com/assets/6667703/7323634/b0ba0378-ea75-11e4-8e89-1647988200bd.png)

Here's a mockup of my suggestions:
![after](https://cloud.githubusercontent.com/assets/6667703/7323636/bd53409a-ea75-11e4-9f83-baf3fc3f4b1a.png)

Align the text and input boxes better and move the audio quality combo box.(audio quality isn't really an advanced option)

**Comment by gregsheremeta** [comment]
+1 looks nicer. I'd make it just a bit wider so the proxy labels aren't so squished.

**Comment by TingPing** [comment]
I think wider is good but I also think the link looked better centered and the checkbox looks worse right justified.

I would really like to kill that Pandora One checkbox entirely though.. its pretty stupid that we have to specify ahead of time what our account is.

**Comment by TingPing** [comment]
Oh also the heading is "Account" and sound quality doesn't really relate to your account.

**Comment by gregsheremeta** [comment]
Does the Pandora One checkbox have any functionality?

**Comment by TingPing** [comment]
It sets a different client key.

**Comment by JasonLG1979** [comment]
> Oh also the heading is "Account" and sound quality doesn't really relate to your account.

No but it's an account setting.

> I would really like to kill that Pandora One checkbox entirely though.. its pretty stupid that we have to specify ahead of time what our account is.

You can if you look at the Pandora API there's isSubscriber. Basically from what I understand you can pass that with the username and password and Pandora will tell you if the user has a Pandora One account. From then you can use that to automatically set the client key accordingly.

**Comment by JasonLG1979** [comment]
> +1 looks nicer. I'd make it just a bit wider so the proxy labels aren't so squished.

Right now it's just a mockup in GIMP. No actual code.

**Comment by JasonLG1979** [comment]
I've also wondered why there are 3 different quality settings. For a non-Pandora One account High and Medium are both 64 and low is 32. For a Pandora One account High is 192, Medium is 64 and there is no low. Really there only needs to be High and low. High should be 192 or 64 and low would be 64 or 32 depending on if you have a Pandora One account.

**Comment by eode** [comment]
I really think that rather than just "<quality>", it should say "<quality> (<rate>)", as my primary purpose to change rates is bandwidth-related, and I don't think I'm alone in that by any stretch of the word.  Example menu content:

High (192kbps)
Medium (64kbps)
Low (32kbps)

Regarding JasonLG's comment:  Do you mean that as a Pandora One subscriber, that the 32kbps option is no longer available to me?   ..is this API level, or just what Pandora's official clients do?

**Comment by JasonLG1979** [comment]
Currently Pithos requests either "highQuality", *mediumQuality", or "lowQuality" for both free and Pandora One users. For free users Pithos pretends to be the Android client. And for Pandora One users Pithos pretends to be the adobe AIR desktop client. When Pithos requests a playlist it gets the url's for all possible qualities for the particular client that it's pretending to be. It just so happens that 32 and 64 are the only available formats for the Android client we are pretending to be and 64 and 192 are the only formats available for the adobe AIR client we are pretending to be. Other streams are available if we request additional formats but that's not how it currently works. As it sits we ask for a particular quality and Pandora decides what we get.
