### ISSUE TITLE
Plugin request: explicit song filter 

### ISSUE THREAD

**Issue by JasonLG1979** [pithos/pithos#181]
It's possible to tell Pandora to not play explicit song as far as I can tell from the API.

I normally wouldn't care about explicit lyrics but a situation last weekend made me think that having the ability to filter out explicit song might not be a bad idea. My kids had a bunch of their friends over and Pantera F'n Hostile started playing. F'n Hostile doesn't faze my kids since they've been listening to Pantera since the womb, but I really don't need the neighbors coming over wondering why their kids are screaming the f word like a demon after visiting my house,lol!!!

It could also be useful in other situations where you don't want explicit songs played too, like work for example.

I'll see what I can come up with but other more talented individuals might be able to whip something up a lot faster then I can.

**Comment by gregsheremeta** [comment]
You're a fantastic parent for raising the kids on Pantera.

That is all.

**Comment by JasonLG1979** [comment]
> You're a fantastic parent for raising the kids on Pantera.

Parenting done right,lol!!!

**Comment by doyousketch2** [comment]
I dunno how you could block all adult songs locally, 'cuz Pandora sends somewhat random songs.
You could tag ones you happen to hear play, but you'd have catch 'em before they come.

A better method would be if the songs you tagged are shared.
As far as I know there's no internet blocklist for adult songs.

If you feel like manufacturing one, then everyone who tags a song could, in theory, help others to keep kids safe, in that regard.

I think each song would need to have a least a few votes before they're considered blacklisted for the community.  So you'd need someone to essentially maintain the list, make sure only valid songs are tagged.

Maybe something simple like a wiki-page where anyone can add a song, then others can up-vote or down-vote entries, with an admin who can have a final say-so.

While do-able, it seems like a lot.  You might be better off picking a station that won't, or toggling the explicit filter on your Pandora account, or creating another username that's always set as such just for that purpose.

https://www.internetsafetyproject.org/wiki/how-filter-explicit-songs-pandora

**Comment by TingPing** [comment]
@doyousketch2 Uh.. yea we can just set that account option - http://6xq.net/playground/pandora-apidoc/json/account/#settings

**Comment by doyousketch2** [comment]
Oh, ok.  I read the first sentence in the thread wrong.
I thought Jason was saying it wasn't possible through the API.

**Comment by JasonLG1979** [comment]
> Uh.. yea we can just set that account option - http://6xq.net/playground/pandora-apidoc/json/account/#settings

That's exactly what I was talking about.

**Comment by JasonLG1979** [comment]
In a perfect world. It would be in the plugin section. And like I said in another issue. There's also a way to tell if a user has a Pandora One account on that same doc page so we could also get rid of the Pandora One check box in the preferences dialog.

**Comment by TingPing** [comment]
>In a perfect world. It would be in the plugin section

I think that is a fairly reasonable thing to just have under account in preferences.

**Comment by JasonLG1979** [comment]
Whatever works. It could basically just replace the Pandora One checkbox if we made Pithos automatically check for Pandora One.

**Comment by JasonLG1979** [comment]
@TingPing:
turn_explicit_filter_on = self.json_call('user.setExplicitContentFilter', {'isExplicitContentFilterEnabled': True})

turn_explicit_filter_off = self.json_call('user.setExplicitContentFilter', {'isExplicitContentFilterEnabled': Fasle})

That's pretty much all that's needed to toggle the explicit content filter setting except the UI bits. Was wondering if maybe you could throw something together?(the user has to be authenticated/logged in before it's called)

**Comment by TingPing** [comment]
@JasonLG1979 Maybe. So if you set this it is account wide on every device or does it need to be set every login? Will be slightly tricky, would want to have the toggle insensitive until you log in and I don't think the Pandora module really exposes that (Wish it was just a GObject but that is a whole different issue).

**Comment by JasonLG1979** [comment]
I'll have to check but I'm pretty sure that it's account wide. But yep you have to be logged in to get the state of it and change it. If you try to to set it before the user is logged in you get a error about not be authenticated. So it would have to be insensitive until the state is figured out. Why not make it a GObject?

**Comment by TingPing** [comment]
> Why not make it a GObject?

- Adds a very large dependency for any external project using our module
- Just one of many many things on my todo list...

**Comment by JasonLG1979** [comment]
Right on. Keeping it pure python keeps it more portable.
Anyway...
get_explicit_fliter_state = self.json_call('user.getSettings', {'includeFacebook': False}, https=True)
if ('isExplicitContentFilterEnabled') in get_explicit_fliter_state:
    is_explicit_fliter_set = get_explicit_fliter_state['isExplicitContentFilterEnabled']

Will tell you the state of the filter.

**Comment by JasonLG1979** [comment]
@TingPing I've got a working prototype of a complete implementation. I'll put the code in a branch this weekend for you to look at. I'm sure it could use some polish.

Basically it works like this... Pithos starts with the check box setting handler disabled until we're authenticated and then we query the setting and override the saved pref right before we ask for a playlist(and then after that we resync the setting every time we ask for a playlist so the setting stays in sync since it can be changed outside of Pithos) then the check box works as expected. The change to the filter take effect as far as Pandora is concerned when the box is toggled but to the user it wouldn't take effect until they get a new playlist.

I use a signal to talk to pithos.py from the pref dialog.py to change the settings.

![desktop_001](https://cloud.githubusercontent.com/assets/6667703/10858764/60ce07b6-7f25-11e5-9e45-cf373473f369.png)

**Comment by JasonLG1979** [comment]
@TingPing I've completely decoupled it from the settings, ie: Pithos doesn't save a setting for the filter setting since, like I said before the setting is account wide and "lives" in/at Pandora. I need your opinion on the behavior. On 1st run the current state of the filter is not know since the user is not signed in yet. So I set the check box as clickable and delay the setting of the filter to after connection but before a playlist is fetched so the check box's state/user selection is honored. The alternative is to make the check box unclickable during 1st run. After 1st run the check box state is synced with Pandora every time the prefs window is opened and made unclickable for the split sec it takes to ask Pandora the state of the filter and then set to reflect the current filter state and made clickable. In that way it's always in sync. The big question is when the filter state is changed should a new playlist be fetched immediately to reflect the change or should the remaining songs in the playlist be allowed to play out(the filter setting will not take effect until a new playlist is fetched)?

**Comment by TingPing** [comment]
If explicit songs are disabled I think it makes sense to get a new playlist but is less important if they are being enabled.

Regarding sensitivity I'm not sure which I prefer, I'd have to see how smoothly it all works out but I would guess that pretending to set it before log in might have some unobvious behaviour.

**Comment by JasonLG1979** [comment]
> If explicit songs are disabled I think it makes sense to get a new playlist but is less important if they are being enabled.

I can see that. If you want to go filter enabled to disabled it's less important than if you want to go from filter disabled to enabled. 

> Regarding sensitivity I'm not sure which I prefer, I'd have to see how smoothly it all works out but I would guess that pretending to set it before log in might have some unobvious behaviour.

It's not pretending. It gets set to what the box is at 1st run. It's just that it has potential to override the account setting if it differs.

**Comment by TingPing** [comment]
> It's just that it has the potential to override the account setting if it differs.

That is what I would call unobvious behaviour.

**Comment by JasonLG1979** [comment]
> That is what I would call unobvious behaviour.

No problem, it can be set to unclickable on 1st run.

**Comment by JasonLG1979** [comment]
@TingPing What do you think of this... https://github.com/JasonLG1979/pithos/tree/explicit_content_filter
