### ISSUE TITLE
Stop is only used internally in Pithos. It should not be exposed to the user.

### ISSUE THREAD

**Issue by JasonLG1979** [pithos/pithos#183]
Stop is only used internally in Pithos. It isn't exposed to the user anywhere else. It shouldn't be exposed to the user in _mpris.py. It should either be mapped to pause or passed(my vote) or some logic needs to be come up with so that if you press stop and then play again it skips to the next song and plays it. Right now if you hit stop and then play again it starts the song over. Which IMHO is not expected behavior for a "Radio" player.

**Comment by JasonLG1979** [comment]
No comments/thoughts on this? Anyone?

**Comment by TingPing** [comment]
Pausing seems reasonable. Shame mpris requires exposing stop of some sort.

**Comment by gregsheremeta** [comment]
Agree, I vote for mapping it to pause. Definitely should be no starting a song over :-/

**Comment by JasonLG1979** [comment]
The mpris plugin needs a lot of work. While messing with adding track time to it I found that basically every time ANY property is updated it takes the nuclear route and updates EVERYTHING. Aside from actually changing the metadata every action pretty much tells mpris that there's a new song.

**Comment by JasonLG1979** [comment]
> Definitely should be no starting a song over :-/

That's actually what it's suppose to do according to spec, start the song over. That just doesn't fit for Pithos.

http://specifications.freedesktop.org/mpris-spec/latest/Player_Interface.html#Method:Stop
