### ISSUE TITLE
Please update the Ubuntu PPA

### ISSUE THREAD

**Issue by hotice** [pithos/pithos#190]
Can you please push the latest Pithos 1.1.0 to the Ubuntu PPA? 

To make it easier, I uploaded the latest version to my test PPA: https://launchpad.net/~nilarimogard/+archive/ubuntu/test/+copy-packages?field.name_filter=pithos&field.status_filter=published&field.series_filter= - you can copy it directly to the Pithos PPA or reupload it.

Also, since the changelog says that Pithos 1.1.0 requires GTK >= 3.14, and the old 1.0.1 version has the severe buffer bug: https://github.com/pithos/pithos/issues/94 , I also built packages with version 1.0.1 for Ubuntu 14.10 and 14.04 LTS which include a patch to disable the download buffer, fixing this major issue. The packages are in the same PPA listed above, feel free to copy them to the Pithos PPA.

**Comment by gregsheremeta** [comment]
Thanks, that's really awesome of you!

I had 1.1.0 ready to go in our staging repo [1]. I'll push that to our official pithos PPA (only for vivid) right now.

For 14.10 and 14.04, we're going to release a 1.0.2 with that fix. I can get that done, packaged, and pushed today.

Sounds like you're an experienced Debian packager. I'm a novice. Do you mind looking at my packaging script [2] and giving me feedback? Packaging python in Ubuntu seems ridiculously hard.

[1] https://launchpad.net/~gsheremeta/+archive/ubuntu/pithos-staging/+packages
[2] https://github.com/gregsheremeta/pithos-debian-package

**Comment by hotice** [comment]
Why not use the already existing packaging (the one used in the PPA), which I tweaked a while back? Using that, you won't need an "install" file and you can use the source from the GitHub  instead of a modified source which I see is used in the staging PPA. 

Here's your packaging from the staging PPA merged with the changes from the official Pithos PPA: https://dl.dropboxusercontent.com/u/1113424/pithos-1.1.0.tar.gz

Changes:
- removed the `debian/install` file
- to get the package to build with Python 3 properly, changed `dh $@ --with=python3` to `dh $@ --with=python3 --buildsystem=pybuild` in the `debian/rules` file
- control: added `Build-depends` to `python3-setuptools`
- used the original .tar.gz from GitHub which includes setup.py, etc. 
- used `3.0 (quilt)` in debian/source/format to allow using pithos_1.1.0.orig.tar.gz
- since the new version requires gtk >= 3.14, I modified the control file and added "libgtk-3-0 (>= 3.14)" to the package "Depends".

I hope this helps.

**Comment by gregsheremeta** [comment]
Thanks, that helps a lot. I need to read about quilt.

**Comment by gregsheremeta** [comment]
@hotice I'm stuck. Any idea? Google turns up nothing.

```
greg@ubuntu-1504-1:~/projects/pithos-debian-package/build/pithos-1.1.0$ debuild -S -sa
 dpkg-buildpackage -rfakeroot -d -us -uc -S -sa
dpkg-buildpackage: source package pithos
dpkg-buildpackage: source version 1.1.0-1
dpkg-buildpackage: source distribution vivid
dpkg-buildpackage: source changed by Greg Sheremeta <greg@gregsheremeta.com>
 dpkg-source --before-build pithos-1.1.0
 fakeroot debian/rules clean
debian/rules: line 4: fg: no job control
   dh_testdir -O--buildsystem=pybuild
   dh_auto_clean -O--buildsystem=pybuild
	pybuild --clean -i python{version} -p 3.4 --dir .
E: pybuild pybuild:82: cannot detect build system, please use --system option or set PYBUILD_SYSTEM env. variable
dh_auto_clean: pybuild --clean -i python{version} -p 3.4 --dir . returned exit code 11
dpkg-buildpackage: error: fakeroot debian/rules clean gave error exit status 11
debuild: fatal error at line 1376:
dpkg-buildpackage -rfakeroot -d -us -uc -S -sa failed
```

rules file:
```
export DH_VERBOSE=1
export PYBUILD_NAME=pithos

%:
	dh $@ --with python3 --buildsystem=pybuild --system=setuptools
```

relevant error seems to be
```
E: pybuild pybuild:82: cannot detect build system, please use --system option or set PYBUILD_SYSTEM env. variable
```

I tried folllowing that advice, but same error.

**Comment by hotice** [comment]
I'm not sure, I've never encountered this issue. Hmm try installing `dh-python` and `python3-setuptools` and see if it still occurs.

**Comment by hotice** [comment]
By the way, I just tried it in a fresh Ubuntu 14.04 virtual machine and it works (I only installed `python3-setuptools` and `devscripts`). 

Also, I uploaded the exact packaging which I linked in my earlier comment to a test PPA and everything seem to work...:
PPA: https://launchpad.net/~nilarimogard/+archive/ubuntu/test5/+packages
build log: https://launchpadlibrarian.net/206197409/buildlog_ubuntu-vivid-amd64.pithos_1.1.0-1_BUILDING.txt.gz

So probably something on your system triggers that error (maybe you've installed some newer packages via pip).

**Comment by hotice** [comment]
A few more things to check for:
- make sure this is available at the top of the rules file: `#!/usr/bin/make -f`
- before `dh $@ --with=python3 --buildsystem=pybuild` there's a tab

**Comment by gregsheremeta** [comment]
Thanks. I'm on a fresh 15.04 machine. I'll try 14.04.

**Comment by hotice** [comment]
I'm also on 15.04 so that's not it...

**Comment by gregsheremeta** [comment]
I ran out of time, so I released using my install file. I'll take another crack at setuptools next time. Thanks for the help!

**Comment by gregsheremeta** [comment]
@hotice I got it working. Thanks for the help!

**Comment by hotice** [comment]
Great! I'm glad I could help.
