### ISSUE TITLE
Unclear license

### ISSUE THREAD

**Issue by ibara** [pithos/pithos#191]
Pithos's license is unclear. On the GitHub README.md and Pithos's About pop-up it says it is GPLv3+ yet in code comments it says:
```
# Copyright (C) 2010-2012 Kevin Mehall <km@kevinmehall.net>
# This program is free software: you can redistribute it and/or modify it
# under the terms of the GNU General Public License version 3, as published
# by the Free Software Foundation.
# without the standard "or, at your option, any later version" language.
```
For the [OpenBSD port](http://cvsweb.openbsd.org/cgi-bin/cvsweb/ports/audio/pithos/) I use the following:
```
# Github page says GPLv3+
# But the code says GPLv3 only
# pithos/pandora/blowfish.py: AGPLv3+
```

It would be nice to have this cleared up.

**Comment by TingPing** [comment]
Well blowfish.py is from a third party project so it is under a different license and that is correct.

As for 3+ or 3 I think 3 would be more accurate since the code headers say this

**Comment by kevinmehall** [comment]
For the record: I did not intentionally leave that clause out and am fine with the use of GPLv3+ for any portion of the code for which I hold copyright. However, I'll let the currently-active contributors make a license determination.

**Comment by TingPing** [comment]
> For the record: I did not intentionally leave that clause out and am fine with the use of GPLv3+ for any portion of the code for which I hold copyright. However, I'll let the currently-active contributors make a license determination.

I'm not sure it is worth tracking down every contributor and making sure they agree to a license change.

**Comment by kevinmehall** [comment]
It's not. Especially since the distinction is moot until there's a GPLv4.

I'm not sure if the AGPL blowfish library is an issue. It appears that this implementation replaced a GPL (unclear version) + Artistic implementation with the [port to Python 3](https://github.com/pithos/pithos/commit/64624e243d2d66954590c7b19c52044e7da41a0e).

**Comment by TingPing** [comment]
> I'm not sure if the AGPL blowfish library is an issue.

Shouldn't be:

> Notwithstanding any other provision of this License, you have permission to link or combine any covered work with a work licensed under version 3 of the GNU General Public License into a single combined work, and to convey the resulting work. The terms of this License will continue to apply to the part which is the covered work, but the work with which it is combined will remain governed by version 3 of the GNU General Public License.

and since pithos is not a networked service the extra clauses of the AGPL3 don't really apply.
