### ISSUE TITLE
I'm on version 1.0.2-2ppa1 but about tab says 1.01

### ISSUE THREAD

**Issue by JunkYardTM** [pithos/pithos#193]
Is everything 42's?

**Comment by gregsheremeta** [comment]
> Is everything 42's?

Huh?

> I'm on version 1.0.2-2ppa1 but about tab says 1.01

I just checked the [deb file](https://launchpad.net/~pithos/+archive/ubuntu/ppa/+files/pithos_1.0.2-2ppa1_all.deb), and it definitely has 1.0.2 in there. So this is some kind of installation problem. Can you:

```
sudo apt-get purge pithos
sudo updatedb
locate pithos | grep site-packages
```
output of that `locate` should be empty. If it finds files in /usr/lib/python, pithos isn't actually purged. You'll have to manually delete those files.

Then reinstall pithos again and you should be good.

```
sudo apt-get update
sudo apt-get install pithos
```

**Comment by JunkYardTM** [comment]
Still shows 1.0.1

**Comment by gregsheremeta** [comment]
Sure.

Did you use apt-get to install it?

Run `locate pithosconfig.py` and see if you find another copy hiding somewhere else on your system. Paste the results here.

**Comment by JunkYardTM** [comment]
I did as you suggested, yes. 

locate pithosconfig.py returns nothing.

Nor did: locate pithos | grep site-packages btw

:|

**Comment by gregsheremeta** [comment]
Try `sudo updatedb && locate pithosconfig.py`

**Comment by JunkYardTM** [comment]
Ah ha

/usr/lib/python3/dist-packages/pithos/pithosconfig.py

**Comment by JunkYardTM** [comment]
I wish I had a dollar for every time I ran locate without updating. I'd have some beer money..

**Comment by gregsheremeta** [comment]
Now `grep VERSION /usr/lib/python3/site-packages/pithos/pithosconfig.py`

**Comment by JunkYardTM** [comment]
/usr/lib/python3/dist-packages/pithos/pithosconfig.py:VERSION = '1.0.2'
/usr/lib/python3/dist-packages/pithos/pithosconfig.py:    print(VERSION)

Reboot wouldn't be required I'd think?

**Comment by gregsheremeta** [comment]
You probably have a pithos process hanging around. I'd reboot to be safe.

**Comment by JunkYardTM** [comment]
I'll give it a shot. When I start it, it lost my settings as expected but I'll brb.

Thanks

**Comment by JunkYardTM** [comment]
That did it. 

It did remember the pandora login info actually. How would it have done that through the purge, out of curiosity?

Great help,, great app.

Obliged sir

**Comment by gregsheremeta** [comment]
Linux apps are usually smart enough to store user prefs somewhere other than the install directory. For example, see `~/.config/pithos.ini`. So `purge` removes the app files, but leaves `pithos.ini` alone.

Glad it worked out :)

**Comment by JunkYardTM** [comment]
I just noticed something.

I'm currently out of the States and Pandora doesn't allow streaming here. I have to vpn home etc.

pithos crashes with a "code 0" when I add a station,, refresh etc.

Any chance of adding a sanity check to detect regional restrictions? 
 
;)

**Comment by JunkYardTM** [comment]
New issue?

Again,, thanks.

**Comment by gregsheremeta** [comment]
Yeah, you can open a new issue for that.

**Comment by JunkYardTM** [comment]
Good deal, thanks.
