### ISSUE TITLE
Very high CPU usage during buffering of AAC streams.

### ISSUE THREAD

**Issue by JasonLG1979** [pithos/pithos#198]
As we have come to find out AAC buffering is not well behaved in Gstreamer. As a result of that for AAC streams Pithos receives literately 1000+ buffering messages in the sec or 2 it takes to buffer the stream. On my machine that results in about a 50% CPU usage spike during buffering. The most likely culprit is the "self.update_song_row()" in the buffering function.(since 1000+ buffering messages = 1000+ UI updates.) 

Here's a Video of stock Pithos with a couple added counters to keep track of the buffer messages and recover count to illustrate my point.

https://www.youtube.com/watch?v=nLVIg7wd9gY

I propose that since the buffering % is pretty much useless for AAC streams(as it goes from 0 straight to 100 most of the time.) and the only reason "self.update_song_row()" is in the buffering function is to update said useless buffer message we get rid of it and simply show "Buffering..." in the UI when Pithos is buffering and not actively update the UI during buffering.

Not actively updating the UI during buffering drops the CPU usage down into the 3-8% range on my machine.

**Comment by TingPing** [comment]
How is the performance if that info was say thrown in the status bar out of curiosity?

**Comment by TingPing** [comment]
Also I think a generic "spinner" for buffering would be reasonable without showing the real percentage in the statusbar also, what do you think? See Nautilus for what I'd like it to look like.

**Comment by JasonLG1979** [comment]
I'll check on the status bar. But really I don't think it matters. Any form of buffer percent/progress indicator that depends on the buffer % is pretty much useless as the % goes from 0 to 100 without much in between. We would still just be waisting CPU cycles updating an empty progress bar. The spinner might not be a bad idea though.

**Comment by TingPing** [comment]
Oh and just for another data-point the cpu usage as is is completely reasonable for me, maybe around 3% on a few generation old i5.

**Comment by JasonLG1979** [comment]
What are you basing that off of? If you're going off the task manager make sure you set the update interval as fast as you can the default is something like 3secs. Not fast enough to catch the spike.

**Comment by TingPing** [comment]
@JasonLG1979 Good call, for 1 sec it can hit about 6% :P

**Comment by JasonLG1979** [comment]
Strange? How many cores? Hyper threaded?

**Comment by JasonLG1979** [comment]
I ask because task manager averages CPU load by the number of cores. If you have a 4 core processor with HT the OS sees 8 cores. The UI runs on 1 thread so 6% actually means that it's using 48% of one of your cores.

**Comment by JasonLG1979** [comment]
I'm running a 2 core non HT 2.something? GHz sanybridge Pentium.

**Comment by TingPing** [comment]
Ok the real usage then is about 24% of a single core. Being a pentium might be enough to explain the difference from an i5 of around the same age.

**Comment by JasonLG1979** [comment]
24% is still pretty high to show a pretty much useless message don't you think?

**Comment by TingPing** [comment]
Absolutely.

**Comment by JasonLG1979** [comment]
I like the spinner idea. It shows the user that "something" is going on and I guessing it won't be directly tied to the buffer %.

**Comment by TingPing** [comment]
@JasonLG1979 What do you think, I'll be changing the UI layout, but otherwise? ^

**Comment by JasonLG1979** [comment]
I like that. But you might want to guard it so it isn't called 1000 times. Come to think of it, it might not be a bad idea to guard everything in the buffer function especially the < 100 part so it's not called 1000 + times. It really only needs to be set to "Paused" 1 time once buffering starts. Right now anything in the < 100 part is called 1000 + times every time buffering happens.
