### ISSUE TITLE
code clean up?

### ISSUE THREAD

**Issue by JasonLG1979** [pithos/pithos#199]
Is there any reason get_album_art and NewPithosWindow are hanging out all by their lonesome outside of a class and why the NewPithosWindow function is camel cased? get_album_art can be tucked into the get playlist function and NewPithosWindow can be tucked into The PithosApplication class and cased properly.

**Comment by TingPing** [comment]
related to New*. I am really interested in using https://github.com/virtuald/pygi-composite-templates.

It would likely clean up hundreds of lines of code.
