### ISSUE TITLE
New default album art image

### ISSUE THREAD

**Issue by JasonLG1979** [pithos/pithos#208]
@TingPing what do you think about this for the new default album cover image?
![screenshot from 2015-05-23 19 24 14](https://cloud.githubusercontent.com/assets/6667703/7785513/1dd84cee-0182-11e5-8bac-8ab5e7619f21.png)
It's suppose to be a record single. (If you kids remember what records look like,lol!!!) Another idea I have is a cassette tape made to look like a mixed tape, grayed out a bit like the album cover.

**Comment by TingPing** [comment]
> If you kids remember what records look like,lol!!!

Before my time :P

I think it might look too good though, it looks like something that could be a real cover and you would not realize its a default.

**Comment by JasonLG1979** [comment]
Simplify it then? More line art like?

**Comment by JasonLG1979** [comment]
Why not use the icon theme's default media icon on a plain white background?

**Comment by TingPing** [comment]
> Why not use the icon theme's default media icon on a plain white background?

Could be fine.

**Comment by JasonLG1979** [comment]
That way everything matches.

**Comment by JasonLG1979** [comment]
Will the treeview upscale images to fit in the box? I ask because if so the plain white background would only have to be 1px x 1px.

**Comment by TingPing** [comment]
@JasonLG1979 BTW as of f3922cddb089fa81ba904ae0a9633f0a1c97781d this is now theme-able. You can install `pithos-album-default` icons and we should load it.

**Comment by JasonLG1979** [comment]
> You can install pithos-album-default icons and we should load it.

How would I go about installing that?

**Comment by TingPing** [comment]
Hmm, upon testing it the priority for which icons are loaded doesn't behave how I expected, I'll look into it later.
