### ISSUE TITLE
This application does not seem to be translatable

### ISSUE THREAD

**Issue by fitojb** [pithos/pithos#212]
Hello,

I would like to share this application with my non-English-speaking friends, so I gave a quick look to the repository and didn’t find any trace of internationalization support. Can this be added? Then I can contribute two translations into my mother tongues.

Thanks!

**Comment by TingPing** [comment]
Yes! This has been on my todo list for a while that is a must.

**Comment by TingPing** [comment]
This is still a work in progress but you can sign up and start translating here: https://www.transifex.com/projects/p/pithos/

**Comment by fitojb** [comment]
Thank you!
