### ISSUE TITLE
Last.FM Scrobble plugin doesn't work

### ISSUE THREAD

**Issue by ShapeShifter499** [pithos/pithos#216]
On Pithos 1.1.1  the Last.FM Scrobble plugin option turns grey when I turn it on and doesn't do anything else. It does not open the Last.FM website or give me any options to pair Pithos with my Last.FM account.

**Comment by TingPing** [comment]
Because python3-pylast is not installed.

**Comment by TingPing** [comment]
I'll assume you are on Fedora, the problem is they don't package it:

```
sudo yum install python3-pip
python3-pip install pylast --user
```

**Comment by JasonLG1979** [comment]
He's on arch last time I checked. I'm pretty sure(I may be wrong?) but in arch python3 is the default python version so he'll need python-pylast.

**Comment by TingPing** [comment]
Nah only Fedora users would notice a difference since its not packaged.

**Comment by JasonLG1979** [comment]
> Nah only Fedora users would notice a difference since its not packaged.

?

**Comment by ShapeShifter499** [comment]
I grabbed the latest pylast from the AUR for Arch Linux. Thank you for pointing that out. Working fine again.

**Comment by TingPing** [comment]
Should have never been an issue in arch, the packages still have it as a dep.

**Comment by ShapeShifter499** [comment]
I just noticed that the official package has it as a optional dependency.

[lance@Arch-Chromebook ~]$ pacman -Qi pithos-git
Name           : pithos-git
Version        : 1:480-1
Description    : Pandora Internet Radio player for GNOME
Architecture   : any
URL            : http://pithos.github.io/
Licenses       : GPL3
Groups         : None
Provides       : pithos
Depends On     : python  gtk3  python-gobject  gst-plugins-good
                 gst-plugins-bad  gst-plugins-base  python-setuptools
                 python-cairo
Optional Deps  : libkeybinder3: for media keys plugin
                 gst-plugins-ugly: MP3 playback support [installed]
                 libappindicator-gtk3: Unity indicator applet support
                 python-pacparser: PAC proxy support
                 python-pylast: Last.fm scrobbling support [installed]
                 libnotify: Notification support [installed]
                 python-dbus: MPRIS/Screensaver Pause/Gnome mediakeys support
                 [installed]
Required By    : None
Optional For   : None
Conflicts With : pithos-bzr  pithos
Replaces       : None
Installed Size : 660.00 KiB
Packager       : Unknown Packager
Build Date     : Fri 29 May 2015 09:46:19 AM PDT
Install Date   : Fri 29 May 2015 09:46:20 AM PDT
Install Reason : Explicitly installed
Install Script : Yes
Validated By   : None

[lance@Arch-Chromebook ~]$

**Comment by TingPing** [comment]
Ah yea, forgot arch does the terrible optional deps on everything.
