### ISSUE TITLE
Issue with some Pulseaudio modules, Pithos locks up

### ISSUE THREAD

**Issue by ShapeShifter499** [pithos/pithos#223]
Hi,

I have a new issue that occurs if I try to use "module-pipe-sink" or "module-simple-protocol-tcp" that is part of Pulseaudio.   Pithos will play but if I attempt to skip a song or change the station it will lock up. I find this does not occur if I don't use either of those Pulseaudio modules.

**Comment by TingPing** [comment]
This is certainly something to report to the gstreamer/pulseaudio folks.

**Comment by ShapeShifter499** [comment]
So you don't think this has anything to do with pithos code?

**Comment by TingPing** [comment]
Well pithos code maybe related but random pulseaudio modules *should* have no effect on applications like that.

**Comment by ShapeShifter499** [comment]
This appears totally at fault with Pulseaudio, closing this issue.
