### ISSUE TITLE
Forbidden error box and unable to upgrade..

### ISSUE THREAD

**Issue by netgooroo** [pithos/pithos#225]
Hey guys, 

I am running Linux Mint 17 (qiana) Mate edition. 

I currently have Pithos 1.0.3 installed and when I go to play one of my streams, I get an error box pop up that says "Forbidden". Also, when I go to try and upgrade to version 1.1.1 from term, I get the message "pithos is already the newest version."

I have been using Pithos flawlessly for some time now and wanted to share my bug issue with you guys. 

Thanks for making this awesome streaming app and I look forward to being able to use it again soon.
netgooroo

**Comment by gregsheremeta** [comment]
1.0.3 is probably the newest version for your distro. 1.1.x series is GTK 3.16+ only.

Can you try with a fresh account? Pandora is angry at you for some reason :)

**Comment by netgooroo** [comment]
I can use my account fine if I log in from the web site...  however, I just checked and, it seems they may be having some streaming issues..  I will update when I find out whats up. 

Thanks.
