### ISSUE TITLE
Pithos causes computer to reset after a while

### ISSUE THREAD

**Issue by bladernr** [pithos/pithos#226]
I first started experiencing this with an older version of Pithos installed from Universe in Ubuntu.  I updated that with the PPA version to 1.0.3-1ppa1 on Ubuntu 14.04.3.

I have also run this on two different computers, an Alienware m15X with a Core i7 and an HP Z220 Workstation with a slightly newer Core i7 CPU.  The m15X had 8GB or RAM, the z220, 16GB of RAM.

What happens is that I launch Pithos and it begins playing one of my stations on Pandora (any station).  After a while, sometimes an hour, sometimes shorter, sometimes longer, the computer makes a horrible screeching sound (from the speakers) and abends, resets and  reboots.

I have, as I mentioned, repeated this on two machines (same HDD swapped between both machines) and two versions of Pithos:

0.3.17-2
1.0.3-1ppa1

I have also played the same stream from Pandora using Chrome (streaming directly from the pandora site via the browser) and that does not cause this system failure to occur.

The onset is quite sudden and nothing is logged to syslog.  This seems to have started after an update to the 3.13 kernel in Ubuntu 14.04 LTS.

**Comment by TingPing** [comment]
Well... whatever is going on is much deeper than Pithos. Could be anywhere deeper in the stack from gstreamer, pulseaudio, alsa, the kernel. The lower you go the more likely it makes sense it could possibly reboot your system.

> I have, as I mentioned, repeated this on two machines (same HDD swapped between both machines)

Try a clean install on a different drive, something is probably corrupted.

> This seems to have started after an update to the 3.13 kernel in Ubuntu 14.04 LTS.

Very likely candidate for your problem then.
