### ISSUE TITLE
Incorrect album art shown on notifications

### ISSUE THREAD

**Issue by jkugler** [pithos/pithos#227]
Pithos 1.0.3 on KDE 4.14.2

When there is not album art for a song, when the notification for the song comes up, it shows (in the notification) the album are for the last song that did have album art.

**Comment by JasonLG1979** [comment]
Upstream bug.
https://github.com/eonpatapon/gnome-shell-extensions-mediaplayer/issues/248

**Comment by JasonLG1979** [comment]
Known issue. Many applets(I guess KDE's included?) do not error check when given a http coverart url. A fix/workaround on our side is hopefully in the works.

**Comment by TingPing** [comment]
In general this is probably fixed when we switched to the temp files. Though it will be wrong for a split second for the mentioned reason.

**Comment by JasonLG1979** [comment]
My bad oops... I'm downloading the Fedora 23 KDE spin right now to see if it's still a valid bug.

**Comment by JasonLG1979** [comment]
Although last time I checked Pithos dodn't work at all with the KDE 5 media applet. Possibly because we don't include a trackid in the metadata? I'll compare the master branch with my fixes branch.

**Comment by JasonLG1979** [comment]
With the current master Pithos does not work at all with the KDE 5 sound menu in Fedora KDE.
![snapshot2](https://cloud.githubusercontent.com/assets/6667703/13410998/688a55aa-df00-11e5-82f1-18f712b6240e.png)

With my MPRIS_fixes branch it seems to work as expected.
![snapshot1](https://cloud.githubusercontent.com/assets/6667703/13411013/82ab7f04-df00-11e5-844a-fdcd04e33d51.png)

**Comment by JasonLG1979** [comment]
Notifications also seem to work as expected in my branch.

**Comment by TingPing** [comment]
So is this still an issue, a lot has changed?

**Comment by JasonLG1979** [comment]
Just tested it in Kubuntu 16.04.1. Still an issue.

**Comment by JasonLG1979** [comment]
Our current implementation still exhibits this bug, but my hacked together solution to get rid of libnotify in #298 does not. It works as expected. The only thing it's missing is actions buttons, and their usefulness is debatable with just about everyone having a MPRIS implementation. gnome-music actually went so far as to totally remove notifications because GNOME now has MPRIS built in.

**Comment by TingPing** [comment]
Probably just KDE not liking persistent notifications.

**Comment by JasonLG1979** [comment]
Still not a bad idea to get rid of libnotify and port everything over to Gio/gdbus though. Especially if it fixes the problem.

**Comment by TingPing** [comment]
Well you can use libnotify without persistence..

**Comment by JasonLG1979** [comment]
Nope, doesn't help. I just tried:
```
        self.notification.set_hint('resident', GLib.Variant.new_boolean(False))
        self.notification.set_hint('transient', GLib.Variant.new_boolean(True))
```

The bug is still there.

**Comment by JasonLG1979** [comment]
I think KDE doesn't like libnotify,lol!!!

**Comment by JasonLG1979** [comment]
This was fixed with GioNotify.
