### ISSUE TITLE
RPMFusion F22 package

### ISSUE THREAD

**Issue by orbisvicis** [pithos/pithos#229]
@TingPing: You packaged 1.1.1 for F21 (according to the [changelog](http://download1.rpmfusion.org/free/fedora/updates/21/x86_64/repoview/pithos.html))? I would love to see this version for F22.

**Comment by TingPing** [comment]
Odd, I'll get around to that, in the mean time there will be no harm in using the F21 package.

**Comment by TingPing** [comment]
1.1.2 is in F22 and F23.
