### ISSUE TITLE
Windows / OS X Support and Installation Instructions?

### ISSUE THREAD

**Issue by giantspeck** [pithos/pithos#230]
The changelog for Pithos mentions the addition of support for Windows (as of version 1.0.0, released on 1 May 2014) and OS X (as of version 1.0.1, released on 21 September 2014).

Has support for either of these operating systems ever been fully realized?  And if so, are there special instructions to install Pithos on either operating system?

**Comment by TingPing** [comment]
> Has support for either of these operating systems ever been fully realized?

I would say no, the issues largely lie in GStreamer. Playback often fails or crashes on both Win32 and OSX.

A brief intro to installation though:

Windows:

- Use [msys2](https://msys2.github.io/) to install all deps or
- Use the [pygobjectwin32 project](http://sourceforge.net/projects/pygobjectwin32/)

OSX:

- Use [homebrew](http://brew.sh/) and [my package](https://github.com/TingPing/homebrew-gnome/blob/master/pithos.rb) (unmaintained) or
- Use [JHBuild](https://wiki.gnome.org/Projects/Jhbuild/Mac_OS) and [my patches](https://github.com/TingPing/jhbuild/tree/tingping/osx)

**Comment by giantspeck** [comment]
Hey, just letting you guys know that [Hermes](https://github.com/HermesApp/Hermes) for OS X has pretty much abandoned their project and are willing to hand off development to anyone.
