### ISSUE TITLE
Playback fails with GStreamer error gst-resource-error-quark: Server sent bad data

### ISSUE THREAD

**Issue by dkogias** [pithos/pithos#234]
```
ERROR - pithos:on_gst_error:677 - Gstreamer error: gst-resource-error-quark: Server sent bad data. (9), gstsouphttpsrc.c(1519): gst_soup_http_src_parse_status (): /GstPlayBin:player/GstURIDecodeBin:uridecodebin6/GstSoupHTTPSrc:source:
Message Corrupt (8), URL: http://mediaserver-sv5-rt-1.pandora.com/access/8728382399721748365.mp4?version=4&&lid=...&token=..., Redirect to: (NULL), 9
WARNING - pithos:get_playlist:531 - Too many gstreamer errors. Not retrying
```

I'm on F22, pithos installed from rpmfusion, free account.  Playback worked until yesterday.  I did do quite a few skips yesterday.

**Comment by TingPing** [comment]
> Playback worked until yesterday.

So that points to Pandora being the issue, guess you can try waiting it out to see if it resolves itself.

**Comment by gregsheremeta** [comment]
Pandora was down for me earlier today.

Oddly, so were several other services, including Google's cloud stuff.

**Comment by dkogias** [comment]
Just commenting here for posterity: My Pandora punishment seems to be over and I can stream again.  Many thanks again for this app!

**Comment by pitoulambert** [comment]
Sorry for disturbing you. 
I am facing some issues with bbc/brave , the audio/video editor

 ERROR: [   output1] GStreamer error from sink: gst-resource-error-quark: Error while writing to file "/usr/local/share/brave/output_images/img_19777.jpg". (10)
   ERROR: [   output1] GStreamer error debug: gstmultifilesink.c(793): gst_multi_file_sink_write_buffer (): /GstPipeline:pipeline25/GstMultiFileSink:sink:
No such file or directory
   ERROR: [   output1] GStreamer error message: Error while writing to file "/usr/local/share/brave/output_images/img_19777.jpg".


I need help please
