### ISSUE TITLE
No Notification Icon in KDE 5 (Kubuntu 15.04)

### ISSUE THREAD

**Issue by Ironlenny** [pithos/pithos#236]
I installed Pithos from the Pithos ppa. I installed recommended dependencies. Pithos works, but when I change the "Notification Icon" preference to on, no icon appears in the notification tray. This worked previously in KDE 4.

**Comment by TingPing** [comment]
Currently appindicators are hard-coded to Unity: [pithos/plugins/notification_icon.py#L24](https://github.com/pithos/pithos/blob/9d316e3a428fa7b2224ce2c95f01e59b0fa5f295/pithos/plugins/notification_icon.py#L24)

KDE 5 and ElementaryOS (probably more) also do not support traditional tray icons. I think it might be reasonable to just always use appindicators if installed. The only behavior difference would be middle click for actions vs left click.

**Comment by Ironlenny** [comment]
libappindicator3-1 has been patched with KDE 5 notification support: http://blog.martin-graesslin.com/blog/2014/06/where-are-my-systray-icons/

Unity's Application Indicator is an implementation of KDE 5's Status Notifier API: http://blog.martin-graesslin.com/blog/2014/03/system-tray-in-plasma-next/

So you should be able to use Application Indicator without any additional code.

Something like this (pardon my Python) 
`if os.environ['XDG_CURRENT_DESKTOP'] == 'Unity' || 'plasma':`
should work.

**Comment by TingPing** [comment]
Right, my point is we should just always use them.

**Comment by Ironlenny** [comment]
I see. Yes, that's a good idea.

**Comment by TingPing** [comment]
On a somewhat related note, could anybody test to see if enabling this line works on a system  that supports AppIndicator (verifying on both KDE and Unity would be great): [notification_icon.py#L95-L96](https://github.com/pithos/pithos/blob/b325db4ed62d4cc0bf2a5e5af68054a378c428f3/pithos/plugins/notification_icon.py#L95-L96)

(Ping @JasonLG1979 ^)

**Comment by Ironlenny** [comment]
Pithos does show up in KDE's system tray now, but I do not have an icon. There's just a blank space where Pitho's indicator is.

**Comment by TingPing** [comment]
> Pithos does show up in KDE's system tray now, but I do not have an icon.

Ah ok that makes sense actually, I'll push another patch in a few.

**Comment by JasonLG1979** [comment]
> On a somewhat related note, could anybody test to see if enabling this line works on a system that supports AppIndicator

I'm on Xubuntu 15.04 right now. Not a huge Unity fan and KDE 5 kinda sucked the last time I checked. But I can grab a couple *buntu 15.10 images and give it a test on a LiveUSB. On a related note, I've noticed that GNOME is using symbolic/silhouette(?) icons on the panel do you need some more icons for different DE's so everything looks all pretty?

**Comment by TingPing** [comment]
> But I can grab a couple *buntu 15.10 images and give it a test on a LiveUSB.

I actually grabbed an Ubuntu ISO myself to test soon, but I would like to know about KDE.

> On a related note, I've noticed that GNOME is using symbolic/silhouette(?) icons on the panel do you need some more icons for different DE's so everything looks all pretty?

Yes we would need a small symbolic icon for the panel and a large symbolic icon for accessibility when users enable hicontrast mode. https://wiki.gnome.org/Initiatives/GnomeGoals/HighContrastAppIcons

**Comment by JasonLG1979** [comment]
> Yes we would need a symbolic icon for the panel and for accessibility when users enable hicontrast mode.

I'll put that on my list. From what I've read it's a little more complicated than just pooping out a svg.

**Comment by Ironlenny** [comment]
Everything is working for me on Kubuntu 15.04 now. Thanks for the work @TingPing!
