### ISSUE TITLE
How do you install from source now?

### ISSUE THREAD

**Issue by JasonLG1979** [pithos/pithos#239]
setup.py is MIA.

**Comment by TingPing** [comment]
```sh
./autogen.sh
make
# Install
sudo make install 
# Or run locally
./bin/pithos
```

**Comment by JasonLG1979** [comment]
./autogen.sh: 12: ./autogen.sh: aclocal: not found

**Comment by TingPing** [comment]
> Tried to install:

Depends on autoconf, automake, intltool.

> Tried to run locally:

You can't run without making it.

**Comment by JasonLG1979** [comment]
After installing dependencies:
XMLLINT not set and xmllint not found in path; skipping xml preprocessing.
XMLLINT not set and xmllint not found in path; skipping xml preprocessing.
Makefile:1123: *** missing separator (did you mean TAB instead of 8 spaces?).  Stop.

**Comment by TingPing** [comment]
Well the error is straight forward, xmllint is provided by libxml2.

**Comment by JasonLG1979** [comment]
jason@Inspiron-One-2020:~$ sudo apt-get install libxml2
Reading package lists... Done
Building dependency tree       
Reading state information... Done
libxml2 is already the newest version.

**Comment by TingPing** [comment]
Debian does the debian thing, they split it into libxml2-utils.

**Comment by JasonLG1979** [comment]
Makefile:1123: *** missing separator (did you mean TAB instead of 8 spaces?).  Stop.

**Comment by TingPing** [comment]
Pastebin `Makefile`

**Comment by JasonLG1979** [comment]
http://pastebin.com/Z00dujat

**Comment by TingPing** [comment]
Debian split that into libglib2.0-dev.

**Comment by JasonLG1979** [comment]
jason@Inspiron-One-2020:~/pithos$ make
  GEN      pithos.gresource
data/pithos.gresource.xml: to-pixbuf preprocessing requested but GDK_PIXBUF_PIXDATA not set and gdk-pixbuf-pixdata not found in path.
Makefile:1172: recipe for target 'pithos.gresource' failed
make: *** [pithos.gresource] Error 1

**Comment by TingPing** [comment]
Debian split that into libgdk-pixbuf2.0-dev.

**Comment by JasonLG1979** [comment]
Well it installed now I get:
jason@Inspiron-One-2020:~$ pithos

** (pithos:29848): WARNING **: Couldn't connect to accessibility bus: Failed to connect to socket /tmp/dbus-pKterxnbha: Connection refused
Traceback (most recent call last):
  File "/usr/local/bin/pithos", line 37, in <module>
    from pithos import application
  File "/usr/local/lib/python3.4/site-packages/pithos/application.py", line 26, in <module>
    from .pithos import PithosWindow
  File "/usr/local/lib/python3.4/site-packages/pithos/pithos.py", line 40, in <module>
    from . import AboutPithosDialog, PreferencesPithosDialog, StationsDialog
  File "/usr/local/lib/python3.4/site-packages/pithos/AboutPithosDialog.py", line 20, in <module>
    from .util import open_browser
  File "/usr/local/lib/python3.4/site-packages/pithos/util.py", line 23, in <module>
    gi.require_version('Secret', '1')
  File "/usr/lib/python3/dist-packages/gi/__init__.py", line 100, in require_version
    raise ValueError('Namespace %s not available' % namespace)
ValueError: Namespace Secret not available

**Comment by TingPing** [comment]
Debian split that into gir1.2-secret-1.

**Comment by JasonLG1979** [comment]
OK that worked. Damn that's a lot of splitting. Thanks!!!

**Comment by JasonLG1979** [comment]
So that's:
autoconf automake intltool libxml2-utils libglib2.0-dev libgdk-pixbuf2.0-dev gir1.2-secret-1

Added to the dependencies for Ubuntu.

**Comment by TingPing** [comment]
Sorry about that, I just made a whole lot of changes really fast, never even crossed my mind people would have to install new packages for them (other than autotools/intltool/libsecret) since they are all tools in the packages we already depend on.

I might bundle gsettings.m4 so your first error is more obvious though.

**Comment by JasonLG1979** [comment]
Totally minor thing but now it doesn't show up as Pithos in the task manager. Just python3.

**Comment by Ironlenny** [comment]
Just ran into the dependence problem myself.

**Comment by JasonLG1979** [comment]
I followed the wiki on how to install in Fedora and I get:
```[liveuser@Inspiron-One-2020 pithos]$ ./autogen.sh
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /usr/bin/mkdir -p
checking for gawk... gawk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking whether make supports nested variables... (cached) yes
checking for a Python interpreter with version >= 3.3... python3
checking for python3... /usr/bin/python3
checking for python3 version... 3.4
checking for python3 platform... linux
checking for python3 script directory... ${prefix}/lib/python3.4/site-packages
checking for python3 extension module directory... ${exec_prefix}/lib64/python3.4/site-packages
configure: error: gsettings.m4 not found```

**Comment by TingPing** [comment]
@JasonLG1979 `dnf provides gsettings.m4`, feel free to edit the wiki I just listed what i knew off the top of my head.

**Comment by JasonLG1979** [comment]
dnf was already installed. ```glib2-devel``` did the trick.

**Comment by TingPing** [comment]
That was a dnf command, provides says what provides a file :P

**Comment by JasonLG1979** [comment]
Oh OK. I'm not the Fedora master you are,lol!!!

**Comment by orbisvicis** [comment]
I'm thinking it's no longer possible to run locally?

```
Running locally...

(pithos:18801): GLib-GIO-ERROR **: Settings schema 'io.github.Pithos' is not installed

Trace/breakpoint trap (core dumped)
```

**Comment by TingPing** [comment]
@orbisvicis Sadly GSettings cannot be ran locally atm, so you do have to install once (the schema technically being the only required thing). After that you can run `./bin/pithos` and it will use everything else local.

**Comment by kwoodham** [comment]
Just wanted to say thanks for capturing this progression - helped a ton!  - Kurt

**Comment by madars** [comment]
As a quick comment: you can inject additional GSettings schemas by first compiling them (`glib-compile-schemas data`) and then passing the full path to the directory of compiled schemas in `GSETTINGS_SCHEMA_DIR` environment variable. More precisely, `glib-compile-schemas data/ && GSETTINGS_SCHEMA_DIR=$(readlink -f data) bin/pithos` works and doesn't require root privileges.

**Comment by TingPing** [comment]
@madars It already does this now.
