### ISSUE TITLE
Are you guys interested in 128kbit/s for free users and a fix to the buffering issue? 

### ISSUE THREAD

**Issue by JasonLG1979** [pithos/pithos#240]
I'm working on a patch to pandora.py that uses 'additionalAudioUrl' for the most of the audio qualities with the exception of high quality for Pandora One. I've mentioned this in another bug report, but basically it would look like this:

Free users:
High Quality - 128 kbit/s mp3 from 'additionalAudioUrl'
Medium Quality - 64 kbit/s aacplus adts from 'additionalAudioUrl'
Low Quality - 32  kbit/s aacplus adts from 'additionalAudioUrl'

Pandora One users:
 High Quality - 192 kbit/s mp3 from the standard high quality stream
Medium Quality - 64 kbit/s aacplus adts from 'additionalAudioUrl'
Low Quality - 32  kbit/s aacplus adts from 'additionalAudioUrl'

It has the added benefit that the aacplus adts stream/codec doesn't suffer from the nasty buffering behaviour and everyone would get access to 3 actual stream quality choices. In the event that 'additionalAudioUrl' becomes unavailable it seamlessly falls back to using the current streams.

**Comment by TingPing** [comment]
Sounds great.

**Comment by JasonLG1979** [comment]
Pandora One users have access to 7 different audio streams so far that I have found (192mp3, 128mp3, 64mp4, 64aac, 32mp4, 32aac, 40aac_mono)

Free users have access to 6 different audio streams (all streams listed above minus 192mp3)

Working on a system that has 5 main qualities settings and 2 fallback(the crappy ones with buffering issues) I'm testing it right now. But basically it seamlessly cascade fails from the top down and from the bottom up so that unless absolutely none of the streams were available Pithos would play something.

![preferences_006](https://cloud.githubusercontent.com/assets/6667703/10556951/c61359c0-745b-11e5-9408-d6bbf3333d23.png)

It abuses try: A LOT though.

**Comment by TingPing** [comment]
> It abuses try: A LOT though.


Wow, maybe work on a loop :P

```python
for i in reversed(range(3)):
    try:
        _pandora_one = d['additionalAudioUrl'][i]
        break
    except ValueError:
        continue
else:
    logging.warning('All out of audio =(')
```

**Comment by JasonLG1979** [comment]
I knew there would be a better way to do it. Your kungfu is much stronger than mine,lol!!! It's VERY much top down execution so I could wrap my head around it. I'll try working with loops.

**Comment by JasonLG1979** [comment]
Something more like this?
http://pastebin.com/LYX9C5HF

**Comment by TingPing** [comment]
Still seems overly-complex, though I'd have to play with it myself to think of a clean solution.

**Comment by JasonLG1979** [comment]
It is very convoluted. The goal is to try to use the requested audio setting if possible otherwise fallback. I'm sure you could come up with something better that does the same thing.

**Comment by TingPing** [comment]
I wonder what Pandora would think of us using the 128k stream, from the website:

>Pandora on the Web plays 64k AAC+ for free listeners and 192kbps for Pandora One subscribers. All in-home devices play 128kbps audio, and mobile devices receive a variety of different rates depending on the capability of the device and the network they are on, but never more than 64k AAC+.

The ADTS streams look like they are intended for mobile since they are variable bitrate, the lower stream simply existing for lower bandwidth. I imagine the in-home devices higher quality for free users is offset by licensing fees.

**Comment by TingPing** [comment]
To expand upon that, I think this is currently all of Pandora's current offerings:

## Web

One: 192 mp3
Free: 64 aac+

Only fixed bitrate is used here and there is no lower bandwidth options as they expect
decent connections.

## In-home device

All: 128 mp3

I think the fact AAC is not used here is purely for 3rd party partners (since this is the only place anybody else uses their API) not for quality purposes.

## Mobile

All: 64 aac+ adts w/ option to downgrade to 32 aac+ adts

Only variable bitrate is used here as they expect crap connections.

## Other

The few others probably exist for legacy reasons and I don't see any docs from them on what uses it.

**Comment by JasonLG1979** [comment]
Really officially we aren't supposed to be using any of the streams. But if you really want to not use the 128 stream that's fine. I have a Pandora One account so I get the 192 stream.

**Comment by JasonLG1979** [comment]
It would be nice if Pithos could become an official Pandora partner but I don't think that could happen. Even better would be if they had a public API.

**Comment by TingPing** [comment]
I think I would be fine with using it, but just going by ear I'm not sure its actually higher quality.

**Comment by JasonLG1979** [comment]
Sound "quality" is one of those things that's hard to quantify. But I'd personally agree that if there is much of a difference between the 64 aac adts and 128 mp3 it's certainly not twice as good. A lot of other people would disagree though. I think it's up to the user to decide that. It defaults to 64 and that will probably be fine for 99% of people.

**Comment by arcooke** [comment]
I just picked up pithos for the first time tonight.. it's great.  But yeah, within 15 minutes I already ran into the buffering bug.  I'd definitely support anything that would fix that

**Comment by JasonLG1979** [comment]
It's in the works.

**Comment by arcooke** [comment]
Any idea when this might get rolled out?  That buffering issue is driving me nuts

**Comment by JasonLG1979** [comment]
> Any idea when this might get rolled out? That buffering issue is driving me nuts

I'm still working on it.



> By the way- What theme are you using in the screenshot above? I really like that

https://github.com/horst3180/Arc-theme

**Comment by xmbwd** [comment]
Love Pithos!  So clean and usable.  A buffering fix would rock.  It didn't happen in the prior version of Pithos I was using, but now it randomly slows, then speeds about 1x per 3 hours.  I'm listening thru Pithos about 12 hours a day...........

**Comment by N4RPS** [comment]
Hello, All!

My thanks to EVERONE who developed Pithos! This past holiday season, the Linux version played on an ancient Compaq Evo N600c P3-1066 laptop, with 512MB RAM and AntiX-15, 45 days straight for me without missing a beat!


I imagine that Pandora isn't very happy about this program, PERIOD. THAT would serve to explain why the Android version of Pithos seems to have basically DIED in 2013. (What I wouldn't give for one that WORKED!)

Is there any active development still taking place on the Windows version? It basically works, but I'm having this problem on 64-bit machines: 

At high quality, sometimes, only a percentage of the song is buffered. Of course, at the end of the percentage that was buffered, the song stops. To continue, one must manually click on the next selection - which may (or may not) do the same thing.

Lastly, how might I support this project's further development financially?

73 DE N4RPS
Rob

**Comment by TingPing** [comment]
> Android version of Pithos

Never knew such a thing existed, link? It would have only shared a few lines with this client though...

> Is there any active development still taking place on the Windows version?

That's issue #24. I largely stopped because I don't use Windows anymore and GStreamer is pretty rough on it.

> Lastly, how might I support this project's further development financially?

I haven't been very active lately... but you could throw me a few bucks on bitcoin or paypal.

**Comment by N4RPS** [comment]
Hello!


> I haven't been very active lately... but you could throw me a few bucks on bitcoin or paypal.


Nonetheless, I'll see what I can scrounge up for you. Besides, the Linux version works flawlessly, and trying to fix what wasn't broke has ruined many a program. I guess there's not much need to try and fix it for the latest versions of Windows, as it's much more useful to the Linux community anyway.


> That's issue #24<https://github.com/pithos/pithos/issues/24>. I largely stopped because I don't use Windows anymore and GStreamer is pretty rough on it.


My bad. Didn't mean to dupe an existing issue. If there weren't things that I need to do in Windows that can't be done in Linux with WINE, I'd leave M$ behind, too. Despite this, there's no way I'd EVER use 10. Pure evil, it is. I stop at 8.1!


Pithos for Windows seems to work just fine for me on my 7 desktop PC. I have been listening to several successful songs in a row on it as I have crafted this reply. I think it's just 8/8.1/10 where it misbehaves. Besides, if a boatload of Windozers started using Pithos all of a sudden, Pandora just might decide to make life rough on ALL of us!


If there weren't things that I need to do in Windows that can't be done in Linux with WINE, I'd leave M$ behind, too. Despite this, there's no way in Hades I'd ever use 10. I stop at 8.1! Besides, I'm just too dependent on Media Center here to give it up for 10, anyway.


> Never knew such a thing existed, link? It would have only shared a few lines with this client though...


Here's a link to Pithos for Android, but it 404s now:


https://github.com/davidcollins4481/Pithos-for-Android


It was mentioned here:


https://www.reddit.com/r/androidapps/comments/1d2kxh/pithos_for_android/


David Collins' GitHub page still exists; it just no longer mentions PFA. Might reach out to him to see if he still has the source code, ask him if he'll share it with me, and to find out whether or not Pandora applied any pressure on him to abandon the project. Even if it DID ever work, it would most likely need just about a total rewrite for more recent versions of Android anyway.


Again, thank you for your efforts on the project!


73 DE N4RPS

Rob Sargeant

Charlotte, NC




________________________________

**Comment by TingPing** [comment]
Looks like it was mirrored here: https://github.com/Stuart4/Pithos-for-Android

It has nothing to do with Pithos' code base though, just looks like he rewrote a simliar library in Java based on Pithos logic.
