### ISSUE TITLE
Using the spacebar in the stations-popover search box causes Pithos to pause.

### ISSUE THREAD

**Issue by JasonLG1979** [pithos/pithos#242]
The title pretty much says it all. If you use the spacebar in the stations-popover search box it pauses Pithos instead of adding a space to your search as would be expected.

**Comment by TingPing** [comment]
Can't reproduce, opening the popover focuses the input box and it takes the space for me.

**Comment by JasonLG1979** [comment]
I'm on Xubuntu 15.04. Maybe it's a Xfce thing? I'll test on a few other different DE's to see what they do.

**Comment by TingPing** [comment]
Maybe its an old Gtk bug, I doubt the DE is relevant. I am on Gtk 3.18.2.

**Comment by JasonLG1979** [comment]
Maybe? Ubuntu 15.04 runs a bastardizes version of mostly 3.14 I believe. If that is the case I guess you can mark this as fixed upstream.

**Comment by TingPing** [comment]
I just tested on Ubuntu 15.10 with version 3.16.7 and it behaved as expected.

**Comment by JasonLG1979** [comment]
Well then I close this. Fixed upstream.
