### ISSUE TITLE
Pithos does not seam to be 15.10 compatible. 

### ISSUE THREAD

**Issue by noah2828** [pithos/pithos#244]
I get this if I try to install.

`pithos : Depends: python3-gi-cairo`

`sudo apt-get install python3-gi-cairo` returns 
`python3-gi-cairo : Depends: python3-gi (= 3.16.2-1build1) but 3.18.0-0ubuntu1~wily3 is to be installed`

**Comment by JasonLG1979** [comment]
3.18 in 15.10? are you using the GNOME staging ppa?

**Comment by noah2828** [comment]
ok thanks
