### ISSUE TITLE
No arts in the sound menu

### ISSUE THREAD

**Issue by dbfin** [pithos/pithos#245]
Hi, I am using the new 1.1.1 version on LMDE 2, MPRIS plugin is ON, so it adds the song info/controls to the system sound menu, but no album arts. To tell the truth, I do not remember how it worked with the version 0.3.18_4 on my previous system, which was LMDE 1.

**Comment by JasonLG1979** [comment]
I seem to remember running into the same issue while testing LMDE 2. For me after a fresh install and installing Pithos album art showed up in the sound menu. But after I did a apt-getupgrade, apt-get dist-upgrade album art no longer showed up in the sound menu. I'll test it out this weekend to see if I can find the breakpoint.

**Comment by dbfin** [comment]
Thanks, that would be awesome!

Here is a tip on how I use it. I enabled plugins Mpris, Mediakeys and Notification Icon, but I do NOT have appindicator's libraries installed, so there is no icon in the system tray. The reason I still have the Notification Icon plugin on, is to force Pithos not to exit when I close the window (the plugin keeps Pithos running when you close the window regardless of whether it can add icon to the system tray or cannot). The other two plugins should be clear.

So, I have Pithos in the sound menu only (no taskbar, no icon in the system tray), but the sound menu in LMDE 2 allows me to open the Pithos window if I need it. This works perfectly for me, except there is no arts...

**Comment by dbfin** [comment]
Yes, I also tried to run Pithos from the terminal to see if it produces any warnings, but it does not. I thought, at least, it would give me some errors/warnings regarding missing appindicator's libraries, since the Notification Icon plugin is on, but no. Maybe you know of some way to create Pithos logs or where to look at?

**Comment by JasonLG1979** [comment]
Pithos -vv will spit out a bunch of logging info.

**Comment by TingPing** [comment]
Though the mpris plugin doesn't actually log a single thing =\

**Comment by dbfin** [comment]
Thanks again.

The relevant information produced by Pithos:

    INFO - pithos:start_song:499 - Starting song: index = 0
    INFO - pandora:audioUrl:375 - Using audio quality highQuality: 64 aacplus
    INFO - pithos:art_callback:585 - Downloaded album art for 0
    INFO - pithos:check_if_song_is_ad:762 - Not an Ad..
    INFO - pithos:art_callback:585 - Downloaded album art for 1
    INFO - pithos:art_callback:585 - Downloaded album art for 2
    INFO - pithos:art_callback:585 - Downloaded album art for 3

Still no arts, even though it seems to be downloaded.

Besides, when I press Skip, now it just gives the first three lines per song:

    INFO - pithos:start_song:499 - Starting song: index = 1
    INFO - pandora:audioUrl:375 - Using audio quality highQuality: 64 aacplus
    INFO - pithos:check_if_song_is_ad:762 - Not an Ad..
    INFO - pithos:start_song:499 - Starting song: index = 2
    INFO - pandora:audioUrl:375 - Using audio quality highQuality: 64 aacplus
    INFO - pithos:check_if_song_is_ad:762 - Not an Ad..

No indication of arts being downloaded starting from the second song.

**Comment by dbfin** [comment]
I just realized that it did not download arts for the second and third songs because it downloads 4 songs at once. Sorry for confusion.

**Comment by dbfin** [comment]
> Though the mpris plugin doesn't actually log a single thing =\

That's too bad, I guess... Any way to manually debug it? Or is it possible that it produces some system messages, as a side effect, for example, when a library function fails etc.?

**Comment by JasonLG1979** [comment]
Stupid question.: Have you tested to make sure album art shows up in the sound menu when using other music players?

**Comment by dbfin** [comment]
Actually, not so stupid, as I have not. In fact, I just realized that I don't have any MP3's with images.

So what I just did. I installed EasyTag, downloaded an image for one of audio books I have, used EasyTag to embed the picture into the mp3 file, run Audacious, and the picture does show in the sound menu.

**Comment by JasonLG1979** [comment]
Mpris it's self is more complicated then it needs to be IMHO and a bit flaky. I'm not sure if it's implemented 100% correctly in Pithos.

**Comment by dbfin** [comment]
Since, as you suggested, I tested Audacious and it works, is there any way to see how different is their implementation and what libraries/methods they use?

**Comment by JasonLG1979** [comment]
You can have a peak at Pithos' mpris plugin and compare it to the mpris2 docs and Audacious' implementation.

**Comment by TingPing** [comment]
The mpris stuff is pretty simple, a song changes then we set a dictionary of info including the current album art. The obvious problem with this is if the song gets an album art after that point it is too late such as the first one when you open the client. This usually shouldn't apply to later songs though.

**Comment by JasonLG1979** [comment]
The plugin also send a new dict everytime play is called. So everything play called mpris thinks it's a new song...

**Comment by JasonLG1979** [comment]
*Every time play is called.

**Comment by TingPing** [comment]
Heh, could either of you test out gnome-music's mpris support? If theirs works well we can just directly use that: https://github.com/GNOME/gnome-music/blob/master/gnomemusic/mpris.py

**Comment by JasonLG1979** [comment]
I plan on probably installing Ubuntu 15.10 GNOME on my computer today anyway so sure. Thanks for the link I've been looking for a good example.

**Comment by JasonLG1979** [comment]
Dang phone... *I wa planning on probably...

**Comment by JasonLG1979** [comment]
I'd love to see a proper/more complete implementation. Things like track time and such. The killer would be playlists though. We could treat stations like playlists and played and upcoming songs as tracks in playlists.

**Comment by TingPing** [comment]
I just installed the mpris extension for Gnome and it still works fine here.

@JasonLG1979 Maybe open an issue about it where we can track missing features, we already expose track position through mpris though I don't see the length metadata set (which would probably depend on your pandora duration changes anyway).

**Comment by JasonLG1979** [comment]
I was able to get time working by using the track duration reported by Pandora.(you have to report the song duration right when you start a song.) reporting tracking position doesn't seem to matter. Mpris/Dbus uses it's own clock to keep track of elapsed track time. Unless you know the duration right when the song starts it either totally just doesn't work or the time is off. Also resending the metadata dict every time play is called resets the time since it thinks it's a new song.

I start a new issue with a wishlist.

**Comment by dbfin** [comment]
Audacious is written is C, so direct comparison was difficult. Instead, I used qdbus to see if there are any differences in what mpris knows about the two players.

OK, so, using qdbus I compared what metadata is available when Pithos and Audacious play. The main difference in mpris:artUrl is that Audacious has a link to a local file, while Pithos has a link to a file on the Pandora website. Can this make the difference? I found on some forums that yes, it can.

So, I manually put a link to a local (fixed) image in the mpris plugin, and voila! It showed the picture.

I, actually, wrote today a patch that works on my system. It creates local temporary files for downloaded album arts, which are deleted on exit, and this all works fine, including the arts for the first song.

**Comment by dbfin** [comment]
I created a pull request, and put #245 in it, but it did not end up here. It created a new pull request #248 .

Edit: I modified the message there, and at least it shows a reference in this issue. This is all quite confusing.

**Comment by dbfin** [comment]
@JasonLG1979 Since you seem to have access to many OSs, would you mind testing the changes? If, as you told me, you run pithos -vv, you should see a few messages telling you what temporary directory and files inside it are created, and when the folder is removed. Thanks.

**Comment by JasonLG1979** [comment]
I don't really have access to many OS's per say. I just test stuff on Live USB's mostly.(all just different, mostly Debian based Linux distros) But I'll test it out on all of the *buntu 15.10 flavors. You're running LMDE and TingPing is running Fedora(?) So that should cover those. I like where you're going with it. It would be nice to see a more complete Mpris2 in Pithos. But like TingPing said in your PR make sure to follow spec.

**Comment by TingPing** [comment]
> TingPing is running Fedora

Gnome 3.18 with https://github.com/eonpatapon/gnome-shell-extensions-mediaplayer

**Comment by JasonLG1979** [comment]
> Gnome 3.18 (on Arch) with https://github.com/eonpatapon/gnome-shell-extensions-mediaplayer

My bad,lol!!!... That extension is probably the most complete Mpris2 plugin/client/controller(whatever you'd call it?) that I've seen. The Cinnamon sound menu is close if not about the same.

**Comment by dbfin** [comment]
Thanks to both of you. I will submit the corrected link shortly.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    From: Jason GraySent: Saturday, October 24, 2015 2:38 PMTo: pithos/pithosReply To: pithos/pithosCc: VadimSubject: Re: [pithos] No arts in the sound menu (#245)
Gnome 3.18 (on Arch) with https://github.com/eonpatapon/gnome-shell-extensions-mediaplayer


My bad,lol!!!... That extension is probably the most complete Mpris2 plugin/client/controller(whatever you'd call it?) that I've seen. The Cinnamon sound menu is close if not about the same.  

—Reply to this email directly or view it on GitHub.

**Comment by dbfin** [comment]
I submitted the changes making it compliant to the specifications. Please see and test at your convenience. Please let me know if it works fine on the systems being tested, and if there are any further adjustments to do.

**Comment by dbfin** [comment]
After discussion with @TingPing I submitted a new version. I tested it on my system, and qdbus shows URI starting with "file://". Just in case you might need it, this is what I used to see what qdbus reports:

    qdbus `qdbus | grep pithos` /org/mpris/MediaPlayer2 org.mpris.MediaPlayer2.Player.Metadata

**Comment by dbfin** [comment]
Here is one additional question. Sometimes I see that there are pithos-... directories left in tmp. Those are left only when I run Pithos from the command line (for debugging purposes) and interrupt it then. I think, this is unusual way to run Pithos, but there might be other reason why Pithos would quit unexpectedly without running quit().

Hence, I thought, if we can prevent this, or do we even need this. I can see three ways:

1. Find a way to clean the temporary directory when Control-C is pressed. This would not resolve the issue when Pithos is terminated for another reason, though.

2. Clean all /tmp/pithos-* folders on start.

3. Do nothing. Other programs also leave stuff in /tmp/ when they are interrupted.

I personally, decided not to get things more complicated than necessary and vote for 3. But if this is a problem, we can think about it.

**Comment by JasonLG1979** [comment]
/tmp is a junk folder. files /tmp are not guaranteed to survive a reboot for the most part. Many people actually mount /tmp to RAM and many distros clear /tmp on every reboot. There's no need to worry about /tmp.

**Comment by dbfin** [comment]
Yes, this is what I think. Anyway, wanted to mention just in case.

**Comment by dbfin** [comment]
So, as far I can say for these two weeks it works perfectly fine for me. Have any of you been able to test it on any other system? Thanks.

**Comment by TingPing** [comment]
It behaved fine when I briefly tested it, I have been a bit busy lately so I'll try to get around to merging things soon.

**Comment by JasonLG1979** [comment]
@TingPing this can probably be closed too?

**Comment by TingPing** [comment]
Fixed by 32946f26ad2bcb448455c6b2cf6789628d4cf182
