### ISSUE TITLE
UI fails to redraw

### ISSUE THREAD

**Issue by JasonLG1979** [pithos/pithos#246]
I doubt this is a Pithos problem, more than likely a Ubuntu/Compiz issue. But here we go...

Here's what it looks like if you maximize Pithos...
![screenshot1](https://cloud.githubusercontent.com/assets/6667703/10679465/652c83b6-78de-11e5-96f8-c6a9d97deb38.png)
If you resize the window, it's contents don't scale...
![screenshot3](https://cloud.githubusercontent.com/assets/6667703/10679520/b487edb0-78de-11e5-9126-e8e2628a69fb.png)
And or course you get the nice black corners on CSD's.
![screenshot4](https://cloud.githubusercontent.com/assets/6667703/10679678/c64451c8-78df-11e5-9fbf-3d7ec58b52c0.png)

Pretty craptacular... I figured I point this stuff out so you can direct people to this issue when they run into it... 
 EDIT:
Nope not a Unity/Compiz issue. Very similar issues in Ubuntu GNOME 15.10.
![screenshot from 2015-10-23 14-23-19](https://cloud.githubusercontent.com/assets/6667703/10695205/13b13e00-7992-11e5-83fd-bfda99de8685.png)

**Comment by JasonLG1979** [comment]
Update:

I guess I never really tried to resize the window in Xubuntu 15.04. It does pretty much the same thing as in 15.10.

![screenshot_5](https://cloud.githubusercontent.com/assets/6667703/10699892/b43b5116-797f-11e5-9f6d-556fff9ad94e.png)

I will test in Fedora to see if possibly it's a driver issue?

**Comment by TingPing** [comment]
We don't have any custom widgets so it is certainly a lower issue than our application. Black bars just means a redraw isn't being triggered, can you reproduce it in other gtk3 applications?

**Comment by JasonLG1979** [comment]
No it only effects Pithos as far as I can tell.

**Comment by TingPing** [comment]
I can reproduce in my 15.10 VM, so maybe I'll play around with it.

**Comment by JasonLG1979** [comment]
![screenshot from 2015-10-23 15-19-40](https://cloud.githubusercontent.com/assets/6667703/10702740/9f7f6b8a-7999-11e5-8413-b0af07ff03cb.png)
Same issue in Fedora 22.

**Comment by JasonLG1979** [comment]
+1 good job on the quick fix!!!
