### ISSUE TITLE
Window title out of order, odd tab naming in preferences

### ISSUE THREAD

**Issue by arcooke** [pithos/pithos#247]
These are both extremely minor, and I debated even bringing it up.  Really no big deal but I thought it would be worth mentioning.

* Most application window titles seem to follow a "\<content\> - AppName" standard, whereas Pithos uses "Pithos - Song Name"

I checked about a dozen other programs and I can't find any other that use this format.  

![Example](http://i.imgur.com/w4MyIdf.png)

* It seems backwards to me to have application settings nested under a Plugins tab in the Preferences dialog.  I think it would make more sense to rename that tab "options" or "settings", and possibly move audioscrobbler off to its own plugins tab, or just live as part of the application settings.

**Comment by TingPing** [comment]
> Most application window titles seem to follow a " - AppName" standard, whereas Pithos uses "Pithos - Song Name"

Sounds reasonable.

> It seems backwards to me to have application settings nested under a Plugins tab in the Preferences dialog.

They are not application settings they are plugin settings.

> possibly move audioscrobbler off to its own plugins tab, or just live as part of the application settings. 

It used to do that but it made pylast a required dependency and it required special code in the main app for a single plugin, effectively making it not a plugin. This was redone to clean everything up and make it modular so now any plugin can provide settings.

**Comment by arcooke** [comment]
Oh, alright.  Got ya on the plugins.   Thanks for the response, have a nice weekend.
