### ISSUE TITLE
xfce4-notifyd: No Album Art

### ISSUE THREAD

**Issue by hhhorb** [pithos/pithos#249]
Hey, Pithos is great, thank you!

I'm running Pithos version 1.1.1-2 under Debian jessie and Xfce (I've backported the Pithos version from stretch). Everything seems to be working great, except I don't have cover art in my notification popups.

Cover art appears in the main Pithos window, and I have python3-gi, python3-gi-cairo and python3-dbus all installed. Am I perhaps still missing dependencies, does album art not work with xfce4-notifyd or am I misunderstanding and this feature doesn't exist?

Thanks for your time and this great client!

**Comment by TingPing** [comment]
Do you see a generic music symbol instead?

**Comment by hhhorb** [comment]
Indeed I do.

**Comment by hhhorb** [comment]
Sorry, that means the commit fixes this?

**Comment by TingPing** [comment]
Should!

**Comment by hhhorb** [comment]
Doesn't seem to have worked. I edited the file /usr/share/pithos/pithos/plugins/notify.py, here it's line #124 to read ```self.notification.update(song.title, msg, 'audio-x-generic' if not song.art_pixbuf else None)```  and restarted pithos, no joy.

I guess I'll try building from your source and see if that works. Would you reopen this till then?

**Comment by hhhorb** [comment]
Scratch all that, I copied the raw content to my file and it's working. I think it needs one song to play first, but whatever. Thank you much!

**Comment by TingPing** [comment]
> I think it needs one song to play first, but whatever. Thank you much!

Yes it would be possible for us to update an image after the notification is shown but currently it relies on it being downloaded before the notification is shown. This is a separate issue though.

**Comment by hhhorb** [comment]
The current file-path in jessie is /usr/lib/python2.7/dist-packages/pithos/plugins/notify.py
