### ISSUE TITLE
/usr/lib/python3/dist-packages/gi/module.py:176 errors

### ISSUE THREAD

**Issue by JasonLG1979** [pithos/pithos#253]
Running Pithos from the terminal in Ubuntu 15.10 spits this out:
```
/usr/lib/python3/dist-packages/gi/module.py:176: Warning: g_array_append_vals: assertion 'array' failed
  g_type = info.get_g_type()
/usr/lib/python3/dist-packages/gi/module.py:176: Warning: g_hash_table_lookup: assertion 'hash_table != NULL' failed
  g_type = info.get_g_type()
/usr/lib/python3/dist-packages/gi/module.py:176: Warning: g_hash_table_insert_internal: assertion 'hash_table != NULL' failed
  g_type = info.get_g_type()
```
As per https://issues.mediagoblin.org/attachment/ticket/5066/GstPbutils_import_workaround.patch:
The workaround is to call Gst.init(None) before importing GstPbutils

```python
Gst.init(None)
from gi.repository import GstPbutils
```
I don't know if this Ubuntu specific or has been fixed upstream yet.

**Comment by TingPing** [comment]
Can you test this solution instead?

```python
import sys
sys.modules["gi.overrides.Gst"] = None
sys.modules["gi.overrides.GstPbutils"] = None
```

**Comment by JasonLG1979** [comment]
That seems to have done the trick.

**Comment by TingPing** [comment]
I spoke with the gst-python developer and from what I gathered gst-python is not meant to ever be optional and it is just a packaging error on Debian/Arch/Everyone's end. So maybe I'll handle it how you first mentioned.
