### ISSUE TITLE
butt/Icecast Integration

### ISSUE THREAD

**Issue by 19kestier** [pithos/pithos#256]
Using ![butt (broadcast using this tool)](http://butt.sourceforge.net/), I am able to stream anything playing back on a machine to an Icecast server. I then can play the stream on other devices in the house. 

![butt](https://cloud.githubusercontent.com/assets/4749568/11762942/ad73f262-a0c5-11e5-859c-8f2a94801863.png)

In butt, there is an option to update the "Now Playing" song title in Icecast from a file. So, would it be possible to write the current playing song to a file and update the file every time a new song comes on?
A plugin has already been written for Amarok, if this helps any. 
[butt_amarok.amarokscript.zip](https://github.com/pithos/pithos/files/60189/butt_amarok.amarokscript.zip)

**Comment by TingPing** [comment]
Pithos does have plugin support: https://github.com/pithos/pithos/tree/master/pithos/plugins

You could do something similar to *notify.py* except just write to a file instead of showing a notification.
