### ISSUE TITLE
404 Not Found on updates in Wily

### ISSUE THREAD

**Issue by txtad** [pithos/pithos#259]
I'm not sure when this started, but apt-get update is getting these errors now:

```
W: Failed to fetch http://ppa.launchpad.net/pithos/ppa/ubuntu/dists/wily/main/binary-amd64/Packages  404  Not Found

W: Failed to fetch http://ppa.launchpad.net/pithos/ppa/ubuntu/dists/wily/main/binary-i386/Packages  404  Not Found
```

Is Pithos supported on 15.10 yet?

**Comment by xmbwd** [comment]
I have the same issue.  I have previously installed 1.1.1-2, but get the above distribution update error on `sudo apt-get update`.  I currently have the Pithos sources disabled to avoid this error.  Hoping just temporary until Wily is supported.

**Comment by TingPing** [comment]
Yea somebody just needs to rebuild the package against willy.

**Comment by mbott001** [comment]
Is there going to be a replacement for Greg?  

-- 
Mike

**Comment by TingPing** [comment]
I don't think I personally have access to the PPA so you would really need to contact him, he might be more responsive by direct email.

**Comment by mbott001** [comment]
Tried that in November & December: no joy.

**Comment by gregsheremeta** [comment]
ack

I'll get this done :)

**Comment by mbott001** [comment]
Great, Thanks!

**Comment by bjmc** [comment]
I'm still getting 404 errors from the PPA on Ubuntu 15.10. Is there anything I can to do to help? In terms of building binaries or testing?

**Comment by mbott001** [comment]
And exactly how long does it take to rebuild the packages against Wily?

**Comment by mbott001** [comment]
At this date, I'm wondering if the same issue will soon impact Ubuntu 16.04 LTS (Xenial Xerus).

**Comment by TingPing** [comment]
You realize anybody can make their own package/PPA?

**Comment by mbott001** [comment]
And if I had the knowledge and experience, I would.

**Comment by TingPing** [comment]
Wily reaches end of life this month so I did not make any releases to it as users should upgrade to 16.04 but I did release updated packages for that. See #294 for more information.
