### ISSUE TITLE
Identity property missing from MPRIS DBus interface

### ISSUE THREAD

**Issue by hemebond** [pithos/pithos#262]
This property is a friendly name to identify the media player to users and is missing for Pithos.

http://specifications.freedesktop.org/mpris-spec/latest/Media_Player.html#Property:Identity

I can see from the source code that it should be supplying the Identity property (and many others) but they aren't showing up when I browse using D-feet. I tried to install from source but it wouldn't run for me. I am using version 1.0.3 via the PPA.

**Comment by hemebond** [comment]
I'm going to close this because I suspect it's just me and all the properties are missing, not just Identity.

**Comment by TingPing** [comment]
https://github.com/pithos/pithos/blob/d27f25db6fe3f6a09ea37769d49dc1649aafbc3b/pithos/plugins/_mpris.py#L144

**Comment by hemebond** [comment]
Hi @TingPing, that's the line I found and why I closed the ticket. Unfortunately none of those properties are accessible to me (via python-dbus or d-feet) for some reason.

**Comment by TingPing** [comment]
![d-feet screenshot](https://i.imgur.com/2ZnqfQE.png)

**Comment by hemebond** [comment]
Which version of Pithos are you using?

**Comment by TingPing** [comment]
Latest from git.

**Comment by hemebond** [comment]
Yeah, I'm on 1.0.3, the latest in the PPA for this version of Ubuntu.

**Comment by TingPing** [comment]
afaict not a whole lot has changed in the mpris area since then.

**Comment by TingPing** [comment]
Does manually calling `Get()` with `'org.mpris.MediaPlayer2', 'Identity'` not work?

**Comment by hemebond** [comment]
No, no properties. Also, there are some methods registered, Raise, Next, PlayPause and Previous.

**Comment by TingPing** [comment]
> (though the properties aren't immediately visible like they are for other media players).

Now that I know I fixed in 1.1.0 but it really only matters for browsing in d-feet.
