### ISSUE TITLE
PPA not getting updated anymore?  Still on version 1.0.3 from May 2015

### ISSUE THREAD

**Issue by arcooke** [pithos/pithos#265]
Hey all. The website says that the latest version is 1.1.2, however the PPA that is recommended on the site has not been updated since last May and is still on 1.0.3 with the buffering issues.

Is this PPA no longer being maintained?  Or just an oversight?

**Comment by TingPing** [comment]
This was discussed in #259 where @gregsheremeta said he would get around to it.

**Comment by arcooke** [comment]
Oh, OK.  Thanks

I've been beating my head against the wall with the old buffering issue, and I just now realized it's been fixed for months.. just the PPA hadn't been updated.

**Comment by TingPing** [comment]
1.0.3 already has the buffering changes.

**Comment by arcooke** [comment]
It's not fixed on my end, I still get it constantly.  Playlist freezes with a buffering message every 20 minutes or so.

![](http://i.imgur.com/XRQ9UV7.png)

**Comment by arcooke** [comment]
Just wanted to drop by and show that the buffering issue is still there on 1.0.3



![](http://i.imgur.com/0Qy9Z5Q.png)

then 4 songs later...

![](http://i.imgur.com/MF6HAuZ.png)

then 3 songs later...

![](http://i.imgur.com/QGq4460.png)

**Comment by JasonLG1979** [comment]
The freezing and buffing issues are a Gstreamer problem. They have nothing to do with the version of Pithos you're using and everything to do with your Gsteamer version. I don't remember exactly when the problems 1st started showing up, I think Gstreamer 1.2? In any event as of 1.6(the version that ships with Ubuntu 15.10) everything seems to be working just fine. I haven't had an issue in months.
