### ISSUE TITLE
Missing 'Manage Stations', 'About', 'Preferences' menus.

### ISSUE THREAD

**Issue by aamadis** [pithos/pithos#266]
Just upgraded to Ubuntu 15.04 and the menu bar that had the drop down option to change stations and preferences is missing. I thought maybe it had something to do with my upgrade but I see that the screenshot on the Pithos website is also missing this menu bar. Is this how the current Pithos is supposed to look? And if so how do I find those options now?

**Comment by TingPing** [comment]
I don't use Unity so I am not sure where they place menus anymore... it is either here:

![](http://images.techhive.com/images/article/2014/02/globalmenus-100247152-large.png)

or here:

![](http://core5.staticworld.net/images/article/2014/02/ubuntu-menu-in-app-100247151-large.png)

Or there is an option to change things: http://www.omgubuntu.co.uk/2015/01/ubuntu-15-04-always-show-menu-bar-option

**Comment by aamadis** [comment]
I don't use Unity either. I'm talking about the menu bar in Pithos. Before I upgraded there was an extra section of title bar right below the  Max/Min/Close buttons that said "Pithos" and when you clicked on it a drop down menu was revealed with options to manage your stations or change your preferences for how you connect to Pandora. That is not in this screenshot which is on the Pithos website. Looking at the screenshot, where do you select those options?

![](http://pithos.github.io/img/screenshot1.0.png)

**Comment by TingPing** [comment]
The placement of the menu depends on your DE, so what do you use?

**Comment by aamadis** [comment]
Gnome Fallback.

**Comment by TingPing** [comment]
I installed gnome-flashback 3.18.1 to test and the menubar was created in the window under the titlebar where you said it previously was. Perhaps an issue with the specific versions you have.

**Comment by aamadis** [comment]
I guess I was trying to ask if my Pithos looks exactly like the one in the screenshot, where does that one (in the screenshot) have the preferences menu located?

**Comment by TingPing** [comment]
That screenshot was taken on Unity and as my first comment mentioned it draws the menus externally.

**Comment by aamadis** [comment]
Ok thank you. First comment did not exactly indicate that the screenshot picture was taken with Unity, only that if I was using Unity I would find them externally. Hence the confusion.
