### ISSUE TITLE
Proper(ish) MPRIS implementation

### ISSUE THREAD

**Issue by JasonLG1979** [pithos/pithos#268]
It's known that MPRIS in Pithos is broken/not implemented properly. It's also apparent from skimming the MPRIS spec that it really wasn't designed for a "radio" app like Pithos. It's geared more towards your traditional media players in a lot of respects.(an example is that a media player is expected to have a "stop" function/button, which Pithos lacks.)

Aside from fixing what we do have(which is definitely needed) MPRIS does offer a few more neat features we could implement like track time/progress indication, and playlist support.

I opened this issue in the hopes of sparking discussion and to track progress on the way to a properly working MPRIS implementation in Pithos. And also as a way to wrangle MPRIS bugs.

**Comment by TingPing** [comment]
I don't think what we have is *that* broken but yes it could use improvements.

> we could implement like track time/progress indication

:+1: 

> and playlist support.

Playlists don't map perfectly to stations, but it is an interesting idea to play with.

**Comment by JasonLG1979** [comment]
> I don't think what we have is that broken but yes it could use improvements.
It doesn't "appear" broken but it is. It would be nice if it worked properly.
 
> Playlists don't map perfectly to stations, but it is an interesting idea to play with.

That's where the "ish" part comes in. My thought is for stations to appear as empty playlists(if that's possible?) When you click on the station the playlist would populate as you'd expect.

**Comment by TingPing** [comment]
> My thought is for stations to appear as empty playlists(if that's possible?) When you click on the station the playlist would populate as you'd expect.

That is what I was thinking.

> It doesn't "appear" broken but it is. It would be nice if it worked properly.

Other than not showing the length.. honestly it works perfectly for me.

**Comment by JasonLG1979** [comment]
> Other than not showing the length.. honestly it works perfectly for me.

It works for the most part but it's flaky at best. On every widget(or what ever you call them) I tested on, GNOME, Unity, and Cinnamon something always breaks after a while. On KDE 5 + it doesn't work at all.

**Comment by JasonLG1979** [comment]
So maybe we could set a roadmap for MPRIS? My thoughts are...

1. Clean up what we have and make it as close to spec as makes sense.
2. Add track time/progress indication.
3. Play with the whole playlist idea.

I'll have a week or so off because I'm transitioning to a new job, so I'll read up on the spec and look at a few examples from other apps to see what I come up with. After that the track time/progress indication stuff is pretty easy I played with that and got it working a couple months ago it's just a matter of remembering what I did,lol!!!

**Comment by JasonLG1979** [comment]
@TingPing, your thoughts on how the playlist/stations thing should behave?

My thoughts are that the playlist should only contain upcoming "playable" songs. It shouldn't show the current song(redundant) and shouldn't show past played songs since they can't be replayed anyway and after a while the list could get huge.

**Comment by TingPing** [comment]
Well the *MediaPlayer2.TrackList* interface should show [some] past, current, and future songs; To quote the docs:

> Provides access to a short list of tracks which were recently played or will be played shortly. This is intended to provide context to the currently-playing track, rather than giving complete access to the media player's playlist.

As for *MediaPlayer2.Playlists* it doesn't actually lists songs so it is just the station names.

**Comment by JasonLG1979** [comment]
My concern is that it will expect to be able to play past songs and start the current song over.

**Comment by TingPing** [comment]
I think it is fine to include the past 2-3 tracks and just do nothing when *GoTo* is called on them. The risk of people being that confused that their "radio" client can't replay tracks shouldn't be too bad.

**Comment by JasonLG1979** [comment]
Fair enough I'll shoot for showing 2 playlists(8 songs max) 1 past playlist and the current playlist.

**Comment by JasonLG1979** [comment]
Making some progress cleaning it up and adding track time/progress indication.

![screenshot from 2016-02-21 17-20-09](https://cloud.githubusercontent.com/assets/6667703/13206313/089a0b26-d8c1-11e5-986e-c662d2d134f5.png)

Running into a little weirdness though. I'm not sure if it's the media player extension or something I'm doing(it's probably me) but for the time to show up I have to toggle the feature off then on again in the extension's setting. Also since we don't know the track duration when the song starts I'm using the duration provided by Pandora so it's off every now and then. MPRIS also doesn't seem to use Pithos for position(it seems to use it's own clock?) so the position is off a little sometimes to. I may just create a new "song-started" signal to sync their position.

**Comment by JasonLG1979** [comment]
@TingPing, have a look at this. It's just a little bit of cleanup and a fix up on the ratings so they follow spec more closely(from what I can tell anyway) The net effect is that the Metadata is not updated every time a single property is updated or every time the play state is changed. This should help with not bombarding media applets and should make things more stable.

 https://github.com/JasonLG1979/pithos/tree/MPRIS_cleanup

**Comment by TingPing** [comment]
Less metadata changes sounds good. Shouldn't you keep setting playstate to paused when `stop()` is is called though?

**Comment by JasonLG1979** [comment]
I'm not sure how it effect the rest of Pithos but from a mpris standpoint we never paused really. If anything we should set the play state in mpris to stopped when we're stopped. When it comes time to add track time indication we'll have to anyway. Mpris seems to use its own clock setting the play state to stopped in mpris is how it knows to clear the time. Otherwise the clock keep ticking in between songs and never resets.

**Comment by JasonLG1979** [comment]
@TingPing could you test that branch? I added time indication but it's very flaky across applets. The Ubuntu sound menu doesn't expose time so it has no effect there. The default Cinnamon sound applet in Fedora 23 doesn't show time either but one of the other downloadable applets does show the time and it seems to work as expected. I'm going to test on GNOME shortly.

**Comment by JasonLG1979** [comment]
@TingPing, does 'def Introspect' in _mpris.py actually do anything?

**Comment by TingPing** [comment]
> does 'def Introspect' in _mpris.py actually do anything?

It is mostly useful for debugging, without it external applications like *d-feet* don't know what properties our interface actually exposes.

**Comment by JasonLG1979** [comment]
Right on. So far I've tested on Ubuntu(doesn't expose much, works fine), 2 widgets in Cinnamon and 2 widgets GNOME. I can't get consistent behavior for track time on any of the widgets. What works in one widget breaks the other widgets.

**Comment by JasonLG1979** [comment]
@TingPing, Test this would you.
https://github.com/JasonLG1979/pithos/tree/MPRIS_changes

I pretty much rewrote the MPRIS implementation roughly based on GNOME Music's implementation.

**Comment by JasonLG1979** [comment]
Also a question. is the '/net/kevinmehall/Pithos' interface obsolete? Disabling it seems to have no effect.

**Comment by TingPing** [comment]
> Disabling it seems to have no effect.

I'm not sure what you expect to happen...

> Also a question. is the '/net/kevinmehall/Pithos' interface obsolete?

Sort of, the reason I left it is because love/ban interface. Mapping that to MPRIS ratings is weird (and do we even support changing those?).

**Comment by JasonLG1979** [comment]
> I'm not sure what you expect to happen...

I wasn't sure what to expect? But disabling it had no effect.

> Sort of, the reason I left it is because love/ban interface. Mapping that to MPRIS ratings is weird (and do we even support changing those?).

Those methods can be moved to _mpris and exposed on the mpris interface. MPRIS applets/controllers can then add support for them if they like and call them. We already expose  love/ban/tired/None(well '' for None as Mpris can't handle None) in pithos:rating in the MPRIS metadata. So if an applet were to add support for changing the rating by calling those methods the pithos:rating would be updated. At the moment in my changes I mapped a "love" rating to 5 and everything else to 0 so applets that support displaying ratings would show 5 stars(or whatever) for a loved song and 0 stars/unrated for everything else.

**Comment by JasonLG1979** [comment]
From https://wiki.gnome.org/MiloszDerezynski

>The principle is simple: Players acquire a bus name in the namespace of 'org.mpris.*' (e.g. org.mpris.vlc for VLC), and an interface name of org.freedesktop.MediaPlayer, with several objects exposed. They can provide own, custom objects for custom methods, but the MPRIS-specced objects conform to the one spec, and thus clients can rely on identical behaviour from each media player.

**Comment by TingPing** [comment]
Oh right I forgot we added `pithos:rating` but it is still read-only so yea we would need custom setters for it.

**Comment by JasonLG1979** [comment]
All the metadata is technically read only in the sense that to change one thing you have to reload all the metadata but it can be updated any time you want. Try by branch and love and unlove some songs. The rating updates in the applets.

**Comment by JasonLG1979** [comment]
I just set up a 'mpris-metadata-changed' signal that fires in pithos.py whenever something changes that requires a metadata update.

**Comment by JasonLG1979** [comment]
I've added the ratings methods to _mpris.py in my latest commit and confirmed they are accessible via dbus-send.

Available methods are:
LoveCurrentSong
BanCurrentSong
TiredCurrentSong
UnrateCurrentSong
Next
Pause
PlayPause
Stop (mapped to pause)
Play

They can be tested with:
```
dbus-send --print-reply --dest=org.mpris.MediaPlayer2.Pithos /org/mpris/MediaPlayer2 org.mpris.MediaPlayer2.Player.*METHOD*
```

**Comment by TingPing** [comment]
> LoveCurrentSong
BanCurrentSong
TiredCurrentSong
UnrateCurrentSong

Could probably combine these into one method, `Rate()` or simliar.

**Comment by JasonLG1979** [comment]
I'm not sure if arguments can be passed from the bus.

**Comment by TingPing** [comment]
Sure they could.. see the `in_signature` arg.

**Comment by JasonLG1979** [comment]
Cool so we could do def RateCurrentSong(self, rating):

**Comment by TingPing** [comment]
`CurrentSong` is extraneous info, all of the methods operate on the current song.

**Comment by JasonLG1979** [comment]
> CurrentSong is extraneous info, all of the methods operate on the current song.

At the moment they do but in the future we may implement TrackList. That's what the trackid is for, so we may want to add an arg for the trackid too to future proof it a bit maybe?

**Comment by TingPing** [comment]
At that point we could add a `RateTrack()` method to the `MediaPlayer2.TrackList` interface.

**Comment by JasonLG1979** [comment]
> At that point we could add a RateTrack() method to the MediaPlayer2.TrackList interface.

True. So I guess we could just RateSong then. I'm unsure how the args map though. Is it just def RateSong(self, rating): or does it need to be in the decorator?

**Comment by TingPing** [comment]
> or does it need to be in the decorator

Yes as I said it takes `in_signature` so try that out. (I never use python-dbus, *shrug*)

**Comment by JasonLG1979** [comment]
Along the way to  #269 I figured out by rading the GNOME media indicator source code that it makes some odd assumptions and some bad decisions(IMHO).

For example:
1. The "CanSeek" prop has to be True for Position slider to be shown. Like it's not possible to have valid position/duration if you can't seek?

2. It checks for a change in the song url to tell if a song has changed instead of relying on the trackid(which the spec clearly says is the one value the metadata is absolutely expected to have)

Anyway I tweaked my pull request to account for some of it's quirks and now track time/progress indication works as expected.

**Comment by TingPing** [comment]
>  I figured out by rading the GNOME media indicator source code that it makes some odd assumptions and some bad decisions(IMHO).

Seems actively developed, should fix the problems upstream.

**Comment by JasonLG1979** [comment]
I have an issue out about the track time issue. I'll open one about the trackid. In the mean time, like I said my pull request accounts for the quirks. Since most of the other applets are based on the GNOME media indicator it is kinda the defacto standard.

**Comment by JasonLG1979** [comment]
The Laine extension also works as expected after accounting for the quirks. I'll test the Mint applets.

**Comment by JasonLG1979** [comment]
@TingPing what do think about using the default audio mime type icon for the cover in mpris if we don't get a cover from Pandora?

Something like this should do it.

```
        if song.artUrl or song.artRadio:
            artUrl = song.artUrl or song.artRadio
        else:
            icon_theme = Gtk.IconTheme.get_default()
            icon_info = icon_theme.lookup_icon('audio-x-generic', 48, 0)
            artUrl = ("file:///%s"  %icon_info.get_filename())
```

**Comment by TingPing** [comment]
Seems unnecessary, if we return nothing the client can choose how to display it.

**Comment by JasonLG1979** [comment]
I agree but different clients handle and empty string(what we return if there is no cover) differently. Many clients reuse the cover from the last song.

**Comment by JasonLG1979** [comment]
This way we could get consistent behavior another option which I actually like is to return the file path of the Pithos icon.

**Comment by JasonLG1979** [comment]
For the sake of consistency I'm for show the generic icon in MPRIS if we don't have a cover because the notify plugin does the same.
```
        self.notification.update(song.title, msg, 'audio-x-generic' if not song.art_pixbuf else None)
        self.notification.show()
```

**Comment by JasonLG1979** [comment]
Something like this would be functionally the same for MPRIS.
```
        #try to use the generic audio MIME type icon from the user's current theme
        #for the cover image if we don't get one from Pandora else return an empty string
        if song.artUrl or song.artRadio:
            artUrl = song.artUrl or song.artRadio
        else:
            icon_theme = Gtk.IconTheme.get_default()
            icon_info = icon_theme.lookup_icon('audio-x-generic', 48, 0)
            if icon_info is not None:
                artUrl = ("file://%s" %icon_info.get_filename())
            else:
                artUrl = ""
```

**Comment by TingPing** [comment]
When is artRadio ever an empty string? I've never encountered one.

**Comment by JasonLG1979** [comment]
OK my bad it should be:

        #try to use the generic audio MIME type icon from the user's current theme
        #for the cover image if we don't get one from Pandora else return an empty string
        if song.artUrl:
            artUrl = song.artUrl
        else:
            icon_theme = Gtk.IconTheme.get_default()
            icon_info = icon_theme.lookup_icon('audio-x-generic', 48, 0)
            if icon_info is not None:
                artUrl = "file://%s" %icon_info.get_filename()
            else:
                artUrl = ""

**Comment by JasonLG1979** [comment]
Edit: If there's no album cover displayed in the UI artRadio is an empty string in _mpris.py

**Comment by JasonLG1979** [comment]
@TingPing I amended my pull request with:

``` 
        #try to use the generic audio MIME type icon from the user's current theme
        #for the cover image if we don't get one from Pandora else return an empty string 
        if song.artUrl is not None:
            artUrl = song.artUrl
        else:
            icon_theme = Gtk.IconTheme.get_default()
            icon_info = icon_theme.lookup_icon('audio-x-generic', 48, 0)
            if icon_info is not None:
                artUrl = "file://%s" %icon_info.get_filename()
            else:
                artUrl = ""
```
As I said before it fixes the issue of some clients/applets reusing the past song's cover if there is no cover(pretty much all of them except the Ubuntu SoundMenu) and it's consistent with the notify plugin.

**Comment by TingPing** [comment]
@JasonLG1979 I'm not sure what you are saying about `song.artRadio`, this completely ignores it which should always be a valid url, sure *some* clients seem to not understand `http://` so they might be broken but I don't think that should mean we ignore it.

**Comment by JasonLG1979** [comment]
> I'm not sure what you are saying about song.artRadio, this completely ignores it which should always be a valid url,

We can safely ignore it because if  song.artRadio doesn't error out(actually points to a valid image) song.artUrl is a temp file of the image created specifically for MPRIS .

> some clients seem to not understand http:// so they might be broken
...Some clients mean ALL of them except the Ubuntu SoundMenu.

If you put:

```
        if self.window.current_song is not None:
            print(type(self.window.current_song.artRadio), self.window.current_song.artRadio)
```
in song_changed in _mpris.py you'll see that if there is no album cover in the UI,  song.artRadio is an empty string.

**Comment by TingPing** [comment]
I used the gnome extension for years and it supported the `http://` urls.

**Comment by JasonLG1979** [comment]
Not very well. If you don't give it a valid url(valid meaning it actually points to an image) it reuses the last song's cover.

**Comment by JasonLG1979** [comment]
I don't know anything about js but it doesn't seem to do any error checking for http:// urls...
```
if (state.trackCoverUrl) {
          let cover_path = "";
          // Distant cover
          if (state.trackCoverUrl.match(/^http/)) {
            // Copy the cover to a tmp local file
            let cover = Gio.file_new_for_uri(decodeURIComponent(state.trackCoverUrl));
            // Don't create multiple tmp files
            if (!this._trackCoverFileTmp)
              this._trackCoverFileTmp = Gio.file_new_tmp('XXXXXX.mediaplayer-cover')[0];
            // asynchronous copy
            cover.read_async(null, null, Lang.bind(this, this._onReadCover));
          }
          // Local cover
          else if (state.trackCoverUrl.match(/^file/)) {
            state.trackCoverPath = decodeURIComponent(state.trackCoverUrl.substr(7));
```

**Comment by JasonLG1979** [comment]
I'll start a new issue for that too. I started out trying to fix mpris in Pithos and I'm going to end up reporting 75 bugs in the media indicator,lol!!!

**Comment by JasonLG1979** [comment]
Edit after reading the code it backs me up.
```
            if (!this._trackCoverFileTmp)
              this._trackCoverFileTmp = Gio.file_new_tmp('XXXXXX.mediaplayer-cover')[0];
```

Seems to me to say that there is only ever 1 tmp file if decodeURIComponent errors out it doesn't create a new tmp file.

**Comment by JasonLG1979** [comment]
https://github.com/eonpatapon/gnome-shell-extensions-mediaplayer/issues/247
https://github.com/eonpatapon/gnome-shell-extensions-mediaplayer/issues/248

2 more issues to reference.

**Comment by TingPing** [comment]
Good work tracking these issues down upstream, if I figure out a good workflow for debugging extensions I might look into helping fix them.

**Comment by JasonLG1979** [comment]
My little brother is a js/web developer by trade. I'm trying to con him into helping me with some pull requests to fix the issues and maybe add proper Pithos rating support to the extension both setting and reading. The long game is to move all the functionality of the tray icon to the extension.

**Comment by JasonLG1979** [comment]
It would also be nice to add tracklist support to the extension. It supports Playlists but not Track lists from what I can tell?

**Comment by JasonLG1979** [comment]
In the meantime until the issues are fixed upstream the workarounds don't break functionality for other clients what do you think?

**Comment by JasonLG1979** [comment]
Edit: Oops I put this in the wrong bug report,lol!!!

With the current master Pithos does not work at all with the KDE 5 sound menu in Fedora KDE.
![snapshot2](https://cloud.githubusercontent.com/assets/6667703/13410998/688a55aa-df00-11e5-82f1-18f712b6240e.png)

With my MPRIS_fixes branch it seems to work as expected.
![snapshot1](https://cloud.githubusercontent.com/assets/6667703/13411013/82ab7f04-df00-11e5-844a-fdcd04e33d51.png)

**Comment by JasonLG1979** [comment]
Here's what I'd like to see as far as moving the functionality of the tray icon to the GNOME mediaplayer indicator. This is more of a "functional" mockup as it's not meant to show/convey style just how I'd like it to function.
![mockup](https://cloud.githubusercontent.com/assets/6667703/13414118/b76c3cd2-df15-11e5-8f6b-be84338ec3b9.png)
