### ISSUE TITLE
Notification icon can become out of sync.

### ISSUE THREAD

**Issue by JasonLG1979** [pithos/pithos#270]
Raising the window with an MPRIS applet(Ubuntu sound menu, GNOME Media Indicator) can cause the Notification icon to be out of sync.

Expected:
Raising the window with MPRIS should tell the Notification icon that the window has been raised and it should act accordingly.

Current behavior:
Raising the window with MPRIS causes the "Show Pithos" toggle to be out of sync so that the toggle has the opposite intended effect and the window can not be closed until it is raised again by MPRIS.

**Comment by TingPing** [comment]
Is this still an issue? Was this solved by 972f60b74cd3ef0cdc8c5525afe613f013f6e610?

**Comment by JasonLG1979** [comment]
Seems to fix GNOME, I'll check in Ubuntu tomorrow.

**Comment by JasonLG1979** [comment]
Nope still an issue on Ubuntu.

**Comment by JasonLG1979** [comment]
That did the trick!!!
