### ISSUE TITLE
Ubuntu 15.10 Build failure

### ISSUE THREAD

**Issue by seanrich** [pithos/pithos#272]
The autogen.sh script fails to configure correctly.
```
(~/pithos)$ autoreconf --force --install -Wno-portability
configure.ac:16: warning: AM_NLS is m4_require'd but not m4_defun'd
m4/intltool.m4:27: IT_PROG_INTLTOOL is expanded from...
configure.ac:16: the top level
configure.ac:16: warning: AM_NLS is m4_require'd but not m4_defun'd
m4/intltool.m4:27: IT_PROG_INTLTOOL is expanded from...
configure.ac:16: the top level
configure.ac:16: warning: AM_NLS is m4_require'd but not m4_defun'd
m4/intltool.m4:27: IT_PROG_INTLTOOL is expanded from...
configure.ac:16: the top level
configure.ac:16: warning: AM_NLS is m4_require'd but not m4_defun'd
m4/intltool.m4:27: IT_PROG_INTLTOOL is expanded from...
configure.ac:16: the top level
configure:2702: error: possibly undefined macro: AM_NLS
      If this token and others are legitimate, please use m4_pattern_allow.
      See the Autoconf documentation.
autoreconf2.50: /usr/bin/autoconf failed with exit status: 1
```
```
(~/pithos)$ aclocal --install -I "/usr/share/aclocal"
(~/pithos)$ intltoolize --force --copy --automake
(~/pithos)$ autoreconf  --force -I "/usr/share/aclocal" --install -Wno-portability
```

Was successful at configuring. Using the supplied m4 directory does not work.

**Comment by TingPing** [comment]
Install gettext dev packages.

**Comment by TingPing** [comment]
The docs already included intltool - https://github.com/pithos/pithos/wiki/Installing-from-Source

**Comment by seanrich** [comment]
```
(~/pithos)$ dpkg --get-selections | grep gettext
gettext                                         install
gettext-base                                    install
libgettextpo-dev:amd64                          install
libgettextpo0:amd64                             install
liblocale-gettext-perl                          install
```
```
(~/pithos)$ dpkg --get-selections | grep intltool
intltool                                        install
intltool-debian                                 install
```
I followed the guide and installed all recommended packages. Is there something I'm missing? I have the dependencies installed, or else pointing to my local `/usr/share/aclocal` directory wouldn't work.

**Comment by TingPing** [comment]
`AM_NLS` is in `nls.m4` which is a part of gettext.

**Comment by TingPing** [comment]
Nothing wrong with the `./autogen.sh` script. I'm not sure why you ran those other commands in your original comment but those are bogus. Worst case you can copy `nls.m4` manually to the m4 dir.

**Comment by seanrich** [comment]
Ahh, I see you're misunderstanding.

```
(~/pithos)$ ./autogen.sh 
configure.ac:16: warning: AM_NLS is m4_require'd but not m4_defun'd
m4/intltool.m4:27: IT_PROG_INTLTOOL is expanded from...
configure.ac:16: the top level
configure.ac:16: warning: AM_NLS is m4_require'd but not m4_defun'd
m4/intltool.m4:27: IT_PROG_INTLTOOL is expanded from...
configure.ac:16: the top level
configure.ac:16: warning: AM_NLS is m4_require'd but not m4_defun'd
m4/intltool.m4:27: IT_PROG_INTLTOOL is expanded from...
configure.ac:16: the top level
configure.ac:16: warning: AM_NLS is m4_require'd but not m4_defun'd
m4/intltool.m4:27: IT_PROG_INTLTOOL is expanded from...
configure.ac:16: the top level
configure.ac:16: warning: AM_NLS is m4_require'd but not m4_defun'd
m4/intltool.m4:27: IT_PROG_INTLTOOL is expanded from...
configure.ac:16: the top level
configure.ac:16: warning: AM_NLS is m4_require'd but not m4_defun'd
m4/intltool.m4:27: IT_PROG_INTLTOOL is expanded from...
configure.ac:16: the top level
configure:2702: error: possibly undefined macro: AM_NLS
      If this token and others are legitimate, please use m4_pattern_allow.
      See the Autoconf documentation.
autoreconf2.50: /usr/bin/autoconf failed with exit status: 1
```

The `autogen.sh` script does not work. I simply showed the line where it fails, instead of just the whole script.

The other lines in my comment are how I fixed the problem in the first place.

I tried what you suggested:
```
 (~/pithos)$ cp /usr/share/aclocal/nls.m4 m4/
 (~/pithos)$ ./autogen.sh 
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /bin/mkdir -p
checking for gawk... gawk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking whether make supports nested variables... (cached) yes
checking for a Python interpreter with version >= 3.4... python3
checking for python3... /usr/bin/python3
checking for python3 version... 3.4
checking for python3 platform... linux
checking for python3 script directory... ${prefix}/lib/python3.4/site-packages
checking for python3 extension module directory... ${exec_prefix}/lib/python3.4/site-packages
configure: error: gsettings.m4 not found
```
It seems likely that the `-I m4` in `aclocal --install -I m4 || exit 1` is overriding the include of the system's aclocal directory.

**Comment by TingPing** [comment]
> It seems likely that the -I m4 in aclocal --install -I m4 || exit 1 is overriding the include of the system's aclocal directory.

Nope you can read aclocal yourself, system paths are hardcoded and always used.

Anyway whatever problem you have it is of your system, perhaps the version of autotools, perhaps a distro specific patch. *shrug*.

**Comment by JasonLG1979** [comment]
The wiki was missing ```libxml2-utils``` as a dependency. I fixed it. If you follow the instructions now you should be fine.

**Comment by TingPing** [comment]
> The wiki was missing libxml2-utils as a dependency.

Shouldn't that be in the optional line?

**Comment by JasonLG1979** [comment]
> Shouldn't that be in the optional line?

No. It won't build without it...

**Comment by TingPing** [comment]
> No. It won't build without it...

Curious which step fails?

**Comment by JasonLG1979** [comment]
```
XMLLINT not set and xmllint not found in path; skipping xml preprocessing.
XMLLINT not set and xmllint not found in path; skipping xml preprocessing.
Makefile:1123: *** missing separator (did you mean TAB instead of 8 spaces?).  Stop.
```

**Comment by JasonLG1979** [comment]
It's all in #239

**Comment by JasonLG1979** [comment]
Before people file new issues they should search closed issues to make sure that someone else hasn't already solved the problem.

**Comment by JasonLG1979** [comment]
To me the only real issue is that it wasn't on the wiki and that's fixed now. So this bug is invalid now.

**Comment by TingPing** [comment]
> XMLLINT not set and xmllint not found in path; skipping xml preprocessing.

Ok so that is simply a warning and not a problem.

> Makefile:1123: *** missing separator (did you mean TAB instead of 8 spaces?).  Stop.

Would have to see the Makefile to know exactly what it is pointing at.

**Comment by JasonLG1979** [comment]
I just remember that it won't build without it. I've been meaning to update the wiki, just haven't got around to it. I'm on Fedora right now so I can test on (an un-hacked) GNOME 3.18 so I can't give you a make file.
