### ISSUE TITLE
Skipping current song sometimes skips one extra song

### ISSUE THREAD

**Issue by maddin77** [pithos/pithos#275]
Sometimes when skipping a song, one extra song gets skipped (currently playing song 1, press skip, now it's playing song 3 instead of 2).

I don't really know how to reproduce this other than trying a bunch of times (takes me like 3-5 times until it happens).

I'm not sure how/if these are related, but i noticed that when the extra skip happens, the problem i just described in #261 *always* happens.

I'm still using the [MPRIS_fixes](https://github.com/JasonLG1979/pithos/tree/MPRIS_fixes) branch in case that's relevant.

**Comment by JasonLG1979** [comment]
Don't file issues on the main Pithos if you're running someone else's fork. It's too hard to tell if it's a problem with Pithos proper or with the particular fork.

**Comment by maddin77** [comment]
Sorry, i didn't think about that.

I tested master and can't reproduce the issue so i'll close this.
