### ISSUE TITLE
"smart" Pandora One checkbox

### ISSUE THREAD

**Issue by JasonLG1979** [pithos/pithos#280]
We can do something similar to what we do with the explicit content filter checkbox with the Pandora One checkbox. Basically we can make it insensitive(uncheckable) if the user is not a Pandora On subscriber.

This will return if the user is a Pandora One subscriber or not.

``` python
    @property
    def is_subscriber(self):
        """The User must already be authenticated before this is called.
           returns if the user is a Pandora One subscriber
        """
        can_subscribe = self.json_call('user.canSubscribe', https=True)
        return can_subscribe['isSubscriber']
```

**Comment by JasonLG1979** [comment]
Doing some looking Pandora is kind enough to return a canListen attr when a user authenticates that can be used to tell if a listener can, you guessed it, listen. Basically if a free user tries to login with the Pandora One checkbox checked canListen will be False. We can use that to drop them down to a free account more gracefully and re log them in. Combined with the isSubscriber stuff we can make it so that the Pandora One checkbox is inactive for free users and any new accounts entered will fallback gracefully.

**Comment by TingPing** [comment]
Ideally I'd like to not expose that check box at all. It should automatically upgrade or downgrade the login for you.

**Comment by JasonLG1979** [comment]
Well the problem is as far as I can tell there's no way to get far enough in the auth process without picking a client.

**Comment by TingPing** [comment]
If it requires a relog that is acceptable, it should only happen rarely.

**Comment by JasonLG1979** [comment]
> If it requires a relog that is acceptable, it should only happen rarely.

Shouldn't be hard. isSubscriber will tell us that if the user is a Pandora One user or not. We just start with the assumption that everyone is a free user(because most are) and use the default creds. But then if someone isSubscriber we bump them up and remember. Later if that account goes free again we bump them back down.

**Comment by JasonLG1979** [comment]
You can get isSubscriber during auth by adding 'returnIsSubscriber': True to the parms.

**Comment by JasonLG1979** [comment]
So worst case A user changing tiers gets a double login the 1st time.

**Comment by JasonLG1979** [comment]
Get the async password stuff merged and I'll get to work on it. I've tested the re-login and it seems to work just fine.

**Comment by JasonLG1979** [comment]
It would be beneficial to split up authentication and retrieving stations at that point. We should authenticate then check to see if the user is a subscriber go from there to see if we should change clients then once we got the one we want finally get the stations. Right now it's all in one shot, auth then get stations.

**Comment by JasonLG1979** [comment]
https://github.com/pithos/pithos/pull/462

There you go auto client, no Pandora One checkbox.
