### ISSUE TITLE
CPU usage seems unusually high

### ISSUE THREAD

**Issue by rickpage** [pithos/pithos#281]
Pithos 1.1.1-2
Pithos: ~40% CPU usage
Chrome: ~8-20% CPU Usage

Even when the player is paused, CPU usage is about 40%. Intel i3-6100 so recent CPU. Running Ubuntu 16.04. This is a real shame, I like the idea behind Pithos but for me, it is not so light on system resources.
Compare this with chrome, Version 47.0.2526.111 unknown (64-bit), max 22% but sitting around 6-8% mostly . Chrome only logged in to Pandora.com. Pandora One account, so assuming no ad-skipping.
 I get roughly the same CPU usage when both are running, even if I let both play at the same time on different stations.

I'd like to further debug this but I haven't had time to look through source. Any pointers appreciated on how to better profile this to find the issue..

Im also open to any ideas/settings that would change CPU usage. All of the plugins I have turned off then reloaded Pithos, to no avail.

**Comment by JasonLG1979** [comment]
Strange I have not seen that. For me running the latest git on Fedora 23 GNOME with and Intel Pentium CPU G2030T @ 2.60GHz × 2, Pithos idles, according to htop anywhere from 0 - 2% and hit maybe 6 - 10% buffering(because the buffering function hammers the UI with a crazy amount of updates during buffering to show the buffering progress) I have never seen a 40% idle.

Did you install from source, a ppa or what?

I'll fire up a VM and/or LiveUSB and see what I get.

**Comment by JasonLG1979** [comment]
Ok I installed and ran Ubuntu 16.04 in a VM and installed Pithos from git. I could reproduce your bug(and other issues) with the default themes. I got anywhere from 20 - 30% CPU usage. But after installing the arc theme and switching to it the issues including the high CPU usage went away. I'd say their theme is screwed up some how. @rickpage can you try switching to a non-default theme and seeing if that solves the problem?

**Comment by JasonLG1979** [comment]
Well the problem seems to be that Ubuntu uses a gradient background which doesn't play well with bgcolor_data_func in init_ui. It basically spins it's wheels trying to figure out the color. I think I fixed it(at least it fixed the problem for me?) @rickpage could you give this a test.

https://github.com/JasonLG1979/pithos/tree/high-cpu-usage-fix

**Comment by JasonLG1979** [comment]
@TingPing The point of bgcolor_data_func seems to be to always set the background color of the current song to selected/active. It only seems to work(and when I say work I also mean cause this nasty bug) on Ubuntu's default theme. It does nothing except use up CPU cycles on any other theme that I've tested it on.(no background color change) Just getting rid of it would solve this issue and free up the CPU a bit. Thought?

**Comment by TingPing** [comment]
@JasonLG1979 Sounds fine.. the widget should already be changing the color on selection so I am unsure what it is doing.

**Comment by JasonLG1979** [comment]
OK I'll put in a PR here in a sec.

**Comment by JasonLG1979** [comment]
PR's in.

**Comment by JasonLG1979** [comment]
> the widget should already be changing the color on selection so I am unsure what it is doing.

It basically sets/keeps the current song's cell background to active. On the default Ubuntu themes that means the current song's cell background is always orange if it's selected or not. Which is a little confusing if you ask me if you select another song you end up with 2 songs with active/selected backgrounds. But Like I said on any other theme I tested it on it did nothing.

**Comment by rickpage** [comment]
Switching to stock high contrast theme in Ubuntu lets the CPU usage drop to 6%-11%, switching to Ambiance (default) moves up to 30-40%. ...  Installed from source just now, huge improvement. Thanks for quick fix @JasonLG1979 and @TingPing working great now on Ubuntu 16.04 (with Ambiance theme)

**Comment by JasonLG1979** [comment]
@rickpage so you're back to the 0 - 2% idle?

**Comment by rickpage** [comment]
yes

**Comment by rowntreerob** [comment]
FWIW on 'xenial', the high-cpu-usage-fix branch solved issues with CPU%   (from  40 down under 5). getting thru the 'autogen.sh' required number of errors / prereq installs.  Then it install fine and run great.

**Comment by rathboma** [comment]
Hey guys, I just installed 16.04 and installed Pithos and I'm seeing this problem. The version I have is 1.1.1-2. Can someone suggest the best way to get the default pithos package updated for Ubuntu's repos?

**Comment by TingPing** [comment]
@rathboma The packages in the main repos will never be updated if that is what you mean, Ubuntu by design doesn't support most of their packages. The PPA is simply the way users should get Pithos on Ubuntu.

**Comment by rathboma** [comment]
Yep, that's what I was getting at. Fair Enough


Matthew Rathbone
==
matthew.rathbone@gmail.com
