### ISSUE TITLE
Deprecated and unnecessary things in CellRenderers

### ISSUE THREAD

**Issue by JasonLG1979** [pithos/pithos#284]
In CellRendererAlbumArt, get_size has been deprecated since 3.0.
https://developer.gnome.org/gtk3/stable/GtkCellRenderer.html#gtk-cell-renderer-get-size
It can be replaced with render_icon.set_fixed_size(ALBUM_ART_SIZE, ALBUM_ART_SIZE) in init_ui

ALBUM_ART_X_PAD is unnecessary. The same thing can be achieved by adding horizontal padding to render_text in  init_ui with  render_text.set_padding(12, 0) (or whatever value you like, 12 looks good to me?)

**Comment by JasonLG1979** [comment]
Rolled it in to #276

**Comment by TingPing** [comment]
This seems unrelated to that, please don't clump things together, if you want me to merge things in a reasonable time keep them contained.

**Comment by JasonLG1979** [comment]
I figured I was changing CellRendererAlbumArt anyway. They seemed very related?

**Comment by JasonLG1979** [comment]
I can roll it back if you want?

**Comment by TingPing** [comment]
If you really want it in the same PR fine, but it is a separate logical change and should be a separate commit at the very least.

**Comment by JasonLG1979** [comment]
I'll make it a separate commit

**Comment by JasonLG1979** [comment]
There 2 separate commits.

**Comment by TingPing** [comment]
Merged as 8a4616afc3c6c878f5f104c3cf29b95e24eb19c1
