### ISSUE TITLE
Ubuntu distributions, brand new and end-of-life

### ISSUE THREAD

**Issue by Olathe** [pithos/pithos#294]
According to [the Ubuntu release end of life chart](http://www.ubuntu.com/info/release-end-of-life), there are a few issues with [the distributions supported by the Pithos PPA](http://ppa.launchpad.net/pithos/ppa/ubuntu/dists/).

### New releases should be added

The most important thing is that new releases should be added, since otherwise [the installation instructions](https://pithos.github.io/#install) won't work. The following releases should be added:

* Wily Werewolf (Ubuntu 15.10) reaches end-of-life in July 2016
* Xenial Xerus (Ubuntu 16.04 LTS) reaches end-of-life in April 2021

### Unsupported releases should be removed

Less important is that Ubuntu releases eventually reach end-of-life, which means they get no updates, including security patches, which is quite dangerous. People should be pushed toward releases that are being updated. As such, here is a list of no-longer-updated releases that you may want to remove:

* Quantal Quetzal (Ubuntu 12.10) reached end-of-life in July 2013
* Raring Ringtail (Ubuntu 13.04) reached end-of-life in January 2014
* Saucy Salamander (Ubuntu 13.10) reached end-of-life in July 2014
* Lucid Lynx (Ubuntu 10.04 LTS) reached end-of-life in April 2015
* Utopic Unicorn (Ubuntu 14.10) reached end-of-life in July 2015
* Vivid Vervet (Ubuntu 15.04) reached end-of-life in January 2016

### Remaining releases

The proposed final list would include only:

* Wily Werewolf (Ubuntu 15.10) reaches end-of-life in July 2016
* Precise Pangolin (Ubuntu 12.04 LTS) reaches end-of-life in April 2017
* Trusty Tahr (Ubuntu 14.04 LTS) reaches end-of-life in April 2019
* Xenial Xerus (Ubuntu 16.04 LTS) reaches end-of-life in April 2021

**Comment by JasonLG1979** [comment]
My vote would be to support only the latest LTS and the latest release and drop support of non-LTS releases as newer releases come out . So since 16.04 is the latest release and an LTS don't support anything older than that. But really it's not up to me last I knew @gregsheremeta did the packaging and he's been off getting paid to do stuff and hasn't been very active lately. But in any event there's nothing stopping anyone from grabbing the source and putting it up in a PPA...

**Comment by masternetra** [comment]
@JasonLG1979 - I'd go somewhere between that. LTS and only the non-LTS between LTS's. Ether way xenial for sure could use a ppa as the verison in default repos is a verison behind current release.

**Comment by JasonLG1979** [comment]
@masternetra that would be up to whoever does the packaging for Ubuntu really. If you'd like to step up speak to TingPing.

**Comment by masternetra** [comment]
@JasonLG1979 - I have no experience with handling ppa's or any of this stuff personally.

**Comment by JasonLG1979** [comment]
Neither do I. I also am not a Ubuntu user,

**Comment by TingPing** [comment]
I've never touched it but it looks like I might have push access to the PPA, so even though I loathe it I might look into updating it.

**Comment by TingPing** [comment]
Ok so I have uploaded new builds:

14.04 and 16.04 are packaged in the PPA.
16.10 has the latest release in the universe repo.
All other releases are unsupported.
