### ISSUE TITLE
Redundant/Double entry in notification menu Gnome 3.20 with MPRIS and notify plugins enabled.

### ISSUE THREAD

**Issue by JasonLG1979** [pithos/pithos#298]
As I'm sure everyone knows GNOME 3.20 introduced (very basic) MPRIS functionality in the notification menu(or whatever you call it?) As it sits right now that leads to 2 entries in the notification menu if both the notify and MPRIS plugins are enabled.

![screenshot from 2016-06-24 19-32-14](https://cloud.githubusercontent.com/assets/6667703/16353620/c398031e-3a42-11e6-85ce-e7fb22995ce7.png)

Combine that with the fact that notifications seem to be persistent by default(at least in the menu) it means that unless the user closes the notification in the menu there will always be 2 entries. GNOME also seems to frown on and ignore the transient hint and notification timeouts. I've managed to workaround this by adding this to notify.py:

```
 def prepare_notify(self):
...
        if 'persistence' in caps:
            self.notification.set_hint('resident', GLib.Variant.new_boolean(False))
...

    def set_notification_notify(self, song, playing):
...
        GLib.timeout_add_seconds(5, self.close_notification)

    def close_notification(self):
        self.notification.close()
        return False
```

This will make the notification disappear from the screen/notification menu after 5 secs.(or whenever, I'm not married to a 5 sec timeout.)

**Comment by TingPing** [comment]
Notifications have a timeout variable already but they are persistent on purpose anyway.

Regarding the duplication I sort of think we shouldn't care, afaik Notify is disabled by default and I think we want to just push people that MPRIS is good enough if you use gnome.

**Comment by JasonLG1979** [comment]
> Notifications have a timeout variable already but they are persistent on purpose anyway.

The timeout is ignored even if set from what I can tell. And to me it doesn't make sense for a song change notification to be persistent. To me it should pop up and then go away.

> Regarding the duplication I sort of think we shouldn't care, afaik Notify is disabled by default and I think we want to just push people that MPRIS is good enough if you use gnome.

MPRIS in GNOME is very basic. I wish I knew a way to turn it off. The extension is way more functional. And ofc without the notify plugin you don't get notifications when the song changes. To me it's 1 step forward and 2 steps back.

**Comment by JasonLG1979** [comment]
Maybe some user options for the notify plugin. Timeout and persistence?

**Comment by TingPing** [comment]
> The timeout is ignored even if set from what I can tell. 

Probably need to remove 'resident' also.

> MPRIS in GNOME is very basic. I wish I knew a way to turn it off.

Honestly it is the right amount of useful for me, but that is a discussion to have with upstream anyway. Depending on what you want they might accept it.

> Maybe some user options for the notify plugin. Timeout and persistence?

I'd be ok with that, we added generic preference support for a reason.

**Comment by JasonLG1979** [comment]
> Honestly it is the right amount of useful for me, but that is a discussion to have with upstream anyway. Depending on what you want they might accept it.

IMHO they should have just pulled that in instead of just basically copying Unity's functionality(a couple years late,lol)

> I'd be ok with that, we added generic preference support for a reason.

I'll play with it and see what I can come up with.

**Comment by JasonLG1979** [comment]
> Probably need to remove 'resident' also.

set_timeout still has no effect for me even after removing resident.

**Comment by JasonLG1979** [comment]
resident also seems to have no effect one way or the other, so it's not needed.

Judging from this:

>Transient

>When a notification is transient, only a banner is displayed, and the notification isn't displayed in the Message Tray/notification list.

>For this redesign, it would be good to try and remove the concept of transtient notifications, both because of problems associated with them (eg. what to do when a transient notification is due to be displayed and the message list is open), and in order to reduce design and implementation complexity.

>Instead of using transient notifications, the notification sender can automatically remove the notification after a short time period.

https://wiki.gnome.org/Design/OS/Notifications

It's up to the app to remove it's own notification if it wants to do so. And since set_timeout doesn't work the notification pref could just consist of a checkbox to make Notifications "Non-Persistent"(?) and a spin button for setting the timeout. With something like this in notify.py:

```
    def set_notification_notify(self, song, playing):
...
        if non_persistent:
            GLib.timeout_add_seconds(timeout, self.close_notification)

    def close_notification(self):
        self.notification.close()
        return False
```

**Comment by TingPing** [comment]
> https://wiki.gnome.org/Design/OS/Notifications

That may or may not be relevant but I wouldn't use that as a source. We do not use their API (Gio.Notifications nor org.gtk.Notifications). So how it was designed and behaves is slightly different.

**Comment by JasonLG1979** [comment]
> That may or may not be relevant but I wouldn't use that as a source. We do not use their API (Gio.Notifications nor org.gtk.Notifications). So how it was designed and behaves is slightly different.

I was looking at that to figure out GNOME's notification server behavior more than anything.

**Comment by JasonLG1979** [comment]
I was looking at this:
https://developer.gnome.org/notification-spec/
and this:
https://lazka.github.io/pgi-docs/Notify-0.7/classes/Notification.html#
For our side of things.

**Comment by TingPing** [comment]
> "transient"	boolean	When set the server will treat the notification as transient and by-pass the server's persistence capability, if it should exist.

Perhaps that will do it?

**Comment by JasonLG1979** [comment]
```
def prepare_notify(self):
...
        if 'persistence' in caps:
            self.notification.set_hint('transient', GLib.Variant.new_boolean(True))
```

Causes inconsistent behavior. The notification is transient as long as the notification menu is not open. If it is open when the notification is received it's treated as a persistent notification. It seems to be on purpose, as I said GNOME doesn't seem to like the idea of transient notifications.

>For this redesign, it would be good to try and remove the concept of transtient notifications, both because of problems associated with them (eg. what to do when a transient notification is due to be displayed and the message list is open), and in order to reduce design and implementation complexity.

>Instead of using transient notifications, the notification sender can automatically remove the notification after a short time period.

https://wiki.gnome.org/Design/OS/Notifications

**Comment by JasonLG1979** [comment]
Manually removing our own notifications after a timeout seems to be the way GNOME wants it if we want the notifications to exhibit transient  behavior.

**Comment by JasonLG1979** [comment]
A hybrid approach would be to set the transient hint, set a long timeout and connect to the notification closed signal so that if notification is received with the menu open it will be manually closed by the timeout otherwise if notification is received when the menu is not open it will close it's self and the timeout is canceled.

**Comment by TingPing** [comment]
Alright then.

**Comment by JasonLG1979** [comment]
So you like that idea?

**Comment by JasonLG1979** [comment]
To me the expected behavior of song notifications should be transient. They should popup and go away. They should not spam notification servers/systems that keep a list of notifications. In KDE4 Pithos song notifications were kept in the notification list so after listening for a while you could have 20 song notification in the list. I don't know how KDE5 handles it. I'm going to fire up a few VM's with various DE's and see if I can get manage to get somewhat consistent behavior across the various notification servers.

**Comment by TingPing** [comment]
This was done pre-Gnome 3.20 because the notification acted like a controller, it has buttons to pause/skip and they stuck around on the lock screen, etc. Once a song changed the notification *should* be replaced with a new one and there should never be two.

**Comment by JasonLG1979** [comment]
Most DE's have some kind of MPRIS support. To me there's no reason for the notification to ever stick around. Don't get me wrong the controls in the notifications are nice, it allows you to skip the song if you don't like it without opening the MPRIS plugin when the song 1st starts. But to me after that it seems redundant to have MPRIS controls and controls in a persistent notification.

**Comment by JasonLG1979** [comment]
I guess what I need is,  what to you is the expected behavior?

**Comment by TingPing** [comment]
Well Gnome didn't have mpris support until 3.20... Anyway if we make the assumption that mpris clients are built into modern desktops I am fine with moving notifications to be a purely transient popup on new songs. Once we go that far I think we can also drop using libnotify and use Gio.Notification directly.

**Comment by JasonLG1979** [comment]
What's the difference between Gio.Notification libnotify?

**Comment by JasonLG1979** [comment]
from: https://lazka.github.io/pgi-docs/#Gio-2.0/classes/Notification.html

>The key difference between Gio.Notification and other similar APIs is that, if supported by the desktop environment, notifications sent with Gio.Notification will persist after the application has exited, and even across system reboots.

>Since the user may click on a notification while the application is not running, applications using Gio.Notification should be able to be started as a D-Bus service, using Gio.Application.

Doesn't really seem to be a fit for Pithos. Song notifications for sure don't need to survive reboot. And it makes no sense to be able to pause or skip a song that's no longer playing because Pithos is no longer running or to start Pithos again when a notification(that's not suppose to be persistent in the 1st place) is interacted with.

**Comment by TingPing** [comment]
I think the API can behave the same when it comes to being transient, that feature is just a possibility with their dbus API at `org.gtk.Notification`. The benefit to use is we get to drop libnotify which is a poorly made library anyway (everything it does is blocking IO...) and Gio.Notification is cross platform, I wrote the OSX backend myself and could make a Windows one someday.

**Comment by TingPing** [comment]
>  g_application_withdraw_notification ();

**Comment by JasonLG1979** [comment]
Sounds good, less dependencies is a good thing.  It doesn't seem to be a drop in replacement. I've just only skimmed the docs so far and it looks like we'll have to add callbacks to application.py among other things(?)... I'll give it a shot. Might take a while,lol...

**Comment by TingPing** [comment]
Another new plus is that Gio.Notifications will better integrate with the flatpak sandboxing in the future.

**Comment by TingPing** [comment]
Also just wanted to make note that the Gnome MPRIS integration also makes the MediaKeys plugin meaningless. Honestly I think relying on MPRIS for keybindings is the best way forward but we would need to investigate what other DE's do this.

**Comment by JasonLG1979** [comment]
> Also just realized that the Gnome MPRIS integration also makes the MediaKeys plugin meaningless. Honestly I think relying on MPRIS for keybindings is the best way forward but we would need to investigate what other DE's do this.

I agree. The more "generic" we can make things by offloading to/relying on stuff like MPRIS and such the better. The sticky part is like you said how do other DE deal with stuff. It seems I spend more time working around how different DE's behave then anything. I really wish everyone could get together and agree to handle the basic stuff the same way...

**Comment by JasonLG1979** [comment]
@TingPing are you going to handle porting to Gio.Notifications? Do you want me to take a crack at it or do you want me to do the additionalUrls or the new_default_icon stuff?

**Comment by TingPing** [comment]
I can look into the notifications though I'm still not sure what direction we want to go in.

**Comment by JasonLG1979** [comment]
Ok I'll start with the easiest thing. additionalUrls.

**Comment by TingPing** [comment]
So in my brief testing I think Gio.Notification is just a poor fit. Something as simple as updating the icon when it changes does not behave the same (it considers it a new notification).

**Comment by JasonLG1979** [comment]
So no go on that? Are you down with what I was talking about, as far as my expected behavior of notifications?

**Comment by TingPing** [comment]
Sure as an option since not everybody has mpris.

**Comment by JasonLG1979** [comment]
I'll mess with this after 1.2.

**Comment by JasonLG1979** [comment]
I've been playing with notifications without libNotify.

Based on this old example http://cheesehead-techblog.blogspot.com/2009/02/five-ways-to-make-notification-pop-up.html I've managed to cobble this together:

```
import logging
import html
from pithos.plugin import PithosPlugin

import gi
from gi.repository import (GLib, Gio)

class NotifyPlugin(PithosPlugin):
    preference = 'notify'
    description = 'Shows notifications on song change'

    SESSION_BUS = Gio.BusType.SESSION
    CANCELLABLE = None
    PROXY_PROPS = 0
    INTERFACE_PROPS_ARRAY = None
    PATH = '/org/freedesktop/Notifications'
    INTERFACE = 'org.freedesktop.Notifications'
    METHOD = 'Notify'
    APP_NAME = 'Pithos'
    CONNECTION = Gio.bus_get_sync(SESSION_BUS, CANCELLABLE)
    DBUS_NOTIFY = Gio.DBusProxy.new_sync(CONNECTION, PROXY_PROPS, INTERFACE_PROPS_ARRAY,
                                         INTERFACE, PATH, INTERFACE, CANCELLABLE)

    _notification = None
    _notification_id = 0
    _action_list = []
    _hints_dict = {'resident': GLib.Variant.new_boolean(False),
                   'transient': GLib.Variant.new_boolean(True),
    }

    def on_prepare(self):
        pass

    def on_enable(self):
        self.song_callback_handle = self.window.connect("song-changed", self.song_changed)

    def set_notification(self, song, *ignore):
        msg = 'by {} from {}'.format(song.artist, song.album)
        msg = html.escape(msg, quote=False)
        if song.artUrl:
            self.new_notification(song.title, msg, song.artUrl)
        else:
            self.new_notification(song.title, msg, 'audio-x-generic')

    def new_notification(self, title, body, icon, display_ms=5000, timeout=-1):
        args = GLib.Variant('(susssasa{sv}i)', (self.APP_NAME, self._notification_id, icon, title, body,
                                                self._action_list, self._hints_dict, display_ms))

        self._notification = self.DBUS_NOTIFY.call_sync(self.METHOD, args, self.PROXY_PROPS, timeout, self.CANCELLABLE)
        self._notification_id = self._notification.unpack()[0]
        

    def song_changed(self, window,  song):
        if not self.window.is_active():
            GLib.idle_add(self.set_notification, window.current_song)

    def on_disable(self):
        self.window.disconnect(self.song_callback_handle)

```

It's ugly but it kinda works. There are no actions(do we really need them anymore with GNOME's MPRIS integration?) but it's a start maybe?

**Comment by TingPing** [comment]
@JasonLG1979 Yea, I've done the same basically. The reason that I made a `dbus_util` dir is because I implemented a wrapper around the Notification API and the MediaKeys API. At that point I just wonder if it is silly to reinvent the work that's already done.

**Comment by JasonLG1979** [comment]
I don't know either I was just playing around. I was also not sure if our current implementation gets out of the flatpack sandbox?

**Comment by TingPing** [comment]
> I was also not sure if our current implementation gets out of the flatpack sandbox?

Not automatically, we have to explicitly allow it which is generally not ideal since we want these decisions up to users.

This is the flatpak dbus portal they expose - http://flatpak.org/xdg-desktop-portal/portal-docs.html#gdbus-org.freedesktop.portal.Notification

It is really designed around how Gio.Notifications behave so in the end I think we just have to continue what we do.

**Comment by JasonLG1979** [comment]
>Note that in contrast to most other portal requests, notifications are expected to outlast the running application. If a user clicks on a notification after the application has exited, it will get activated again.

I really hate that part. To me it makes more since to default to NOT reactivating the app.

**Comment by TingPing** [comment]
@JasonLG1979 It is really designed around applications that notify you of events like clocks and calandars. Music players have by far the most transient information so it maps very poorly to this. Chat applications are also sometimes like this but less so as a missed message is still relevant later.

**Comment by JasonLG1979** [comment]
> It is really designed around applications that notify you of events like clocks and calandars. Music players have by far the most transient information so it maps very poorly to this. Chat applications are also sometimes like this but less so as a missed message is still relevant later.

Yep, to me song changes are about the bottom of the priority list as far as notifications are concerned.

**Comment by JasonLG1979** [comment]
It would just be nice to get rid of as many external dependencies as possible(even for plugins).

**Comment by TingPing** [comment]
For now I think libnotify is fairly harmless. The worst thing about it is that it does a blocking IO call we cannot avoid but our other plugins have some of that too (that I will slowly erode away).

**Comment by JasonLG1979** [comment]
blocking IO is the Devil, especially in python...

**Comment by TingPing** [comment]
I think we need some extensions to our plugin API to make it more async friendly. But d7bbaf502c017ce73ce7ecdc061733029f3d3e4a should be completely async now.

It also complicates things having multiple different codepaths in a single plugin, `try_win32()`, `try_osx()`, `try_x11()`, etc. So I was possibly thinking of having either suffixed files or suffixed functions that are only ever called on a specific platform automatically which would really clean things up I think.

**Comment by JasonLG1979** [comment]
How well does Pithos actually work on Windows or OSX? Is it even worth worrying about them at all?

**Comment by TingPing** [comment]
Well.. hmm. When I first joined the project I put a lot of love into win32 and osx and they were functional. Since the last release I have gone down a much more Gnome focused release so 1.2 will not run on either platform. I would like that to be temporary but I don't think I have the will to do the work on those platforms anymore.

**Comment by JasonLG1979** [comment]
There are already clients for both platforms right? It would make for a cleaner code base if all that crap out.(that realistically no one really is going to use)

**Comment by TingPing** [comment]
None that are actively maintained, Hermes on OSX is largely dead (the dev uses Pithos and hangs around), and Elpis on Windows is entirely dead.

**Comment by JasonLG1979** [comment]
Windows has a crappy AdobeAIR client and a Metro app I thought? I know nothing about OSX. Last time I used it was around 2001 in college...

**Comment by TingPing** [comment]
> Windows has a crappy AdobeAIR client 

Speaks for itself :P

> a Metro app I thought?

Probably, thankfully nobody uses Windows 7...

Also from a glance it looks like Hermes does have a maintainer now.

**Comment by JasonLG1979** [comment]
> Also from a glance it looks like Hermes does have a maintainer now.

Cool so no need to cling to dead code then?

**Comment by TingPing** [comment]
Maybe.

**Comment by JasonLG1979** [comment]
Updated version of Notify.py without libnotify. Async notifications, still working on actions(if they are even need?)

```
import logging
from pithos.plugin import PithosPlugin
import gi
from gi.repository import GLib, Gio

class NotifyPlugin(PithosPlugin):
    preference = 'notify'
    description = 'Shows notifications on song change'

    def on_prepare(self):
        pass

    def on_enable(self):
        self.SESSION_BUS = Gio.BusType.SESSION
        self.CANCELLABLE = None
        self.PROXY_PROPS = 0
        self.DISPLAY_MS = 5000
        self.TIMEOUT = -1
        self.INTERFACE_PROPS_ARRAY = None
        self.PATH = '/org/freedesktop/Notifications'
        self.INTERFACE = 'org.freedesktop.Notifications'
        self.METHOD = 'Notify'
        self.APP_NAME = 'Pithos'
        self.CONNECTION = Gio.bus_get_sync(self.SESSION_BUS, self.CANCELLABLE)
        self.DBUS_NOTIFY = Gio.DBusProxy.new_sync(self.CONNECTION, self.PROXY_PROPS, self.INTERFACE_PROPS_ARRAY,
                                                  self.INTERFACE, self.PATH, self.INTERFACE, self.CANCELLABLE)

        self._notification_id = 0
        self._action_list = []
        self._hints_dict = {'category': GLib.Variant.new_string('x-gnome.music'),
                            'desktop-entry': GLib.Variant.new_string('pithos'),
                            'resident': GLib.Variant.new_boolean(False),
                            'transient': GLib.Variant.new_boolean(True),
        }

        self.song_callback_handle = self.window.connect("song-changed", self.song_changed)

    def song_changed(self, window, song):
        if self.window.is_active():
            return

        def on_notify_call_finished(notify, result):
            notification = notify.call_finish(result)
            self._notification_id = notification.unpack()[0]

        title = song.artist
        body = song.title
        if song.artUrl:
            icon = song.artUrl
        else:
            icon = 'audio-x-generic'

        args = GLib.Variant('(susssasa{sv}i)', (self.APP_NAME, self._notification_id, icon, title, body,
                                                self._action_list, self._hints_dict, self.DISPLAY_MS))

        self.DBUS_NOTIFY.call(self.METHOD, args, self.PROXY_PROPS, self.TIMEOUT,
                              self.CANCELLABLE, on_notify_call_finished)

    def on_disable(self):
        self.window.disconnect(self.song_callback_handle)
```

Still needs a lot of work, could be more pretty, but it works pretty good.

**Comment by JasonLG1979** [comment]
Tested to work perfectly as expected on Kubuntu and Ubuntu 16.04.1 and Fedora 24. I'm going to test on Xubuntu, Ubuntu Mate and Lubuntu to see how their notification systems handle it.

**Comment by TingPing** [comment]
@JasonLG1979 Here is probably a cleaner base to start from: https://gist.github.com/TingPing/312e0fafbde71860fe5502d7c7c5b70f

And from there we could add wrappers to make it slightly cleaner.

**Comment by JasonLG1979** [comment]
Right on, I give it a shot. 
What are your thoughts on:
1. Actions, do we really need them? MPRIS pretty much makes them redundant IMHO.
2. Notification content. In my latest hacked up example I made them match what shows up in the GNOME MPRIS implementation.

**Comment by TingPing** [comment]
> Actions, do we really need them? MPRIS pretty much makes them redundant IMHO.

We still have users on XFCE, Mate, Gnome < 3.20, etc.

**Comment by JasonLG1979** [comment]
> We still have users on XFCE, Mate, Gnome < 3.20, etc.

I've been playing with adding them I just haven't figured out how yet...

**Comment by JasonLG1979** [comment]
Notification content?

**Comment by TingPing** [comment]
No strong thoughts on content atm.

Regarding Actions. In my paste you can override `do_g_signal()` and look for the `ActionInvoked` signal.

(Just going off docs here: https://developer.gnome.org/notification-spec/)

**Comment by JasonLG1979** [comment]
> Regarding Actions. In my paste you can override do_g_signal() and look for the ActionInvoked signal.
> 
> (Just going off docs here: https://developer.gnome.org/notification-spec/)

Over my head atm. I'll have to do some reading.

**Comment by TingPing** [comment]
http://lazka.github.io/pgi-docs/index.html#Gio-2.0/classes/DBusProxy.html#Gio.DBusProxy.do_g_signal

**Comment by JasonLG1979** [comment]
I can't get you example to work.

**Comment by JasonLG1979** [comment]
Here's the best I can do. Fully async now. Still no action yet.
https://gist.github.com/JasonLG1979/809604ae2f8967c0f46c0d34b0074184

**Comment by JasonLG1979** [comment]
Here you go @TingPing. libNotify-less notify.py. It's functionally identical to the old version and is a drop in replacement except for no OSX support(which you could add back in if you wanted to)

https://gist.github.com/JasonLG1979/f9438e637d4473bee1b909f2710975eb

**Comment by JasonLG1979** [comment]
@TingPing  https://github.com/pithos/pithos/pull/366 is a drop in re-implementation of our current notifications. It functions exactly the same as our current libnotify based notifications. The end user will not notice a difference except maybe that we dropped the libnotify dependency, if they notice that. With the exception of initializing GioNotify all methods are async. It is possible to initialize GioNotify async(the class contains a async_init method for future use) but with our current plugin system sync_init is a better fit.

Docs are here: https://github.com/JasonLG1979/possibly-useful-scraps/wiki/GioNotify

The API is stupid simple and very similar to the libnotify bindings.

**Comment by JasonLG1979** [comment]
I think we've pretty much implemented everything we've talked about @TingPing? I'm going to close this because of that and the original issue was about redundant info and I did the best I could to fix that with the transient notifications PR.
