### ISSUE TITLE
Flatpak: Media Keys Issue

### ISSUE THREAD

**Issue by Ironlenny** [pithos/pithos#299]
I'm using Kubuntu 16.04. I followed the instructions on the wiki for installation, and was successful. Pithos runs, but my keyboards media keys do not work. They do work when I use the Ubuntu package.

**Comment by TingPing** [comment]
Yes this will not be possible sadly. We have two methods for binding media keys: Over dbus with `org.gnome.SettingDaemon` or with libkeybinder which works at the X11 level to take global keybindings.

The latter is what would be used on every platform that isn't gnome based and is insecure, shouldn't be used, and seems to fail in Flatpak's sandbox. If anybody knows of a KDE specific API to do this from within the sandbox let me know.

**Comment by Ironlenny** [comment]
Might this be helpful? https://specifications.freedesktop.org/mpris-spec/latest/

**Comment by TingPing** [comment]
Pithos already provides a complete MPRIS2 implementation so clearly KDE isn't using that for keybindings.

**Comment by Ironlenny** [comment]
Is there a way to see pithos' dbus registration?

**Comment by Ironlenny** [comment]
I found this in .xsession-errors:
    plasma.engine.mpris2: Found MPRIS2 service "org.mpris.MediaPlayer2.pithos"
    plasma.engine.mpris2: Haven't already seen "org.mpris.MediaPlayer2.pithos"
    plasma.engine.mpris2: "org.mpris.MediaPlayer2.pithos" does not implement org.freedesktop.DBus.Properties correctly
plasma.engine.mpris2: Error message was "org.freedesktop.DBus.Python.TypeError" "Traceback (most recent call last):\n  File \"/usr/lib/python3/dist-packages/dbus/service.py\", line 707, in _message_cb\n    retval = candidate_method(self, *args, **keywords)\n  File \"/usr/share/pithos/pithos/plugins/_mpris.py\", line 157, in GetAll\n    'Position': dbus.Int64(self._get_position()),\n  File \"/usr/share/pithos/pithos/plugins/_mpris.py\", line 114, in _get_position\n    return self.window.query_position() / 1000\nTypeError: unsupported operand type(s) for /: 'NoneType' and 'int'\n"
plasma.engine.mpris2: Failed to find working MPRIS2 interface for "org.mpris.MediaPlayer2.pithos"

**Comment by TingPing** [comment]
That is interesting, but that bug was fixed in 32946f26ad2bcb which was included in the flatpak so that must be an old error.
