### ISSUE TITLE
Flatpak: AppIndicator

### ISSUE THREAD

**Issue by Ironlenny** [pithos/pithos#300]
I know that AppIndicator testing is a know issue, but I didn't find an open ticket for it. If there is please feel free to close this ticket.

I'm using Kubuntu 16.04. I successfully installed Pithos following the wiki instructions. When I launch Pithos I do not get an icon in the system tray. I do get a icon when I'm using the latest Git build.

**Comment by TingPing** [comment]
Yea I simply need to know the dbus interface names to add them and I didn't find any good docs nor have a Unity install.

**Comment by TingPing** [comment]
Ah it is a bit more work than that, we need to package libappindicator and its dependencies. Also currently you can lose the window if you enable the option and close it so that is not ideal.

**Comment by Ironlenny** [comment]
Since this ticked was opened, the tray icon has worked. That is, until this last month. I did a 'flatpak update' and now tray icon has gone away. When I try to enable it I get this error:
```
(process:18625): GLib-GIO-CRITICAL **: g_dbus_message_set_body: assertion '(body == NULL) || g_variant_is_of_type (body, G_VARIANT_TYPE_TUPLE)' failed
ERROR - notification_icon:on_has_name_owner:68 - g-io-error-quark: Method 'org.freedesktop.DBus.NameHasOwner' returned type '()', but expected '(b)' (13)
Traceback (most recent call last):
  File "/app/lib/python3.5/site-packages/pithos/plugins/notification_icon.py", line 65, in on_has_name_owner
    is_owned = bus.call_finish(result)[0]
GLib.GError: g-io-error-quark: Method 'org.freedesktop.DBus.NameHasOwner' returned type '()', but expected '(b)' (13)
```

I'm still on 16.04.

**Comment by TingPing** [comment]
Oh, so this original issue is solved by https://github.com/flathub/io.github.Pithos/commit/0cf4ba1eed8dd662fdc4cc1da091b43e7897b73d

 (Users should be getting their flatpak from https://flathub.org now, not my repo)

Your new exception is an unrelated issue, can you please open a new one over it.
