### ISSUE TITLE
Can't build 1.1.2 with build from source instructions and no instructions are supplied.

### ISSUE THREAD

**Issue by masternetra** [pithos/pithos#303]
Yea. The 1.1.2 version source isn't build-able by wiki instructions (apparently installation is done via python it looks like, but have no clue how to install it using python) and there are no instructions with it and "git clone https://github.com/pithos/pithos.git" is still pulling 1.1.1 for me.

**Comment by TingPing** [comment]
I'm confused, the wiki is completely fine: https://github.com/pithos/pithos/wiki/Installing-from-Source

Which part failed?

**Comment by TingPing** [comment]
Oh.. I see you are just hung up on the versioning. The master branch has all of the work from the 1.1.2 bugfix release but is actually the code for what will become the 1.2.0 release.

**Comment by masternetra** [comment]
No I am speaking of the 1.1.2 release here: https://github.com/pithos/pithos/releases, I was trying to install 1.1.2 from source but the wiki instructions don't seem to apply with the "source" download.

**Comment by TingPing** [comment]
All instructions apply to git, that is why the directly reference downloading git.

The main difference for the older versions is you would run `./setup.py install`
