### ISSUE TITLE
Keyboard Shortcuts menu item unclickable *buntu 16.04.

### ISSUE THREAD

**Issue by JasonLG1979** [pithos/pithos#310]
In the process of testing some stuff I'm working on against *buntu 16.04 I noticed that the Keyboard Shortcuts menu item is unclickable in every version.(Ubuntu, Kubuntu, Xubuntu and Mint) Does it depend on GNOME 3.20?

**Comment by TingPing** [comment]
Ah yes it does. It should be possible to dynamically add the entry but that is a bit of a PITA.
