### ISSUE TITLE
Ubuntu sound indicator integration broken.

### ISSUE THREAD

**Issue by JasonLG1979** [pithos/pithos#311]
Pithos no longer shows up in the Ubuntu Ubuntu sound indicator. The regression happened sometime between 2edf7308ab03f049013b2f5b4c3104535442f70a and now. It's not a problem with MPRIS as the MPRIS applet in Kubuntu still works just fine.

**Comment by TingPing** [comment]
You can use `git bisect` to find the bad commit:

```
git bisect bad
git bisect good 2edf7308ab
git bisect start

# Each iteration
make run
# and git bisect good or bad until found
```

**Comment by JasonLG1979** [comment]
It's weird. I can install from the current source and it doesn't work but if I start from 2edf7308ab and step though the commits it works all the way up to the current source? Maybe something to do with changing the name of stuff to io.github.Pithos? IDK?

**Comment by TingPing** [comment]
> Maybe something to do with changing the name of stuff to io.github.Pithos? IDK?

Would be my guess also.

**Comment by TingPing** [comment]
Ah try fixing 'DesktopEntry': 'pithos',` in _mpris.py

**Comment by JasonLG1979** [comment]
It doesn't seem to matter either way. I get very inconsistent behavior, sometimes it works sometimes it doesn't? I'll double check the MPRIS plugins in KDE, Cinnamon and the GNOME extension in *buntu 16.04 and if they work fine looks like it might just be the Ubuntu sound indicator... (I don't use Ubuntu most of the time anyway anymore so meh,lol!!!)

**Comment by JasonLG1979** [comment]
Closing this it works fine now.
