### ISSUE TITLE
Dependency problem on Ubuntu 14.04

### ISSUE THREAD

**Issue by bayonne** [pithos/pithos#313]
Available Version: 1.1.2-1ppa2

$ apt-get install pithos

The following packages have unmet dependencies:
 pithos : Depends: libgtk-3-0 (>= 3.14) but 3.10.8-0ubuntu1.6 is to be installed
E: Unable to correct problems, you have held broken packages.

**Comment by TingPing** [comment]
Welp, then 14.04 won't be supported anyway..

**Comment by TingPing** [comment]
I guess I'll try to package up 1.0 since it is still functional, but it will be unsupported and never updated as far as I'm concerned.

**Comment by TingPing** [comment]
Ok 1.0.3 is now published in the PPA for 14.04.
