### ISSUE TITLE
Asynchronous/caching album art 

### ISSUE THREAD

**Issue by JasonLG1979** [pithos/pithos#316]
@TingPing, Check this out:
http://pastebin.com/tJdVuZSs

It's based on:
https://github.com/GNOME/gnome-music/blob/master/gnomemusic/albumArtCache.py

The advantages are crazy over what we're doing now. It downloads, processes and saves the album art totally Asynchronously. It also caches the album art so that if it already exists the cached art is used and no downloading happens. In my tests it's MUCH faster then what we currently got going when downloading art and is practically  instantaneous for cached art. It also gets rid of the art thread worker as there's no need for it.

What do you think?

Right now I have it in the pithos.py but I think it could go in it's own file.

**Comment by TingPing** [comment]
I have thought of caching art before but in the end I didn't think it was a good fit. IME artwork is not repeated often so in order for it to be valuable you need to cache like 100 of them.

**Comment by JasonLG1979** [comment]
It's cached based on album, artist. So songs of the same album would share covers. After messing around and loading playlist after playlist on a couple different accounts my cache folder has about 400 covers in it. Caching the cover greatly improves preformance. We could set an option to clear the cache on close?

**Comment by JasonLG1979** [comment]
Another option is to use the tmp folder system that we use now(that deletes the tmp folder after each session) and cache to that. Actual cache hits would be much more less likely but a little caching is better then none?

**Comment by TingPing** [comment]
I would personally be more content if we cleaned it out ourselves. Unlike gnome-music where you manage your collection and the application can expect to repeatedly see the same thing a radio client cannot and will build up over time.

So if we do move forward:

>  It also gets rid of the art thread worker as there's no need for it.

We still have to download the actual images the same as before.

- We use proxies for data also and Gio's proxy support might not equal Pythons.
- For http support we would need to use libsoup.

**Comment by JasonLG1979** [comment]
Gio.file.new_from_uri and async_read takes care of downloading the art asynchronously for us.

**Comment by JasonLG1979** [comment]
After the async read completes it splits out 2 more async calls one to async scale the art to a pixbuf for the UI and one to async save the art to the cache folder. Like I said its all asyn so there's no need for the art worker. I'll throw what I got into a branch for you to check out when I get off work later today.

**Comment by TingPing** [comment]
> Gio.file.new_from_uri and async_read takes care of downloading the art asynchronously for us.

https://github.com/pithos/pithos/issues/316#issuecomment-233609390

**Comment by JasonLG1979** [comment]
Derp... Yep sorry misunderstood. Does downloading album covers even have proxy support currently? I don't use a proxy and have no idea how it works in Pithos?

**Comment by TingPing** [comment]
As I understand it these lines set the proxy for all future calls to `urllib.request`: https://github.com/pithos/pithos/blob/e80bc117738813605ef374e5f8386fc56f95c89d/pithos/pithos.py#L379-L383

**Comment by JasonLG1979** [comment]
Does album art really need to proxy support? I mean I wonder if it's even region restricted? Well it look like I'm going to have to figure out proxies,lol...

**Comment by TingPing** [comment]
Some people use proxies for privacy reasons, or because their network blocks connections by default, etc.

**Comment by JasonLG1979** [comment]
> Some people use proxies for privacy reasons or because their network blocks connections by default, etc.

Right on.

Anyway back to downloaded cover handling. Right now a new album-art tmp file is created at each session and deleted when Pithos closes. I have recreated that with the addition of caching(although the chance of a cache hit is kinda small when the folder only survives for that session) What exactly is your expected/desired cache/tmp folder behavior?
