### ISSUE TITLE
Hangs on login

### ISSUE THREAD

**Issue by darakian** [pithos/pithos#318]
Hey All,

Just today it seems like pithos is unable to login. I get the 'Logging in...' text at the bottom of the window and it just never returns. Program does respond to quitting (which is nice), but that's about it.  I'm on version 1.1.2 on fedora 23

**Comment by TingPing** [comment]
You can run `pithos -vv` to get some more verbose logs (don't pastebin the login part publicly) but really there isn't anything that can be done on our end if their service is down.

**Comment by darakian** [comment]
Just gave it a spin with the -vv option and things seemed to work. Slow as all hell, but maybe it's just a network issue on my end. Thanks!
