### ISSUE TITLE
New screenshot and change the color scheme of the web page.

### ISSUE THREAD

**Issue by JasonLG1979** [pithos/pithos#323]
The screenshot on http://pithos.github.io/ needs updating for sure. In addition to that I would suggest changing the orange background to maybe a light blue(?) and using the default GNOME theme in the screenshot to reflect the fact that it's not just a Ubuntu app.

Here's a screenshot if you want to use it you can.

![screenshot from 2016-07-28 19-08-54](https://cloud.githubusercontent.com/assets/6667703/17233778/5c8a5606-54f8-11e6-9ce5-edd04018928b.png)

**Comment by TingPing** [comment]
Sounds good, feel free to submit a PR to pithos/pithos.github.io

**Comment by JasonLG1979** [comment]
Yep. Believe it or not my web design skills are lacking even more than my Python skills... The last time I did any web design was in college... about 20 years ago... And the site I made then sucked even by late 90's standards,lol!!! So It'll probably be this weekend before I figure it out.

**Comment by TingPing** [comment]
It doesn't take much skill to make something prettier than what we have :P

**Comment by JasonLG1979** [comment]
My little brother is a web dev by profession. So maybe I cna get him to whip us up something prettier?

**Comment by JasonLG1979** [comment]
https://github.com/bob-gray/solv
He stayed at a Holiday Inn last night,lol!!!

**Comment by TingPing** [comment]
Why was this closed?

**Comment by JasonLG1979** [comment]
Because nothing was being done with it.
