### ISSUE TITLE
DBus Error

### ISSUE THREAD

**Issue by jakoch5876** [pithos/pithos#325]
After upgrade to version 1.2 the DBus interface appears broken.

Called with php script attached. It is used to feed song information to conky.

`#!/usr/bin/php
<?php

$song=`dbus-send --print-reply --dest=net.kevinmehall.Pithos /net/kevinmehall/Pithos net.kevinmehall.Pithos.GetCurrentSong`;

$matches = array();

switch($argv[1]) {
    case 'album':
        $pattern = '~"album".*?"(.*?)".*~s';
        break;
    case 'title':
        $pattern = '~"title".*?"(.*?)".*~s';
        break;
    case 'artist':
        $pattern = '~"artist".*?"(.*?)".*~s';
        break;
    default:
        exit;
}

preg_match($pattern, $song, $matches);

if($matches) {
    echo $matches[1];
}

?>
`
Response: Error org.freedesktop.DBus.Error.IOError: Method net.kevinmehall.Pithos.GetCurrentSong failed with: 'PithosDBusProxy' object has no attribute 'song_to_dict'

**Comment by JasonLG1979** [comment]
I'm not very familiar with the deprecated net.kevinmehall.Pithos interface but looking at the source it appears it may just be a typo.

Try changing line 80 in _dbus_service.py to:
```
        return GLib.Variant('a{sv}', self.song_to_variant(self.window.current_song))
```

**Comment by TingPing** [comment]
(Do use MPRIS though, it works with all players)
