### ISSUE TITLE
GobjectWorker doesn't need a Queue

### ISSUE THREAD

**Issue by JasonLG1979** [pithos/pithos#326]
GobjectWorker doesn't need a Queue. Removing it like so seems to actually make things more responsive(especially station creation searches) and make the album art load faster.

```
class GObjectWorker:
    def __init__(self):
        pass

    def send(self, command, args=(), callback=None, errorback=None):
        def run(data):
            command, args, callback, errorback = data
            try:
                result = command(*args)
                if callback:
                    GLib.idle_add(callback, result)
            except Exception as e:
                e.traceback = traceback.format_exc()
                if errorback:
                    GLib.idle_add(errorback, e)
        if errorback is None: errorback = self._default_errorback
        data = command, args, callback, errorback
        thread = threading.Thread(target=run, args=(data,))
        thread.daemon = True
        thread.start()

    def _default_errorback(self, error):
        logging.error("Unhandled exception in worker thread:\n{}".format(error.traceback))
```

If I had to guess it's because the queue synchronizes the worker jobs into just one thread. This would instead spawn a new thread for each job sent to the worker basically making it an async worker.

**Comment by TingPing** [comment]
I'd imagine the purpose is for things to be ran in a deterministic order.

**Comment by JasonLG1979** [comment]
I'm sure it was. But we don't need it. We already handle our own synchronization with the callbacks. The Queue slows things down by marshaling(if that's the right word?) all the jobs into well, a queue. Jobs that could benefit from asynchronization, either they don't need to be in a certain order like downloading album art or that are unrelated suffer.

**Comment by JasonLG1979** [comment]
In my tests I've had no issues. Like I said things seem to run a little faster actually.

**Comment by TingPing** [comment]
what i meant is if you do:

```
worker.send(print_1)
worder.send(print_2)
```

The result will always be 1, 2 as-is. If you remove that and let threads run as they wish that will be undetermined. Now this may be fine but this isn't a change you just want to make without looking into what exactly will change.

**Comment by JasonLG1979** [comment]
I know what you mean. The Queue insures that jobs are processed in a FIFO manner. What I'm telling you is that it's not needed and actually slows thing down.

**Comment by JasonLG1979** [comment]
We handle our own determinism already with the callbacks.

**Comment by JasonLG1979** [comment]
Give it a test you'll see what I mean. The code I posted is a drop in replacement.

**Comment by JasonLG1979** [comment]
Here @TingPing give this a try:
https://github.com/JasonLG1979/pithos/tree/no_queue_worker

**Comment by TingPing** [comment]
@JasonLG1979 btw this idea is fine, feel free to open a PR.

**Comment by JasonLG1979** [comment]
Ok, I'll reopen it and put in a PR.
