### ISSUE TITLE
Pithos v1.2 Crashes in Kubuntu 16.04

### ISSUE THREAD

**Issue by CyberNode** [pithos/pithos#327]
Pithos v1.2 crashes on a freshly installed Kubuntu 16.04 that has had updates install first and no other apps added. 

Hardware
HP Pavilion g7
4gb ram
Quad Core
AMD Vision Graphics

**Comment by TingPing** [comment]
run `pithos -v` from the terminal and paste the output.

**Comment by JasonLG1979** [comment]
You'll need gnome-keyring for it to work in Kubuntu.
```
sudo apt-get install gnome-keyring -y
```
Let us know if that does the trick.

**Comment by JasonLG1979** [comment]
It should probably be added as a dependency in the wiki. It kinda went unnoticed because most other DE's are GTK based and include it by default.

**Comment by TingPing** [comment]
KWallet should implement secret service too?

**Comment by JasonLG1979** [comment]
Last time I tried to run Pithos on Kubuntu it crashed and complained about needing gnome-keyring. I'm downloading a Kubuntu 16.04.1 image right now. I'll fire it up in Boxes and see what we get.

**Comment by TingPing** [comment]
I'll try to make a prettier popup dialog when that fails

**Comment by JasonLG1979** [comment]
Next time maybe we release a beta for wider testing before the proper release?

**Comment by JasonLG1979** [comment]
Just tested the package from the ppa crashed hard on Kubuntu. Installed gnome-keyring fixed the issue.

**Comment by TingPing** [comment]
@JasonLG1979 It has been in 'beta' for like 6 months. It's no big deal we can throw out a 1.2.1 soon with a bit more polish.

**Comment by JasonLG1979** [comment]
True, True.

**Comment by JasonLG1979** [comment]
Updated the wiki to include gnome-keyring for Ubuntu and Fedora. I know nothing about openSUSE?

**Comment by TingPing** [comment]
I pushed an update to the PPA including gnome-kerying as a dep.

**Comment by TingPing** [comment]
@JasonLG1979 Any other rough edges you know of for a point release?

**Comment by JasonLG1979** [comment]
Not that I'm aware of off the top of my head?
