### ISSUE TITLE
Gtk-WARNING ** : Allocating size to SearchDialog

### ISSUE THREAD

**Issue by JasonLG1979** [pithos/pithos#328]
```
(pithos:2881): Gtk-WARNING **: Allocating size to SearchDialog 0x555ce81dc960 without calling gtk_widget_get_preferred_width/height(). How does the code know the size to allocate?
```
When entering stuff in the stations search box.

**Comment by TingPing** [comment]
What Gtk version?

**Comment by JasonLG1979** [comment]
3.20.2 Fedora 24

**Comment by TingPing** [comment]
I do not get this on 3.20.6.

**Comment by JasonLG1979** [comment]
I'll test on *buntu and see what I get also.

**Comment by JasonLG1979** [comment]
Didn't get the warning on Kubuntu 16.04.1. Even with the warning on Fedora it doesn't seem to effect anything. May be harmless and safe to ignore?

**Comment by TingPing** [comment]
Yea probably harmless and probably just fixed in a Gtk update.

**Comment by JasonLG1979** [comment]
This looks similar:
https://github.com/linuxmint/nemo/issues/1153

**Comment by TingPing** [comment]
So fixed upstream.

**Comment by JasonLG1979** [comment]
> So fixed upstream.

I didn't see that? That was an issue the Nemo file manager. It's probably fixed upstream if it doesn't effect you? I was just reinforcing that it's probably harmless spam.
