### ISSUE TITLE
New version for Ubuntu Trusty on the PPA??

### ISSUE THREAD

**Issue by edwinbarton** [pithos/pithos#337]
Not everyone has or can move to Xenial yet so why not put an updated version for Trusty on the PPA?  (incidentally I'm posting this here because your site seriously lacks working contact info (the IRC channel refused to connect on repeated attempts and that seems to be the only other way listed on the site to contact you)).

**Comment by TingPing** [comment]
Trusty is far too old for the current release of Pithos, sorry.

**Comment by edwinbarton** [comment]
Except that Trusty at least works!!  I spent the day trying to get that POS Xenial installed and working only to have the desktop crash every time I tried to do anything, the login screen not appear forcing me to login from a shell prompt, and numerous other crashes and problems all AFTER installing all of the updates.

**Comment by TingPing** [comment]
I mean I'm not calling either version a good OS. It is just the fact Trusty does not have the libraries Pithos requires.
