### ISSUE TITLE
Last.FM plugin disabled and unconfigurable

### ISSUE THREAD

**Issue by Zetaphor** [pithos/pithos#338]
OS: Linux Mint 18 Cinnamon (Ubuntu 16.04 LTS)
Version: 1.2.1

My LastFM scrobbler plugin shows as enabled, but is completely greyed out, it cannot be toggled and I cannot access the preferences.

I have installed pylast via pip and restarted both the machine and Pithos.

Any suggestions?

**Comment by Zetaphor** [comment]
Just did a sudo apt-get install python-pylast based on a suggestion in #216, still no luck.

**Comment by Zetaphor** [comment]
I managed to resolve this myself. For anyone from the future with the same issue, I first had to install python3, then python3-pip, then pip3 install wheel (for the binaries), then I was finally able to pip3 install pylast --user.

Restart pithos and everything should be in order.

**Comment by TingPing** [comment]
Uh... Not only does Ubuntu package `python3-pylast`: http://packages.ubuntu.com/xenial/python3-pylast  
the PPA package also has a Recommends dependency on it. I think I've heard Mint disables installing Recommends by default (which is stupid) though.

**Comment by TingPing** [comment]
Updated the website to workaround Mint's stupidity - https://github.com/pithos/pithos.github.io/commit/dff9bc2d8817e502ede557ebff5379a9727d2ae2

**Comment by m0ngr31** [comment]
Thank you. I was having the same issue on Mint 18.
