### ISSUE TITLE
Pithos Error on start. pithos:8321

### ISSUE THREAD

**Issue by almurillo** [pithos/pithos#341]
Can anyone help me? I keep getting this error every time I try to open pithos.
(pithos:8321): GLib-GIO-ERROR **: Settings schema 'io.github.Pithos' does not contain a key named 'audio-format'
Trace/breakpoint trap (core dumped)

Anyone know anything about this?

**Comment by TingPing** [comment]
What version, how did you install it?

**Comment by TingPing** [comment]
As a quick solution you can just open `~/.config/pithos.ini` in an editor and remove the `audio_format` line.

**Comment by almurillo** [comment]
Hi Ting 
Thank you for your quick response. I have ubuntu 16.04 and I added this repository
 sudo add-apt-repository ppa:pithos/ppa
sudo apt-get install pithos
Hope that helps. 
I will try your solution noa

**Comment by almurillo** [comment]
I just try deleting the line and still gives me the same error

**Comment by TingPing** [comment]
That doesn't quite make sense.. You could just delete the entire file.

**Comment by almurillo** [comment]
That did it Ting. Thanks a million. Deleted the file and start working.
