### ISSUE TITLE
Pithos stops playing at beginning of random song Raspberry Pi

### ISSUE THREAD

**Issue by levibostian** [pithos/pithos#342]
Hello there. I am still having this issue. Here are some details:
- Pithos v1.2.1
- Raspberry Pi 2
- Ubuntu Mate 16.04
- Wired ethernet connection and I have tried WiFi connection. Both connections 50+ mbps lines.
- Pandora account not One subscription.
- Running Pithos from terminal and no warnings thrown in standard output.
- Desktop running with no screensaver, no sleep, etc. Always up and running.
- Pithos no plugins installed. No proxy. Explicit music allowed.

Same issue as this issue was initially having issues with. Pithos will play great for 20 - 60 minutes then randomly it will get to a song and not play. No issues stopping halfway into a song, but not playing the next song in station.

More details located [on other issue](https://github.com/pithos/pithos/issues/94) starting at [this comment](https://github.com/pithos/pithos/issues/94#issuecomment-243298951)

**Comment by levibostian** [comment]
@JasonLG1979 able to reproduce via his Raspberry Pi 2 with Ubuntu Mate.

**Comment by TingPing** [comment]
Probably also worth noting 16.04 ships GStreamer 1.8.0 which is 3 micro versions behind.

**Comment by JasonLG1979** [comment]
I'll do some more testing and search though the Ubuntu / Ubuntu Mate RPI2 / Gstreamer bug trackers to see where the blame goes. But at this point it looks like it's probably an upstream bug.

**Comment by JasonLG1979** [comment]
> Probably also worth noting 16.04 ships GStreamer 1.8.0 which is 3 micro versions behind.

The current Gstreamer version in Ubuntu is 1.8.2. I'm not sure of the versioning system of Gstreamer but if it's like GNOME than 1.8.3 is the current stable.(the 1.9.x stuff is dev builds?) If so it's only 1 update behind. Provided 1.8.3 is a bug fix release it should get into the 16.04 repos eventually.

**Comment by JasonLG1979** [comment]
I'll see if I can't get Pithos running on Raspbian Jessie. @TingPing what's the min GTK version for Pithos again? Raspbian Jessie has 3.14 I do believe.

**Comment by TingPing** [comment]
3.14.

**Comment by JasonLG1979** [comment]
Well crap. Jessie has Gstreamer 1.2. It may be just trading one playback bug for another. We'll see...

**Comment by TingPing** [comment]
Well if 1.2 works you can just bisect years worth of changes to track it down :P

**Comment by JasonLG1979** [comment]
No. Thank. You,lol!!!

My plan was if Pithos works fine on Raspbian was to recommend it over Ubuntu for owners of Raspberry Pi 2's that want to use Pithos on them.(and prefer a Debian based OS)

**Comment by JasonLG1979** [comment]
Well so far so good. Pithos built and installed with the Ubuntu instructions in the wiki. Pithos is surprisingly well behaved. It uses about the same amount of resources as it does on Ubuntu. I'm impressed. I'm going to let it run over night and check it to see if anything goes south. If everything looks good in the morning I'll let it run until this time tomorrow.

On a side note: Raspbian seems to run MUCH smoother and faster than Ubuntu Mate even without Pithos as a consideration I think I would recommend Raspbian over Ubuntu Mate any way...

**Comment by JasonLG1979** [comment]
From indicator-sound_12.10.2+16.04.20160406/src/service.vala:
```vala
		/* Everything is built, let's put it on the bus */
		try {
			export_actions = bus.export_action_group ("/com/canonical/indicator/sound", this.actions);
		} catch (Error e) {
			critical ("%s", e.message);
		}

		this.menus.@foreach ( (profile, menu) => menu.export (bus, @"/com/canonical/indicator/sound/$profile"));
```

It appears all you'd have to do is look for the /com/canonical/indicator/sound interface maybe?

**Comment by levibostian** [comment]
A few hours ago I installed Raspbian Jesse on the Pi 2. I am currently playing Pithos so far so good. I have not ran Raspbian in a while and wow, it has gotten much faster! Super impressed. I usually just run terminal and no gui on Pis. 

I will let it play all day see if there are issues. Keep you updated.

**Comment by JasonLG1979** [comment]
@levibostian I can write a very simple test app that just loops an mp3 to see if I can reproduce with a local file if you'd like to report this bug upstream.

**Comment by levibostian** [comment]
Everything going well here as well. Music used to stop after 15 minutes but today it has been running about 8 hours non-stop. Still going. 

I do not *need* to run Mate. Simply whatever OS runs Pithos all day and Jessie is solving that need for me. I chose Mate thinking it would have the best compatibility with Pithos. Pure assumption on my part. 

I think we should add a note in the README and wiki specifying Pithos does not work well on Ubuntu Mate (assuming full desktop versions of Ubuntu work great. I used to use Pithos with Lubuntu and Xubuntu.) for future readers. 

Then, only if you want to, have you create a simple test app to reproduce bug and can submit issue to Ubuntu Mate tracker. I don't know enough about Linux sound as you do so I wouldn't be able to create a test app. Or I could create an issue in the tracker simply telling them to install Pithos?

**Comment by TingPing** [comment]
> I think we should add a note in the README and wiki specifying Pithos does not work well on Ubuntu Mate (assuming full desktop versions of Ubuntu work great.

There is no issue with Pithos on Mate. Mate might be garbage on a pi or GStreamer 1.8 might be garbage on ARM but these are external issues.

**Comment by JasonLG1979** [comment]
I agree with @TingPing. The issue is probably either Gstreamer 1.8 on ARM in general or maybe some patch that Ubuntu adds to Gsreamer 1.8 on ARM? It's really hard to say without doing a lot of digging. The Mate desktop it's self more than likely has nothing to do with it.

**Comment by levibostian** [comment]
Good point. Reason I mentioned adding a note to the README/wiki is to inform potential users of Pithos on Mate about issues. Help them to avoid issues that I have been having to push them to use Jessie to get up and running. 

Save time and frustration for people, as myself, who want to install Pithos on a system that is tested to work and can enjoy their tunes.

**Comment by JasonLG1979** [comment]
It's not about Mate. I wouldn't recommend any flavor of Ubuntu on the Raspberry Pi2 for anyone that wants to use Pithos on it. The Mate flavor just so happens to be the version that goes out of their way to make it easy to install on the Raspberry Pi2. They get a bad rap in this case as they don't have anything to do with why it doesn't work. So my personal official recommendation is if you want to run a Debian based OS and Pithos on your Raspberry Pi2 then stick to Raspbian Jessie.

**Comment by JasonLG1979** [comment]
@levibostian: Here is a test app you can use to play either local files or audio files from urls. You can either type the uri in or drag and drop them.(absolute file paths)

https://gist.github.com/JasonLG1979/70c493bfb351a7f98bd188158b87dab2

I have a theory as to what the problem is. Normally when you use Gstreamer to play a http stream you would set up a buffering mechanism. Basically you start the audio pipeline in a  paused and wait for the track to buffer enough to start playing and then set it to play. For local files however it seems that if you try that they never trigger the buffer message and they just sit there. I work around that in the test app so it works as expected with both local and non-local files. My theory is that for some reason the ubuntu-armhf version of Gstreamer in 16.04 for some reason is mistaking the non-local uri provided by Pandora for a local file and is not sending buffer messages. I'll test it out this weekend. If that's the case I'll file a bug report with Ubuntu.

**Comment by TingPing** [comment]
Yea it isn't our job to tell users what distros work on their hardware. Github is pretty google friendly so if somebody encounters the same issue as you they can easily find this discussion.

**Comment by levibostian** [comment]
Thanks @JasonLG1979 I submitted a bug on Ubuntu Mate bug report. 

Should we close this issue? Jessie is the solution.

**Comment by JasonLG1979** [comment]
I would leave it open since it's still an issue an link to your upstream bug report.

**Comment by JasonLG1979** [comment]
Nevermind @levibostian. Found the bug https://bugs.launchpad.net/ubuntu-mate/+bug/1621946

**Comment by levibostian** [comment]
@JasonLG1979 if you wish, you could help on the [Ubuntu Mate bug](https://bugs.launchpad.net/ubuntu-mate/+bug/1621946) to get them the information they wish. I don't have the raspberry pi anymore. I got Jessie installed, got it working, then handed it off. I don't have a raspberry pi with Ubuntu Mate anymore.

**Comment by JasonLG1979** [comment]
I'll jump on there and get them up to speed and do some testing with my test app. One thing I do know is that it's not Pithos. Pithos doesn't do anything fancy with Gstreamer. Pretty much textbook playbin stuff.

**Comment by levibostian** [comment]
Great. I am not much help to them with this issue so they would appreciate that.
