### ISSUE TITLE
Plugin switch should reset to off on error loading plugin

### ISSUE THREAD

**Issue by JasonLG1979** [pithos/pithos#344]
Currently if a user tries to enable a plug in and something goes south, pylast is not installed for example, the plugin row is set to insensitive with no way for the user to set the switch to off but the switch is not reset to off. The result is that Pithos tries to load the plugin every time it starts for no reason from then on. IMHO expected behavior would be for the switch to also be set to off in addition to setting the row to insensitive. I can put a PR in for that behavior if you like @TingPing?

**Comment by TingPing** [comment]
Seems reasonable. An ideal might be to turn it off, show some error icon with the tooltip, and then allow the user to re-enable it.

**Comment by JasonLG1979** [comment]
I'm having a heck of a time with this it should be fairly simple. This works for me on my PC running Fedora 24 but segfaults on Raspbian:

(in PreferencesPithosDialog.py)
```python
    def __init__(self, plugin):
       ....

        switch_handler = self.switch.connect('notify::active', self.on_activated)
       ....

        if plugin.prepared and plugin.error:
            self.set_sensitive(False)
            self.set_tooltip_text(plugin.error)
            with self.switch.handler_block(switch_handler):
                self.switch.set_active(False)

       ....

    def on_activated(self, obj, params):
       ....

        if self.plugin.prepared and self.plugin.error:
            self.get_parent().unselect_row(self)
            self.set_sensitive(False)
            self.switch.set_active(False)
            self.set_tooltip_text(self.plugin.error)
        elif self.plugin.prepared:
            self.get_toplevel().preference_btn.set_sensitive(self.plugin.preferences_dialog is not None)
```

Even if I block the handler in on_activated when I set the switch to inactive.

**Comment by TingPing** [comment]
> but segfaults on Raspbian

Perhaps recursion with `on_activated()` calling `set_active()`?

**Comment by JasonLG1979** [comment]
I'm sure that's what it is. But on Fedora it doesn't seem to be the problem and on Raspbian even if I block the handler while doing the set active it still segfaults.

**Comment by JasonLG1979** [comment]
I'll give:

```python
            self.switch.handler_block_by_func(self.on_activated)
            self.switch.set_active(False)
            self.switch.handler_unblock_by_func(self.on_activated)
```
a shot to see if it works on the Pi...

**Comment by JasonLG1979** [comment]
Nope... Am I doing something wrong here?

**Comment by JasonLG1979** [comment]
The recursion is caused by:
```python
        plugin.settings.bind('enabled', self.switch, 'active', Gio.SettingsBindFlags.DEFAULT)
```
Even if the 'notify::active' signal handler is blocked the above line with still cause a recursive loop if you set the switch to active in on_activated.

**Comment by infirit** [comment]
Works fine for me with below. Why do you think there is a need to block?

```diff
diff --git a/pithos/PreferencesPithosDialog.py b/pithos/PreferencesPithosDialog.py
index e19e7cf..cf17003 100644
--- a/pithos/PreferencesPithosDialog.py
+++ b/pithos/PreferencesPithosDialog.py
@@ -70,6 +70,7 @@ class PithosPluginRow(Gtk.ListBoxRow):
         if self.plugin.prepared and self.plugin.error:
             self.get_parent().unselect_row(self)
             self.set_sensitive(False)
+            self.switch.set_active(False)
             self.set_tooltip_text(self.plugin.error)
         elif self.plugin.prepared:
             self.get_toplevel().preference_btn.set_sensitive(self.plugin.preferences_dialog is not None)

```

**Comment by JasonLG1979** [comment]
> Works fine for me with below. Why do you think there is a need to block?

It works fine for me to on a PC running Fedora 24 on GNOME 3.20 but as I said on Raspbian(Gtk 3.14) on a Raspberry Pi2 it segfaults. It may be due to the ancient Gtk version or because the Pi is orders of magnitude slower than even the most generic desktop, idk? But this works as expected on both.
 https://gist.github.com/JasonLG1979/3c0ecb0772a602f8fc03c4b1e6be63b6

**Comment by JasonLG1979** [comment]
@TingPing as far as the icon thing, do you mean something like this?

![output](https://cloud.githubusercontent.com/assets/6667703/18460207/25e2c4f6-7935-11e6-9293-6d9e5cdcc34c.gif)

**Comment by TingPing** [comment]
Yea.

**Comment by JasonLG1979** [comment]
Right on well that gist above has all the changes in it. Off the top of my head there's switch resting on error. I changed the settings bindings to make them one way so the switch effects the plugin setting but not the other way around. And I set the plugin descriptions to small so they don't get truncated. Give it a look and let me know what you think.
