### ISSUE TITLE
Slow/timeout issues under Fedora 24

### ISSUE THREAD

**Issue by mcrbids** [pithos/pithos#347]
Fairly fresh install of Fedora 24 on an i7 Dell Precision M3800, 16 GB of RAM. Pithos ran beautifully under previous Fedora versions, but now is very slow. Based on the behavior, I'm guessing that there's some type of timeout that happens between every significant activity. 

During these delays the UI is "responsive" in that hovering over buttons highlights them, menus pop up when clicked, etc. During these delays, I can click Pithos -> About and get the about screen. 

This is true with the RPM install of 1.1.2, and while running a downloaded source copy of 1.2.1. 

1) From program launch,  it immediately says "Logging in" at the bottom and then does nothing else for almost exactly 90 seconds before displaying "Getting songs...". Never less than 90 seconds. (1:31 is typical) 

2) Once it says "Getting songs....", nothing displays for almost exactly 30 seconds. (The songs appear at about 2:01 from program launch) 

3) Songs take :15 seconds to start playing - there is a :15 second delay between each song played, and this delay also happens when you skip to the next song.

**Comment by JasonLG1979** [comment]
It's Fedora specific. I run Fedora 24 also and up until a day or 2 ago had no problems. And then I get the same results. Ubuntu 16.04.1 in VM on the same machine has no problems what so ever.

**Comment by JasonLG1979** [comment]
I'll go through and check to see what packages I recently updated and find the problem here in a few hours after I'm off work.

**Comment by mcrbids** [comment]
Thanks. I've just installed so it never worked without the timeouts.

**Comment by JasonLG1979** [comment]
I went through and downgraded all the packages that were installed 2 days ago when I did my last update and it didn't do any good. I'm stumped for the moment. I wiped Fedora and am installing Xubuntu 16.04.1 to see if a real install of *buntu has the same problem. Like I said before *buntu in a VM worked perfectly. This is looking like an upstream issue so far. Pithos hasn't changed in 24 days and I just started having the problem a couple days ago after the update. Idk?

**Comment by JasonLG1979** [comment]
In debug mode it <i><b>seems</b></i> like Pandora is taking forever to respond to our requests. At 1st I thought it was just a connection issue or that they were doing some maintenance. But no dice. My 1st is that it's a bug in the python3 update that was pushed a couple days ago. It's definitively something to do with networking somewhere as the covers for me also take forever to download.

**Comment by JasonLG1979** [comment]
OK, this is getting weird... Xubuntu 16.04.1 clean install just ``` sudo apt-get update && sudo apt-get dist-upgrade``` and installed the dependencies to install from source and Pithos exhibits the same behavior stalls for a while at each call to Pandora. Installed Xubuntu and Pithos the <b>exact</b> same configuration inside GNOME Boxes inside the Xubuntu 16.04.1 clean install, and it has no problems at all, works perfectly... Whatever Boxes is doing as far as networking in between Pithos on the VM and Pandora seems to fix the problem? I have no idea what that is at this point...

**Comment by JasonLG1979** [comment]
Got it. Pithos is choking on IPV6. Disabling IPV6 on Xubuntu seems to have fixed the problem. Not really ideal. Kinda like using a sledge hammer to swat a fly. I'm looking into how to disable IPV6 inside Pithos it's self so it doesn't have to be system wide.

**Comment by JasonLG1979** [comment]
Update: Re-enabled IPV6 and Pithos has no issues now. Looks like it was a issue on Pandora's side that appears to be fixed now.

**Comment by JasonLG1979** [comment]
@mcrbids do you have a <b>working</b> IPV6 connection? Because my ISP doesn't do IPV6 so I can't test if that's the problem.

There's no way to cleanly disable IPV4 in python that I can find but it can be monkey patched.
See:
http://stackoverflow.com/questions/2014534/force-python-mechanize-urllib2-to-only-use-a-requests

I re-enabled IPV6 on my system and used the above to disable IPV6 in python and the Pandora calls work as normal but Gstreamer still stalls for a couple seconds in between songs.(disabling IPV6 in python doesn't disable it in Gstreamer) If I had to guess Pandora may have just enabled IPV6 on their system. The stalls are probably connection timeouts because the (broken) IPV6 connections fail. It sucks but this is an upstream issue. 2 issues really. 1. Tell your ISP to support IPV6(if it doesn't already) and 2. Python and Gstreamer not having an easy way to disable IPV6.

**Comment by JasonLG1979** [comment]
Update on this issue:
After installing Fedora 25 I have working IPV6 and Pithos functions normally. The broken IPV6 is apparently a shared issue of Fedora 24 and Ubuntu 16.04.(and possibly Ubuntu 16.10?) Fedora 25 does not have this issue thus far.

**Comment by JasonLG1979** [comment]
Closed because it's an upstream IPV6 issue not a Pithos issue.
