### ISSUE TITLE
Use Last.fm for album art if no art is provided by Pandora

### ISSUE THREAD

**Issue by JasonLG1979** [pithos/pithos#348]
We already have a Last.fm API key that's used by the Last.fm plugin. In the rare event that Pandora doesn't provide album art we can use our key to get an image url from Last.fm. The methods used to get get album art/an artist image don't require a user login. I've got working code that if no art is provided by Pandora it asks Last.fm for an album cover url if Last.fm has no album cover url it asks for a artist image url. It works pretty good. Any interest @TingPing?

Here's an example of an artist image(ignore the UI layout, that a separate deal):
![screenshot_2016-09-24_19-54-51](https://cloud.githubusercontent.com/assets/6667703/18812496/25eded84-829c-11e6-986d-dcef1432db53.png)

**Comment by TingPing** [comment]
I like keeping last.fm in plugin territory and Pandora doesn't really have a problem of missing art IME.

**Comment by aFoxNamedMorris** [comment]
I've experienced Pithos showing no album art before. It doesn't happen often, but it is quite annoying when it does happen. 

I'd say put this functionality in as an option within the Last.FM plugin.

**Comment by JasonLG1979** [comment]
@TingPing my code doesn't depend on pylast. The Last.fm API is stupid simple. Honestly I could probably rewrite the Last.fm plugin to not even depend on pylast.

**Comment by JasonLG1979** [comment]
@aFoxNamedMorris Putting it in the plugin is possible but it makes more sense to have it in the main logic. There's really not much to it. The most complicated part is cleaning the album titles and artist names. Last.fm does not like "()" or "[]" in either or any variation of LP or EP and the end of an album name, So you have to get rid of "()" and "[]" and all text in side them and strip off LP and EP.

And as far as Pandora not providing covers I think it depends on what you're listening too. On More generic stations like my Classic Rock station I'll hardly ever get a missing cover. On other stations I get missing covers ALL THE TIME.

Here I just started Pithos and the 1st playlist is missing 2 covers.(Replaced by Lasf.fm covers)

![screenshot_2016-09-25_15-06-26](https://cloud.githubusercontent.com/assets/6667703/18817901/aa4f3336-8331-11e6-8120-1d4786f001fe.png)

The covers for "Blame" and "Roses" came from Last.fm.

**Comment by JasonLG1979** [comment]
@TingPing Here's how simple it is:
http://ws.audioscrobbler.com/2.0/?method=album.getinfo&api_key=997f635176130d5d6fe3a7387de601a8&artist=Cher&album=Believe&format=json

Then you just snag the url to the image you want.

**Comment by JasonLG1979** [comment]
@aFoxNamedMorris check this branch out:
https://github.com/JasonLG1979/pithos/tree/covers_from_lastfm

**Comment by aFoxNamedMorris** [comment]
@JasonLG1979 That makes sense. Thanks for the clarification.

I'm super pleased about this. Keep up the great work, guys!

**Comment by JasonLG1979** [comment]
It seems that not getting a cover is not so much an error on Pandora's part and more that they just don't have a cover for that song.

A couple examples:
https://www.pandora.com/chainsmokers/closer-single/closer-feat-halsey

https://www.pandora.com/travis-barker-yelawolf/out-of-control-single/out-of-control

**Comment by JasonLG1979** [comment]
@TingPing Better as a separate plugin?
 https://github.com/JasonLG1979/pithos/tree/lastfm_art_scraper

**Comment by JasonLG1979** [comment]
@aFoxNamedMorris do you mind giving the plugin version above a test on stations that normally would give you songs with missing covers?

**Comment by aFoxNamedMorris** [comment]
@JasonLG1979 I guess I could do it sometime soon. Although it may take a few days, since I am actually taking Python and Qt courses.

**Comment by JasonLG1979** [comment]
Right on. Pithos -v will get you a running log of events and will tell you when/if the plugin has fetched a cover from Last.fm. It's still a WIP. It's about as functional as it can be but the code may be a little ugly to look at. I'm self taught in Python so I'm sure I break about a thousand convention and PEP,lol!!!

**Comment by aFoxNamedMorris** [comment]
@JasonLG1979 I can't build this under Mint 18, for some reason. I think it has to do with the fact that I can't seem to install certain packages.

**Comment by JasonLG1979** [comment]
Try adding --install-recommends when installing the dependencies. Apt in Mint is configured not to install recommended packages by default if I remember.(unlike Ubuntu)

**Comment by aFoxNamedMorris** [comment]
Gives me this:
```
The following packages have unmet dependencies:
 libgdk-pixbuf2.0-dev : Depends: libpng12-dev but it is not going to be installed
E: Unable to correct problems, you have held broken packages.
```

**Comment by JasonLG1979** [comment]
Yep welcome to Linux Mint. They also like to pin packages and/or use there own repos/version of packages set to higher priority.

**Comment by JasonLG1979** [comment]
When I started using Linux about 8 years ago Mint was great with the preinstalled codecs and familiar Windoze like layout and what not. But any more unless you absolutely HAVE to have the Cinnamon DE on a (broken)Ubuntu base you're better off just using a flavor of *buntu IMHO.

**Comment by JasonLG1979** [comment]
I have no experience building debs I'll give it a shot.

**Comment by aFoxNamedMorris** [comment]
Would it run from a tarball if unzipped?

**Comment by JasonLG1979** [comment]
I don't know I always build from source so I have the most current version.

**Comment by JasonLG1979** [comment]
I don't think so though.

**Comment by aFoxNamedMorris** [comment]
Damn. I'm so sorry. I really miss my rig now...

**Comment by JasonLG1979** [comment]
You can try this. But it may very well not work. I have no idea what I'm doing as far as building debs like I said.
https://drive.google.com/file/d/0B8q3lj15AC-YeEYwdURxeU84dTQ/view?usp=sharing

**Comment by JasonLG1979** [comment]
Assuming you're running 64bit...

**Comment by aFoxNamedMorris** [comment]
Success! All is working well!

**Comment by JasonLG1979** [comment]
@aFoxNamedMorris: Running with pithos -v are you getting covers from Last.fm when Pandora doesn't provide an art url?

**Comment by aFoxNamedMorris** [comment]
Yup.

**Comment by JasonLG1979** [comment]
Right on. It works great for me too. It's not perfect though. It's kinda a "fuzzy search" For album covers it strips all text after after and including and brackets ( ' (  [  {  ' ) for the artist's name and for album names in addition to the brackets it strips off any variation of 'EP' or 'LP'. So 'My Awesome Album (Bat Sh!t Crazy Techno Remixes) (Special Edition) - EP' by 'Me (and your Mom)' becomes  'My Awesome Album' by 'Me'. So there's a chance you may get the wrong cover.

**Comment by aFoxNamedMorris** [comment]
Still, this is nice.

**Comment by JasonLG1979** [comment]
The only real wrong image I've received so far is the artist image for Pink. Pink(the female American singer) doesn't seem to have an image on Last.fm I end up getting a image of an 80's Japanese New Wave band,lol!!!

**Comment by JasonLG1979** [comment]
Well Pink apparently stylizes her name as "P!nk" and Pandora is inconsistent with her artist credits. So far if a song is by her alone they use Pink as the artist but sometimes if it's her and others(P!nk & whoever) they use P!nk so I added a way to manually correct artist names . Basically it's this(Pink is the only entry so far, The 80's Japanese New Wave band is not on Pandora so it's safe to change Pink to P!ink ):

```python
...
ARTIST_CORRECTIONS = {'Pink': 'P!nk'} 
...
        if artist:
            for wrong, correct in self.ARTIST_CORRECTIONS.items():
                if text == wrong:
                    text = correct
                    break
```

**Comment by JasonLG1979** [comment]
Update:
I've added a repo for artist name corrections(https://github.com/JasonLG1979/Lastfm-corrections) and changed the plugin code to use the corrections from the repo so users will always have the most up to date corrections without having to update/rebuild Pithos. If you find a needed correction you can put in a PR there.

**Comment by aFoxNamedMorris** [comment]
@JasonLG1979 Thanks! This is a very nifty feature, and will hopefully be appreciated by everyone. 
Excellent work!

**Comment by JasonLG1979** [comment]
@aFoxNamedMorris right on thanks. I reverted the artist correction part. I got to thinking about it and I don't like the idea of having a separate repo or depending on downloading stuff from github for an app.

**Comment by aFoxNamedMorris** [comment]
@JasonLG1979 I'd leave it in, to a degree, but have a section in the preferences for adding the substitutions manually. What do you think?

**Comment by JasonLG1979** [comment]
I like the idea of adding it in the plugin's prefs. Plugins already have a generic 'data' string dumpster that they can store arbitrary data. It wouldn't be much to whip up a UI that allows the user to make their own corrections I could store them as a json in the data dumpster.

**Comment by JasonLG1979** [comment]
I'll work on it tomorrow. When I'm done I'll build you a new deb to test.

**Comment by aFoxNamedMorris** [comment]
Thanks a ton, man!

**Comment by JasonLG1979** [comment]
@aFoxNamedMorris: Something like this work the UI?
![image](https://cloud.githubusercontent.com/assets/6667703/19024358/9e5b230a-88c7-11e6-9bd4-86a6ee12c275.png)

**Comment by aFoxNamedMorris** [comment]
That works! Though what if the string difference is in the album information?

**Comment by JasonLG1979** [comment]
I'm working on that. I'm going to do 2 lists basically 1 for albums and 1 for artists. Where albums would be an artist , album pair and artist would just like it is in the above. The album list would take precedent over the artist list. Basically the Album list would be an exact Pandora vs Last.fm comparison text inside brackets and all and would only apply if both the artist and album matched the correction. The artist list is more of a fuzzy search. It's based on just the artist's name with no brackets and it applies to all songs by an artist that matches a correction.

The trick is how to pull that off in a UI so it doesn't look like a train wreck,lol!!!

**Comment by aFoxNamedMorris** [comment]
I hear you. I'm learning Python and PyQt at the moment. I'm attempting to rewrite one of my projects in such a way so as to accommodate  a GUI. It's all very complex and difficult to get "just right".

**Comment by JasonLG1979** [comment]
Here's a link to a new build with the artist name corrections UI.
https://drive.google.com/file/d/0B8q3lj15AC-YMHhoWHdVT3pybXM/view?usp=sharing

The "Pandora Artist Name" should be an the artist name you want to correct before any brackets so My Awesome Band not My Awesome Band(feat. Your Mom) The "Last.fm Artist Name" should be the exact artist name as per Last.fm. Name pairs are editable once added and the columns are sort-able(ascending, descending, and by timestamp) editing changes the timestamp to when you edited it.

**Comment by JasonLG1979** [comment]
The sort order is remembered across sessions as a side effect of how I sort the treeview.

**Comment by JasonLG1979** [comment]
Oh and you can delete a correction by right clicking it and clicking "Delete Correction"

**Comment by JasonLG1979** [comment]
@aFoxNamedMorris I think I'm about done with the plugin. It's HUGE though (963 lines) so it may have to wait until we implement out of tree plugins, IDK? It's up to @TingPing. Otherwise it works like a charm. It's pretty good at making educated guesses and gets the right album cover probably about 80% of the time. The 20-ish % fail rate is generally because Last.fm doesn't have a cover.

**Comment by JasonLG1979** [comment]
I'm going to close this as there is no interest in adding this feature to Pithos.
