### ISSUE TITLE
mpris plugin no longer updating interface when song changes on Cinnamon 3.0.7

### ISSUE THREAD

**Issue by neoh4x0r** [pithos/pithos#356]
Compiled from commit: bb7b8408ec6e2d5fb347df706b8dda3df1331a2b

When I enable the mpris plugin (in pithos) the cinnamon sound applet will show the currently playing song -- which indicates that the interface is, at least, working.

However, when a new song starts the mpris client on cinnamon is not updated to reflect the
new song that is playing.

Disabling and re-enabling the plugin will update the applet, but as soon as a new song starts playing the issue repeats.

**Version information:**
```
$ pithos --version
Pithos 1.2.1

$ cinnamon --version
Cinnamon 3.0.7

$ apt-cache policy cinnamon
cinnamon:
  Installed: 3.0.7-1
  Candidate: 3.0.7-1
  Version table:
     3.0.7-2 -1
         -1 https://mirrors.ludost.net/debian sid/main amd64 Packages
 *** 3.0.7-1 1001
       1001 https://mirrors.ludost.net/debian stretch/main amd64 Packages
        100 /var/lib/dpkg/status
     2.2.16-5 -1
         -1 https://mirrors.ludost.net/debian jessie/main amd64 Packages

$ cat /etc/os-release
PRETTY_NAME="Debian GNU/Linux stretch/sid"
NAME="Debian GNU/Linux"
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"

$ uname -a
Linux desktop1 3.16.0-4-amd64 #1 SMP Debian 3.16.36-1+deb8u1 (2016-09-03) x86_64 GNU/Linux
```

**Comment by JasonLG1979** [comment]
@neoh4x0r - Everything in your version info says Debian sid. Are you in fact running cinnamon on vanilla Debian sid or a distro based on Debian sid? Just want to know what I should be testing against.

**Comment by JasonLG1979** [comment]
@neoh4x0r - I just fired up Mint 18 with Cinnamon 3.0.7 and it works just fine.

May be related to #343. What's your Gtk version?

**Comment by JasonLG1979** [comment]
@TingPing I vote we bump the minimum Gtk version to 3.18. That's the version that comes with the latest Ubuntu LTS and the only current distros that ship anything less that I'm aware of would be CentOS 7 and Debian Jessie.

**Comment by TingPing** [comment]
@JasonLG1979 The relevant library versions would be glib, gobject-introspection, and pygobject for the mpris plugin btw. As for Gtk version I see no reason to bump that until a feature we need requires so.

**Comment by JasonLG1979** [comment]
Right on. I'd say this is a case of sid not having the right version of something yet.

**Comment by neoh4x0r** [comment]
@JasonLG1979 
I'm running Debian/Testing (Stretch)
```
$ dpkg-query -W libgtk-3-bin libgtk-3-bin 
libgtk-3-bin	3.22.1-1

$ python3 -c 'from gi.repository import Gio; help(Gio.DBusConnection)' | grep register_object
 |  register_object = gi.FunctionInfo(register_object)
 |      register_object(self, object_path:str, interface_info:Gio.DBusInterfaceInfo, method_call_closure:GObject.Closure=None, get_property_closure:GObject.Closure=None, set_property_closure:GObject.Closure=None) -> int
 |  unregister_object = gi.FunctionInfo(unregister_object)
 |      unregister_object(self, registration_id:int) -> bool
```

**Comment by JasonLG1979** [comment]
Does Pithos throw any exceptions or does it say anything that would indicate something wasn't working while running ```pithos --debug```

**Comment by JasonLG1979** [comment]
Does MPRIS work correctly with other apps?

**Comment by JasonLG1979** [comment]
If disabling and enabling the plugin updates it it sounds like maybe the song change handler isn't getting triggered. Like the signal isn't getting received or emitted. Does the notifications plugin work? It depends on the same signal.

**Comment by neoh4x0r** [comment]
@JasonLG1979 
@TingPing 
I believe we can mark this as invalid.

Cinnamon crashed on me just now -- while I was testing pithos -- forcing cinnamon to have to be restarted and now the mpris plugin seems to be working as expected.

I guess all that was needed was to restart Cinnamon.

**Comment by JasonLG1979** [comment]
Yep welcome to Debian sid,lol!!!

**Comment by neoh4x0r** [comment]
Closing this as it's not a bug with pithos.
The Cinnamon desktop simply needed to be restarted.
