### ISSUE TITLE
Unable to get Songs

### ISSUE THREAD

**Issue by MC42** [pithos/pithos#360]
I've launched pithos as follows and it doesn't work, either from the Ubuntu package, or from source.

Logs are as follows:

```
INFO - application:do_activate:128 - Pithos 1.2.1
INFO - pithos:init_core:216 - Created temporary directory /tmp/pithos-m17q32hn
INFO - plugin:enable:39 - Enabling module notify
INFO - plugin:enable:39 - Enabling module mpris
INFO - plugin:enable:39 - Enabling module mediakeys
INFO - mediakeys:bind_dbus:43 - Got session bus
INFO - mediakeys:bind_dbus:89 - Bound media keys with DBUS (org.gnome.SettingsDaemon.MediaKeys)
INFO - _dbus_service:on_name_acquired:36 - Got bus name: net.kevinmehall.Pithos
INFO - _mpris:on_name_acquired:54 - Got bus name: org.mpris.MediaPlayer2.pithos
INFO - pandora:connect:228 - Time offset is 0.19846677780151367
INFO - pithos:pandora_ready:457 - Pandora connected
INFO - pithos:process_stations:512 - Restoring saved station: id = 3199769869290235851
INFO - pithos:station_changed:743 - Selecting station 3199769869290235851; total = 31
INFO - pandora:get_playlist:326 - pandora: Get Playlist
```

Upon launching, Pithos seems to launch normally but loads no songs or thumbnails, constantly remaining stuck "Getting songs..."

**Comment by JasonLG1979** [comment]
Looks like a duplicate of #347

**Comment by MC42** [comment]
I attempted to disable IPv6 and it did not resolve the issue.  In addition, I'm using Ubuntu 16.04.

**Comment by JasonLG1979** [comment]
Read the issue. It effects Ubuntu as well. Disabling IPV6 in network manager doesn't disable IPV6 system wide.

**Comment by MC42** [comment]
I've disabled it at the kernel level with no change, as well as enabling IPv6 from top to bottom with no change.

Why would IPv6 be causing it to not work anyways?  Where are the requests made for new songs?

**Comment by JasonLG1979** [comment]
Both Python and Gstreamer prefer IPV6. If IPV6 on your system is broken somehow it will hang because it's waiting for a response before it falls back to IPV6.

**Comment by MC42** [comment]
I used the IPv6 kernel level disable *sledgehammer* and it still isn't working.

Shame, I didn't plan to reinstall but I need my music.

**Comment by JasonLG1979** [comment]
If you have enabled IPV6 and verified it to be working it could be possible that it's broken on Pandora's side?(I have no way to tell) I can recreate your issue by enabling IPV6 on my system. With IPV6 disabled I have no issue.

**Comment by JasonLG1979** [comment]
To be clear you have edited ```/etc/sysctl.conf``` and added:
 ```
net.ipv6.conf.all.disable_ipv6 = 1
net.ipv6.conf.default.disable_ipv6 = 1
net.ipv6.conf.lo.disable_ipv6 = 1
```
And then used the ```sudo sysctl -p``` to make the changes take effect?

**Comment by MC42** [comment]
I just checked, apparently I forgot to apply the changes....  Thank you, that fixed it.
