### ISSUE TITLE
Playlist/Stations support in MPRIS

### ISSUE THREAD

**Issue by JasonLG1979** [pithos/pithos#368]
MPRIS supports a Playlist interface that allows the user to view and start playlists form supporting applets. For Pithos Stations would map to Playlists. I'm working on adding Playlist support to our MPRIS implementation.
![screenshot from 2016-11-10 15-38-01](https://cloud.githubusercontent.com/assets/6667703/20196543/c0629cd2-a760-11e6-94ed-e9d3a76ece06.png)

Any interest in adding this feature @TingPing?

**Comment by TingPing** [comment]
Sure.

**Comment by JasonLG1979** [comment]
Still working on the details of sorting the stations. Basically we expose a Orderings prop with the available sort orders and in the GetPlaylists method we return a playlist with a requested order. The GNOME shell media extension asks for an alphabetical ordering even if  alphabetical isn't listed in the Orderings prop. But it's up to us to do the sorting so we can return in whatever order we like. We have a couple options:

1. We can only advertise "user" as a sort order and we can tie the sorting to the of the stations popover.
2. We can add alphabetical to the Orderings prop and sort it alphabetical if asked.
3. We can only advertise "Created" and do no sorting.

Thoughts?

**Comment by TingPing** [comment]
Expose "Created" and "Alphabetical" I suppose.

**Comment by JasonLG1979** [comment]
The thing I don't like about that is there's no way to sort the stations in the applet so we're stuck with "Alphabetical".

**Comment by TingPing** [comment]
Does it just request the first order we return? Honestly alphabetical seems fine for the default.

**Comment by JasonLG1979** [comment]
No, it's hardcoded to ask for "Alphabetical".
https://github.com/eonpatapon/gnome-shell-extensions-mediaplayer/blob/7bcb3231e6cd7cdda441619e22e74e7ae513850d/src/player.js#L472

**Comment by JasonLG1979** [comment]
But like I said it'll take whatever we give in whatever order we decide.

**Comment by TingPing** [comment]
Oh, well that is entirely broken but my stance is the same, expose both of them and respect it properly.

**Comment by JasonLG1979** [comment]
> Oh, well that is entirely broken but my stance is the same, expose both of them and respect it properly.

Agreed. Ok then I'll expose "Created" and "Alphabetical" and do what the applet wants with the exception that the QuickMix should always be 1st IMHO like the above pic.

**Comment by TingPing** [comment]
> with the exception that the QuickMix should always be 1st IMHO like the above pic.

Seems reasonable.

**Comment by JasonLG1979** [comment]
Does this look right to you:
```python
    @dbus_method(MEDIA_PLAYER2_PLAYLISTS_IFACE, in_signature='uusb', out_signature='a(oss)')
    def GetPlaylists(self, Index, MaxCount, Order, ReverseOrder):
        playlists = self._playlists[:]        
        quick_mix = playlists.pop(0)
        if Order == 'Alphabetical':
            playlists = sorted(playlists, key=lambda playlist: playlist[1])
        if ReverseOrder:
            playlists.reverse()
        playlists = playlists[Index:MaxCount -1]
        playlists.insert(0, quick_mix)
        return playlists
```

Where:
self._playlists = a list of tuples (obj_path, station_name, '')

**Comment by TingPing** [comment]
Largely seems fine but you might want:
```python
            playlists = sorted(playlists, key=lambda playlist: playlist[1], reverse=ReverseOrder)
```

**Comment by JasonLG1979** [comment]
Order and ReverseOrder are 2 different things if I did:
```python
    @dbus_method(MEDIA_PLAYER2_PLAYLISTS_IFACE, in_signature='uusb', out_signature='a(oss)')
    def GetPlaylists(self, Index, MaxCount, Order, ReverseOrder):
        playlists = self._playlists[:]        
        quick_mix = playlists.pop(0)
        if Order == 'Alphabetical':
            playlists = sorted(playlists, key=lambda playlist: playlist[1], reverse=ReverseOrder)
        playlists = playlists[Index:MaxCount -1]
        playlists.insert(0, quick_mix)
        return playlists
```

I could miss the ReverseOrder if Order != 'Alphabetical'.

**Comment by TingPing** [comment]
How about:

```python
if Order == 'Alphabetical':
  playlists = sorted(...)
elif Order == 'CreationDate':
  if ReverseOrder:
    playlists = reversed(playlists)
else:
  # ERROR
```

**Comment by JasonLG1979** [comment]
Another question. Is it CreationDate or Created?

**Comment by TingPing** [comment]
I.. don't know. The docs don't explain the word in parens at all. My guess was the first word is the real one?

**Comment by JasonLG1979** [comment]
I'll have to look though some source code for apps that expose that interface and see what everyone else is using?

**Comment by TingPing** [comment]
Might as well.

**Comment by JasonLG1979** [comment]
As far as I can tell from searching source code everyone uses 'CreationDate'.

**Comment by JasonLG1979** [comment]
I put in a PR to fix a couple issues with the GNOME media extension. If/when they get merged I'll put in a PR for what I've got so far for the playlist stuff on our side of it.
 https://github.com/eonpatapon/gnome-shell-extensions-mediaplayer/pull/280

**Comment by JasonLG1979** [comment]
@TingPing this what I have so far:
https://github.com/JasonLG1979/pithos/commit/0b4a3bae62b03b461d231559df652c0c6bc3cb0f

It works perfectly when used in conjunction with my PR to fix the issue in the GNOME media extension. It also works in the Ubuntu sound menu as well as any other implementation. The Ubuntu sound menu is broken in different ways than the GNOME media extension. The Ubuntu sound menu doesn't update playlists or indicate the current playlist. Basically if you add, remove or rename a playlist it doesn't reflect the changes. I tested it with Rhythmbox so it's not my code that's the problem. As far as I can tell I follow spec. But again NO ONE else seems to follow the MPRIS spec.

**Comment by JasonLG1979** [comment]
@TingPing I'll work on that in the next couple days. There's no real hurry as far as I can tell. The only 2 desktop clients so far that I've found that support it(the Ubuntu sound menu and the GNOME media extension) are both broken in different ways.

**Comment by JasonLG1979** [comment]
Update:
Working on fixing bugs/tweaking things upstream.
https://github.com/eonpatapon/gnome-shell-extensions-mediaplayer/pull/280
https://github.com/eonpatapon/gnome-shell-extensions-mediaplayer/pull/283
https://github.com/eonpatapon/gnome-shell-extensions-mediaplayer/pull/286
https://github.com/eonpatapon/gnome-shell-extensions-mediaplayer/pull/287

When everything works like I want it to I'll put in a PR for adding playlist support.

**Comment by TingPing** [comment]
Nice work.

**Comment by JasonLG1979** [comment]
A neat little side effect of the PR dealing with the Orderings prop is that we can effectively sort our own playlist by connecting the station sort setting to a handler that sends a Orderings prop change with only          ```['Alphabetical']``` or ```['CreationDate']``` without breaking other applets.

**Comment by JasonLG1979** [comment]
Next up I think I'm going to fix the whole we have to lie about being able to seek thing for the Position to be shown in the extensions UI. My thought is that if a player is able to give a valid position and duration not being able to seek shouldn't matter the position should be shown in the UI and it should just be made so that you can't interact with it.

I'd really love to be able to remove as many workarounds as I can from our implementation...

**Comment by JasonLG1979** [comment]
@TingPing slightly off topic, but what do you think of this:
 https://github.com/eonpatapon/gnome-shell-extensions-mediaplayer/issues/294

My idea is still a little rough but I think the concept is a good one.

If they do something like this it will allow us to git rid of the _dbus_service.py as it would cover ratings. Ban and tired aren't really ratings exactly and would be out of scope of a generic ratings interface though.

With your DBusServiceObject.py it would be stupid easy to add something like this to Pithos.

**Comment by JasonLG1979** [comment]
Closed with https://github.com/pithos/pithos/commit/0528ef06006351993f66895b1fb0af418b8053a2
