### ISSUE TITLE
Relog/Reacquire token after timeout flaky

### ISSUE THREAD

**Issue by stevekuznetsov** [pithos/pithos#369]
I've recently updated to 352f321830283ef15665d90da9aabe9789d91e36 and when my auth token becomes invalid while the radio is paused, re-acquiring the token and/or re-logging is flaky. Previously (1.1.2) I never had to manually re-log-in or skip songs to get the token to refresh.

**Comment by JasonLG1979** [comment]
Song urls are only valid for 1 hour. That's Pamdora's doing. I have a PR in to address the issue by comparing the time at which the URL was requested and the time the player goes into a play state that would automatically skip the song if it becomes invalid. It just waiting to be merged.

**Comment by JasonLG1979** [comment]
https://github.com/pithos/pithos/pull/354

**Comment by TingPing** [comment]
It wasn't the song that was the problem, he was getting error 1001 (invalid auth) and for some reason Pithos wasn't logging back in.

**Comment by JasonLG1979** [comment]
I wasn't sure if all the errors from the invalid song wasn't somehow effecting Pithos's ability to re-authenticate?

**Comment by JasonLG1979** [comment]
If you get too many Gstreamer errors Pithos stops retrying. If you got a playlist full of Gstreamer errors because the songs were no longer valid that would do it.

**Comment by TingPing** [comment]
I don't think its relevant, `pithos -t` even fails if you uncheck authenticated.

**Comment by JasonLG1979** [comment]
https://github.com/pithos/pithos/blob/master/pithos/pithos.py#L632-L636

**Comment by JasonLG1979** [comment]
Do we know how long a token is even good for?

**Comment by stevekuznetsov** [comment]
@JasonLG1979 @TingPing reproduced this (very easy to do ... are you guys running the latest devel? every single time auth token times out Pithos does not correctly return to playing after reconnect)

I got this log:

```
ERROR - pithos:on_gst_error:793 - Gstreamer error: gst-resource-error-quark: Forbidden (15), gstsouphttpsrc.c(1612): gst_soup_http_src_parse_status (): /GstPlayBin:player/GstURIDecodeBin:uridecodebin5/GstSoupHTTPSrc:source:
Forbidden (403), URL: http://t3-1.p-cdn.com/access/XXXX.mp3?version=5&lid=XXXX&token=XXXX, Redirect to: (NULL), 15
Traceback (most recent call last):
  File "/home/skuznets/Documents/go/src/github.com/pithos/pithos/pithos/pithos.py", line 801, in on_gst_error
    self.next_song()
  File "/home/skuznets/Documents/go/src/github.com/pithos/pithos/pithos/pithos.py", line 571, in next_song
    self.start_song(self.current_song_index + 1)
  File "/home/skuznets/Documents/go/src/github.com/pithos/pithos/pithos/pithos.py", line 547, in start_song
    self.update_song_row()
  File "/home/skuznets/Documents/go/src/github.com/pithos/pithos/pithos/pithos.py", line 915, in update_song_row
    self.songs_model[song.index][1] = self.song_text(song)
  File "/home/skuznets/Documents/go/src/github.com/pithos/pithos/pithos/pithos.py", line 879, in song_text
    if not song.bitrate is None:
AttributeError: 'Song' object has no attribute 'bitrate'
INFO - pandora:get_playlist:326 - pandora: Get Playlist
DEBUG - pandora:json_call:118 - https://internal-tuner.pandora.com/services/json/?partner_id=XX&user_id=XXXX&auth_token=XXXX&method=station.getPlaylist
DEBUG - pandora:json_call:119 - b'{"additionalAudioUrl": "HTTP_32_AACPLUS,HTTP_128_MP3", "includeTrackLength": true, "syncTime": 1481810151, "stationToken": "XXXX", "userAuthToken": "XXXX"}'
Traceback (most recent call last):
  File "/home/skuznets/Documents/go/src/github.com/pithos/pithos/pithos/pithos.py", line 571, in next_song
    self.start_song(self.current_song_index + 1)
  File "/home/skuznets/Documents/go/src/github.com/pithos/pithos/pithos/pithos.py", line 547, in start_song
    self.update_song_row()
  File "/home/skuznets/Documents/go/src/github.com/pithos/pithos/pithos/pithos.py", line 915, in update_song_row
    self.songs_model[song.index][1] = self.song_text(song)
  File "/home/skuznets/Documents/go/src/github.com/pithos/pithos/pithos/pithos.py", line 879, in song_text
    if not song.bitrate is None:
AttributeError: 'Song' object has no attribute 'bitrate'
DEBUG - pandora:json_call:138 - {"stat":"fail","message":"An unexpected error occurred","code":1001}
ERROR - pandora:json_call:145 - fault code: 1001 message: An unexpected error occurred
INFO - pithos:eb:333 - Automatic reconnect after invalid auth token
```

**Comment by TingPing** [comment]
I could repro it not automatically relogging in, somebody just needs to look into it.

**Comment by stevekuznetsov** [comment]
I'm happy to look at it but I'm not familiar with this code-base. I have some questions:
 - in the above log, is the stacktrace expected?
 - in the above log, we see that an automatic reconnect happened, but it seems like after this re-playing songs doesn't start. does that seem like the correct understanding of the issue for you?

**Comment by TingPing** [comment]
> in the above log, is the stacktrace expected?

It should probably handle bitrate being unset.

> in the above log, we see that an automatic reconnect happened, but it seems like after this re-playing songs doesn't start. does that seem like the correct understanding of the issue for you?

Sounds right but I didn't look into it.

**Comment by stevekuznetsov** [comment]
Ok. Cool. I'll try to dig into it.

**Comment by stevekuznetsov** [comment]
@TingPing @JasonLG1979 Thanks :)
