### ISSUE TITLE
Pithos plays to speakers even when sound preferences sets output to another destination

### ISSUE THREAD

**Issue by edgreenberg** [pithos/pithos#372]
Running Fedora 24 Mate Spin (fork of Gnome 2).  I installed 1.1.2-1.fc24 from rpmfusion-free. 

Plugged in a USB headset and set output to the USB headset.  All other sound sources obeyed the sound app to send sound to the USB headset. Pithos did not.  Music still goes to the internal speakers.

**Comment by JasonLG1979** [comment]
Pithos doesn't do anything special with sound output. It uses Gstreamer pretty generically. Basically it just goes "here Gstreamer play this URL." Our involvement ends there. If you're having sound routing issues it's not Pithos.

**Comment by edgreenberg** [comment]
Just what I need to know.  I will look to Gstreamer.

**Comment by edgreenberg** [comment]
Just for others, I found the problem.  When one plugs in a USB sound card, and then selects it in Sound Preferences, one must stop and restart the application (Pithos) in order to pick up the change.   Firefox displays the same behaviour.  Plugging in the USB device and selecting it, doesn't affect FIrefox until it is restarted.  So it's not just gstreamer, it's the way things work.

**Comment by JasonLG1979** [comment]
That must be specific to that device. I use a USB DAC and I can plug it in while Pithos is running,(or any other app that makes noise) select it as the default output device and switches over just fine.
