### ISSUE TITLE
Seg fault when trying to use with X Forwarding

### ISSUE THREAD

**Issue by jadar** [pithos/pithos#375]
Recently I tried starting Pithos while SSH'd into my box with X Forwarding enabled. It begins to start but before the window shows up, the app seg faults. 

Steps to reproduce:
1. SSH into another box with X Forwarding enabled.
2. Execute `pithos`
3. Crash

```
$  pithos
/usr/share/pithos/pithos/pithos.py:36: PyGIWarning: GstPbutils was imported without specifying a version first. Use gi.require_version('GstPbutils', '1.0') before import to ensure that the right version gets loaded.
  from gi.repository import Gst, GstPbutils, GObject, Gtk, Gdk, Pango, GdkPixbuf, Gio, GLib
[1]    9526 segmentation fault (core dumped)  pithos
```

**Comment by JasonLG1979** [comment]
More info needed. Distro? Versions of everything? The latest source does check GstPbutils but I doubt that's your problem. Have you tested other pygi apps? Specifically other pygi based media players?

**Comment by JasonLG1979** [comment]
What is your expected result? I'm not very familiar with X Forwarding at all, but a quick Google search says that audio isn't forwarded unless you do some additional steps with pulseaudio. So audio would be played on the server not the client. So unless you do those things or don't have working audio on your server(again I'm not sure if you want sound on your server or client) you're not going to get audio.

If this is still relevant(again, I'm not very familiar with X Forwarding at all):
http://superuser.com/questions/231920/forwarding-audio-like-x-in-ssh

**Comment by JasonLG1979** [comment]
@jadar I need more info...

**Comment by JasonLG1979** [comment]
@jadar Closing this because I'm going to assume you figured it out since you never responded to my request for more info...
