### ISSUE TITLE
Network error: <urlopen error EOF occurred in violation of protocol (_ssl.c:600)>

### ISSUE THREAD

**Issue by stevekuznetsov** [pithos/pithos#377]
After normal execution (with very frequent incidence of #369) I suddenly got `Network error: <urlopen error EOF occurred in violation of protocol (_ssl.c:600)>` and Pithos stopped being able to play anything. Opening the preferences hung the application and I had to kill it manually. Accessing Pandora through their web client worked fine. Journal log follows. 

<details>
<summary> Journal Log </summary>

```
Nov 11 11:06:31 io.github.Pithos[9742]: Not an Ad..
Nov 11 11:06:31 io.github.Pithos[9742]: Using audio quality highQuality: 192 mp3
Nov 11 12:08:29 io.github.Pithos[9742]: Gstreamer error: gst-resource-error-quark: Forbidden (15), gstsouphttpsrc.c(1612): gst_soup_http_src_parse_status (): /GstPlayBin:player/GstURIDecodeBin:uridecodebin178/GstSoupHTTPSrc:source:
                                        Forbidden (403), URL: http://t1-2.p-cdn.com/access/2802062859101343801.mp3?version=5&lid=360925471&token=zbb6AGIL5%2BAu%2F6Y87dorF6bT%2FMZJlqFnpuS1Bj%2Ffi35Rn7Mimds7BVGflEEOfNt9WWenZy8Iy6geyN6LSLePY7niSNahbfrdNdz5TB3Iz1Tpz2Lx8nk6NzgaAt8QdPa977z8Povmk30nf%2FuQ2TxBD8p6KdzuaTgoCRxsMK1FNGlQg%2BbGaSFijrQ4qXQK5YeQCYWdlkfk5Xe%2F1foQ01mTXj4wraF9TxnQ2GeKKD1rtlToCr3T46rtSGLyGGNG%2F78xiOgyam4xQnOfJ1cWhvJZKLb52Da2zLAMu4abCni9c8nnwhL%2F000I7zBEDO3eeKeIDIjtm1vuTVz1UzQ4WXbThA%3D%3D, Redirect to: (NULL), 15
Nov 11 12:08:41 io.github.Pithos[9742]: pandora: Get Playlist
Nov 11 12:08:42 io.github.Pithos[9742]: Downloaded album art for 43
Nov 11 12:08:42 io.github.Pithos[9742]: Downloaded album art for 40
Nov 11 12:08:42 io.github.Pithos[9742]: Downloaded album art for 42
Nov 11 12:08:42 io.github.Pithos[9742]: Downloaded album art for 41
Nov 11 12:08:43 io.github.Pithos[9742]: Starting song: index = 40
Nov 11 12:08:43 io.github.Pithos[9742]: Using audio quality highQuality: 192 mp3
Nov 11 12:08:43 io.github.Pithos[9742]: Using audio quality highQuality: 192 mp3
Nov 11 12:08:43 io.github.Pithos[9742]: Not an Ad..
Nov 11 12:08:43 io.github.Pithos[9742]: Using audio quality highQuality: 192 mp3
Dec 14 16:25:46 io.github.Pithos[9742]: Selecting station 2833412658794023199; total = 49
Dec 14 16:25:46 io.github.Pithos[9742]: pandora: Get Playlist
Dec 14 16:25:52 io.github.Pithos[9742]: Selecting station 3172841149648029983; total = 49
Dec 14 16:25:52 io.github.Pithos[9742]: pandora: Get Playlist
Dec 14 16:25:53 io.github.Pithos[9742]: Network error: <urlopen error [Errno 104] Connection reset by peer>
Dec 14 16:25:58 io.github.Pithos[9742]: Manual retry
Dec 14 16:25:58 io.github.Pithos[9742]: pandora: Get Playlist
Dec 14 16:25:58 io.github.Pithos[9742]: Network error: <urlopen error EOF occurred in violation of protocol (_ssl.c:600)>
Dec 14 16:25:59 io.github.Pithos[9742]: Network error: <urlopen error [Errno 104] Connection reset by peer>
Dec 14 16:26:00 io.github.Pithos[9742]: Manual retry
Dec 14 16:26:00 io.github.Pithos[9742]: pandora: Get Playlist
Dec 14 16:26:00 io.github.Pithos[9742]: Manual retry
Dec 14 16:26:00 io.github.Pithos[9742]: pandora: Get Playlist
Dec 14 16:26:00 io.github.Pithos[9742]: Network error: <urlopen error EOF occurred in violation of protocol (_ssl.c:600)>
Dec 14 16:26:01 io.github.Pithos[9742]: Manual retry
Dec 14 16:26:01 io.github.Pithos[9742]: pandora: Get Playlist
Dec 14 16:26:02 io.github.Pithos[9742]: Network error: <urlopen error EOF occurred in violation of protocol (_ssl.c:600)>
Dec 14 16:26:03 io.github.Pithos[9742]: Manual retry
Dec 14 16:26:03 io.github.Pithos[9742]: pandora: Get Playlist
Dec 14 16:26:11 io.github.Pithos[9742]: Network error: <urlopen error [Errno 104] Connection reset by peer>
Dec 14 16:26:15 io.github.Pithos[9742]: Network error: <urlopen error [Errno 104] Connection reset by peer>
Dec 14 16:30:12 io.github.Pithos[9742]: Manual retry
Dec 14 16:30:12 io.github.Pithos[9742]: pandora: Get Playlist
Dec 14 16:30:12 io.github.Pithos[9742]: Manual retry
Dec 14 16:30:12 io.github.Pithos[9742]: pandora: Get Playlist
Dec 14 16:30:14 io.github.Pithos[9742]: Network error: <urlopen error EOF occurred in violation of protocol (_ssl.c:600)>
Dec 14 16:30:15 io.github.Pithos[9742]: Manual retry
Dec 14 16:30:15 io.github.Pithos[9742]: pandora: Get Playlist
Dec 14 16:30:16 io.github.Pithos[9742]: Network error: <urlopen error EOF occurred in violation of protocol (_ssl.c:600)>
Dec 14 16:30:20 io.github.Pithos[9742]: Network error: <urlopen error [Errno 104] Connection reset by peer>
Dec 14 16:30:25 io.github.Pithos[9742]: Network error: <urlopen error [Errno 104] Connection reset by peer>
```
</details>

**Comment by stevekuznetsov** [comment]
I was previously on 352f321. Updating to 5b85365d7620238584e19e3331e39b497cb4b4cb did not help.

**Comment by stevekuznetsov** [comment]
I am a Pandora One subscriber, @glennimoss confirmed in IRC this seems to only affect subscribers. Switching to the `./bin/pithos` application (_not_ launching `pithos` from the binary created with `make install`) works fine.

**Comment by JasonLG1979** [comment]
> I was previously on 352f321. Updating to 5b85365 did not help.
Neither have anything to do with networking really.

I'm by no means a networking or ssl expert but that's 2 bugs related to connecting with Pandora that no one else can duplicate. Possibly your network configuration?

> Switching to the ./bin/pithos application (not launching pithos from the binary created with make install) works fine.

By that do you mean you have 2 versions of Pithos installed at once?

**Comment by stevekuznetsov** [comment]
> that's 2 bugs related to connecting with Pandora that no one else can duplicate. Possibly your network configuration?

On IRC another Pandora One subscriber confirmed having the same exact symptoms.

> By that do you mean you have 2 versions of Pithos installed at once?

I've got the source checked out. When you do a `make install` it places binaries at `/usr/local/bin` and creates the `.desktop` file, but it also results in binaries in `"${REPO}/bin/pithos`. I'm not familiar with what the `make` targets are doing here but I am surprised that the placed binary at `/usr/local/bin` isn't identical or mostly identical to that in the repository. Nevertheless, I can 100% reproduce this failure with the `pithos` binary in my system `$PATH` (pointed to by the `.desktop` file) but the binary in the repository checkout is fine.

**Comment by stevekuznetsov** [comment]
Also on my system (again, clean checkout of master, `make install` is all I did) if I run the `pithos` in the system `$PATH` with `--verbose` and `--debug` I don't see any output to the terminal (and nothing extra goes to the systemd journal). This is why I originally switched to use the binary inside of the repository. I get the output there, correctly.

**Comment by markschultz** [comment]
I'm a pandora one subscriber and I was having this exact issue yesterday but somehow today everything seems to work fine.

**Comment by stevekuznetsov** [comment]
Yeah, looks like it's definitely a `requests` or SSL bug, and waiting for whatever cache to be cleared has fixed it for me -- that's also probably why the binary in the repo worked,  different cache, wasn't reusing whatever was breaking things for the `pithos` in the system `$PATH`. Cool.

**Comment by TingPing** [comment]
FYI Pithos doesn't use requests but it is the same error deep within Python/OpenSSL.
