### ISSUE TITLE
Buffering progress in debug output doesn't make much sense

### ISSUE THREAD

**Issue by stevekuznetsov** [pithos/pithos#378]
The output doesn't simply increase over time -- is this due to information we get from the Pandora API? Or is this calculated in Pithos code?

```
DEBUG - pithos:on_gst_buffering:826 - Buffering (19%)
DEBUG - pithos:on_gst_buffering:826 - Buffering (14%)
DEBUG - pithos:on_gst_buffering:826 - Buffering (5%)
DEBUG - pithos:on_gst_buffering:826 - Buffering (0%)
DEBUG - pithos:on_gst_buffering:826 - Buffering (8%)
DEBUG - pithos:on_gst_buffering:826 - Buffering (0%)
DEBUG - pithos:on_gst_buffering:826 - Buffering (8%)
DEBUG - pithos:on_gst_buffering:826 - Buffering (14%)
DEBUG - pithos:on_gst_buffering:826 - Buffering (22%)
DEBUG - pithos:on_gst_buffering:826 - Buffering (25%)
DEBUG - pithos:on_gst_buffering:826 - Buffering (17%)
DEBUG - pithos:on_gst_buffering:826 - Buffering (11%)
DEBUG - pithos:on_gst_buffering:826 - Buffering (2%)
DEBUG - pithos:on_gst_buffering:826 - Buffering (11%)
DEBUG - pithos:on_gst_buffering:826 - Buffering (19%)
DEBUG - pithos:on_gst_buffering:826 - Buffering (28%)
DEBUG - pithos:on_gst_buffering:826 - Buffering (31%)
DEBUG - pithos:on_gst_buffering:826 - Buffering (39%)
DEBUG - pithos:on_gst_buffering:826 - Buffering (48%)
DEBUG - pithos:on_gst_buffering:826 - Buffering (54%)
DEBUG - pithos:on_gst_buffering:826 - Buffering (62%)
DEBUG - pithos:on_gst_buffering:826 - Buffering (71%)
DEBUG - pithos:on_gst_buffering:826 - Buffering (79%)
DEBUG - pithos:on_gst_buffering:826 - Buffering (88%)
DEBUG - pithos:on_gst_buffering:826 - Buffering (96%)
DEBUG - pithos:on_gst_buffering:826 - Buffering (100%)
DEBUG - pithos:on_gst_buffering:837 - Buffer 100%. Song starting
```

**Comment by TingPing** [comment]
This is calculated by GStreamer and I believe it behaves like this because it does not actually know the full length at first. @JasonLG1979 probably knows more about it.

**Comment by JasonLG1979** [comment]
@TingPing is correct in a way. 100% buffered doesn't mean the entire song in buffered it just means enough is buffered to begin/restart playback. Until Gstreamer figures out what the file is (codecs, bitrate and what not) it doesn't know what "enough" is, so it basically guesses. As a result the initial buffering %'s are pretty much useless.

**Comment by TingPing** [comment]
We could just not ever log them if its just noise.

**Comment by JasonLG1979** [comment]
It pretty much is. Also instead of:
```python
if buffer < 100:
    pause_or_whatever()
else:
    play_or_whatever()
```

We could do:
```python
if buffer == 100:
    play_or_whatever()
elif buffer < some_threshold:
    pause_or_whatever()
```

**Comment by JasonLG1979** [comment]
Download buffering is the ideal solution to bad it's horribly buggy...

**Comment by JasonLG1979** [comment]
We could also get rid of the buffering % in the UI. And just make it say buffering. That would also stop the UI thrashing I've ranted on and off about in the past.

**Comment by JasonLG1979** [comment]
@TingPing looking at the buffering messages it seems it also likes to go from 0 to 100% randomly though out the song. Playback doesn't seem to stop but it happens really fast so just may not be noticing it. I'm working on an improvement to player state handling and buffering.

**Comment by stevekuznetsov** [comment]
@JasonLG1979 it does seem like whatever API is used to determine the progress doesn't know about the real size of the song until pretty far into the process -- above in my log it's when `2%` is printed. Past that point, the progress is monotonically increasing as you would expect. If there were a way to determine from GStreamer when it knows about the full size of the song, that would help make the display more useful.

**Comment by JasonLG1979** [comment]
Right now we use playbin which is basically a jack of all trades but master of none. We would have more control if we built our own pipeline.

**Comment by JasonLG1979** [comment]
I'm not entirely sure how it decides the buffer settings, the docs aren't very clear on that. But whatever it's doing it isn't doing a very good job. I may try my hand at building a custom pipeline this weekend.

**Comment by JasonLG1979** [comment]
After playing around with making custom pipelines. I've learned a lot. It seems the best solution is to double buffer. Set uridecodebin's buffer to a reasonable level and put a queue2 element right after it and set it 1/2 of uridecodebin's buffer and set it to not "guess" so it's pretty much based solely on size not time as much as possible. That seems to be the biggest problem the buffers by default try to guess too much to do time based buffering and are just not good at all at guessing.

Here's a Gist with a simple custom pipeline for double buffering a network stream. In this example in the buffering function I ignore uridecodebin's buffer altogether and only respond to the 2nd buffer. It seems more reliable. I just need to figure out if I can insert a queue into playbin or if I have to build a custom pipeline to enable something like this in Pithos?

https://gist.github.com/JasonLG1979/3816cfb62d55f764274f0b018d7f0602

**Comment by JasonLG1979** [comment]
@stevekuznetsov and @TingPing Give this a try it should be an improvement as far as buffering.
https://github.com/JasonLG1979/pithos/tree/double-buffer-player

**Comment by JasonLG1979** [comment]
@stevekuznetsov and @TingPing give this a try:
https://github.com/JasonLG1979/pithos/tree/tame-the-buffer

It works like a charm for me. Drastic improvement.

**Comment by stevekuznetsov** [comment]
The `tame-the-buffer` branch works great for me!

**Comment by JasonLG1979** [comment]
> The tame-the-buffer branch works great for me!
It's not perfect but it makes for a lot less rebuffering, and debug spamming.

**Comment by JasonLG1979** [comment]
I've got a lot more changes in mind to improve the situation but as per @TingPing though I have to split out the Gstreamer code from the main class 1st. Right now the player logic, the main core logic and UI logic is all in the same class. They need separated and abstracted out.

**Comment by TingPing** [comment]
@JasonLG1979 If you really want this to land first we can do that, I just thought it makes sense if you plan on refactoring to save changes until after.

**Comment by JasonLG1979** [comment]
That branch is not a complete solution. Ideally during buffering the user should not actually be able to change the player state. Pithos should go though all the motions of a state change (emitting signals, changing icons, updating the UI and what not) but the actual Gstreamer pipeline should not change state until buffering completes only then should the pipeline actually go to the appropriate state. It's all in that last PR I closed. I could revert the stuff about download buffering and reopen it?

**Comment by TingPing** [comment]
> It's all in that last PR I closed. I could revert the stuff about download buffering and reopen it?

Sure

**Comment by JasonLG1979** [comment]
There I reset back to before the downloadbuffer stuff on that branch. You can force buffering and test what I'm talking about as far as honoring buffering and the user's desired state by starting a song and disconnecting your network. Pithos should go to buffering. While buffering you can from Play to Pause and back again however many times you want and Pithos goes though all the motions. Then reconnect to your network and after a bit Pithos will buffer up and go to whatever state you left it in(playing or paused).

https://github.com/JasonLG1979/pithos/tree/Gst-Changes

**Comment by TingPing** [comment]
Looks like you should have reopened the PR first then force pushed.

**Comment by JasonLG1979** [comment]
I noticed that. I looked at the closed PR after I reset and it still show the commits I wiped out. I need to rebase anyway. You merged that other PR for validating songs so I need to see how that works together in self.play.

**Comment by JasonLG1979** [comment]
I'll also split out that commit about duration stuff. It's not really directly related. To the buffering behavior.

**Comment by JasonLG1979** [comment]
Before I put in a PR @TingPing give this a look over and test and tell me what you think.
https://github.com/JasonLG1979/pithos/tree/improved-buffering-behavior

**Comment by TingPing** [comment]
@JasonLG1979 I suppose it is fine, few comments but I'll save that for the PR.

**Comment by JasonLG1979** [comment]
OK. I'm not done just yet. When I am I'll put in a PR.

**Comment by JasonLG1979** [comment]
We'll see if it passes your bot. How exactly do you run flake locally?

**Comment by TingPing** [comment]
Install flake8, run `flake8` in the directory.

**Comment by JasonLG1979** [comment]
Yep I figured it out. Man that's a lot of output,lol!!!

**Comment by TingPing** [comment]
Happens when you ignore style for many years. I fixed a few files but didn't want to touch `pithos.py` to interfere with you.

**Comment by JasonLG1979** [comment]
I was going to fix GioNotify.py real quick since it's mostly trivial stuff and I wrote it. I can do that in about 5 min and put in a PR?

**Comment by JasonLG1979** [comment]
Closed with https://github.com/pithos/pithos/commit/b7258a350e2b9d79f73672397f62e09dfcf59ddd and https://github.com/pithos/pithos/commit/3f73906fe703b59152c5aca1e570286dcd1683a3
