### ISSUE TITLE
First use of keyring may fail

### ISSUE THREAD

**Issue by ShapeShifter499** [pithos/pithos#380]
I have a issue on my system where when I start Pithos it will have me log in with my Pandora account then ask me for a password to my keychain. This seems wrong, if the Pandora account password is stored to the keychain then shouldn't Pithos just ask me for my keychain password and nothing else?

System
Pithos version 1.2.1
Arch Linux 64bit
XFCE4
Linux Y40-80 4.8.13-1-ARCH #1 SMP PREEMPT Fri Dec 9 07:24:34 CET 2016 x86_64 GNU/Linux

**Comment by JasonLG1979** [comment]
If you have it set so that you don't have to enter a password to login your desktop then your keyring is still locked. The 1st time you try to access your keyring you'll have to unlock it.

**Comment by TingPing** [comment]
Seems like the problem is that it doesn't ask on the first time. I'm not really sure there is much Pithos would be at fault for that but rather `gnome-keyring` probably.

**Comment by JasonLG1979** [comment]
> Seems like the problem is that it doesn't ask on the first time. I'm not really sure there is much Pithos would be at fault for that but rather gnome-keyring probably.

Locked means that you can't store anything in it either. Like I said if you set up your session to be password-less Pithos would ask for the password and then try to store it in the keyring but it's still locked so it's asking for the keychain password.

**Comment by JasonLG1979** [comment]
In any event it's not a Pithos problem.

**Comment by TingPing** [comment]
Right but that is the problem; Pithos isn't prompting for the keychain password and it just opens with no password. A random guess is that on the first call the keyring isn't running on xfce so it autostarts and Pithos continues.

**Comment by JasonLG1979** [comment]
> Right but that is the problem; Pithos isn't prompting for the keychain password and it just opens with no password. A random guess is that on the first call the keyring isn't running on xfce so it autostarts and Pithos continues.

So we need to manually make sure the keychain is unlocked Pithos starts then?

**Comment by mattlyons0** [comment]
Below is a description of the problem in older versions (I was having this problem using pithos from the AUR). I can confirm building from the git repo this problem is solved and the keyring is properly requested to be unlocked upon startup.

I'm having this problem too. If my keyring is locked when I open Pithos it brings up the login screen (without asking for the password to unlock it) which has no saved preferences. Then once I hit Apply (from the preferences popup) it asks for the password to unlock my keyring. 

However if the keyring is unlocked it works as expected (remembers previous login).

**Comment by TingPing** [comment]
I still encounter the issue on master.

**Comment by TingPing** [comment]
I use autologin on one machine so the keyring is not unlocked on login.

**Comment by nhumrich** [comment]
> In any event it's not a Pithos problem.
I disagree. Every program I know of that uses the keyring will prompt me if the keyring is unlocked on start-up or at least before I get to a password input field. The problem is if your keyring is locked, pithos asks for your pandora login instead of reading from the keyring. But once you enter the login, you have to unlock the keyring anyways.

**Comment by JasonLG1979** [comment]
> I disagree. Every program I know of that uses the keyring will prompt me if the keyring is unlocked on start-up or at least before I get to a password input field. The problem is if your keyring is locked, pithos asks for your pandora login instead of reading from the keyring. But once you enter the login, you have to unlock the keyring anyways.

I stand corrected. I just set my account to autologin and it does exactly as you said. @TingPing we need to figure out a way to see if the keyring is locked and unlock it if it is. A quick look at https://lazka.github.io/pgi-docs/#Secret-1 doesn't show a simple way to do that.

**Comment by JasonLG1979** [comment]
A Hacky workaround would be to try to set a dummy password before we try to retrieve the real password. That would cause keyring to show the unlock prompt if it were locked.

**Comment by JasonLG1979** [comment]
Again very hacky, I'm sure there's got to be a proper way to do it. But this works:

```python
_DUMMY_SCHEMA = Secret.Schema.new('io.github.Pithos.Dummy', Secret.SchemaFlags.NONE,
                                  {"dummy": Secret.SchemaAttributeType.STRING})

_ACCOUNT_SCHEMA = Secret.Schema.new('io.github.Pithos.Account', Secret.SchemaFlags.NONE,
                                    {"email": Secret.SchemaAttributeType.STRING})


# TODO: Async
def get_account_password(email):
    Secret.password_store_sync(_DUMMY_SCHEMA, {"dummy": "dummy"}, Secret.COLLECTION_DEFAULT,
                               "Dummy", "dummy", None)
    return Secret.password_lookup_sync(_ACCOUNT_SCHEMA, {"email": email}, None) or ''
```

**Comment by TingPing** [comment]
@JasonLG1979 Mind testing a theory for me. Try using the `async` APIs for lookup, maybe the secret service avoids blocking too long on the `sync` one so gives up quickly.

**Comment by JasonLG1979** [comment]
The docs say that look_sync may block indefinitely. I'll try it out but I don't think that's the problem. I don't think it's giving up. If the keyring is locked you would expect the look up to return None because what you're looking up doesn't exist as far a secret is concerned.

**Comment by JasonLG1979** [comment]
As far as sync vs async I think when we figure out how to make sure the keyring is unlocked we should use a sync method. That way it keeps the Pithos window from apearing until after the unlock prompt. We don't gain anything from an async method. Nothing is happening yet to worry about blocking. After that we can go all async.

**Comment by JasonLG1979** [comment]
I can work on making what we have all async. Shouldn't be too hard. It's just a matter of breaking up the function/methods that get and save the password into call callback.

**Comment by TingPing** [comment]
> If the keyring is locked you would expect the look up to return None because what you're looking up doesn't exist as far a secret is concerned.

I'd expect that it blocks indefinitely starting the keyring service, asking for your keyring password, then finally returning the password.

**Comment by JasonLG1979** [comment]
> I'd expect that it blocks indefinitely starting the keyring service, asking for your keyring password, then finally returning the password.

I see your point. It's kinda weird that looking up a password doesn't try to unlock the keyring but saving one does?

**Comment by JasonLG1979** [comment]
> Mind testing a theory for me. Try using the async APIs for lookup, maybe the secret service avoids blocking too long on the sync one so gives up quickly.

Nope. an async lookup returns None also if the keyring is locked.

**Comment by JasonLG1979** [comment]
Well it's kinda convoluted IMHO but this <i>seems</i> to be the right way to unlock the keyring if it's locked

```python
_SERVICE = Secret.Service.get_sync(
    Secret.ServiceFlags.NONE,
    None,
)

_DEFAULT_COLLECTION = Secret.Collection.for_alias_sync(
    _SERVICE,
    'default',
    Secret.CollectionFlags.NONE,
    None,
)

if _DEFAULT_COLLECTION.get_locked():
    _SERVICE.unlock_sync([_DEFAULT_COLLECTION,], None)
```

@TingPing what do you think? And where do you want it?

**Comment by JasonLG1979** [comment]
for anyone who wants to test it out. This should do the trick. https://github.com/JasonLG1979/pithos/tree/unlock-keyring

**Comment by JasonLG1979** [comment]
@TingPing could you take a look at that branch and let me know what you think.

The behavior is this:

If the default keyring is unlocked it gets and saves the password from the default keyring. (just like before)

If the default keyring is locked it will try to unlock it the 1st time we try to find a password. If the unlock is unsuccessful(the user clicks cancel at the prompt) from then on we use the session collection. Passwords will not survive past the current session and the user will get no more prompts to unlock the keyring.

**Comment by JasonLG1979** [comment]
I've also added a checkbox to the prefs to disable the unlocking attempt if the user wants. That way a user could check that box and wouldn't be bugged with the dialogs if they don't want. If the attempt is disabled if the default keyring is locked Pithos will just use the session collection with no warnings or attempts to unlock the keyring. If the default keyring is not locked Pithos will use it. I'm not sure about the checkbox or where to put it though?

**Comment by TingPing** [comment]
That makes no sense at all, it isn't optional.

**Comment by JasonLG1979** [comment]
> That makes no sense at all, it isn't optional.

It is optional. If the keyring is not unlocked secret looks in the session collection.

**Comment by JasonLG1979** [comment]
The session collection as the name implies only survives for that session. Currently we don't try to unlock the default collection so if it's not unlocked we look in the session collection. That's why the password doesn't show up. You have Secret.COLLECTION_DEFAULT set in your set_password method that's why it doesn't try to unlock the password until after the user enters it.

**Comment by JasonLG1979** [comment]
Checking the option will just automatically use the session collection if the default collection is not unlocked. Silencing and dialogs.

**Comment by TingPing** [comment]
So why does the second try prompt to unlock it?

**Comment by JasonLG1979** [comment]
```python
    Secret.password_store_sync(_ACCOUNT_SCHEMA, attrs, Secret.COLLECTION_DEFAULT,
                               "Pandora Account", password, None)

```

Secret.COLLECTION_DEFAULT makes it try to store the password in the default collection.

**Comment by JasonLG1979** [comment]
So basically what we're doing now if the keyring is not unlocked is checking the session collection. (The password will never be in the session collection the 1st time) and then trying to save it in the default collection.

**Comment by JasonLG1979** [comment]
@TingPing kinda related but checkout the latest commit to the branch. Async password handling(where it makes sense)
