### ISSUE TITLE
Is gst-plugins-bad really needed?

### ISSUE THREAD

**Issue by Stebalien** [pithos/pithos#381]
So, I just uninstalled them (to avoid some nasty security bugs) and haven't noticed any issues (Pandora One subscriber, high quality). Is this dependency really necessary? They're called "bad" for a reason (poor code quality) so I'd like to be able to remove them as a dependency from the arch package.

**Comment by TingPing** [comment]
So for low/normal quality we require an aacplus decoder and for high we require an mp3 decoder.

For the former you can get this via:

- gst-plugins-bad + faad
- gst-libav + ffmpeg

For the latter:

- gst-plugins-bad + mpg123
- gst-plugins-libav + ffmpeg

There *might* be more options as gstreamer doesn't document every possible codec very well but those are the ones I know of.

**Comment by Stebalien** [comment]
Got it. Do you think it would be reasonable for me to swap out the
gst-plugins-bad dep for gst-libav (which depends on ffmpeg) or is there
some reason to keep it as it is? On Arch, both Firefox and Chromium
depend on ffmpeg so this would actually be reducing the number of
packages on many user's systems.

As far as I know, ffmpeg is a bit better maintained than many of the
plugins in gst-plugins-bad. It certainly doesn't pull in an old, buggy
video a game emulator which has been the source of these recent security
problems.

**Comment by TingPing** [comment]
It is a shame Pacman doesn't have boolean dependencies nor does Arch add provides to the gstreamer packages. Given those limitations I think it is fairly reasonable to just depend upon gst-libav.

**Comment by Stebalien** [comment]
Features? Arch? More seriously, the correct way to do this in arch would be to have all gst plugin libraries provide `gst-format-foo` (`gst-format-mp3`, `gst-format-acc`, ...) but that's a *lot* of work.

---

Also, while we're at it, why `gst-plugins-good` (when you have time)?

**Comment by TingPing** [comment]
> the correct way to do this in arch would be to have all gst plugin libraries provide gst-format-foo (gst-format-mp3, gst-format-aac, ...) but that's a lot of work.

Fedora does this on the RPMs `gstreamer1(decoder-audio/ogg)`, it is a shame how Arch doesn't even use the full features Pacman does have.

> Also, while we're at it, why gst-plugins-good (when you have time, out of curiosity)?

I updated my original comment (Never rely on emails for github notifications). I believe good is required for HTTP support.

**Comment by Stebalien** [comment]
Thanks.
