### ISSUE TITLE
Missing gi.require_version('Gtk', '3.0')

### ISSUE THREAD

**Issue by eosrei** [pithos/pithos#382]
I'm running the Ubuntu 16.04 repo version of Pithos 1.1.1. It crashes with the following:

```
$ pithos
/usr/share/pithos/pithos/pithos.py:36: PyGIWarning: GstPbutils was imported without specifying a version first. Use gi.require_version('GstPbutils', '1.0') before import to ensure that the right version gets loaded.
  from gi.repository import Gst, GstPbutils, GObject, Gtk, Gdk, Pango, GdkPixbuf, Gio, GLib
/usr/share/pithos/pithos/pithos.py:36: PyGIWarning: Gtk was imported without specifying a version first. Use gi.require_version('Gtk', '3.0') before import to ensure that the right version gets loaded.
  from gi.repository import Gst, GstPbutils, GObject, Gtk, Gdk, Pango, GdkPixbuf, Gio, GLib
```

`gi.require_version('GstPbutils', '1.0')` is in HEAD, but `gi.require_version('Gtk', '3.0')` is not. Adding both to my 1.1.1 install makes Pithos work.

Adding `gi.require_version('Gtk', '3.0')` fixes

**Comment by JasonLG1979** [comment]
We don't maintain the Ubuntu repo package. Tell the maintainer of the package. That was fixed with https://github.com/pithos/pithos/commit/caaeb1fed7ae33732c62f844aa0a7050c390a180

**Comment by eosrei** [comment]
I know you don't maintain the repo package. Sorry for the confusion. I am reporting this against HEAD.

```
gi.require_version('Gtk', '3.0')
```

is not in `/pithos/pithos.py`: https://github.com/pithos/pithos/blob/da95b737758b6a10fc41d16f66105814d2b4fddf/pithos/pithos.py#L33-L34

**Comment by eosrei** [comment]
https://github.com/pithos/pithos/commit/caaeb1fed7ae33732c62f844aa0a7050c390a180 only added `gi.require_version('GstPbutils', '1.0')`.

**Comment by JasonLG1979** [comment]
It fixes the warning messages.

**Comment by eosrei** [comment]
I see `gi.require_version('GstPbutils', '1.0')` is required to fix the crash. `gi.require_version('Gtk', '3.0')` is only a warning.

**Comment by JasonLG1979** [comment]
Generally speaking Ubuntu users should use the ppa version of Pithos. By design you'll pretty much always get an unmaintained old version from the default repos.

**Comment by eosrei** [comment]
I maintain a PPA also, I know the drill. :) I'll run the PPA version. Thanks for your fast reply!
