### ISSUE TITLE
Show Pithos icon in GNOME sound settings.

### ISSUE THREAD

**Issue by JasonLG1979** [pithos/pithos#389]
To make the Pithos icon show up in the GNOME sound menu we need to set the PULSE_PROP_application.icon_name prop.

 ![screenshot from 2017-01-08 13-48-14](https://cloud.githubusercontent.com/assets/6667703/21753037/28ac3e3a-d5a9-11e6-8cd0-95682ca0ce51.png)

```python
os.environ['PULSE_PROP_application.icon_name'] = 'io.github.Pithos'
```

But I'd also like to set a couple other application props including version. I was wondering if the pulse props shouldn't be moved to application.py?

I was thinking inside do_startup:
```python
    def do_startup(self):
        os.environ['PULSE_PROP_application.name'] = 'Pithos'
        os.environ['PULSE_PROP_application.version'] = self.version
        os.environ['PULSE_PROP_application.icon_name'] = 'io.github.Pithos'
        os.environ['PULSE_PROP_media.role'] = 'music'
        ....
```

What do you think @TingPing?

Update: We don't even need os.environ. The same thing can be done in GLib with:

```python
        GLib.setenv('PULSE_PROP_application.name', 'Pithos', True)
        GLib.setenv('PULSE_PROP_application.version', self.version, True)
        GLib.setenv('PULSE_PROP_application.icon_name', 'io.github.Pithos', True)
        GLib.setenv('PULSE_PROP_media.role', 'music', True)
```

Still need to know where to put it though? From the docs I'd say:

```python

    def __init__(self, version=''):
        super().__init__(application_id='io.github.Pithos',
                         flags=Gio.ApplicationFlags.HANDLES_COMMAND_LINE)

        GLib.setenv('PULSE_PROP_application.name', 'Pithos', True)
        GLib.setenv('PULSE_PROP_application.version', version, True)
        GLib.setenv('PULSE_PROP_application.icon_name', 'io.github.Pithos', True)
        GLib.setenv('PULSE_PROP_media.role', 'music', True)
        ...
```

**Comment by TingPing** [comment]
`os.environ` in `do_startup` is fine. Can this not be set via GStreamer somehow?

**Comment by JasonLG1979** [comment]
It could I suppose if we listened to the element setup signal in playbin:
https://gstreamer.freedesktop.org/data/doc/gstreamer/head/gst-plugins-base-plugins/html/gst-plugins-base-plugins-playbin.html#GstPlayBin-element-setup

And then set the props for the pulsesink if it popped up:
https://gstreamer.freedesktop.org/data/doc/gstreamer/head/gst-plugins-good-plugins/html/gst-plugins-good-plugins-pulsesink.html#GstPulseSink--stream-properties

But then we'd be setting the property over and over again since playbin dynamically builds a new pipeline every song.

It seems a lot less convoluted to just do this:

```python
    def __init__(self, version=''):
        super().__init__(application_id='io.github.Pithos',
                         flags=Gio.ApplicationFlags.HANDLES_COMMAND_LINE)

        GLib.setenv('PULSE_PROP_application.name', 'Pithos', True)
        GLib.setenv('PULSE_PROP_application.version', version, True)
        GLib.setenv('PULSE_PROP_application.icon_name', 'io.github.Pithos', True)
        GLib.setenv('PULSE_PROP_media.role', 'music', True)
       ...
```

That's how Lollypop does it.

**Comment by TingPing** [comment]
Ok, that is fine then.

**Comment by JasonLG1979** [comment]
Done in https://github.com/pithos/pithos/commit/9d517fb6257c1c2316cd1f22a3a62180da65ad17

**Comment by TingPing** [comment]
Also btw the icon and name worked already for me.

**Comment by JasonLG1979** [comment]
It didn't work for me in Fedora 25 GNOME 3.22.2. I got the broken image icon.

**Comment by JasonLG1979** [comment]
![screenshot from 2017-01-08 22-12-29](https://cloud.githubusercontent.com/assets/6667703/21757108/a95481aa-d5ef-11e6-8a82-a2343abad158.png)

**Comment by JasonLG1979** [comment]
The name still worked though. I just included the name and version because it seemed more complete to include them.

**Comment by TingPing** [comment]
Very odd, it indeed didn't show on my Fedora install but did on my Arch one.

**Comment by JasonLG1979** [comment]
Who knows? What version of GNOME are you running on Arch? Arch tends to be more cutting edge than Fedora maybe it was changed/fixed upstream and it hasn't hit Fedora yet?

**Comment by TingPing** [comment]
gnome-control-center is 3.22.1 which I imagine is the main version that matters for this.

**Comment by JasonLG1979** [comment]
Same here:
```bash
Name        : control-center
Arch        : x86_64
Epoch       : 1
Version     : 3.22.1
Release     : 2.fc25
Size        : 18 M
Repo        : @System
From repo   : koji-override-1
Summary     : Utilities to configure the GNOME desktop
URL         : http://www.gnome.org
License     : GPLv2+ and GFDL
Description : This package contains configuration utilities for the GNOME
            : desktop, which allow to configure accessibility options, desktop
            : fonts, keyboard and mouse properties, sound setup, desktop theme
            : and background, user interface properties, screen resolution, and
            : other settings.
```

**Comment by JasonLG1979** [comment]
Oh, well. I guess this covers our bases than. It works on both distros now. I haven't tested it on *buntu but I imagine the icon shows up now if it didn't before?

**Comment by TingPing** [comment]
Yup works fine now.
