### ISSUE TITLE
Manually setting buffer size in playbin.

### ISSUE THREAD

**Issue by JasonLG1979** [pithos/pithos#393]
My last PR goes a long way to fixing buffering behavior(by "fixing" I mean workaround Gstreamer's crappy buffering) But it doesn't totally fix it. Gstreamer is still really, really bad at guessing the proper buffer size.

Playbin has two props that we can use to keep Gst from guessing, "buffer-size" and "buffer-duration" I've had really good results with setting the buffer to about 5 secs:
```python
self.player.set_property("buffer-duration", 5 * Gst.SECOND)
# About 5 secs of audio. Assuming my math is correct?
self.player.set_property("buffer-size", int(self.current_song.bitrate) * 625)
```

But what works for me may not work for others. I think a user setting to adjust the buffer size in secs(with a reasonable range) could go along way to stop rebuffering.

Your thoughts @TingPing?

 https://github.com/JasonLG1979/pithos/tree/buffer-size

**Comment by TingPing** [comment]
I have no strong opinion on it really. Minor style thing is I would prefer `self.player.props.buffer_duration = 5 * Gst.Second`

**Comment by TingPing** [comment]
Also what is the magic value of `625`?

**Comment by JasonLG1979** [comment]
buffer-size is in bytes. bitrate * 625 gives us a buffer-size of about 5 secs. Assuming 125 bytes per kbit. That's where I'm not sure kbit/s is data transfer so kilo = 1000 but the buffer size is in bytes so that's storage kilo = 1024.

**Comment by JasonLG1979** [comment]
If it were a user setting it would be bitrate * 125 * user_buffer-time.

**Comment by JasonLG1979** [comment]
The docs are not clear what the defaults actually are. The queue2 element is the only element that actually lists a defaults to a similar props "max-size-bytes" which is 2097152 bytes or 16MB and "max-size-time" which is 2000000000, I assume 2 secs. If I had to guess the props get propagated down the pipeline to be use or not depending on the element. In our case it would be used by the queue2 element if download buffering were enabled it would be the downloadbuffer element.

From what I under buffer is 100%  when either max-size-bytes, max-size-buffers(which we don't have direct access to) or max-size-time is met.

I think the issues we're having are because Gstreamer is having trouble calculating the proper buffer size because it's racing between the props. 16MB is way, way to big a buffer for a lossy audio network stream and 2 secs is not enough sometimes to smooth out network jitter and what not.

Setting buffer-size and buffer-duration seems to stop the guesswork on Gstreamer's part.

**Comment by JasonLG1979** [comment]
On a side note if I were to add a user setting it would under Advanced Settings in the prefs ui. My question is, is the audio quality really an "Advanced Setting"? Shouldn't it just be under the Account settings?

**Comment by TingPing** [comment]
I really don't like exposing such implementation details to users.

**Comment by JasonLG1979** [comment]
> I really don't like exposing such implementation details to users.

A few players expose buffer size, Clementine comes to mind. It not really uncommon. Like I said users would benefit from changing the buffer setting from the defaults as they don't seem realistic at all, but a one-size-fits-all is not a good idea either, because obviously not everyone has the same network. I for example have 150Mb internet. I don't notice much of a difference between a 5 and 60 sec buffer time. But someone with a 1.5Mb connection sure would notice a 60 sec buffer time since initial buffering would not complete until 60 secs of audio was buffered.

**Comment by JasonLG1979** [comment]
I'm playing with a working example where the default is 5 secs with a possible range of 2 - 20 secs.

**Comment by JasonLG1979** [comment]
Basically a user would just bump it up a little if they noticed rebuffering during playback until playback smoothed out.

**Comment by JasonLG1979** [comment]
I'm going to close this it's a dead end.
