### ISSUE TITLE
pausing and replaying results in chopped up noisy audio

### ISSUE THREAD

**Issue by alevis** [pithos/pithos#399]
ubuntu 16.04

**Comment by JasonLG1979** [comment]
What version of Pithos?

**Comment by alevis** [comment]
Pithos 1.1.1

**Comment by JasonLG1979** [comment]
From the stock Ubuntu repo? You shouldn't use that, it's old and contains unfixed bugs.(We don't maintain it) You should at least be using the latest stable version from the PPA, or if you're brave the latest git. Upgrade to the latest stable and see if that helps.

**Comment by JasonLG1979** [comment]
```
sudo add-apt-repository ppa:pithos/ppa
sudo apt-get update
sudo apt-get install --install-recommends pithos
```

**Comment by alevis** [comment]
Just finished installing
No problems!
Thank you
