### ISSUE TITLE
Arch/Manjaro update requires Python 3.6

### ISSUE THREAD

**Issue by joaoherberto** [pithos/pithos#401]
Latest Arch update to 1.2.1-3 has a dependency of Python 3.6, but Python 3.5 is the current version, Pithos cannot update.

**Comment by JasonLG1979** [comment]
This is not a Pithos bug. (although @TingPing is listed as a co-maintainer) From what I understand from the comments here:
https://aur.archlinux.org/packages/pithos/

Python 3.6 is available from an up to date mirror. So you may either need to wait for your mirror to update or change mirrors.

I'm not an Arch/Manjaro user so I'm not sure why 3.6 is listed as a requirement as it runs just fine for me in Fedora 25 with Python 3.5.2.

**Comment by joaoherberto** [comment]
Sounds like a timing issue... Will wait a few days and see if Python gets
upgraded.

Thanks.

**Comment by JasonLG1979** [comment]
Maybe @TingPing can shed some light on why 3.6 is listed as a requirement? Does Pithos actually require python 3.6 or is it a packaging detail/issue in the AUR?

**Comment by joaoherberto** [comment]
It looks like just an AUR package requirement to me, where 1.2.1-3 requires
Python 3.6 I don't know.

I just wanted to pass on the issue in case there was one, git was the only
site listed on the AUR.

**Comment by JasonLG1979** [comment]
Updating to 1.2.1-3 from  1.2.1-x will get you nothing as far as bug fixes or features in Pithos. All 1.2.1-x versions are based on the 1.2.1 release.

**Comment by TingPing** [comment]
You can just remove the version. The package maintainer added it to force people to rebuild since Arch got the 3.6 update. Since Manjaro is a 'fork' that it more outdated it will get it at a later date.
