### ISSUE TITLE
Async plugin loading.

### ISSUE THREAD

**Issue by JasonLG1979** [pithos/pithos#403]
@TingPing we have a few plugins that can be made to load async. I've got this branch with the beginnings of it:

https://github.com/JasonLG1979/pithos/tree/async-plugin-loading

It wouldn't change how sync plugins load it would just allow us to make whatever plugins that can load async async. Do you want me to put in a PR for the changes above and separate PR's porting the plugins that can do async one by one or do you want one big PR with everything async at once?

**Comment by TingPing** [comment]
Lets do the API first, then the plugins. How would a plugin use the API you added, it doens't seem like enough to be complete?

**Comment by JasonLG1979** [comment]
It doesn't take much. Just a method for async plugins to call when they're done with their setup.

**Comment by JasonLG1979** [comment]
I already ported the notifications. It seems to do the trick

**Comment by TingPing** [comment]
Mind pushing that to another branch?

**Comment by JasonLG1979** [comment]
I will tonight when I get home. I still need to identify exactly where GioNotify async_init can fail. Basically the idea is that if a async plugin should fail it should send a error message to on_async_prepared. If it doesn't fail it should call on_async_prepared with no args to let us know it's done doing it's thing.  If no error is returned on_async_enabled is called.

**Comment by JasonLG1979** [comment]
Really to make things uniform enable should call prepare and once a plugin has done it's thing sync or async it should call on_prepared. And at anytime anything goes wrong it should call on_error to disable the plugin. We could also do pre-prepare checks for obvious know reasons a plugin would fail like it depends on certain versions of things or it depends on stuff like pylast for example. We can check to see if a module exists without actually trying to import it. That way a user would know what plugins actually work before trying to enable them.

**Comment by JasonLG1979** [comment]
I'm not so sure it's a good idea, but we can capture all unhanded exceptions that happen in the plugin and disable the plugin without crashing Pithos with(there's prob a better way to do this if it's even a good idea in the 1st place?... metaclass?):

```python
import logging
import glob
import os
import traceback
from gi.repository import Gio

def catch_exceptions(func):
    def _decorator(self, *args, **kwargs):
        try:
            func(self, *args, **kwargs)
        except Exception as e:
            self.error = 'Unhandled exception'
            self.settings['enabled'] = False
            self.enabled = False
            logging.warning('Unhandled exception in {} plugin: {}'.format(self.name, traceback.format_exc()))         
    return _decorator

def for_all_methods(decorator):
    def _decorator(cls):
        for attr in cls.__dict__:
            if callable(getattr(cls, attr)):
                setattr(cls, attr, decorator(getattr(cls, attr)))
        return cls
    return _decorator

@for_all_methods(catch_exceptions)
class PithosPlugin:
...
```

**Comment by TingPing** [comment]
Well an exception shouldn't be *"crashing"* anything in the first place.

**Comment by JasonLG1979** [comment]
Ok I mean make it function in a way you would not expect... ;P

**Comment by JasonLG1979** [comment]
Like I said I'm not even sure it's a good idea but that would cleanly disable the plugin on a unhandled exception so the plugin wouldn't just sit there and puke 25 error messages,lol
