### ISSUE TITLE
Cannot quit pithos - need to find process and kill

### ISSUE THREAD

**Issue by dkogias** [pithos/pithos#404]
This is a recent change in behavior, in the last few days, long after I upgraded to Fedora 25, so something in an F25 update must have triggered this.

Pithos is installed from rpmfusion, 1.2.1-1.fc25

Bringing up the app window and selecting `quit` from the menu doesn't kill the process, and music keeps playing. I have to manually kill the process from the terminal.

At the same time (but I don't know if this is related), pithos no longer pauses when I lock the screen.  Again it used to, until recently.

**Comment by TingPing** [comment]
What plugins do you have enabled in Preferences? Do you see any errors running `pithos -v` from the terminal?

**Comment by dkogias** [comment]
Re: screenlock pause: The corresponding plugin was somehow switched to "off".  I re-enabled and all is well on that front.

**Comment by dkogias** [comment]
So, plugins enabled:
- Mediakeys
- Mpris
- Screensaver pause
- Notification icon

**Comment by dkogias** [comment]
re: unable to quit:  It works only with the originally-displayed window:
- Start pithos (super, start typing "pithos", Enter)
- Starts playing
- Close window
- Continues playing
- "Start" pithos again to get the window
  - Either using Super, or by right-clicking in the MPRIS entry in the system menu ([Media played indicator](https://extensions.gnome.org/extension/55/media-player-indicator/) extension active).
  - Pithos window menu now looks wrong.  Only `quit` available, icon is generic, not pithos
- Select `quit`, nothing happens, have to kill manually.

**Comment by dkogias** [comment]
Substituting first step above (original start) with:
```
$ pithos -v
INFO - application:do_activate:108 - Pithos 1.2.1
INFO - pithos:init_core:216 - Created temporary directory /tmp/pithos-qzxy435f
INFO - plugin:enable:39 - Enabling module mediakeys
INFO - mediakeys:bind_dbus:44 - Got session bus
INFO - mediakeys:bind_dbus:90 - Bound media keys with DBUS (org.gnome.SettingsDaemon.MediaKeys)
INFO - plugin:enable:39 - Enabling module screensaver_pause
INFO - plugin:enable:39 - Enabling module mpris
INFO - plugin:enable:39 - Enabling module notification_icon
INFO - screensaver_pause:on_got_bus:43 - Got session bus
INFO - _dbus_service:on_name_acquired:36 - Got bus name: net.kevinmehall.Pithos
INFO - _mpris:on_name_acquired:54 - Got bus name: org.mpris.MediaPlayer2.pithos
INFO - pandora:connect:228 - Time offset is 1.666191816329956
INFO - pithos:pandora_ready:457 - Pandora connected
INFO - pithos:process_stations:512 - Restoring saved station: id = 3307023096839875359
INFO - pithos:station_changed:743 - Selecting station 3307023096839875359; total = 5
INFO - pandora:get_playlist:326 - pandora: Get Playlist
INFO - pithos:start_song:554 - Starting song: index = 0
INFO - pandora:audioUrl:436 - Using audio quality highQuality: 128 mp3
INFO - pandora:audioUrl:436 - Using audio quality highQuality: 128 mp3
INFO - pithos:check_if_song_is_ad:812 - Not an Ad..
INFO - pandora:audioUrl:436 - Using audio quality highQuality: 128 mp3
INFO - pithos:art_callback:664 - Downloaded album art for 0
INFO - pandora:audioUrl:436 - Using audio quality highQuality: 128 mp3
INFO - pithos:art_callback:664 - Downloaded album art for 1
INFO - pithos:art_callback:664 - Downloaded album art for 2
INFO - pithos:art_callback:664 - Downloaded album art for 3
```
no behavior change

**Comment by JasonLG1979** [comment]
Are you using Wayland? The default session in GNOME on Fedora 25 uses Wayland not X. I remember a bit of weirdness when using Wayland. I'm on Fedora 25. I'll poke around and see what the deal is.

**Comment by TingPing** [comment]
Yea that is probably the problem, the notification icon plugin can't work on Wayland but we still allow it to load and hide the window. That doesn't explain the icon/menu issues though.

**Comment by dkogias** [comment]
Affirmative on Wayland.  [This](https://bodhi.fedoraproject.org/updates/FEDORA-2017-84b0233854) hit stable a few days ago, smells vaguely relevant.

**Comment by dkogias** [comment]
Turning off the notification icon plugin "fixes" the no-quit problem, but now closing the window exits the app.  Sigh, another Wayland them's-the-breaks?

**Comment by TingPing** [comment]
Just minimize the Window for now. Somebody could make a gnome shell extension that behaves similar to a tray or such.

**Comment by dkogias** [comment]
Will do, for now.  Still I can swear that window hiding worked, on F25 under Wayland, till very very recently.

**Comment by JasonLG1979** [comment]
Yep. for some reason GNOME/Wayland seems to loose track of the window state? I get the same thing.


> Somebody could make a gnome shell extension that behaves similar to a tray or such.

Would that solve the problem? You're still hiding the window that seems to be the reason it's loosing track.

But really the built in MPRIS controls are capable of raising Pithos. It would not be hard to ad an option in the MPRIS plugin that allows GNOME 3.20+ users the ability to close the window without quitting.

**Comment by JasonLG1979** [comment]
The built in MPRIS controls basically obsolete the tray icon.

**Comment by TingPing** [comment]
> Would that solve the problem? You're still hiding the window that seems to be the reason it's loosing track.

Yea that part might actually be a Gnome bug.

**Comment by JasonLG1979** [comment]
There's also the fact that the MPRIS controls(actually most MPRIS controls for that matter) doesn't actually call the provided raise method. They "activate" the app which actually calls present. They do this to make sure the player in question appears on primary/current screen/virtual desktop. If we want anything done when they call us(keeping track of position, which also does not work in Wayland last time I checked) we need to override present.

**Comment by JasonLG1979** [comment]
> Yea that part might actually be a Gnome bug.

Yes sir. Putting:
```python
self.connect("delete-event", lambda *ignore: self.hide_on_delete())
```
In pithos.py exhibits the same behavior.

> Somebody could make a gnome shell extension that behaves similar to a tray or such. 

Oh, and I almost forgot, I happen to have push privileges to  https://github.com/eonpatapon/gnome-shell-extensions-mediaplayer so it's go time on Pithos integration,lol!!!

**Comment by TuxmanLC** [comment]
I am running Arch with KDE 5 on X11:

I am having a similar issue with Pithos losing its window state after I minimize the program to the system tray. Once in the system tray, double clicking and right clicking the pithos system tray icon does not bring up the pithos main window.

Sometimes, while clicking the system tray icon, I will see a small auto-fitted window box with the text 'Pithos' right above the system tray icon. While minimized to the tray though, I lose all functionality to the program and must ```$ ps -aux | grep pithos``` to get the PID to kill.

```$ pithos -v``` does not show any issues either. I must resort to unchecking the 'Notification Icon' setting in preferences.

I'm running KDE plasma and don't have GNOME desktop or GNOME components installed other than ```seahorse``` for keyring management, and other misc GNOME dependencies that were installed from other program installs. Please let me know if this sounds like a missing GNOME dependency issue.

```
$ pacaur -Ss pithos
aur/pithos 1.2.1-3 (63, 4.49) [installed]
    Native Pandora Radio client

$ pacman -Ss plasma-meta
extra/plasma-meta 5.8-1 [installed]
    Meta package to install KDE Plasma

$ sudo Xorg -version

X.Org X Server 1.19.1
Release Date: 2017-01-11
X Protocol Version 11, Revision 0
Build Operating System: Linux 4.8.14-1-ARCH x86_64 
Current Operating System: Linux 4.9.6-1-ARCH #1 SMP PREEMPT Thu Jan 26 09:22:26 CET 2017 x86_64
 
Current version of pixman: 0.34.0
        Before reporting problems, check http://wiki.x.org
        to make sure that you have the latest version.

```
(Note: I deleted some content from ```Xorg -version``` output above)

**Comment by JasonLG1979** [comment]
It's a deeper issue than anything we have control of. There's a lot at play especially when you're talking about a Gtk/GNOME app in KDE. At this point the notification icon plugin is more trouble than it's worth. It's pretty much obsolete in GNOME >= 3.20(or any other DE with built in MPRIS support) And apparently now doesn't work correctly in KDE 5? If there was a reliable way to detect if a MPRIS applet was present I'd just get rid of it...

**Comment by JasonLG1979** [comment]
A possibility is to have a "Hide on Close" option in the MPRIS plugin. If a user doesn't have a MPRIS applet enabled and closed the window they would loose the window. But clicking on a Pithos launcher would show the window again. But that behavior is not obvious.

**Comment by TuxmanLC** [comment]
You did it @JasonLG1979 !! 

I assumed that if I opened the pithos launcher while I had pithos running and miniimized, that it would open another process/PID of pithos. *Not* the case. After pithos is minimized (unresponsive), I can get back to the pithos gui by relaunching pithos, which resumes the same process/PID. Awesome!

Thanks for the lead, you made my day!

**Comment by JasonLG1979** [comment]
That's why it not obvious behavior. Depending on the app it could either start another instance or open the current instance.

**Comment by JasonLG1979** [comment]
This is fixed isn't it @TingPing?
