### ISSUE TITLE
Deprecate the tray icon plugin for GNOME Shell in a future release.

### ISSUE THREAD

**Issue by JasonLG1979** [pithos/pithos#420]
Not this upcoming release but maybe the one after that...

Tray icons have pretty much been frowned upon since the beginning of GNOME Shell. With Shell 3.20+ having built-in MPRIS support and tray icon not even working at all in Wayland. I think it may soon be time to deprecate the tray icon plugin for GNOME Shell users. We could instead add an option to the MPRIS plugin to hide Pithos on close if the user is running a version of GNOME Shell with built-in MPRIS support. I'm not sure how that would work with flatpak? Is there an easy way to get the Shell version?

**Comment by BHSPitMonkey** [comment]
I think this is probably the right direction to go, though it's a bummer to lose quick access to Love/Ban/Tired options. Perhaps a proper GNOME top bar extension would be a good way of providing that; I may take a crack at that myself, assuming there's an out-of-process way to send those commands to a running instance, detect when Pithos (and/or pianobar) starts/stops, etc.

**Comment by JasonLG1979** [comment]
I am also a contributor to https://github.com/eonpatapon/gnome-shell-extensions-mediaplayer and recently added support for Love/Ban/Tired with a non-standard MPRIS extension. I plan on adding support for Love/Ban/Tired in the extension after Pithos 1.3.1 is released. At that point the Extension will be more functional than the tray icon.

**Comment by BHSPitMonkey** [comment]
Hey, that was easy! Thanks for that, I'll definitely be using it when it lands.

**Comment by JasonLG1979** [comment]
> Hey, that was easy!

Not really,lol!!! I had the pleasure of deciphering the MPRIS spec from their crap docs and implementing/fixing both the client and server sides of the interfaces,lol!!!

Our current MPRIS interfaces can be seen here:
https://github.com/pithos/pithos/wiki/DBus-Interfaces

We currently implement the complete MPRIS v2.2 spec and out own non-standard ExtensionPithosRatings extension for Love/Ban/Tired.

When complete you will be able to set the ratings for all songs that appear in the Tracklist interface. Basically the current most playlist in Pithos.

**Comment by BHSPitMonkey** [comment]
Easy for me, I mean! Thanks for the work and the documentation, I figured it would be something like that. It would be pretty neat if pianobar supported the same interface (allowing the same GNOME extension to control it too), but of course that's out of scope here.

**Comment by JasonLG1979** [comment]
If I remember pianobar has a control interface. You'd just need to write a shim between that and a MPRIS interface.

**Comment by JasonLG1979** [comment]
With https://github.com/pithos/pithos/blob/master/pithos/plugins/dbus_util/DBusServiceObject.py that @TingPing wrote and https://github.com/pithos/pithos/blob/master/pithos/plugins/dbus_util/GioNotify.py that I wrote you could fully integrate pianobar with MPRIS and desktop notifications. Both work perfectly well outside of Pithos and can be used by any PyGObject app/script.

**Comment by edgreenberg** [comment]
I wish you would keep this.  I run the Fedora Mate spin, and I need the tray icon to get to the program.

**Comment by TingPing** [comment]
@edgreenberg I personally have no plans on removing the tray plugin. We have invested enough time into it that it works fairly well and its disabled by default so harms nobody.

**Comment by JasonLG1979** [comment]
As much as I think the state of panel icons sucks, I have to admit I agree with @TingPing. It really doesn't hurt anything to keep the plugin. It would be nice if it worked more consistently across DE's but it is what it is..

**Comment by JasonLG1979** [comment]
@BHSPitMonkey, I have since taken over  https://github.com/JasonLG1979/gnome-shell-extensions-mediaplayer  https://github.com/JasonLG1979/gnome-shell-extensions-mediaplayer/commit/3fb4ff2a9f44f2b2837a38d25b59116c1c825d5d adds support for setting ratings in Pithos. If you like you can test it out. I'm in the process of testing it. If it works out I'll push an update to the extensions site.

**Comment by JasonLG1979** [comment]
@BHSPitMonkey Here's a screenshot:
![screenshot from 2017-07-02 11-01-01](https://user-images.githubusercontent.com/6667703/27771564-83f60c02-5f16-11e7-96f7-7a80d91505d4.png)

@TingPing It's possible to detect if my extension is installed and enabled. What do you think about a hide on close option for the MPRIS plugin if the extension is installed and enabled. I could make it so that if the extension was not installed and enabled no pref option would show up and if it were disabled the option would be automatically disabled. At this point my extension is WAY more functional than the tray icon. During normal listening you don't even need to open the main Pithos UI unless you want to change a setting or edit stations.

**Comment by TingPing** [comment]
@JasonLG1979 I can live with that.

**Comment by JasonLG1979** [comment]
I'll look into other DE's 1st to see if there's a way to detect other MPRIS clients.

**Comment by TingPing** [comment]
It could be another Pithos specific MPRIS extension?

**Comment by JasonLG1979** [comment]
I think it would be the other way around. We'd want to reach out and try to detect the different clients preferably with gsettings or DBus. But really an option to hide on close in the MPRIS plugin is still safe no matter what. Worse case you have to hit the launcher again to get the window back.

**Comment by JasonLG1979** [comment]
I'll also need to see exactly what goes on during a GNOME Shell restart. I don't know how that effects gsettings as far as an extension could suddenly show up or disappear after a restart.

**Comment by JasonLG1979** [comment]
Something like this will do it.

https://github.com/JasonLG1979/pithos/commit/cd70eeed93a65575ec283b2dd4fcd34bcff57f21

It automatically disconnects and reconnects the delete event according to the setting's state when the mpris plugin is enabled or disabled.

**Comment by JasonLG1979** [comment]
I think we've pretty much got a handle on the tray icon situation.
