### ISSUE TITLE
Master Commit 8b81f4cf2dcc Crashes on Kubuntu 16.04

### ISSUE THREAD

**Issue by Ironlenny** [pithos/pithos#427]
I'm using the Flatpak package on Kubuntu 16.04 and I receive this error when I run `flatpak run io.github.Pithos`

```python
Traceback (most recent call last):
  File "/app/lib/python3.4/site-packages/pithos/application.py", line 157, in do_command_line
    self.do_activate()
  File "/app/lib/python3.4/site-packages/pithos/application.py", line 170, in do_activate
    self.window = PithosWindow(self, self.test_mode)
  File "/app/lib/python3.4/site-packages/pithos/pithos.py", line 256, in __init__
    load_plugins(self)
  File "/app/lib/python3.4/site-packages/pithos/plugin.py", line 107, in load_plugins
    plugin = plugins[name] = load_plugin(name, window)
  File "/app/lib/python3.4/site-packages/pithos/plugin.py", line 70, in load_plugin
    module = __import__('pithos.plugins.' + name)
  File "/app/lib/python3.4/site-packages/pithos/plugins/journald_logging.py", line 76
    **kwargs,
            ^
SyntaxError: invalid syntax
```

**Comment by JasonLG1979** [comment]
@TingPing, looking at the code I 'm wondering why that's invalid syntax and why it only affects flatpak?

**Comment by TingPing** [comment]
I'd imagine because its python 3.4?

**Comment by JasonLG1979** [comment]
So you think it's a python version issue and not a flatpak issue?

**Comment by JasonLG1979** [comment]
Can someone test this branch to see if that fixes it I'm not running *buntu 16.04 nor the flatpak package:
https://github.com/JasonLG1979/pithos/tree/journald-logging-fix

It basically just gets rid of the ```*args, **kwargs``` bits. It works fine either way for me.

**Comment by JasonLG1979** [comment]
I'll fire up a Kubuntu 16.04 VM and see what I get.

**Comment by JasonLG1979** [comment]
@TingPing how would I test that branch with flatpak?

**Comment by TingPing** [comment]
Perhaps not trivial but:

Clone this repo and point this to your repo and branch (with branch property): https://github.com/TingPing/flatpak-packages/blob/master/io.github.Pithos.json#L88

```
make pithos
flatpak build-bundle repo pithos.flatpak io.github.Pithos
flatpak install --user pithos.flatpak
```

**Comment by Ironlenny** [comment]
@JasonLG1979 I've built your branch on my machine and it works, but I don't know if it will work in Flatpak.

**Comment by JasonLG1979** [comment]
So a native install of the master branch throws the same exception?

**Comment by Ironlenny** [comment]
No it doesn't. Pithos runs fine.

**Comment by JasonLG1979** [comment]
> No it doesn't. Pithos runs fine. I have python 2.7.12 along with 3.4 installed on my machine. Does make run differentiate?

I'm not 100% sure but I would think so. 

I'm running on Ubuntu GNOME 16.10(in preparation of the new release I normally run Fedora)  and I can neither install the stock flatpak via the wiki instruction nor the instructions provided on your flatpak repo @TingPing It will also NOT build with your instructions. So ATM I can't test anything...

**Comment by TingPing** [comment]
@JasonLG1979 Works in Flatpak.

**Comment by JasonLG1979** [comment]
@TingPing so that commit fixes the flatpak issue?

**Comment by TingPing** [comment]
Yup

**Comment by Ironlenny** [comment]
Just tested on my machine. It works great! Thank you.

**Comment by JasonLG1979** [comment]
> Just tested on my machine. It works great! Thank you.

Glad it was such an easy fix!
