### ISSUE TITLE
Audio freezes periodically with Gstreamer > 1.8.3

### ISSUE THREAD

**Issue by person666** [pithos/pithos#430]
Periodically pithos says buffering and freezes audio for moment.

I had been just downgrading gstreamer to fix this issue, but there are security issues in 1.8. I am aware this probably is a gstreamer issue, but I do not have experience with gstreamer or the time to learn enough to track this down and or file an issue with gstreamer. This bug has occurred on all of my computers with different internet speeds. I am running up to date arch.

**Comment by JasonLG1979** [comment]
If you know it's a Gstreamer bug report it to Gstreamer.

**Comment by person666** [comment]
It is probable that this is a issue in gstreamer. I don't know for certain
and like I said I don't have the required knowledge of pithos or gstreamer
to track it down and report it. Given that I have only experienced the bug
while using pithos not other applications that use gstreamer. This is
currently the most appropriate location to report the bug.

If pithos code is perfect, but a pithos dependency is no longer working as
needed then this is still relevant issue for pithos.

On Fri, Feb 24, 2017, 8:38 PM Jason Gray <notifications@github.com> wrote:

Closed #430 <https://github.com/pithos/pithos/issues/430>.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/pithos/pithos/issues/430#event-976930021>, or mute the
thread

**Comment by TingPing** [comment]
Does the quality change it, High uses mp3 and Low/Medium uses aacplus? (I believe you have to skip songs to get the new qualitiy)

**Comment by person666** [comment]
It occurs on all quality settings.

**Comment by JasonLG1979** [comment]
Network buffer in Gstreamer has been the bane of our existence for a couple 2 or 3 years now. This is nothing new. Just look though other Pithos issues.

**Comment by person666** [comment]
So have you filled bugs or considered looked into a gstreamer alternative?

**Comment by JasonLG1979** [comment]
I have not filed a bug because it would be duplicate of one of the several open bugs. I did once upon a time  hack together a VLC backend for Pithos but it had it's own drawbacks. It really wasn't any better than Gstreamer.

You're on Arch, that's the price you pay from running on the edge. 1st to get new features 1st to see bugs.
