### ISSUE TITLE
PPA does not serve package for Ubuntu 16.10 (Yakkety)

### ISSUE THREAD

**Issue by yodaldevoid** [pithos/pithos#432]
At the moment the PPA does not serve a package if asked for one for 16.10. This can be worked around my modifying the sources.list.d file for pithos to ask for the 16.10 (Xenial) copy.

**Comment by TingPing** [comment]
Ugh, dealing with Launchpad is a huge PITA. Dunno when I'll get around to that.

**Comment by yodaldevoid** [comment]
Agreed. I figured you should know and that a solution should be documented somewhere official-ish.

**Comment by JasonLG1979** [comment]
We really just need to find someone that can be put in charge of building Ubuntu packages...

**Comment by JasonLG1979** [comment]
Neither I nor @TingPing are Ubuntu users.

**Comment by JasonLG1979** [comment]
In the mean time installing from source is pretty easy ;)

**Comment by JasonLG1979** [comment]
As of Pithos 1.3.0 the official PPA will not be updated until we get someone to take over packaging for Ubuntu. I may takeover temporally or at least start an unofficial development version PPA.

See https://github.com/pithos/pithos/issues/440

**Comment by JasonLG1979** [comment]
Yep nope launchpad does suck. WAY over complicated just to upload a couple debs... Not doing it either.

**Comment by BHSPitMonkey** [comment]
It looks like 1.3.0 packages have been added for xenial, yakkety, and zesty yesterday (#440).

@yodaldevoid - Mind confirming and closing?

**Comment by JasonLG1979** [comment]
Yep. @hotice built the packages for us.
