### ISSUE TITLE
Running on CentOS 7

### ISSUE THREAD

**Issue by kai4785** [pithos/pithos#433]
I have a working pithos 1.1.2 on CentOS 7. I am using the epel python34* packages. I used those packages to build pithos dependencies from source (dbus-python-1.2.0, pycairo-1.10.0, and pygobject-3.10.2).

I set out to upgrade to pithos 1.2.1 today, excited that dbus is gone. I am running into the following stack trace:
```python
Traceback (most recent call last):
  File "/usr/bin/pithos", line 43, in <module>
    from pithos import application
  File "/usr/lib/python3.4/site-packages/pithos/application.py", line 26, in <module>
    from .pithos import PithosWindow
  File "/usr/lib/python3.4/site-packages/pithos/pithos.py", line 41, in <module>
    from . import AboutPithosDialog, PreferencesPithosDialog, StationsDialog
  File "/usr/lib/python3.4/site-packages/pithos/PreferencesPithosDialog.py", line 22, in <module>
    from .util import get_account_password, set_account_password
  File "/usr/lib/python3.4/site-packages/pithos/util.py", line 28, in <module>
    _ACCOUNT_SCHEMA = Secret.Schema.new('io.github.Pithos.Account', Secret.SchemaFlags.NONE, 
AttributeError: type object 'Schema' has no attribute 'new'
```

Turns out that I have a Secret.Schema.newv and .password_lookupv_sync, and password_storev_sync; seeing my pattern? I eventually got pithos to run by updating those calls, but it wasn't much happier. After launching I get this stack trace (but a window opens)

```python
Traceback (most recent call last):
  File "/usr/lib/python3.4/site-packages/pithos/application.py", line 101, in do_command_line
    self.do_activate()
  File "/usr/lib/python3.4/site-packages/pithos/application.py", line 109, in do_activate
    self.window = PithosWindow(self, self.test_mode)
  File "/usr/lib/python3.4/site-packages/pithos/pithos.py", line 146, in __init__
    load_plugins(self)
  File "/usr/lib/python3.4/site-packages/pithos/plugin.py", line 99, in load_plugins
    plugin.enable()
  File "/usr/lib/python3.4/site-packages/pithos/plugin.py", line 40, in enable
    self.on_enable()
  File "/usr/lib/python3.4/site-packages/pithos/plugins/mpris.py", line 41, in on_enable
    self.service = self.PithosDBusProxy(self.window, connection=self.bus)
  File "/usr/lib/python3.4/site-packages/pithos/plugins/_dbus_service.py", line 27, in __init__
    super().__init__(object_path=DBUS_OBJECT_PATH, **kwargs)
  File "/usr/lib/python3.4/site-packages/pithos/plugins/dbus_util/DBusServiceObject.py", line 272, in __init__
    self.__dbus_export()
  File "/usr/lib/python3.4/site-packages/pithos/plugins/dbus_util/DBusServiceObject.py", line 304, in __dbus_export
    self.__dbus_set_property
TypeError: argument vtable: Expected Gio.DBusInterfaceVTable, but got pithos.plugins.dbus_util.DBusServiceObject.method
```

That looks like dbus, even though my python34-dbus is not installed. The app runs after that. Then choosing preferences from the menu gives me:

```python
Traceback (most recent call last):
  File "/usr/lib/python3.4/site-packages/pithos/application.py", line 122, in prefs_cb
    self.window.show_preferences()
AttributeError: 'NoneType' object has no attribute 'show_preferences'
```

I'm fairly sure it's environmental, but I can fix that if I know what it is that needs fixing. I'm just not sure where to start.

**Comment by JasonLG1979** [comment]
@TingPing also ported away from python-dbus with  https://github.com/pithos/pithos/blob/master/pithos/plugins/dbus_util/DBusServiceObject.py so plugins that need Dbus can access it.

**Comment by TingPing** [comment]
Probably just depends upon a newer PyGObject or GLib. We don't explicitly check for versions other than Gtk so it just fails.

**Comment by TingPing** [comment]
We discovered this version requirement in #343 too but never tracked down a specific version.

**Comment by JasonLG1979** [comment]
> Probably just depends upon a newer PyGObject or GLib. We don't explicitly check for versions other than Gtk so it just fails.

Probably both. If I had to guess you'd need to update pretty much the whole Gtk/Glib stack to run the latest git of Pithos on CentOS7. Which would kinda defeat the purpose(rock solid stability) of running CentOS in the 1st place.

**Comment by TingPing** [comment]
I think it is limited to the MPRIS plugin, so if somebody wants to make mpris loading handle that failure safely...

**Comment by JasonLG1979** [comment]
I know it works on at least on whatever comes with Ubuntu 16.04. That's generally the oldest distro I test on.

**Comment by JasonLG1979** [comment]
> I think it is limited to the MPRIS plugin, so if somebody wants to make mpris loading handle that failure safely...

It's more than just the mpris plugin. The OP is getting errors with libSecret also.

**Comment by TingPing** [comment]
@kai4785 Mind testing: https://paste.fedoraproject.org/paste/icW7VG44RH2ZJxDMheIbxl5M1UNdIGYhyRLivL9gydE=

@JasonLG1979 True, but handling mpris failing is good in general.

**Comment by JasonLG1979** [comment]
> @JasonLG1979 True, but handling mpris failing is good in general.

We just need an error callback in plugin.py so anytime an error happens we can deal with it gracefully. That would also help with async plugin loading.

**Comment by JasonLG1979** [comment]
Something like:
```python
    def on_error(self, error):
        logging.error('Error during operation of plugin {}: {}'.format(self.name, error.msg))
        try:
            # Atempt whatever the plugin does to disable itself.
            self.disable()
        except Exception as e:
            logging.error('Error disabling plugin {}: {}'.format(self.name, e.msg))
        # In case we error out before we get that far.
        self.prepared = True
        self.enabled = False
```

**Comment by kai4785** [comment]
@TingPing 
Your patch didn't seem to originate from 1.2.1, but it was clear enough that got something that worked. Here's the two patches I needed to get it to run (listening now).
https://paste.fedoraproject.org/paste/HY6BLF7XxFyka09RRhqzzV5M1UNdIGYhyRLivL9gydE=

I've posted the resulting rpms on my private repo. The modified spec file is, of course, in the source rpm.
http://kai.gnukai.com/repo/el7/

**Comment by TingPing** [comment]
The libsecret workaround is a bit more ugly though...

**Comment by TingPing** [comment]
Looks like this change might be relevant: https://github.com/GNOME/libsecret/commit/d205542ba37d7222112953b44a03c7ea337482fa

**Comment by kai4785** [comment]
Sounds like the mpris plugin issue is resolved, and will be moving forward. The libsecret issue seems strange to me. As a C/C++ developer, I don't know how that updating the comments to say `(rename-to secret_password_store)` would have effected a change like this. I happen to have a handful of live Linux systems around that have libsecret installed. Ubuntu 14.04, 16.04, and CentOS 7 all have these 'v' and non-'v' symbols. They all appear to be present in the library itself.

```
$ nm -D /usr/lib/x86_64-linux-gnu/libsecret-1.so.0 | grep -e ' T .*\(newv\?$\|password_lookupv\?_sync$\|password_clearv\?_sync\|password_storev\?_sync\)$'
000000000001a840 T secret_password_clear_sync
000000000001a6f0 T secret_password_clearv_sync
000000000001a2c0 T secret_password_lookup_sync
000000000001a160 T secret_password_lookupv_sync
0000000000019960 T secret_password_store_sync
0000000000019750 T secret_password_storev_sync
000000000001bcd0 T secret_schema_new
000000000001bb10 T secret_schema_newv
000000000001f000 T secret_value_new
```

Now that I'm looking closely, it seems like the only possible explanation is that my python-gobject bindings don't have the non-'v' interface defined. I'll go digging down that path. It's probably nothing pithos has to worry about, except the possibility of doing a version check of python-gobject.

**Comment by TingPing** [comment]
>  I don't know how that updating the comments to say (rename-to secret_password_store) would have effected a change like this.

Bindings are generated from those comments.

**Comment by kai4785** [comment]
I ran updates today, and if I trust my last comments about python-gobject, it looks like the upgrade from 'pygobject3-3.14.0-3.el7.x86_64' to 'python-gobject-3.22.0-1.el7.x86_64' has solved this particular problem, and I can now run pithos 1.3.1 with out any special patches.
Gotta learn a little meson if I'm going to upgrade to 1.4.0 though.

**Comment by TingPing** [comment]
I strongly just recommend using Flatpak if you want new releases on older distros.

See install line here: https://pithos.github.io/
