### ISSUE TITLE
Error on startup: gst-resource-error-quark: Bad Request (5) - Fatal

### ISSUE THREAD

**Issue by schlameel** [pithos/pithos#435]
Pithos 1.2.1 installed from the PPA
Linux Mint 18.1 Cinnamon
Pandora free account

When I start Pithos, it looks like it loads some songs then opens a dialog box and won't play music.

![Pithos Dialog](https://cloud.githubusercontent.com/assets/2354293/24205211/fd4813c8-0ed7-11e7-9208-02efd887aefc.png)

I don't know what changed (no apt updates related to gstreamer or Pithos, no config changes). Pithos appears to connect to Pandora correctly and get song info (thumbnails, artist, song, album), but quickly skips through 7 songs and opens the error box stating "gst-resource-error-quark: Bad Request (5)".  When I close the dialog box, it seems to skip to the next song, a system notification pops up with the song info, but nothing plays.  

On each song in the main window (except the last song), the error message is repeated below the album line: "Error: gst-resource-error-quark: Bad Request (5)"

![Pithos error messages](https://cloud.githubusercontent.com/assets/2354293/24205620/17cc3e6c-0ed9-11e7-845c-b75b3c7ed0ab.png)

When I run Pithos from the command line I get the error below for each song:

`ERROR - pithos:on_gst_error:793 - Gstreamer error: gst-resource-error-quark: Bad Request (5), gstsouphttpsrc.c(1640): gst_soup_http_src_parse_status (): /GstPlayBin:player/GstURIDecodeBin:uridecodebin0/GstSoupHTTPSrc:source:
Bad Request (400), URL: http://mediaserver-sv5-rt-1-v4v6.pandora.com/access/6192675818421652980.mp3?version=5&lid=51608119&token=2yM2u08Y2H0DoVzgusXuVHPqO1wCC0jh1vsKifxmY3zAROXaSV1UKHLfqqXVZNuKuUTpQ2KMpAzNaW75Aw2uHlbUV2A6PJ8DtbakBXFVmdPeeC8dQldXBem3KGCQleS0FcHJ54j0ydecwgMewfM8Mlzy6DYvcvkLefWc8DKO8aY6axtfM%2Ff6YsiMYDMgO8wafoP8jarwbVbvPrtRU%2B7GcFjV1WQoHor4YITkuZ6e9uZezM7HfFYFVfKDcbR0KFnWIkSCZV%2FKI1tt53ymrHFsSv6Msn%2BA5KzwogXyTFQdJQD32BxDIPYNgve%2BZZ%2BmXJr8TKKZ%2FTvZ5HglhvmjGOvIbyguw5%2BguEoAFYlebYlCJ1HZsmOtF%2BEOC4p9AJqXF1Rfi7RGuBTCg0oONBlP1n6RJwax4DIlIOGwERT1OrU0eOnmmLCZba4VhTL4mE%2Bvijn46Lkx8jnJs7f2ITfw5ksTX2jmebiLuc71IecGSBJ0ZDVNpdiydeFEhaT63Evy%2B3nqWdxTpm%2FwEAo3dpabJ35fjR2oI50aqIk8TZsECPOZOQj89CutG5WlBF3HfbHP%2FqRd, Redirect to: (NULL), 5`

After the third song I get the messages:
`ERROR - pithos:on_gst_error:793 - Gstreamer error: gst-stream-error-quark: Internal data flow error. (1), gstbasesrc.c(2948): gst_base_src_loop (): /GstPlayBin:player/GstURIDecodeBin:uridecodebin3/GstSoupHTTPSrc:source:
streaming task paused, reason error (-5), 1
ERROR - pithos:on_gst_error:793 - Gstreamer error: gst-stream-error-quark: Stream doesn't contain enough data. (4), gsttypefindelement.c(983): gst_type_find_element_chain_do_typefinding (): /GstPlayBin:player/GstURIDecodeBin:uridecodebin3/GstTypeFindElement:typefindelement3:
Can't typefind stream, 4`

Then, after three more songs, I get:
`WARNING - pithos:get_playlist:634 - Too many gstreamer errors. Not retrying`

**Comment by JasonLG1979** [comment]
Strange, a status code of 400 means a malformed request. Are you using a proxy?

**Comment by schlameel** [comment]
No, but I'm seeing that my mobile official Pandora app won't play either. This may be an issue with my account or Pandora.

**Comment by JasonLG1979** [comment]
> No, but I'm seeing that my mobile official Pandora app won't play either. This may be an issue with my account or Pandora.

I'm listening with Pithos right now. no problems for me. I'd say you're probably right. Give it a day and see if it clears it self up.

**Comment by asciiman0** [comment]
Just wanted to corroberate the OP's issue.
Linux Mint 18.0 here, running Pithos 1.1.1. from the Ubuntu repository.
It was functioning beautifully, and integrating well in the Mint desktop until yesterday (March 21, 2017).
Yesterday I started getting the exact same behavior as the OP.
I am not sure if it broke following an update.
I have looked over my update log, but can't seem to find anything that might have broken Pithos.

I can log into Pandora through my browser and it will play my channels fine.

**Comment by JasonLG1979** [comment]
As I said I'm having no problems ATM. I'm running Fedora 25 with the latest git. I'm not really sure what's going on. It's hard to debug on Mint because they do all kinds of pinning and use their own packages. As much as Ubuntu is a bastardization of Debian, Mint is a bastardization of Ubuntu. What works just fine on Ubuntu may not work at all on Mint. Best case Pandora is experiencing outages in your areas. Medium case Mint broke something. Worse case Pandora is rolling out API changes and you're got it before me.

**Comment by asciiman0** [comment]
Just had an Ubuntu security update come down, rated at level "high."
"libaudiofile1" update  0.3.6-2ubuntu16.04.1 seems to have fixed my Pithos breakage.
Pithos would give the OP's error message just minutes prior to the security upgrade.
Now Pithos is OK!

**Comment by schlameel** [comment]
The problem is with my Pandora account and not Pithos.  When I use a different account, Pithos works fine.  My Pandora account will not work on any Pandora interfaces - web, iPhone app, Pithos.  I'm closing the issue.

**Comment by hackel** [comment]
I just experienced this exact issue—console output is identical—with Pithos 1.3.1.  The only difference is that I could log into the web interface and play with that same account just fine.  I had been listening to Pandora with Pithos for about an hour prior to this occurring.

**Comment by thelaurence** [comment]
I'm getting this error with Pithos 1.4.1 installed from the AUR on Manjaro. I installed updates yesterday that touched a couple of Pithos's dependencies (`gst-plugins-good` and `gtk3`) so I downgraded those two packages to the version that was previously installed, but I'm still getting the same error. Pandora's web client works just fine with the same account I'm using in Pithos.

```
ERROR - pithos:on_gst_error:1101 - Gstreamer error: gst-stream-error-quark: Internal data stream error. (1), gstbasesrc.c(2939): gst_base_src_loop (): /GstPlayBin:player/GstURIDecodeBin:uridecodebin0/GstSoupHTTPSrc:source: streaming stopped, reason error (-5), 1
```

I would be happy to work on a fix myself if someone wanted to point me to a tutorial or something to help me get a development environment set up for this type of project. I have very limited experience with Python 3, Meson, etc. I need some help so I can get Pithos running in a debugger.

**Comment by JasonLG1979** [comment]
> Pandora's web client works just fine with the same account I'm using in Pithos.

@thelaurence, Pandora's web client uses a different API and possibly different servers under the hood? A bad request more than likely means a problem on their side. Give it a while and try again later. There's nothing we can do about it.

**Comment by thelaurence** [comment]
@JasonLG1979 OK. Thanks for responding and for all your work on this project! Pithos is great and, sure enough, started working again after a while. I was getting that same error for a few days, but now it's working again.

**Comment by kai4785** [comment]
This is happening to me across versions 1.2.1, 1.3.1, 1.4.0, and 1.4.1. Started yesterday, still happening today.

`ERROR - pithos:on_gst_error:1101 - Gstreamer error: gst-stream-error-quark: Internal data stream error. (1), gstbasesrc.c(2950): gst_base_src_loop (): /GstPlayBin:player/GstURIDecodeBin:uridecodebin3/GstSoupHTTPSrc:source:
streaming stopped, reason error (-5), 1
INFO - pithos:start_song:740 - Starting song: index = 4
INFO - pandora:audioUrl:522 - Using audio quality highQuality: 128 mp3
ERROR - pithos:on_gst_error:1101 - Gstreamer error: gst-stream-error-quark: Internal data stream error. (1), gstbasesrc.c(2950): gst_base_src_loop (): /GstPlayBin:player/GstURIDecodeBin:uridecodebin4/GstSoupHTTPSrc:source:
streaming stopped, reason error (-5), 1
INFO - pithos:start_song:740 - Starting song: index = 5
INFO - pandora:audioUrl:522 - Using audio quality highQuality: 128 mp3
ERROR - pithos:on_gst_error:1101 - Gstreamer error: gst-stream-error-quark: Internal data stream error. (1), gstbasesrc.c(2950): gst_base_src_loop (): /GstPlayBin:player/GstURIDecodeBin:uridecodebin5/GstSoupHTTPSrc:source:
streaming stopped, reason error (-5), 1
INFO - pithos:start_song:740 - Starting song: index = 6
INFO - pandora:audioUrl:522 - Using audio quality highQuality: 128 mp3
ERROR - pithos:on_gst_error:1101 - Gstreamer error: gst-stream-error-quark: Internal data stream error. (1), gstbasesrc.c(2950): gst_base_src_loop (): /GstPlayBin:player/GstURIDecodeBin:uridecodebin6/GstSoupHTTPSrc:source:
streaming stopped, reason error (-5), 1
WARNING - pithos:get_playlist:855 - Too many gstreamer errors. Not retrying
`

**Comment by kai4785** [comment]
And today, it's suddenly working again.
