### ISSUE TITLE
Mediakeys are tied to MPRIS in GNOME 3.24

### ISSUE THREAD

**Issue by JasonLG1979** [pithos/pithos#450]
See this upstream bug: https://bugzilla.gnome.org/show_bug.cgi?id=781326

In GNOME 3.24 mediakeys can't be disabled unless you disable the MPRIS plugin. Hopefully it's temporary but the GNOME dev's have decided to remove the Mediakeys Dbus interface and instead go though MPRIS for mediakeys.

Just figured I put this here for people wanting to file bugs against Pithos when/if the mediakeys plugin behaves strangely. i.e. You can't seem to disable it.

**Comment by TingPing** [comment]
>  Hopefully it's temporary but the GNOME dev's have decided to remove the Mediakeys Dbus interface and instead go though MPRIS for mediakeys.

No they didn't, its a bug; This happened because gnome-settings-daemon was split from plugins into separate processes.

**Comment by JasonLG1979** [comment]
> No they didn't it's a bug; This happened because gnome-settings-daemon was split from plugins into separate processes.

I would believe that if magically MPRIS wasn't tied to the mediakeys... Explain that?

**Comment by TingPing** [comment]
That has been around a few releases.

**Comment by JasonLG1979** [comment]
> That has been around a few releases.

Not in GNOME 3.22 in Fedora 25.

**Comment by JasonLG1979** [comment]
Show me where/when that was added?

**Comment by JasonLG1979** [comment]
Ok. my bad @TingPing you are correct. I guess it is in GNOME 3.22 in Fedora. Sorrrrry ;)

**Comment by JasonLG1979** [comment]
Well i might as well close this bug since the bug is now hidden unless you have "the appropriate permissions." Score another one for transparent development...

**Comment by TingPing** [comment]
Because you made a rude and unhelpful comment. Maybe not the best response but oh well.

**Comment by JasonLG1979** [comment]
It was a little rude in retrospect. I would delete the comment and/or apologize but I can't see the bug anymore...

**Comment by JasonLG1979** [comment]
The KDE Plasma desktop uses MPRIS for it's mediakey bindings also. Everyone keeps breaking our sh!t,lol!!!

**Comment by TingPing** [comment]
Just having MPRIS bind keys shouldn't break anything, for KDE its actually good so it works on Wayland there.

**Comment by JasonLG1979** [comment]
What I mean is that it makes it look like our plugin is misbehaving. A user who tried to disable it might think it wasn't disabling correctly because Pithos would still respond to Mediakeys.

**Comment by JasonLG1979** [comment]
It generally causes inconsistent and confusing behavior.

**Comment by JasonLG1979** [comment]
My other question is what good is keybinder? All it does is global binding with no accounting for focus with things being hooked to mpris which does the exact same thing it seems redundant?

**Comment by TingPing** [comment]
Plenty of people use other window managers, that is the best we've got there.

**Comment by JasonLG1979** [comment]
Did you try out that PR?
