### ISSUE TITLE
For the FAQ: What is the difference between Skip, Ban and Tired?

### ISSUE THREAD

**Issue by orschiro** [pithos/pithos#458]
Dear all, 

To me not clear what the difference is between these three. 

Maybe worth adding to the FAQ?

![image](https://cloud.githubusercontent.com/assets/170947/25469028/fc6c7d0a-2b19-11e7-83df-8e64fdaf63d8.png)

**Comment by JasonLG1979** [comment]
Skip: Just skips to the next song. Doesn't influence anything.

Love: (thumbs up rating) tells Pandora you like that song and to play it and songs like it more often on that particular station.

Ban: (thumbs down rating) tells Pandora you dislike that song and not to play it ever again on that station.

Tired: Don't play that song for a month on this or any other station. I'm not sure how that otherwise influences Pandora as far as what songs it's going to play in the future.

Love, Unrated and Ban can be thought of as +1, 0, and -1. You can Ban a song and then Unrate or Love it to change the rating.

Tired is not really a rating. You can't "Un-tired" a song.

**Comment by orschiro** [comment]
Excellent, thank you!

Maybe the context menu can say:

- Love (+1) or Love (thumbs up or arrow up symbol)
- And the same for Unrated and Ban

https://github.com/pithos/pithos.github.io/pull/1

**Comment by JasonLG1979** [comment]
We generally have used a heart for Love.

**Comment by orschiro** [comment]
A heart is also nice but it does not reflect what this feature does (i.e. rating).

**Comment by JasonLG1979** [comment]
Heart = Love.

**Comment by orschiro** [comment]
Yes, I understood but a heart icon does not make clear that it basically is a +1 (upvote) of the song.

**Comment by JasonLG1979** [comment]
But really unless you can talk @TingPing or someone else to modify the Notification Icon plugin I wouldn't count on anything changing. I really have no interest in that plugin and would be happy if it was gone.

**Comment by JasonLG1979** [comment]
@orschiro Ratings are not limited to the tray icon. You can rate songs in the song treeview context menu. (right click a song)

**Comment by orschiro** [comment]
@JasonLG1979 I am ok if my suggestion is not implemented. 

My initial question is solved. :-)

**Comment by JasonLG1979** [comment]
Although we try to make feature discoverable, at some point I may add a Howto/Features wiki page to show new users all the features of Pithos.

**Comment by TingPing** [comment]
An easy improvement would be for somebody to hook up `f1` opening the wiki for easy access to help.

**Comment by JasonLG1979** [comment]
> An easy improvement would be for somebody to hook up f1 opening the wiki for easy access to help.

And a help Help entry in the main menu.

**Comment by JasonLG1979** [comment]
I've uploaded some screenshots to https://github.com/pithos/pithos.github.io (didn't want to bloat the main git repo with them) for use in a user guide wiki page. I'll do that this weekend and add a help menu. sound good @TingPing?

**Comment by TingPing** [comment]
Sure.

**Comment by JasonLG1979** [comment]
There https://github.com/pithos/pithos/wiki/User-Guide @TingPing can you do me a favor and give that quick proof read and edit it where you think needed?

**Comment by JasonLG1979** [comment]
@orschiro does that work for you as a basic explanation of the features in Pithos?

**Comment by TingPing** [comment]
Looks good, I do think technical details like 'libsecret' are details most users would not be concerned with though.

**Comment by JasonLG1979** [comment]
> Looks good, I do think technical details like 'libsecret' are details most users would not be concerned with though.

I just wanted to avoid bugs like "Why do I have to re-login every time"

**Comment by JasonLG1979** [comment]
To you and I all of that stuff is obvious. But we need to remember that we know the in's and out's of Pithos. Not everyone does. That's why devs write the worst docs,lol!!!

**Comment by TingPing** [comment]
Maybe a common issues page?

**Comment by JasonLG1979** [comment]
> Maybe a common issues page?

It's not an issue. That's how it's designed to work.

**Comment by TingPing** [comment]
My point isn't that we shouldn't describe things my point is you go out of your way to name the library and link to its development page. This is entirely extraneous information.

**Comment by JasonLG1979** [comment]
I can remove the link?

**Comment by JasonLG1979** [comment]
"Pithos stores your Pandora password securely in your login keyring. If you set your account to auto login and you start Pithos without otherwise unlocking your login keyring. You will see this or a similar dialog."

Better?

**Comment by TingPing** [comment]
Yea.

**Comment by orschiro** [comment]
@JasonLG1979, great integration of the section on rating!

**Comment by JasonLG1979** [comment]
Ok then I'm going to call this solved.
