### ISSUE TITLE
1.3.1: Won't Play Songs; Loads OK, Was Working Yesterday - Mint 18.1

### ISSUE THREAD

**Issue by biolife1212** [pithos/pithos#471]
Pithos 1.3.1 loads and will login without any trouble, but will not play any songs. It loads the playlist, mentions buffering and stalls at 0:00/X:XX. Attempted changing radio stations, quality & Pandora one settings, and removal with re-installation with no effect. I am a Pandora One subscriber with the PPA added running on Linux Mint 18.1. My account is working fine if I log into Pandora's web player.

It was working fine yesterday morning as it has since I first installed the program. Mint Update Manager did update libopenshot last night. Not sure if there is a problem there. Any thoughts?

**Comment by JasonLG1979** [comment]
I'll throw Mint in a VM and test it out.

**Comment by JasonLG1979** [comment]
I will also test in Ubuntu 16.04. The problem is that Mint holds back packages and packages their own version of some media libs. If it works in Ubuntu 16.04 and not Mint 18.1 you'll need to file a bug with Mint.

**Comment by biolife1212** [comment]
Thanks! I appreciate you looking into it. Let me know if there is any info on my end that could be useful.

**Comment by JasonLG1979** [comment]
I love to see a debug log.

**Comment by biolife1212** [comment]
How do I get a debug log?

**Comment by JasonLG1979** [comment]
Downloading Mint 18.1 now. I already had a Ubuntu 16.04 VM. Everything seems to work just fine in a fully updated Ubuntu 16.04.

**Comment by biolife1212** [comment]
Ok. Thanks. It may be a problem I need to take over to Mint. I can get you a debug log if you let me know how to. I've searched around in /usr/lib/python3.5/site-packages/pithos but do see a clear way to get one.

**Comment by biolife1212** [comment]
Figured it out... 
[Pithos_Debug_Output.txt](https://github.com/pithos/pithos/files/1016293/Pithos_Debug_Output.txt)

**Comment by JasonLG1979** [comment]
@biolife1212 Make sure to sanitize your debug log when posting it online. It contains your login credentials. I edited your  comment and removed the link.

**Comment by biolife1212** [comment]
Thanks! I noticed that and thought I had removed all the sensitive information. I will change my password now however.

**Comment by biolife1212** [comment]
Apparently changing the password has resolved the issue as playback has resumed and all is well. Thank you for looking into it.

**Comment by JasonLG1979** [comment]
> Apparently changing the password has resolved the issue as playback has resumed and all is well. Thank you for looking into it.

That shouldn't have had anything to do with it. The logs show you had no problems logging into your Pandora account. But I'm glad you're no longer having any issues.
