### ISSUE TITLE
Flatpak raises exception on org.freedesktop.DBus.NameHasOwner

### ISSUE THREAD

**Issue by Ironlenny** [pithos/pithos#474]
I'm using Kubuntu 16.04 and the flatpack package. I used to get the system tray icon when I launched Pithos. Now it doesn't appear. When I try to enable it, I get this message:
```
(process:18625): GLib-GIO-CRITICAL **: g_dbus_message_set_body: assertion '(body == NULL) || g_variant_is_of_type (body, G_VARIANT_TYPE_TUPLE)' failed
ERROR - notification_icon:on_has_name_owner:68 - g-io-error-quark: Method 'org.freedesktop.DBus.NameHasOwner' returned type '()', but expected '(b)' (13)
Traceback (most recent call last):
  File "/app/lib/python3.5/site-packages/pithos/plugins/notification_icon.py", line 65, in on_has_name_owner
    is_owned = bus.call_finish(result)[0]
GLib.GError: g-io-error-quark: Method 'org.freedesktop.DBus.NameHasOwner' returned type '()', but expected '(b)' (13)
```

**Comment by JasonLG1979** [comment]
Works fine in Ubuntu 16.04 installing from source. @TingPing, I really know nothing of flatpack but innotification_icon.py  we call to ```org.freedesktop.DBus``` and that's not a "talk-name" in your flatpak package?

**Comment by Ironlenny** [comment]
I don't know if this is a related bug, but I no longer get album art in the "Media Player" widget. The "Media Player" widget is what implements Mpris in KDE.

**Comment by JasonLG1979** [comment]
> I don't know if this is a related bug, but I no longer get album art in the "Media Player" widget. The "Media Player" widget is what implements Mpris in KDE.

Does it throw an error?

**Comment by TingPing** [comment]
`org.freedesktop.DBus` is in the default permissions and it would throw a different error in that case. The dbus server is replying its just of the wrong type for some reason.

**Comment by TingPing** [comment]
Actually i can reproduce this issue.

**Comment by JasonLG1979** [comment]
I just fired up Pithos in a Kubuntu 16.04 VM and everything works as expected. It's got to be a flatpak issue.

**Comment by TingPing** [comment]
Yes I agree.

**Comment by Ironlenny** [comment]
Here's the error I'm getting from `org.kde.plasma.mediacontroller`:
```
QDBusObjectPath: invalid path ""
file:///usr/share/plasma/plasmoids/org.kde.plasma.mediacontroller/contents/ui/ExpandedRepresentation.qml:72:13: QML Image: Cannot open: file:///tmp/pithos-ztdhe369/art-u3q3bvma
```

I think it's related to https://github.com/flatpak/flatpak/issues/592.

**Comment by TingPing** [comment]
The root cause of this bug reported here: https://github.com/flatpak/flatpak/issues/817

**Comment by TingPing** [comment]
> I think it's related to flatpak/flatpak#592.

We explicitly pass `/tmp` through, so you should be able to verify `file:///tmp/pithos-ztdhe369/art-u3q3bvma` exists.

**Comment by JasonLG1979** [comment]
> We explicitly pass /tmp through, so you should be able to verify file:///tmp/pithos-ztdhe369/art-u3q3bvma exists.

What permissions are the tmp files saved with?

**Comment by TingPing** [comment]
> What permissions are the tmp files saved with?

rw-------.  1 tingping tingping 24484 May 26 17:05 art-78fsznhk

**Comment by JasonLG1979** [comment]
> rw-------. 1 tingping tingping 24484 May 26 17:05 art-78fsznhk

So not the same owner as the user. Could be the problem?

**Comment by TingPing** [comment]
> So not the same owner as the user. Could be the problem?

It *should* always be the same owner as the user, unless the mpris daemon is running as `bob` for some reason.

**Comment by JasonLG1979** [comment]
The reason I ask is that:
>file:///usr/share/plasma/plasmoids/org.kde.plasma.mediacontroller/contents/ui/ExpandedRepresentation.qml:72:13: QML Image: Cannot open: file:///tmp/pithos-ztdhe369/art-u3q3bvma

Says "Cannot open" it doesn't say it doesn't exist?

**Comment by TingPing** [comment]
> Says "Cannot open" it doesn't say it doesn't exist?

Maybe..., vague enough that its hard to say. Also not easy to `strace` all of KDE to easily see the real error code.

This may or may not help: https://github.com/pithos/pithos/commit/8a01a88b39bb0314e460736aa1ee2ba1d53ff1a0

**Comment by JasonLG1979** [comment]
Do you need explicit permission to access the user's cache dir? On a unrelated note you don't need ```"--own-name=net.kevinmehall.Pithos"``` either anymore do you?

**Comment by TingPing** [comment]
> you don't need "--own-name=net.kevinmehall.Pithos" either anymore do you?

Nope, removed.

> Do you need explicit permission to access the user's cache dir?

So by default you do not have any permissions to your users cache dir, Flatpak instead makes a private directory just for your application and sets `XDG_CACHE_HOME` to it. In this case `~/.var/app/io.github.Pithos/cache`

**Comment by JasonLG1979** [comment]
> So by default you do not have any permissions to your users cache dir, Flatpak instead makes a private directory just for your application and sets XDG_CACHE_HOME to it. In this case ~/.var/app/io.github.Pithos/cache

Is that dir accessible from the outside world or is it only accessible in the sandbox?

**Comment by TingPing** [comment]
> Is that dir accessible from the outside world or is it only accessible in the sandbox?

It is accessible by the host, and by the same path, so everything should "just work".

**Comment by JasonLG1979** [comment]
Well 8a01a88 doesn't seem to harm anything as far as a standard install. More Kubuntu 16.04/KDE errors. open_browser doesn't work either...

**Comment by JasonLG1979** [comment]
Doesn't work in Kubuntu 17.04 either.

**Comment by JasonLG1979** [comment]
Found the problem Gtk.show_uri and apparently also Gtk.show_uri_on_window depend on gvfs which is not listed as a dependency for Ubuntu for Pithos. Installing gvfs in Kubuntu solves the problem.

**Comment by TingPing** [comment]
It doesn't actually depend upon `gvfs`, something dumb must be going on.

**Comment by JasonLG1979** [comment]
Kinda a old bug but it seems like it does. https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=513910

**Comment by TingPing** [comment]
Nope, that function has literally nothing to do with `gvfs`. `gtk_show_uri` -> `g_app_info_*` -> `g_desktop_appinfo_*` (this directly looks up associations and launches the application).

**Comment by TingPing** [comment]
@JasonLG1979 Can you verify `shared-mime-info` was installed before `gvfs`? It seems to be only a recommended dep of glib so might not have been pulled in.

**Comment by JasonLG1979** [comment]
https://developer.gnome.org/gtk3/stable/gtk3-Filesystem-utilities.html#gtk-show-uri-on-window

This is a convenience function for launching the default application to show the uri. The uri must be of a form understood by GIO (i.e. you need to install gvfs to get support for uri schemes such as http:// or ftp://, as only local files are handled by GIO itself).

Nope sure does for http://...

**Comment by JasonLG1979** [comment]
> Can you verify shared-mime-info was installed before gvfs? It seems to be only a recommended dep of glib so might not have been pulled in.

Yes shared-mime-info was installed. Installing gvfs makes it work removing it breaks it again.

**Comment by TingPing** [comment]
Well you aren't crazy but I think it should be possible to change glib so it works.

**Comment by JasonLG1979** [comment]
> Well you aren't crazy but I think it should be possible to change glib so it works.

?... Yep, I don't know why it takes a whole virtual file system to figure out the default app for a http uri? But apparently in glib it does...

**Comment by JasonLG1979** [comment]
If i had to guess it uses one tiny bit of gvfs but GNOME devs instead of splitting that part out decided to make it one monolith beast.

**Comment by TingPing** [comment]
@JasonLG1979 Well if we rewind time over a decade Gio didn't even exist and this directly used GVFS which included much of the features that eventually become Gio. They have consistently been migrating common functionality into Gio (for example `gvfs-open` is actually a wrapper to `gio open`). I might spend some more time looking into it. I wrote the OSX backend for GAppInfo so I'm fairly familiar with it (and it obviously doesn't use gvfs there).

**Comment by JasonLG1979** [comment]
> Well if we rewind time over a decade Gio didn't even exist and this directly used GVFS which included much of the features that eventually become Gio. They have consistently been migrating common functionality into Gio (for example gvfs-open is actually a wrapper to gio open). I might spend some more time looking into it. I wrote the OSX backend for GAppInfo so I'm fairly familiar with it (and it obviously doesn't use gvfs there)

Well get at it then, lol!!!
