### ISSUE TITLE
How is the Ubuntu sound menu integration done?

### ISSUE THREAD

**Issue by orschiro** [pithos/pithos#478]
Dear all, 

I am looking for some advice how to properly integrate a program into the Ubuntu sound menu indicator.

Pithos has done a great job and it is working properly. 

With Anoise, however, we are struggling to get it work. The related bug report can be found here [1].

Do you have any tips for us how to properly integrate an application into the sound menu indicator nowadays?

Thank you so much for your help!

Yours,

Robert

![anoise play pause](https://cloud.githubusercontent.com/assets/170947/26753090/e4543296-485e-11e7-949b-939262409260.png)

[1] https://bugs.launchpad.net/anoise/+bug/1693381

**Comment by JasonLG1979** [comment]
@orschiro The sound menu is a MPRIS client the spec is here. https://specifications.freedesktop.org/mpris-spec/latest/interfaces.html

MPRIS can be a pain in the butt. But luckily it looks like the app you're working on is pretty simple. I don't think it would need more than the most basic of implementations. On a basic level based on your screenshot it appears that you are not sending the PropertiesChanged signal to tell the sound menu that the PlaybackStatus has changed.(the buttons don't match) If I had one bit of advice I would say that you should never put up an empty interface. Always at least have dummy default values in place for all the required properties and update them when they change with PropertiesChanged signals. Think of it like this, as far as information about the player the clients are suppose to take a passive role. Players "push" info to clients by emitting PropertiesChanged signals. If a  PropertiesChanged signal is not emitted than there is no way for the client to know that something has changed.

**Comment by orschiro** [comment]
Hi @JasonLG1979,

Thank you very much for your useful advice! I guess we will take it from here and see how far we get. :-)

Yours,

Robert

**Comment by JasonLG1979** [comment]
You're welcome. I'm going to go ahead and close this since it's not really about Pithos. Any further discussion can be done on  https://bugs.launchpad.net/anoise/+bug/1693381.
