### ISSUE TITLE
Unofficial Pandora API Discord

### ISSUE THREAD

**Issue by FireController1847** [pithos/pithos#479]
Hello! 👋 

💠 I'm going around all of the Pandora Libraries's as well as their products, and telling users about a Discord server I've been making to allow us all to communicate easily and quickly. All library creators will be given their own role and their own support channel to (optionally) help users. All product creators will be given their own role, and their own support channels as well. Please join! We're looking to get as many Unofficial Pandora API dev's to come together, and allow for easy communication.

💠 Some more info about me: A simple Discord user. I'm looking to create Node.js API, but noticed there was no way to contact anyone nor a simple community behind it that I could talk to, so I've made this guild to try to make the community visible as one giant group.

💠 We think you'd be an awesome addition to the community, please, join! Let's bring this Unofficial API all into one place for easy support and documentation, as well as product listings and library listings. Hope to see you there! 👍 

[Join Here](https://discord.gg/VqzGTV8)
https://discord.gg/VqzGTV8

**Comment by JasonLG1979** [comment]
This isn't a message board or forum. Email or IRC would be a more appropriate medium for this announcement/invite.

**Comment by FireController1847** [comment]
@JasonLG1979 Sorry, just thought about putting it here because it's public, so not just developers would see it but users aswell. Won't happen again 👋

**Comment by JasonLG1979** [comment]
I'm not sure why a non-developer would care about an API?

**Comment by FireController1847** [comment]
@JasonLG1979 Support

**Comment by FireController1847** [comment]
@JasonLG1979 Do you happen to know the email I can send it to?

**Comment by JasonLG1979** [comment]
You can email me and we can talk but I'm not really interested in discord. I doubt @TingPing would be interested either. Pithos is pretty feature comparable to the official clients, we try to keep up on things. Most of what little functionality we lack is not because of lack of knowledge of the API it's just because we haven't figured out how we want to implement it.

**Comment by FireController1847** [comment]
@JasonLG1979 And I'm not saying that you guys join for support, you'll just be there to be awesome, and at least be part of the community. Y'all don't have to come to give support either, you can just hang around, or you can just stay offline.

**Comment by JasonLG1979** [comment]
> I'm not saying that you guys join for support, you'll just be there to be awesome, and at least be part of the community. Y'all don't have to come to give support either, you can just hang around, or you can just stay offline.

I'm sorry I'm not interested in being decoration or user list padding.
