### ISSUE TITLE
Option to start pithos with playback paused

### ISSUE THREAD

**Issue by austin6598** [pithos/pithos#482]
I would like an option to have pithos paused on startup, instead of automatically playing music.

**Comment by JasonLG1979** [comment]
Question, why not just not start Pithos until you actually want to listen to music?

**Comment by austin6598** [comment]
I run it on startup so I can just use the playbar widget to resume playback.

**Comment by JasonLG1979** [comment]
That's not advisable. Pandora sends us songs in sets of 4 song playlists. Those playlists are only good for 1 hour, so as soon as you fetch the playlist the clock starts ticking whether you play any of the songs or not. After an hour the song urls are not valid and will throw an error if you try to use them. We handle that by comparing the fetched time to the time at which the song will be done playing to make sure we don't throw an exception.

https://github.com/pithos/pithos/blob/master/pithos/pandora/pandora.py#L564-L567

If we run into an invalid song we skip songs until we get a valid one or we get a new playlist.

I can't speak for @TingPing but I don't think that adding a feature to start Paused is a good idea.

**Comment by TingPing** [comment]
I agree that automatic running on startup is a bit odd and likely to hit that timeout issue but I also don't think its a huge deal.

In the mean time it should be fairly easy to make a script that calls pause over dbus a few seconds after launch.

**Comment by JasonLG1979** [comment]
> In the mean time it should be fairly easy to make a script that calls pause over dbus a few seconds after launch.

If you listened for the 1st metadata prop change signal over MPRIS you could call pause right then.

**Comment by JasonLG1979** [comment]
I'll write a quick Python script and post the Gist here in a bit.

**Comment by JasonLG1979** [comment]
Here @austin6598 it's a Gjs script that will Pause Pithos at start. It requires Gjs so you'll need that and you'll have to make it executable and start it before Pithos in your start up programs.

https://gist.github.com/JasonLG1979/32887121b16511124a9ddcfa09f02f66

It listens for Pithos to update it's MPRIS metadata(you'll need to have the MPRIS plugin enabled) and at the first metadata update it Pauses Pithos then the script quits. You can make the script not quit so that it would start Pithos every time you start it by commenting out this line.

 https://gist.github.com/JasonLG1979/32887121b16511124a9ddcfa09f02f66#file-stoppithosatstart-js-L93

**Comment by JasonLG1979** [comment]
As a side note: @TingPing I really wish the python bindings had Gio.DBusProxy.makeProxyWrapper... it makes things super easy.

**Comment by TingPing** [comment]
> As a side note: @TingPing I really wish the python bindings had Gio.DBusProxy.makeProxyWrapper... it makes things super easy.

Indeed. Time to write a patch for pygobject I guess?

**Comment by JasonLG1979** [comment]
I started writing the script in Python but after a bit I decided to go with Gjs because for this case it's simpler IMHO.

**Comment by austin6598** [comment]
> Here @austin6598 it's a Gjs script that will Pause Pithos at start.
@JasonLG1979 Thank you the script works great!

> I agree that automatic running on startup is a bit odd and likely to hit that timeout issue
@TingPing I'm not sure if this is possible, but could pithos run without automatically playing, but wait for the Play signal over MPRIS and then load the station? This would probably require an option in the settings and changing the pithos source code, but it's just an idea.

**Comment by JasonLG1979** [comment]
> Thank you, the script works great!

No problem. It's basically modified bits and pieces of the stock GNOME MPRIS widget re-purposed. 

https://github.com/GNOME/gnome-shell/blob/19816523c7e16dd8b0aef5aaf2f2b9a6e6208760/js/ui/mpris.js

**Comment by JasonLG1979** [comment]
> I'm not sure if this is possible, but could pithos run without automatically playing, but wait for the play signal over MPRIS and then load the station? This would probably require an option in the settings and changing the pithos source code, but it's just an idea.

I don't really see it as being a setting that's accessible from the prefs dialog but a command line arg seems reasonable. Basically we just wouldn't request any playlists until you hit play (via MPRIS or the main UI)

What do you think @TingPing something like '--dont-autoplay'?

**Comment by JasonLG1979** [comment]
I'm going to close this as the script seems to solve the issue.

**Comment by austin6598** [comment]
Unfortunately it seems the script is no longer working. Does it need to be updated or is it something wrong on my end?

**Comment by JasonLG1979** [comment]
Don't know? I'd have to revisit it. Has your configuration changed?

**Comment by austin6598** [comment]
Yes but the script stop working a while ago, I just never got around to posting about it. I believe it was a pithos or kubuntu update that broke it. I am on Kubuntu 17.10 using pithos 1.4.0

**Comment by JasonLG1979** [comment]
In any event. It was just a one off script. I had/have no plans to keep it up to date forever. I don't mean to be rude but it may be an opportunity for you to learn a little Gjs?

 

> Kubuntu 17.10 using pithos 1.4.0

So you've updated Kubuntu since? Did you install the Gjs bindings? They may not be installed by default?

**Comment by austin6598** [comment]
Do i need to install anything besides the gjs package? Also I understand if you don't want to maintain the script, unfortunately I think updating it may be well beyond my capabilities.

**Comment by JasonLG1979** [comment]
You need to update to 1.4.1. 1.4.1 fixes/works around a bug in our MPRIS implementation in 1.4.

**Comment by JasonLG1979** [comment]
Specifically this bug:
 https://github.com/pithos/pithos/issues/516

**Comment by austin6598** [comment]
Ok thanks, that fixed the issue.
