### ISSUE TITLE
Install as Flatpak fails

### ISSUE THREAD

**Issue by jtlpa** [pithos/pithos#483]
command
`flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo`
executed OK

command
`flatpak install flathub io.github.Pithos`
FAILS with no GPG key

OS Debina 9.0, MATE DeskTop

**Comment by TingPing** [comment]
Hmm, this is probably a better question for [flatpak](https://github.com/flatpak/flatpak) but it might have to do with the rather old `flatpak` version.

**Comment by jtlpa** [comment]
Resolved by installing Pithos from the file pithos.flatpakref from http://flatpak.org/apps.html

It appears the instructions at https://github.com/pithos/pithos/wiki/Flatpak are wrong

**Comment by TingPing** [comment]
The instructions aren't wrong, you have some real issue with the flathub repo which should still be resolved there. Anyway closing this since it isn't our issue.
