### ISSUE TITLE
ValueError: Namespace Secret not available

### ISSUE THREAD

**Issue by ArchbishopFlabrus** [pithos/pithos#484]
### Environment

System: Gentoo, kernel 4.9.34-gentoo
Pithos version: 1.3.1
Python info: 

```
~ $ eselect python list
Available Python interpreters, in order of preference:
  [1]   python2.7
  [2]   python3.4
```

### Error 

When trying to launch Pithos:

```
~ $ pithos
Traceback (most recent call last):
  File "/usr/lib/python-exec/python3.4/pithos", line 41, in <module>
    from pithos import application
  File "/usr/lib64/python3.4/site-packages/pithos/application.py", line 24, in <module>
    from .pithos import PithosWindow
  File "/usr/lib64/python3.4/site-packages/pithos/pithos.py", line 40, in <module>
    from . import AboutPithosDialog, PreferencesPithosDialog, StationsDialog
  File "/usr/lib64/python3.4/site-packages/pithos/PreferencesPithosDialog.py", line 21, in <module>
    from .util import get_account_password, set_account_password
  File "/usr/lib64/python3.4/site-packages/pithos/util.py", line 20, in <module>
    gi.require_version('Secret', '1')
  File "/usr/lib64/python3.4/site-packages/gi/__init__.py", line 118, in require_version
    raise ValueError('Namespace %s not available' % namespace)
ValueError: Namespace Secret not available
```

### Troubleshooting

Tried:

- Removing / re-emerging pithos
- `revdep-rebuild` (to check for and fix broken dependencies)

Do I have something screwed up in my system, or is this a problem with the portage ebuild?  Any suggestions?

**Comment by TingPing** [comment]
Build libsecret with gobject-introspection support, the ebuild file should be specifying that.

**Comment by ArchbishopFlabrus** [comment]
This resolved the problem.

Do you know if there's a way to use Pithos without pulling in `gnome-keyring` as an dependency of libsecret?  I may have broken this myself while changing around use flags trying to come up with a workaround.

**Comment by JasonLG1979** [comment]
> Do you know if there's a way to use Pithos without pulling in gnome-keyring as an dependency of libsecret?

Not as far as I know. I think KDE has something similar or at least they're working on it? But AFAIK ATM  gnome-keyring is the only working option.

**Comment by ArchbishopFlabrus** [comment]
Alright, good to know.

Since I caused my own issue and it is now resolved I don't think there's anything actionable here for you kind folks.

**Comment by TingPing** [comment]
@ArchbishopFlabrus The issue should be reported against the package surely.
