### ISSUE TITLE
Notification icon plugin not working in 1.3.1

### ISSUE THREAD

**Issue by alfC** [pithos/pithos#490]
This is the version that ships with Fedora 26. The plugin is grayed out after setting it to ON. The program quits when the window is closed. Pithos doesn't appear in the system tray.

**Comment by JasonLG1979** [comment]
Tray icons of any kind do not work in Wayland.

**Comment by TingPing** [comment]
in GNOME on Wayland\*

A hacky workaround is forcing Pithos to use XWayland but that is not ideal.

**Comment by alfC** [comment]
Thanks, that is a good explanation. I now notice that that media controls are in the "clock" menu. I can minimize Pithos and forget about it. So I won't miss the tray feature too much, (except the "like" button). Thank you so much to Pithos in any case.
