### ISSUE TITLE
notification_icon: Handle gnome-shell 3.26 no longer support tray icons

### ISSUE THREAD

**Issue by TingPing** [pithos/pithos#491]
They removed support so we will have to workaround that. Alternatively drop support for trays on non StatusNotifier platforms.

**Comment by JasonLG1979** [comment]
Told you so,lol!!! Is there really a way to workaround that? My vote is to drop support for trays on non StatusNotifier platforms and go from there.

**Comment by TingPing** [comment]
Well I feel bad for the XFCE users that might want it. Maybe we just hardcode an if GNOME and !statusnotifier check.

**Comment by JasonLG1979** [comment]
The question then becomes how much longer until Gtk.StatusIcon is completely deprecated?

Sniffing DE's is less than reliable.

XFCE is in the process of porting to GTK3 or maybe has already? Between them and MATE they'll have to figure out what they're going to do as far as tray icons.

**Comment by TingPing** [comment]
Gtk4 is when it is removed, we still have some time. I don't think XFCE has any plans to remove their tray.

**Comment by JasonLG1979** [comment]
> I don't think XFCE has any plans to remove their tray.

Then they'll have to figure something out as far as how Gtk apps are going to do tray icon and then we'll have to go from there?

Is there a reliable way to tell for sure we're on GNOME Shell?

**Comment by xmbwd** [comment]
Does [TopIcons](https://extensions.gnome.org/extension/495/topicons/) work in GNOME?  I will try it later but have three other machines in various states at the moment.

**Comment by TingPing** [comment]
Extensions should continue to work fine.

**Comment by JasonLG1979** [comment]
Or https://github.com/JasonLG1979/gnome-shell-extensions-mediaplayer for Pithos at least. It can do everything the notification icon plugin can plus it has full tracklist and playlist support. In Pithos version 1.3 + you can rate songs, change stations and view and jump to upcoming songs.

**Comment by JasonLG1979** [comment]
I've got a PR in to fix this.
So basically it boils down to this:

Any version of GNOME shell with appindicator libs installed with the appindicator extension gets a notification icon via appindicator.

GNOME Shell <= 3.24 without appindicator support gets a standard tray icon.

GNOME Shell  3.26 + without appindicator libs gets nothing.

Everyone else with appindicator libs/KStatusNotifier support gets a notification icon via appindicator

Everyone else without appindicator libs/KStatusNotifier support gets a standard tray icon.

It's rather convoluted but I think that it covers most of the bases.

**Comment by TingPing** [comment]
Sounds good.

**Comment by JasonLG1979** [comment]
Well merge it then ;P

**Comment by JasonLG1979** [comment]
On a related note this PR fixes switching icons in the Notification Icon plugin settings in https://extensions.gnome.org/extension/615/appindicator-support/.

https://github.com/rgcjonas/gnome-shell-extension-appindicator/pull/81

Before it didn't work because they were/are adding "-panel" to every icon name for some reason? Which lead to the icon always falling back to our full color icon.

**Comment by JasonLG1979** [comment]
Everything altogether, my PR's + appindicator libs + the appindicator extension = no disruption in the notification icon plugin + a nice pretty symbolic pithos icon in the panel.
![screenshot from 2017-08-13 14-57-37](https://user-images.githubusercontent.com/6667703/29252997-4db29744-8038-11e7-910b-a6c0249c2ba6.png)

**Comment by TingPing** [comment]
So I discussed this with some GNOME folks and the proper way to do this is check for an owner of `_NET_SYSTEM_TRAY_S*` in X11.

Here was the result in C: https://github.com/hexchat/hexchat/commit/d99cd18fb9e97c4ec264ad7a72bf7e2ba9a6dfa2

This is not easy to translate to Python though since it uses raw Xlib...

Other offered solutions were to make a non-visible `Gtk.StatusIcon` and check its `embedded` property. This seems reasonable though a simple `idle_add` was not sufficient in some cases so we need a more robust solution to that.

**Comment by JasonLG1979** [comment]
That just sounds hacky. If they're going to ditch the panel icons then they need to make the status icon throw an error or something if it's not supported.

**Comment by TingPing** [comment]
> That just sounds hacky.

That is the opposite of hacky IMO, guessing based on versions of shells is hacky.

>  they need to make the status icon throw an error

They can neither time travel nor break API.

**Comment by JasonLG1979** [comment]
It's not a guess if you get the version and you know that version doesn't support it...

...because GNOME never breaks API's,lol!!!

**Comment by JasonLG1979** [comment]
My point is that they're the ones causing a silent failure. They should do something to make the fact that it's not supported a little more easy to figure out.

**Comment by TingPing** [comment]
While I agree its a frustrating change it is worth noting it has always been a silent failure on any desktop that didn't have a system tray which was entirely possible.

**Comment by JasonLG1979** [comment]
Silent Failure no es bueno

**Comment by JasonLG1979** [comment]
As discussed a while ago via email, if we're planning on going full GNOME can we FINALLY just remove the notification icon plugin?

**Comment by JasonLG1979** [comment]
It would cut down on your flatpak sandbox holes...
