### ISSUE TITLE
Meson.build broken for versions < 0.40.0 (The error message that 0.40.0 or later is needed is never shown on older versions of meson)

### ISSUE THREAD

**Issue by neoh4x0r** [pithos/pithos#496]
Meson.build for meson versions less than 0.40.0 will never show 
a message that 0.40.0 or later is needed because Meson.build requires
a language parameter on versions less than 0.40.0.

However, on 0.40.0 or later this is not an issue and it works with the default Meson.build from rev: f5c089061208c1c4f63792292f09f6a554e0e062.

I just wanted to bring this to your attention so people will know that a later version of meson is needed rather than meson.build having syntactic errors.

The error message is something like this:

Error line 1 col 1 .....the project element is missing a language parameter.

This is the contents of Meson.build (as of now):
```meson
project('pithos',
  version: '1.3.1',
  meson_version: '>= 0.40.0'
)
i18n = import('i18n')
pkgdatadir = join_paths(get_option('datadir'), meson.project_name())
install_subdir('pithos', install_dir: pkgdatadir)
subdir('data')
subdir('bin')
subdir('docs')
subdir('po')
meson.add_install_script('meson_post_install.py')
```

Changing it to something like this (including the language parameter) should fix it:
(this also does not introduce any errors on 0.40.0 or later -- so it should be safe to do)
```meson
project('pithos',
  version: '1.3.1', 
  language: 'python',
  meson_version: '>= 0.40.0'
)
i18n = import('i18n')
pkgdatadir = join_paths(get_option('datadir'), meson.project_name())
install_subdir('pithos', install_dir: pkgdatadir)
subdir('data')
subdir('bin')
subdir('docs')
subdir('po')
meson.add_install_script('meson_post_install.py')
```

**Comment by JasonLG1979** [comment]
Put in a PR. I'm sure @TingPing will merge it if it works as you say.

**Comment by TingPing** [comment]
So this is sadly just a mistake of meson in that it parsed the `project()` language bits before it parsed the `meson_version` bits so it doesn't understand that it needs a newer version before it errors. Since we cannot time travel that cannot be fixed in past Meson releases.

The best we can do is document that we need this version of meson. `language: 'python'` isn't a real thing so not a real solution.

**Comment by neoh4x0r** [comment]
@TingPing 
I have amended by previous example at the bottom of the comment...


According to the meson build reference http://mesonbuild.com/Reference-manual.html#project

```
void project(project_name, list_of_languages, ...)
The first argument to this function must be a string defining the name of this project. 

It must be followed by one or more programming languages that the project uses.

Supported values for languages are c, cpp (for C++), objc, objcpp, fortran, java, 
cs (for C#) and vala.

project('foobar', 'c')
if compiling_for_osx
  add_languages('objc')
endif
```

so build.meson should have this then (since according the above it is required as part of the specification):
(where the language parameter could be c, cpp (for C++), objc, objcpp, fortran, java, cs (for C#) and vala)
I'm not sure what "language" would be appropriate for this project -- so I chose c.

I assume that on v0.40.0 or later -- that if the languages are not specified, then it assumes that all supported languages are valid. 

Like I said, adding this does not cause any issues and makes it conform to the spec (so that older versions will parse it correctly).
```
project('pithos', 'c'
  version: '1.3.1', 
  meson_version: '>= 0.40.0'
)
i18n = import('i18n')
pkgdatadir = join_paths(get_option('datadir'), meson.project_name())
install_subdir('pithos', install_dir: pkgdatadir)
subdir('data')
subdir('bin')
subdir('docs')
subdir('po')
meson.add_install_script('meson_post_install.py')
```

**Comment by TingPing** [comment]
Meson moves very fast so I'm not going to waste my time working around old versions. The change you propose certainly has a downside, currently we depend upon no compiler but if we lie and say `'c'` then we pull in dependencies on a C compiler.

You can install a newer version with `pip3 install --user meson`

**Comment by TingPing** [comment]
Also I updated the docs for Meson to be more accurate: https://github.com/mesonbuild/meson/commit/8a636052bd71dde2644890ad2263d2024ab9db76
