### ISSUE TITLE
allow screen to go dark and lock without stopping?

### ISSUE THREAD

**Issue by wolftune** [pithos/pithos#498]
Pithos stops as soon as my screen goes dark and the session locks. I don't want it to inhibit that level of suspend, but I'd like it to inhibit full suspend and to keep playing during a locked screen…

**Comment by TingPing** [comment]
Disable *Preferences > Plugins > Screensaver Pause*

**Comment by wolftune** [comment]
Oh, geez. The *single* menu item just called "Pithos" didn't look like a menu to me, so I didn't realize there *was* a menu at all!

**Comment by JasonLG1979** [comment]
> Oh, geez. The single menu item just called "Pithos" didn't look like a menu to me, so I didn't realize there was a menu at all!

In GNOME Shell that menu is in the panel. In Unity that menu is either in the panel or window border. It's up to your window manager where the menu is. As far as the single "Pithos" menu item, that's standard for GNOME apps.

**Comment by wolftune** [comment]
Gotcha. I'm on KDE

**Comment by JasonLG1979** [comment]
When we eventually migrate to a headerbar it'll be a button on most other DE's. not sure how KDE handles it?

**Comment by TingPing** [comment]
@JasonLG1979 Fun fact, GNOME plans on removing the appmenu.

**Comment by julianrichen** [comment]
@TingPing Where was that discussed? GUADEC? Isn't one of the current GNOME goals porting applications to [GMenu/AppMenu](https://wiki.gnome.org/Initiatives/GnomeGoals/PortToGMenu)?

**Comment by TingPing** [comment]
Nothing has been finalized but it was at least agreed upon at GUADEC that the appmenu in shell has poor usability and they would like to change that.

**Comment by julianrichen** [comment]
Do you know of any on-going discussion about the matter online that we can follow?

Also sorry about derailing this thread.

**Comment by TingPing** [comment]
No I don't, that discussion probably won't happen until after 3.26 at least.
