### ISSUE TITLE
Skips to the next song every 5 seconds.

### ISSUE THREAD

**Issue by elementalwindx** [pithos/pithos#510]
Newest Ubuntu on an ODroid XU-4, not a pandora one account. It's been going on for days. No idea why. Can't get it to stop skipping to the next song every 5 seconds on any station I choose. I've turned off all addons as well.

**Comment by JasonLG1979** [comment]
Do you have any problems playing local audio files with any other Gstreamer based music players?

**Comment by elementalwindx** [comment]
I haven't tried. I don't really know how to try either.





On Wed, Sep 6, 2017 at 2:57 AM -0400, "Jason Gray" <notifications@github.com<mailto:notifications@github.com>> wrote:


Do you have any problems playing local audio files with any other Gstreamer based music players?

-

**Comment by JasonLG1979** [comment]
rhythmbox uses Gstreamer for it audio backend. Do you have any problems with local files or internet radio with it?

**Comment by elementalwindx** [comment]
I don’t have any local mp3’s. It’s just a simple pi like device. I can go to Pandora.com and play the audio just fine though.

**Comment by JasonLG1979** [comment]
Download a free mp3 from the internet archive to test it out.

**Comment by JasonLG1979** [comment]
Internet radio in Rhythmbox doesn't require local mp3's. The reason I ask is testing Internet radio in Rhythmbox may tell us if anything is broken as far as streaming in Gstreamer on ARM. Playing a local mp3  in Rhythmbox may tell us if there's something broken/wrong otherwise as far as Gstreamer mp3 playback on ARM or your system is reconfigured or if you're missing a codec or what not.

**Comment by elementalwindx** [comment]
Apparently Rhythmbox is already installed on this ODroid, and I've went under "Radio" "All genres" "Trance" and it plays that just fine.

**Comment by JasonLG1979** [comment]
Try a local mp3

**Comment by elementalwindx** [comment]
Just tried a local mp3 and it plays just fine in rhythmbox.

**Comment by elementalwindx** [comment]
I just tried pithos and it's magically working again. No idea what changed. Haven't even rebooted the system.

**Comment by JasonLG1979** [comment]
The web site may not use the same servers/content delivery services as Pithos. It sounds like you were having connection issues? We're kinda at their mercy when it comes to that. I've had times where Pithos could not connect and the web site works just fine.

**Comment by JasonLG1979** [comment]
Did you ping the urls that Pithos uses?

**Comment by elementalwindx** [comment]
I wouldn't have a clue as to what those URL's are that it uses. Where would I find them?

**Comment by JasonLG1979** [comment]
I's in the source code. But really what I'm getting at is that just because you can ping google doesn't mean there isn't problems with Pandora.

**Comment by JasonLG1979** [comment]
https://github.com/pithos/pithos/blob/master/pithos/pandora/data.py

**Comment by elementalwindx** [comment]
This morning the problem has returned. No idea why. :(

**Comment by elementalwindx** [comment]
odroid@odroid:~$ ping tuner.pandora.com
PING tuner.pandora.com (208.85.40.35) 56(84) bytes of data.
64 bytes from tuner.pandora.com (208.85.40.35): icmp_seq=1 ttl=239 time=90.8 ms
64 bytes from tuner.pandora.com (208.85.40.35): icmp_seq=2 ttl=239 time=95.2 ms
64 bytes from tuner.pandora.com (208.85.40.35): icmp_seq=3 ttl=239 time=105 ms
64 bytes from tuner.pandora.com (208.85.40.35): icmp_seq=4 ttl=239 time=90.0 ms
64 bytes from tuner.pandora.com (208.85.40.35): icmp_seq=5 ttl=239 time=96.4 ms
64 bytes from tuner.pandora.com (208.85.40.35): icmp_seq=6 ttl=239 time=95.3 ms
64 bytes from tuner.pandora.com (208.85.40.35): icmp_seq=7 ttl=239 time=119 ms
64 bytes from tuner.pandora.com (208.85.40.35): icmp_seq=8 ttl=239 time=90.3 ms
64 bytes from tuner.pandora.com (208.85.40.35): icmp_seq=9 ttl=239 time=92.3 ms
64 bytes from tuner.pandora.com (208.85.40.35): icmp_seq=10 ttl=239 time=91.3 ms
64 bytes from tuner.pandora.com (208.85.40.35): icmp_seq=11 ttl=239 time=95.1 ms
64 bytes from tuner.pandora.com (208.85.40.35): icmp_seq=12 ttl=239 time=91.0 ms
64 bytes from tuner.pandora.com (208.85.40.35): icmp_seq=13 ttl=239 time=90.2 ms
64 bytes from tuner.pandora.com (208.85.40.35): icmp_seq=14 ttl=239 time=90.6 ms
64 bytes from tuner.pandora.com (208.85.40.35): icmp_seq=15 ttl=239 time=90.9 ms
64 bytes from tuner.pandora.com (208.85.40.35): icmp_seq=16 ttl=239 time=93.3 ms
64 bytes from tuner.pandora.com (208.85.40.35): icmp_seq=17 ttl=239 time=91.8 ms
64 bytes from tuner.pandora.com (208.85.40.35): icmp_seq=18 ttl=239 time=90.9 ms
64 bytes from tuner.pandora.com (208.85.40.35): icmp_seq=19 ttl=239 time=89.6 ms
64 bytes from tuner.pandora.com (208.85.40.35): icmp_seq=20 ttl=239 time=91.5 ms
64 bytes from tuner.pandora.com (208.85.40.35): icmp_seq=21 ttl=239 time=92.9 ms
64 bytes from tuner.pandora.com (208.85.40.35): icmp_seq=22 ttl=239 time=90.1 ms
64 bytes from tuner.pandora.com (208.85.40.35): icmp_seq=23 ttl=239 time=90.8 ms
64 bytes from tuner.pandora.com (208.85.40.35): icmp_seq=24 ttl=239 time=90.1 ms
64 bytes from tuner.pandora.com (208.85.40.35): icmp_seq=25 ttl=239 time=90.1 ms
64 bytes from tuner.pandora.com (208.85.40.35): icmp_seq=26 ttl=239 time=90.4 ms
64 bytes from tuner.pandora.com (208.85.40.35): icmp_seq=27 ttl=239 time=90.9 ms
64 bytes from tuner.pandora.com (208.85.40.35): icmp_seq=28 ttl=239 time=91.1 ms
64 bytes from tuner.pandora.com (208.85.40.35): icmp_seq=29 ttl=239 time=91.7 ms
64 bytes from tuner.pandora.com (208.85.40.35): icmp_seq=30 ttl=239 time=91.6 ms
64 bytes from tuner.pandora.com (208.85.40.35): icmp_seq=31 ttl=239 time=91.0 ms
64 bytes from tuner.pandora.com (208.85.40.35): icmp_seq=32 ttl=239 time=90.0 ms
64 bytes from tuner.pandora.com (208.85.40.35): icmp_seq=33 ttl=239 time=90.6 ms
64 bytes from tuner.pandora.com (208.85.40.35): icmp_seq=34 ttl=239 time=90.8 ms
64 bytes from tuner.pandora.com (208.85.40.35): icmp_seq=35 ttl=239 time=90.2 ms
64 bytes from tuner.pandora.com (208.85.40.35): icmp_seq=36 ttl=239 time=90.4 ms
64 bytes from tuner.pandora.com (208.85.40.35): icmp_seq=37 ttl=239 time=90.1 ms
64 bytes from tuner.pandora.com (208.85.40.35): icmp_seq=38 ttl=239 time=90.3 ms
64 bytes from tuner.pandora.com (208.85.40.35): icmp_seq=39 ttl=239 time=90.5 ms
64 bytes from tuner.pandora.com (208.85.40.35): icmp_seq=40 ttl=239 time=91.3 ms
64 bytes from tuner.pandora.com (208.85.40.35): icmp_seq=41 ttl=239 time=94.8 ms
64 bytes from tuner.pandora.com (208.85.40.35): icmp_seq=42 ttl=239 time=90.2 ms
64 bytes from tuner.pandora.com (208.85.40.35): icmp_seq=43 ttl=239 time=149 ms
64 bytes from tuner.pandora.com (208.85.40.35): icmp_seq=44 ttl=239 time=90.5 ms
64 bytes from tuner.pandora.com (208.85.40.35): icmp_seq=45 ttl=239 time=108 ms
64 bytes from tuner.pandora.com (208.85.40.35): icmp_seq=46 ttl=239 time=94.2 ms
64 bytes from tuner.pandora.com (208.85.40.35): icmp_seq=47 ttl=239 time=93.3 ms
64 bytes from tuner.pandora.com (208.85.40.35): icmp_seq=48 ttl=239 time=90.5 ms
64 bytes from tuner.pandora.com (208.85.40.35): icmp_seq=49 ttl=239 time=91.9 ms
64 bytes from tuner.pandora.com (208.85.40.35): icmp_seq=50 ttl=239 time=90.8 ms
64 bytes from tuner.pandora.com (208.85.40.35): icmp_seq=51 ttl=239 time=90.7 ms
^C
--- tuner.pandora.com ping statistics ---
51 packets transmitted, 51 received, 0% packet loss, time 50072ms
rtt min/avg/max/mdev = 89.619/93.795/149.284/9.377 ms

**Comment by elementalwindx** [comment]
Think I just figured it out. Our Sophos XG UTM appliance apparently causes the issue when the firewall rule is set to "Scan HTTP" traffic on that rule where all outgoing traffic from our ODroid to the internet happens.

Weird it magically worked Friday, but not today.

Problem appears to have been solved for now. :) Will report back if it continues.

**Comment by JasonLG1979** [comment]
> Think I just figured it out. Our Sophos XG UTM appliance apparently causes the issue when the firewall rule is set to "Scan HTTP" traffic on that rule where all outgoing traffic from our ODroid to the internet happens.

Well then it appears to be a firewall configuration issue, not an issue with either Pithos or Pandora.
