### ISSUE TITLE
Password Required after Relogging

### ISSUE THREAD

**Issue by MggMuggins** [pithos/pithos#511]
I'm running Manjaro KDE, and using the pithos-git package from the AUR.
Whenever I log in, I have to input my pandora password in preferences. However, if I restart pithos, the password has been saved and is not required. The only time I need to enter the password is when I log in again (or reboot).

**Comment by JasonLG1979** [comment]
https://github.com/pithos/pithos/wiki/User-Guide

**Comment by JasonLG1979** [comment]
I ran into this issue testing out the latest Fedora 27 KDE Spin. The GNOME Keyring deamon is not started at login This fixed it for me (specifically the PAM method):
https://wiki.archlinux.org/index.php/GNOME/Keyring#Using_the_keyring_outside_GNOME

**Comment by MggMuggins** [comment]
Yeah, I got it running, eventually. Lots of work, but it does work.

**Comment by JasonLG1979** [comment]
If KDE had proper support for libsecret you wouldn't need gnome keyring...

**Comment by JasonLG1979** [comment]
I'll update the wiki with the info, or @TingPing is there a way to fix this at install time?

**Comment by JasonLG1979** [comment]
@MggMuggins KSecretService was an attempt to support libsecret/Secret Service but it was still born the other keyring options in KDE are KWallet, which ofc lacks libsecret/Secret Service support and internally on a app by app basis QtKeychain, which interestingly enough on Linux actually prefers GNOME keyring over KWallet if they are both running on a system,lol!!!

I like KDE a lot and used it for a while in the late KDE4 era, but this is an area where it does not shine :(
