### ISSUE TITLE
Playback fails with proxy settings

### ISSUE THREAD

**Issue by Granitosaurus** [pithos/pithos#514]
I'm getting `gst-stream-error-quark` after logging in with proxy and trying to play something. Full log:

> WARNING - util:on_for_alias_finish:64 - Could not get the default Secret Collection.
Attempting to use the session Collection.
ERROR - pithos:on_gst_error:1096 - Gstreamer error: gst-stream-error-quark: Internal data stream error. (1), gstbasesrc.c(2939): gst_base_src_loop (): /GstPlayBin:player/GstURIDecodeBin:uridecodebin0/GstSoupHTTPSrc:source:
streaming stopped, reason error (-5), 1

However when I use the same proxy as an VPN server everything works fine. 

For the record the proxy I'm using requires auth it looks something like:

> http://name%40gmail.com:passsword@127.0.0.1:80

**Comment by Granitosaurus** [comment]
It successfully runs via [proxychains](http://proxychains.sourceforge.net/howto.html) with the same proxy details.

**Comment by JasonLG1979** [comment]
A couple questions:
How are you entering the proxy info into Pithos? There are 3 proxy entries in the prefs window.

Are you able to connect to Pandora just not play song?

Unfortunately I do not have a VPN or proxy service to test against. Simple proxy support seems to work fine (IP:Port)?

**Comment by JasonLG1979** [comment]
We'll need to ask @kreed about proxy support in Gstreamer. He added it in https://github.com/pithos/pithos/commit/7fe5e3b622ffb9026f6199b3e338aff2e88bd778 a few years ago.

**Comment by Granitosaurus** [comment]
I've tried some random free proxy that doesn't require credentials and it works fine, however any proxy from Nordvpn seems to log in but not be able to play any of songs as it throws `gst-stream-error-quark` error four times and then it stops as it reaches the error limit.  

I've only tried using "Proxy url" field as I'm not sure what the other two fields mean.

**Comment by JasonLG1979** [comment]
OK, that tells me that either:
A. ```parse_proxy``` https://github.com/pithos/pithos/blob/master/pithos/util.py#L182-L204 is not parsing the proxy into something Gstreamer understands correctly.

Using your example that function should set the souphttpsrc (https://gstreamer.freedesktop.org/data/doc/gstreamer/head/gst-plugins-good/html/gst-plugins-good-plugins-souphttpsrc.html)

Proxy settings like so:
proxy: 127.0.0.1:80
proxy-id: name%40gmail.com
proxy-pw: passsword


Or, B. Proxy support in souphttpsrc broken.

Have you tired changing name%40gmail.com to name@gmail.com?

**Comment by JasonLG1979** [comment]
To really test this though I would need a Nordvpn account or at least access to one...

**Comment by Granitosaurus** [comment]
For point A:
it seems to parse fine as in if I supply:

    < http://name%40gmail.com:password@68.235.53.92:80
    > ('http', 'name%40gmail.com', 'password', '68.235.53.92:80')

Weirdly enough it works with `@` instead of `%40` - both logging in and streaming!   
Though I could have sworn it didn't work the first time I tried it and I couldn't even log in. Usually `@` is expected to be escaped (as in $http_proxy etc).  

Even weirder now it works without any proxy at all, straight with naked Estonian IP eventhough pandora.com is saying it's not available in my country.

**Comment by JasonLG1979** [comment]
> Usually @ is expected to be escaped (as in $http_proxy etc).

Yep, that function doesn't escape anything, and neither does Gstreamer apparently?

@TingPing since that's only used by Gstreamer do you think we should always escape that?

**Comment by JasonLG1979** [comment]
I signed up for a month of Nordvpn to test it out and can confirm it works if the text is escaped.

**Comment by JasonLG1979** [comment]
So @Granitosaurus does that solve your problem? If so close the issue.

**Comment by Granitosaurus** [comment]
Yup, thanks for the help!

**Comment by TingPing** [comment]
> @TingPing since that's only used by Gstreamer do you think we should always escape that?

Do you have that backwards, gstreamer doesn't want escaped text? Since `@` works?

**Comment by JasonLG1979** [comment]
> Do you have that backwards, gstreamer doesn't want escaped text? Since @ works?

You know what I mean ;P...
```python
urllib.parse.unquote(...)
```
Seems to do the trick.

**Comment by TingPing** [comment]
Why is it getting quoted before it makes it there in the first place?

**Comment by JasonLG1979** [comment]
I'm guessing the OP just copy and pasted it from somewhere?

**Comment by Granitosaurus** [comment]
AFAIK every place that I ever used proxy required `@` symbol to be escaped (e.g. $http_proxy environment variable) 

Maybe it would be worthwhile to unescape it in `parse_proxy`? Wouldn't take much and would handle both cases.

**Comment by JasonLG1979** [comment]
> Maybe it would be worthwhile to unescape it in parse_proxy? Wouldn't take much and would handle both cases.

I agree. Always just ```urllib.parse.unquote(...)``` covers the bases. It doesn't hurt anything.

**Comment by TingPing** [comment]
The problem with always unquoting is there might be a case where that incorrectly changes values and then the user has no solution to it. If the user inputs bad data that is on them.. but we could try to be more clear about that in the tooltip or something.
