### ISSUE TITLE
Pithos unlaunchable, KDE Neon (Ubuntu 16.04)

### ISSUE THREAD

**Issue by ForLoveOfCats** [pithos/pithos#515]
OS: KDE Neon (Ubuntu 16.04)
Issue: Cannot launch Pithos
Install Repository: Official Pithos [PPA](https://launchpad.net/~pithos/+archive/ubuntu/ppa)
Pithos Version: `1.4.0-1~ppa0~xenial`

Update came through, installed update, Pithos no longer launches.
Apt verifies package is installed, pithos.deskop still exists, yet does not show up in desktop menu.
Attempting to launch via Bash gives the following error message: 
`The program 'pithos' is currently not installed. You can install it by typing:
sudo apt install pithos`

Reinstalling package has no effect.
Installing base Ubuntu repo Pithos version results in a functional Pithos, abet very much out of date.

If I have not provided enough information please tell me what information may be needed and I will get back with requested information.

**Comment by TingPing** [comment]
cc @hotice

**Comment by Sirsurfsalot** [comment]
Same problem as ForLoveOfCats

**Comment by necrogram** [comment]
I'm having the same problem on ubuntu gnome 17.04

```
dave@dtidclnx:/usr/bin$ sudo apt install pithos
Reading package lists... Done
Building dependency tree       
Reading state information... Done
pithos is already the newest version (1.4.0-1~ppa0~zesty).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
dave@dtidclnx:/usr/bin$ which pithos
dave@dtidclnx:/usr/bin$ ls -lh /usr/bin/pi*
-rwxr-xr-x 1 root root  9.9K Apr 23  2016 /usr/bin/pi1toppm
-rwxr-xr-x 1 root root  9.9K Apr 23  2016 /usr/bin/pi3topbm
-rwxr-xr-x 1 root root  205K Dec 13  2016 /usr/bin/pic
lrwxrwxrwx 1 root root    22 Sep 26 10:14 /usr/bin/pico -> /etc/alternatives/pico
-rwxr-xr-x 1 root root  8.2K Mar 18  2017 /usr/bin/piconv
-rwxr-xr-x 1 root root   105 Jul  5  2014 /usr/bin/pidgin
-rwxr-xr-x 1 root root 1021K Mar 10  2017 /usr/bin/pidgin.orig
-rwxr-xr-x 1 root root  2.4K Jan 24  2017 /usr/bin/pilconvert
-rwxr-xr-x 1 root root   16K Jan 24  2017 /usr/bin/pildriver
-rwxr-xr-x 1 root root  2.7K Jan 24  2017 /usr/bin/pilfile
-rwxr-xr-x 1 root root  1.1K Jan 24  2017 /usr/bin/pilfont
-rwxr-xr-x 1 root root  2.6K Jan 24  2017 /usr/bin/pilprint
lrwxrwxrwx 1 root root    26 Sep 26 10:14 /usr/bin/pinentry -> /etc/alternatives/pinentry
-rwxr-xr-x 1 root root   59K Feb  6  2017 /usr/bin/pinentry-curses
-rwxr-xr-x 1 root root   67K Feb  6  2017 /usr/bin/pinentry-gnome3
lrwxrwxrwx 1 root root    30 Sep 26 10:14 /usr/bin/pinentry-x11 -> /etc/alternatives/pinentry-x11
-rwxr-xr-x 1 root root   39K Mar  1  2017 /usr/bin/pinky
dave@dtidclnx:/usr/bin$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 17.04
Release:	17.04
Codename:	zesty
dave@dtidclnx:/usr/bin$ 
```

**Comment by stevenbell** [comment]
Same problem here.  It looks like the binaries aren't included in the PPA, only the docs:

```
steven@mycomputer:~$ dpkg-query --listfiles pithos
/.
/usr
/usr/share
/usr/share/doc
/usr/share/doc/pithos
/usr/share/doc/pithos/changelog.Debian.gz
/usr/share/doc/pithos/copyright
```
I'm on Ubuntu 17.04.

**Comment by lordairivis** [comment]
Same problem on Linux Mint MATE 18.2

**Comment by BandonRandon** [comment]
I also have this problem. While waiting on a fix I was able to build from source: https://github.com/pithos/pithos/wiki/Installing-from-Source

**Comment by TingPing** [comment]
I just deleted the new version until somebody gets around to actually fixing it. Ill close this issue though.
