### ISSUE TITLE
MPRIS plugin fails on Ubuntu 17.10

### ISSUE THREAD

**Issue by JasonLG1979** [pithos/pithos#516]
The MPRIS plugin fails with this traceback on Ubuntu 17.10:
```
WARNING - mpris:on_prepare:51 - Failed to create DBus mpris service: Gio.DBusNodeInfo.generate_xml() takes exactly 3 arguments (2 given)
```

The offending line is:
https://github.com/pithos/pithos/blob/master/pithos/plugins/dbus_util/DBusServiceObject.py#L296

Since it's just a logging line I don't really see any harm in just skipping it like so:

```python
        try:
            logging.debug('--- XML: ---\n%s\n-------' %node_info.generate_xml(0).str)
        except TypeError:
            pass
```

What do you think @TingPing?

**Comment by TingPing** [comment]
Seems fine.
