### ISSUE TITLE
Ditch appindicator and write our own DBus interfaces/proxies

### ISSUE THREAD

**Issue by JasonLG1979** [pithos/pithos#517]
As noted in https://github.com/ubuntu/gnome-shell-extension-appindicator/issues/74 it doesn't seem that Canonical plans on maintaining the code and/or they intend to bless an incompatible fork.

Since the parts that we care about are just abstraction layers on top DBus interfaces, either interfaces we can just create ourselves or interfaces we can just connect to I really don't see the point in using 3rd party libs with questionable futures.

Most of the work is already done with https://github.com/pithos/pithos/blob/master/pithos/plugins/dbus_util/DBusServiceObject.py

As convoluted as the state of tray icons in general in Linux is right now it might actually be a cleaner solution...

**Comment by TingPing** [comment]
I did look into this, replacing appindicator is easy the problem is replacing dbusmenu which is god awful.

I honestly think we should try to extend existing implementations of trays to use a new, more sane, standard for menus.

**Comment by JasonLG1979** [comment]
Good luck getting the different DE's to agree on a standard, that's why we're here in the 1st place. Appindicator is the defacto standard ATM just because no one can agree on a standard.

**Comment by JasonLG1979** [comment]
ATM as a developer you're forced to either use nothing or the garbage that is appindicator...

**Comment by TingPing** [comment]
https://github.com/jjk-jacky/statusnotifier

**Comment by JasonLG1979** [comment]
That just glues the KDE statusnotifier interfaces to libdbusmenu. I can do that myself... That doesn't solve the "libdbusmenu sucks" problem at all...

**Comment by TingPing** [comment]
I gets rid of 2/3rds of libappindicator. Rewriting libdbusmenu will not be a fun task.

**Comment by JasonLG1979** [comment]
It's in C. Unless we want to use ctypes we might as well do it our self.

**Comment by TingPing** [comment]
No reason for us to fear C, hell if we make something not awful others can use it then.

**Comment by TingPing** [comment]
Also to clarify it is a standard gobjecty library, we get g-i bindings of course.

**Comment by JasonLG1979** [comment]
> Also to clarify it is a standard gobjecty library, we get g-i bindings of course.

I'm not sure how the whole bindings thing works. I was unaware that any gobjecty library got bindings automagically even if it's not a part of PyGObject?

**Comment by TingPing** [comment]
> I'm not sure how the whole bindings thing works. I was unaware that any gobjecty library got bindings automagically even if it's not a part of PyGObject?

`g-ir-scanner` parses C files and outputs a `.gir` file which describes it then `g-ir-compiler` generates a `.typelib` file from that which PyGObject can import.

**Comment by JasonLG1979** [comment]
Cool. Have you tried that lib to see how well it works?

**Comment by TingPing** [comment]
I only fiddled with it but it seems fine. The codebase is much smaller than AppIndicator and exposes more features of StatusNotifier since it was designed for that interface unlike AI and it doesn't pretend falling back to a legacy tray icon is the same thing.

There are a few minor things it needs like appending the icon path to run in tree and sadly he is not interested in using Meson for its build system so I would have to do slightly more work to bundle it but these are not deal breakers.

In the end though it doesn't have any major wins it is just a slightly better codebase that is maintained. It still technically is a dependency even if bundled and we don't avoid libdbusmenu but I don't think we can easily.

**Comment by JasonLG1979** [comment]
@TingPing I'm going to close this. Currently our plug does pretty well. Thanks to your work on it lately. I agree that there really isn't much to gain from reinventing a broken wheel.
