### ISSUE TITLE
Plugin Idea: Touch Friendly Interface

### ISSUE THREAD

**Issue by Caleb68864** [pithos/pithos#523]
The basic idea would be to make the buttons bigger and more touch friendly.
Also adding buttons from thumbs up, thumbs down, and tired of track to the main screen.
I don't think this would be too difficult, but I'm not sure if this could be done as a plugin or if forking pithos would be necessary.

If some can get me pointed in the right direction I could start on the code.

Thanks,

**Comment by TingPing** [comment]
I don't think anything like that should be a plugin. A UI redesign has been planned for a while and it includes things like buttons for rating.

**Comment by JasonLG1979** [comment]
> The basic idea would be to make the buttons bigger and more touch friendly.
> Also adding buttons from thumbs up, thumbs down, and tired of track to the main screen.

1. We don't generally decide the size of the buttons. You can but It really should be left up to the theme to decide. If you want bigger more touch friendly buttons, choose a theme with more padding in the buttons and/or adjust the scale factor.

2. As @TingPing said For 1.5 we plan on redesigning the UI. A non-functional wip preview can be seen here:
https://github.com/pithos/pithos/issues/487
 and further discussion is here:
 https://github.com/pithos/pithos/issues/273
