### ISSUE TITLE
Add more step-by-step instructions for meson build

### ISSUE THREAD

**Issue by glolsh** [pithos/pithos#526]
Right now build manual is poorly written, so I can't build anything with it.
Meson needs two directories as parameters and some additional info in project.
 I think this needs to be in manual.

**Comment by JasonLG1979** [comment]
The instructions provided by @TingPing work just fine for me? It may be that you are using an old version of meson? If I remember correctly you'll need at least version 1.4.

**Comment by TingPing** [comment]
Meson version of >= 0.40.0

**Comment by TingPing** [comment]
If your distro is outdated you can do `pip3 install --user meson`

**Comment by glolsh** [comment]
Okay, I'll check this, thank you

**Comment by TingPing** [comment]
There are no working deb files afaik. If you just are trying to run Pithos and not develop it simply use the flatpak instructions linked on https://pithos.github.io

**Comment by glolsh** [comment]
Thank you @TingPing.
