### ISSUE TITLE
Interrupt when connecting or disconnecting from VPN

### ISSUE THREAD

**Issue by scottkosty** [pithos/pithos#528]
There is no interruption if I disconnect/reconnect to a WiFi network. However, if I'm listening to Pithos and then I connect to a VPN, at some point (I guess when the buffer runs out?) pithos pauses for about 10 seconds as it appears to need to buffer and could not buffer in advance. I experience the same issue with disconnecting from a VPN.

I can reproduce with two different ways of connecting to a VPN: with Cisco AnyConnect, as well as with expressvpn.

I do not experience a similar issue with e.g. watching a video on youtube. The buffering of the video is not interrupted by connecting or disconnecting from VPN.

I've reproduced with Pithos 1.3.1 and current master (33c0a1c1). I'm on Ubuntu 16.04.

I'm happy to test any potential patch.

**Comment by JasonLG1979** [comment]
It's likely an issue with the souphttpsrc Gstreamer element:
https://gstreamer.freedesktop.org/data/doc/gstreamer/head/gst-plugins-good/html/gst-plugins-good-plugins-souphttpsrc.html

I'm not a soup expert, but if I had to guess the pauses you're seeing is souphttpsrc doing it's thing, whatever that is, trying to renegotiate the connection.

> I do not experience a similar issue with e.g. watching a video on youtube. The buffering of the video is not interrupted by connecting or disconnecting from VPN.

There are many different buffering methods/strategies currently Pithos uses what gstreamer call stream buffering. Basically in memory buffering where as your browser may very well be using download buffering.

**Comment by scottkosty** [comment]
Thanks a lot for the detailed, explanation, Jason! This is obviously a minor issue, and sounds complicated, so no worries if you need to close this to keep things clean. If someone in the future does write a patch that they would want me to test, let me know. I'm happy to do so.

**Comment by JasonLG1979** [comment]
I'm currently working on streamlining our playback pipeline.

**Comment by scottkosty** [comment]
> I'm currently working on streamlining our playback pipeline.

Nice!

**Comment by JasonLG1979** [comment]
Try this branch see if it has any effect:https://github.com/JasonLG1979/pithos/tree/move-player-logic-out-of-main

**Comment by scottkosty** [comment]
Just tried it (commit 60077ff4) and I still see the issue. Note also that I just reproduced the issue with a video on ESPN. So perhaps it is due more due to the specific HTML 5 player that is being used, not just the browser. For the ESPN video, the pause was only 1.5 seconds. For youtube there is no disruption. For Pithos it is about a 10 second pause.

**Comment by JasonLG1979** [comment]
> Just tried it (commit 60077ff) and I still see the issue. Note also that I just reproduced the issue with a video on ESPN. So perhaps it is due more due to the specific HTML 5 player that is being used, not just the browser. For the ESPN video, the pause was only 1.5 seconds. For youtube there is no disruption. For Pithos it is about a 10 second pause.

That branch uses download buffering so once the song is cached to disk network connectivity(or lack there of) shouldn't matter at all. Once it's cached to disk it's playing off the cached file.

**Comment by JasonLG1979** [comment]
I have a 500Mb connection so by like 2 or 3 secs into the song it's cached. I can disable networking completely and the song will continue uninterrupted.

**Comment by scottkosty** [comment]
Ah yes that explains it then.

**Comment by JasonLG1979** [comment]
@scottkosty if you are satisfied with my explanation/speculation feel free to close this.

**Comment by scottkosty** [comment]
OK thanks for your time on this.
