### ISSUE TITLE
Station Drop menu doesn't work - Ubuntu 17.10 (on Wayland)

### ISSUE THREAD

**Issue by masternetra** [pithos/pithos#530]
Have Ubuntu 17.10, and after installing Pithos from it's PPA, I find I am unable to change the station, clicking on the station drop down menu, does nothing. Everything else thus far seems to work though. On the default Wayland session.

**Comment by JasonLG1979** [comment]
The Pithos PPA is as of this writing out of date. If you're a user who want to have the latest and greatest Pithos release flatpak is recommended route. Install instructions are in the wiki:

https://github.com/pithos/pithos/wiki/Flatpak

I can't reproduce your issue with git master on Ubuntu 17.10 wayland.

**Comment by austin6598** [comment]
> The Pithos PPA is as of this writing out of date. 

Would you be able to update the PPA?

**Comment by TingPing** [comment]
It is possible but the build system has changed this release so somebody needs to do that extra work.
