### ISSUE TITLE
Clock sync error since daylight change

### ISSUE THREAD

**Issue by RyanNerd** [pithos/pithos#534]
Error: `Correct your system's clock. If the problem persists, a Pithos update may be required`

My clock uses the network time as read from `time.nist.gov` -- why Pithos thinks my clock is out of sync is beyond me.

![image](https://user-images.githubusercontent.com/10543911/32467962-a9762550-c309-11e7-91fa-4bbc9c0457fc.png)

**Comment by JasonLG1979** [comment]
Pithos isn't causing that error it just relaying a Pandora error.

**Comment by JasonLG1979** [comment]
I can duplicate the error by adding an hour to ```self.time_offset``` in pandora.py:
https://github.com/pithos/pithos/blob/master/pithos/pandora/pandora.py#L299

What is the output of these 2 commands?:
```date```
and
```python3 -c 'from datetime import datetime; print(datetime.now())'```

**Comment by JasonLG1979** [comment]
And also:
```python3 -c 'import time; print(time.time())'```

**Comment by RyanNerd** [comment]
Thanks for looking into this. I discovered my issue. For some reason my laptop now has a delay in establishing a network connection and I have Pithos as a part of my boot sequence so sometimes the time was not getting set properly because of the network connection issue.

**Comment by JasonLG1979** [comment]
> Thanks for looking into this. I discovered my issue. For some reason my laptop now has a delay in establishing a network connection and I have Pithos as a part of my boot sequence so sometimes the time was not getting set properly because of the network connection issue.

The quick and dirty solution would be to use a shell script to start Pithos after a short delay.
