### ISSUE TITLE
If Pithos is relaying a Pandora error then keep `Pithos` out of the error message

### ISSUE THREAD

**Issue by RyanNerd** [pithos/pithos#535]
Related to #534 - Pithos relays a Pandora error when a time sync error occurs -- however part of the error message is:  `a Pithos update may be required`  

This makes it sound like an issue with Pithos and not Pandora.

**Comment by JasonLG1979** [comment]
That's there because at any point Pandora may change their API. Since Pithos is not an official client, when/if they do they don't give us a heads up. So when things break we have to reverse engineer the API and update Pithos.

**Comment by JasonLG1979** [comment]
Also all Pandora generated errors clearly prefaced with, "Pandora Error:" so I think it's pretty clear that they're a Pandora error...

https://github.com/pithos/pithos/blob/master/pithos/pandora/pandora.py#L95
https://github.com/pithos/pithos/blob/master/pithos/pandora/pandora.py#L228-L244

**Comment by TingPing** [comment]
The best we could probably do is have it query our website if an update is available and only tell users to update in that case. This used to be a worse problem years ago which is why this page exists: https://pithos.github.io/itbroke.html

**Comment by RyanNerd** [comment]
Ah...I see. Thx. @TingPing Do you want me to create a PR to query the website and check version tags when this situation occurs?

**Comment by JasonLG1979** [comment]
> Ah...I see. Thx. @TingPing Do you want me to create a PR to query the website and check version tags when this situation occurs?

That would create false positives. You're previous bug for example would trigger it even though an update would not solve your issue. A easier solution would be to just make the error string more clear. Something like:

'If the problem persists it may indicate a Pandora API change. A Pithos update may be required.'

**Comment by RyanNerd** [comment]
Since this change has been made and merged I am closing this issue. Thanks everyone!
