### ISSUE TITLE
Default to High Quality instead of Medium 

### ISSUE THREAD

**Issue by JasonLG1979** [pithos/pithos#538]
MP3 is no longer patent encumbered so the chance that a distro will ship a MP3 decoder out of the box is more likely than it will ship a AAC decoder.

**Comment by TingPing** [comment]
Agreed, plus its a higher quality GStreamer plugin/decoder IME anyway.

**Comment by JasonLG1979** [comment]
There are many choices for decoding MP3's. In my tests mpg123audiodec is the clear winner.

Here's a breakdown of the choices(at least as far as I can find)
mpg123audiodec - smoking fast, light on resources and sounds pretty good.
flump3dec - Slow and doesn't sound the greatest but still light on resources.
avdec_mp3* - Serious resource hog(like 25MB more resident memory than mpg123audiodec)
mad - I haven't tested. Does anyone still use mad?

**Comment by JasonLG1979** [comment]
For AAC's there's really only the choice between faad and avdec_aac*
Of those avdec_aac is again a huge resource hog and really doesn't sound noticeably better.

**Comment by JasonLG1979** [comment]
In the latest commit in https://github.com/pithos/pithos/pull/513 by using giosrc when we don't need proxy support and preferring mpg123audiodec for MP3's and faad for AAC's I've managed to shave off up to around 35-40MB from the resident memory compared to souphttpsrc + libav decoders.(110MB-ish to 72MB-ish) It's all dynamic ofc though. If a user only has libav decoders installed and needs proxy support they're back to about 110MB.

**Comment by TingPing** [comment]
How bout `ffmpeg`'s mp3 decoder?

**Comment by JasonLG1979** [comment]
libav is ffmpeg

**Comment by TingPing** [comment]
Ah `avdec_`, gotcha. So just for the info I was using `ffmpeg` in the flatpaks for last release just to avoid dealing with gstreamer's awful build system but the current stable flatpaks use the `mpg123` and `faad` GStreamer plugins.

**Comment by JasonLG1979** [comment]
> but the current stable flatpaks use the mpg123 and faad GStreamer plugins.

That's the way to go IMHO. But for a standard install normally you'd never know what if any decoders you have until decodebin autoplugs and the rank of the decoders don't seem to follow what I'd expect. To me the priority should be priority: resource useage, speed, sound quality.

**Comment by TingPing** [comment]
There are other factors such as security. `ffmpeg` (especially codecs like mp3 used on the web) is very heavily audited and installing `gst-plugins-ugly` for example is a literal security nightmare because it pulls in 50 completely awful plugins along with the one you want. Luckily none of this affects our usage but ofc traditional packages have side effects to other applications.

**Comment by JasonLG1979** [comment]
My code doesn't require any particular decoder. It just decides the order in which they are preferred.

**Comment by JasonLG1979** [comment]
I would expect mpg123 to be moved out of ugly anyway with the patents expired.

**Comment by TingPing** [comment]
It actually was already moved into `-good`, `faad` remains in `-bad` though.

**Comment by JasonLG1979** [comment]
So we just need good and bad then?

**Comment by TingPing** [comment]
> So we just need good and bad then?

As far as upstream splits them yes. But like Fedora doesn't package half of `bad` including `faad`.

**Comment by JasonLG1979** [comment]
It's all good. Like I said my code doesn't require faad it just prefers to use it if it's there.

**Comment by TingPing** [comment]
Honestly if `faad` and `ffmpeg` are missing it would be nice to hide those quality options. That also could open up the possibility of being packaged in Fedora or distros with patent policies like it.

**Comment by JasonLG1979** [comment]
It could be done pretty easily. I can hide any quality that doesn't have a element to play it. But really that's not needed. Pithos will throw up an error dialog and automatically try to have the system install missing plugins.

**Comment by JasonLG1979** [comment]
Although I doubt that Fedora would want Pithos in the main repo anyway regardless since we use a private API without the owners permission. It's a bit of a gray area there. Plus big daddy Red Hat may very well count Pandora as a customer(?) so there's that. As I've said before I really don't care personally if Pithos is packaged for any particular distro. I'm OK with just having Flatpak/Flathub as the official way to get Pithos. It will make debugging easier the more Flatpak matures. Instead of debugging, testing against and fielding issues against 20 different distros we only have to worry about 1 build. It also helps that you're really involved with Flatpak/Flathub ; P

**Comment by JasonLG1979** [comment]
> But like Fedora doesn't package half of bad including faad.

I'm on Fedora 27 right now with the rpmfusion repos enabled and installed all the Gstreamer media codecs in the software center and I have faad?

**Comment by JasonLG1979** [comment]
BTW the RAM usage is slightly less on Fedora take a look. Here's the usage at start up:
![screenshot from 2017-11-15 08-44-41](https://user-images.githubusercontent.com/6667703/32842042-ae11ff7e-c9e1-11e7-8e34-3dc7da20ff0e.png)

**Comment by ForLoveOfCats** [comment]
Could it be that rmpfusion provided the copy of gstreamer(and variants) which are installed on your system? And further could rpmfusion have included the codec in question within their packages?

**Comment by JasonLG1979** [comment]
> Could it be that rmpfusion provided the copy of gstreamer(and variants) which are installed on your system? And further could rpmfusion have included the codec in question within their packages?

I'm sure that rpmfusion includes non-free plugins for Gstreamer. That's the point of rpmfusion, to host packages that can't be included in the default Fedora repos. I wouldn't expect Fedora to include faad in their repos. AAC is a patent encumbered format. @TingPing made it kinda sound like there might not be a faad gstreamer plugin available for install on Fedora.

**Comment by TingPing** [comment]
I just meant in the official repos.

**Comment by TingPing** [comment]
Also I don't know how reliable the numbers from `gnome-system-monitor` are. Pithos uses 40MiB here.

**Comment by JasonLG1979** [comment]
The one I care about most is resident memory. The last column is a guess at best. There are different ways to calculate that.

**Comment by JasonLG1979** [comment]
> I just meant in the official repos.

Well duh, Fedora isn't going to have a patent encumbered media decoder in the main repo ;p

**Comment by JasonLG1979** [comment]
> Honestly if faad and ffmpeg are missing it would be nice to hide those quality options. That also could open up the possibility of being packaged in Fedora or distros with patent policies like it.

@TingPing Like I've said that PR for moving the player logic out of the main class already looks for MP3 and AAC decoders. For bonus points I can see about throwing up a dialog to offer to try to install those decoders and I'm pretty sure it's possible to "refresh" Gst in place once the plugins are installed. It would be nice to no wait to throw a bunch of errors before we try to install the plugins and then have to restart.

**Comment by JasonLG1979** [comment]
@TingPing Something like this maybe?:

https://github.com/quodlibet/quodlibet/blob/a26437f49bb3515c8be0bb7aa603a8745897aa2c/quodlibet/quodlibet/player/gstbe/player.py#L657-L704
