### ISSUE TITLE
HeaderBar

### ISSUE THREAD

**Issue by ForLoveOfCats** [pithos/pithos#555]
In the course of the ongoing redesigning of Pithos the decision was made to more closely follow the Gnome Shell HIG. While in many ways this is a good thing, one feature of the Gnome Shell HIG, the HeaderBar, will cause Pithos to look out of place on any Desktop Environment other that Gnome.

In an effort to ensure that Pithos does not lose favor with non-Gnome users I took it upon myself to find a way for the HeaderBar to be used without the unfortunate side effects. I believe I have done so.

I have written a wrapper around HeaderBar, with an almost one to one API, that will allow for HeaderBar to be enabled/disabled with one function call and no duplicated code. I have released this wrapper under GPL 2 and request that the Pithos community look into using either it or the ideas it is built upon.

Wrapperbar: https://github.com/ForLoveOfCats/wrapperbar

**Comment by JasonLG1979** [comment]
window.get_position() doesn't currently work with wayland.

**Comment by JasonLG1979** [comment]
I also get this:
```
Gtk-WARNING **: gtk_window_set_titlebar() called on a realized window
```

**Comment by TingPing** [comment]
I would make a Gtk.ApplicationWindow subclass that automatically uses the expected one so it can just be used in the gtkbuilder file.

That said I'm not convinced we really need to support the old layout as it will just look bad using a toolbar or something at the top.

**Comment by ForLoveOfCats** [comment]
I should have documented that Gtk-WARNING better in the project. That simply means that Gtk must reinitialize the window. All window contents are preserved so there are no side effects. Unfortunately there is no way around this.

**Comment by ForLoveOfCats** [comment]
```That said I'm not convinced we really need to support the old layout as it will just look bad using a toolbar or something at the top.```

Using a toolbar looks arguably better than a HeaderBar on non-Gnome platforms especially as DE's such as XFCE and Plasma 5 use their own systems for handling Window Decorations which this would allow Pithos to respect while still using HeaderBar if the user wishes.

**Comment by ForLoveOfCats** [comment]
I am aware much code in this library is more than likely naive or not up the the quality standards of Pithos. If you find anything wrong, low quality, or a missing feature please feel free to send me a PR.

**Comment by JasonLG1979** [comment]
I really don't see the benefit of moving the contents of the header bar below the title bar. One of the main complaints of the header bar is that it makes the title bar "fat" and takes up more space. This doesn't solve that at all.

I'm with @TingPing just have a user preference that uses one of 2 UI files. I really don't see the need to make it dynamic. If you want it to be dynamic just destroy the old window and make another one in place.

**Comment by ForLoveOfCats** [comment]
```window.get_position() doesn't currently work with wayland.```

I opened an issue and will look into that.
https://github.com/ForLoveOfCats/wrapperbar/issues/1

**Comment by JasonLG1979** [comment]
> I opened an issue and will look into that.

It's a wayland thing. There's no way in currently in wayland to get absolute window position.

**Comment by JasonLG1979** [comment]
> not up the the quality standards of Pithos.

Have you seen some of the code I write,lol!!! No worries.

**Comment by ForLoveOfCats** [comment]
> It's a wayland thing. There's no way currently in wayland to get absolute window position.

I know, and am currently writing logic to not run window position code on Wayland.

> Have you seen some of the code I write,lol!!! No worries.

Good to know 😂 

> I'm with @TingPing just have a user preference that uses one of 2 UI files. I really don't see the need to make it dynamic. If you want it to be dynamic just destroy the old window and make another one in place.

I am all for any method which allows for the toggling of HeaderBar. I built this wrapper to allow for this feature to be added as easily as possible.

> I really don't see the benefit of moving the contents of the header bar below the title bar. One of the main complaints of the header bar is that it makes the title bar "fat" and takes up more space. This doesn't solve that at all.

Actually it does!

![image](https://user-images.githubusercontent.com/30666851/34321165-bf6ecf32-e7d6-11e7-9dbc-a8db935d537f.png)
![image](https://user-images.githubusercontent.com/30666851/34321184-07db033a-e7d7-11e7-9ef4-df66171979cb.png)

As you can see, the second image not only respects my custom Window Decorations; it also look much more native on my Plasma 5 install.

**Comment by JasonLG1979** [comment]
> As you can see, the second image not only respects my custom Window Decorations; it also look much more native on my Plasma 5 install.

Point taken. I don't like the Gtk warnings. And the positioning problems though. I still say it better to just destroy the window and recreate it if you want to do it dynamically.

**Comment by ForLoveOfCats** [comment]
Please excuse my lack of knowledge but would that no require Pithos to rebuild the UI or would this require a Pithos restart?

**Comment by TingPing** [comment]
@ForLoveOfCats See I'm honestly just confused because I think your screenshots there are a perfect example of why headerbars are great and even look good on plasma :P

**Comment by JasonLG1979** [comment]
> Please excuse my lack of knowledge but would that no require Pithos to rebuild the UI or would this require a Pithos restart?

If written correctly data model(s) will be separate from the UI view. So currently it would require a restart since our main class contains the data and the view. When everything is said and done with the rewrite I hope to separate the data from the view.

**Comment by ForLoveOfCats** [comment]
@TingPing  I can understand that. From a Gnome design perspective the HeaderBar looks and functions wonderfully. However while some non-Gnome users are sure to like the look of HeaderBar, it does not respect custom Window Decorations, Window Controls placement, and as mentioned are rather bulky.

@JasonLG1979 Awesome! 👍

**Comment by JasonLG1979** [comment]
If you wanted to go all out you could write a Qt Pandora client?

**Comment by ForLoveOfCats** [comment]
😆 I personally do not have enough free time to even start on a project that large.

**Comment by JasonLG1979** [comment]
You could always use our backend stuff and just write a Qt UI for Pithos but then you'd be pulling in a bunch of GObject stuff and I'm not sure if it would play well with a Qt event loop?

**Comment by ForLoveOfCats** [comment]
Probably not. Anyway a better idea would be to do what LibreOffice does and have an internal UI API which can be used to build plugins which display the UI in different toolkits.

**Comment by TingPing** [comment]
> You could always use our backend stuff and just write a Qt UI for Pithos but then you'd be pulling in a bunch of GObject stuff and I'm not sure if it would play well with a Qt event loop?

I've heard of it being technically possible to mix the two.

**Comment by JasonLG1979** [comment]
> a better idea would be to do what LibreOffice does and have an internal UI API which can be used to build plugins which display the UI in different toolkits.

That would require a generic non-toolkit specific backend. That sounds like way more trouble then it's worth.

**Comment by TingPing** [comment]
>  Anyway a better idea would be to do what LibreOffice does and have an internal UI API which can be used to build plugins which display the UI in different toolkits.

If Pithos were a multi-million line of code complex application funded by a large organization perhaps. But you can write a complete Pandora client in a few thousand lines.

**Comment by ForLoveOfCats** [comment]
@JasonLG1979  That is what I was meaning. True it would be much trouble, but it would be better than hacking a Qt UI on top of a Gtk app. I was not actually implying that it would be a good idea to do.

**Comment by JasonLG1979** [comment]
> I've heard of it being technically possible to mix the two.

I suppose if you use Gstreamer in qt you're using glib in a qt event loop?

**Comment by TingPing** [comment]
> I suppose if you use Gstreamer in qt you're using glib in a qt event loop?

Looks like no, it pulls GLib into Qt: https://cgit.freedesktop.org/gstreamer/qt-gstreamer/tree/src/QGlib
