### ISSUE TITLE
Pithos switches from bluetooth headphones to speakers when song changes

### ISSUE THREAD

**Issue by jdburton** [pithos/pithos#556]
I am running Pithos 1.1.1 on Kubuntu 16.04.3

When I launch Pithos, the sound comes through on my bluetooth headphones, as expected. When the first song ends and the second song starts, Pithos stops playing on headphones and starts playing it on the laptop speakers. 

On pavucontrol, the Playback tab shows Pithos: Playback Stream on BeatsSolo Wireless when playing through the bluetooth headphones. When the song changes, the Pithos: Playback stream briefly disappears, then reappears with Pithos: Playback Stream on Built-in Audio Analog Stereo and playing through the speakers. 

Manually changing the playback to BeatsSolo Wireless sends audio back to the the headphones, but it is unacceptable to have to reset my audio settings after each song!

[pithos-screenshots.zip](https://github.com/pithos/pithos/files/1595498/pithos-screenshots.zip)

**Comment by JasonLG1979** [comment]
That's got nothing to do with Pithos. We don't decide what output the sound goes to. That's between Gstreamer and PulseAudio.

**Comment by JasonLG1979** [comment]
As a side note 1.1.1 is ancient and not supported anyway...

**Comment by jdburton** [comment]
If anyone has a similar problem, the default sink in Pulseaudio was not properly set when the bluetooth headphones were connected. Pithos simply triggered the (Kubuntu?) bug. 

Solution was to load the module-device-manager to Pulseaudio by adding the following to ~/.config/pulse/default.pa

`.include /etc/pulse/default.pa`
`.ifexists module-device-manager.so`
`load-module module-device-manager`                                                                                                                        
`.endif`

**Comment by JasonLG1979** [comment]
If i had to guess that's what all the hubbub was about when they said they improved bluetooth audio with the release of 17.10?
