### ISSUE TITLE
Flatpak running as superuser?

### ISSUE THREAD

**Issue by lordairivis** [pithos/pithos#560]
I'm running Pithos 1.4.1 from flatpak on Mint 18.3, kernel 4.13.0-32 and according to the app titlebar it appears to be running as superuser every time I launch it. I don't recall this being the behavior when using the version from the Ubuntu PPA repository but sadly that version is very out of date at the present time (currently 1.1.1-2).

Command used to launch the flatpak while logged in as a normal user: flatpak update io.github.Pithos && flatpak run io.github.Pithos

![selection_001](https://user-images.githubusercontent.com/2335608/36011236-2bb1b310-0d13-11e8-8e6e-5e1ff03e50dc.png)

Not sure if this is intended, or if I'm doing something wrong, or if I just fundamentally misunderstand flatpak.

**Comment by TingPing** [comment]
`flatpak` is a `suid` binary on your distro but the actual application is not ever running as root.

**Comment by TingPing** [comment]
Personally I might report that to the Cinnamon folks (presumably that is what you use) and maybe they could add `flatpak` to a blacklist to avoid confusion.

Eitherway I guess I'll close that if it is a satisfying answer.
