### ISSUE TITLE
SSL: CERTIFICATE_VERIFY_FAILED

### ISSUE THREAD

**Issue by jam01** [pithos/pithos#562]
**System:**
    Pithos 1.4.1-1.fc27
    Fedora 27
    openssl 1.1.0g-1.fc27

**Problem:**
Pithos consistently fails to connect to the pandora servers with an SSL certificate verification error.
ERROR - pandora:json_call:208 - Network error: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:802)>

**Comment by ForLoveOfCats** [comment]
Same issue here.

OS: Manjaro
Pithos: 1.4.1 (built from latest master)
OpenSSL: 1.1.0.g-1
Python: 3.6.4-2
Python2: 2.7.14-2

Could it be that today is the day that Pandora decided to remove support for the old API? If so then this is a sad day indeed.

**Comment by JasonLG1979** [comment]
Free or Paid subscription? I have had no issues personally with my account, which is a free account. (I let my paid subscription lapse. Either Pandora or Spotify had to go.)

**Comment by ForLoveOfCats** [comment]
Free account here.

**Comment by JasonLG1979** [comment]
Pastebin the output of ```openssl s_client -connect tuner.pandora.com:443``` and I'll compare it to what I get.

**Comment by bhimberg** [comment]
Free account here as well, and same error.

System:
Pithos 1.4.1
Arch 4.15.8-1-ARCH
OpenSSL 1.1.0g

**Comment by Person-93** [comment]
Same issue here.
OS: Debian buster/sid
Kernel: Linux 4.14.0-3-amd64
Pithos: 1.1.2-1 (installed from package manager)
OpenSSL: 1.1.0g-2

**Comment by JasonLG1979** [comment]
OK, enough me 2's. Someone who has the issue please give me the output of the above command in a pastebin.

**Comment by bhimberg** [comment]
https://pastebin.com/BJEuXm2G

**Comment by akcoder** [comment]
I have a free account as well.

https://pastebin.com/pRV8F1CA

**Comment by JasonLG1979** [comment]
OK, I get a different cert. I have no idea how their CDN servers work but if I had to guess it just hasn't filtered down to the server I'm connected to yet? Anyway looks like they've pretty much done the same thing they did in the past. See https://github.com/pithos/pithos/issues/251#issuecomment-155240542

**Comment by JasonLG1979** [comment]
Looks like we might have to ship that cert like we do the cert for paid accounts... @TingPing?

**Comment by JasonLG1979** [comment]
For comparison purposes this is what I get:
https://pastebin.com/RyyKCQB7

**Comment by Person-93** [comment]
https://pastebin.com/1zMUc34J

**Comment by crominger** [comment]
This got my free account playing again on Kubuntu 17.10
sudo wget https://www.geotrust.com/resources/root_certificates/certificates/GeoTrust_Primary_CA.pem -P /etc/ca-certificates/trust-source/anchors/ && sudo update-ca-certificates

**Comment by bhimberg** [comment]
For arch, this worked for me
`sudo wget https://www.geotrust.com/resources/root_certificates/certificates/GeoTrust_Primary_CA.pem -P /etc/ca-certificates/trust-source/anchors/ && sudo trust extract-compat`

This is from a comment in #251, linked above, modified for the correct cert.

**Comment by ForLoveOfCats** [comment]
Worked for me.

**Comment by TingPing** [comment]
@JasonLG1979 Yea we can just include the new one too.

**Comment by 8bg** [comment]
> For arch, this worked for me
> `sudo wget https://www.geotrust.com/resources/root_certificates/certificates/GeoTrust_Primary_CA.pem -P /etc/ca-certificates/trust-source/anchors/ && sudo trust extract-compat`
> 
> This is from a comment in #251, linked above, modified for the correct cert.

I am encountering this problem now on Ubuntu 19.04, but the above commands give an error:

ERROR: cannot verify www.geotrust.com's certificate, issued by ‘CN=DigiCert SHA2 Extended Validation Server CA,OU=www.digicert.com,O=DigiCert Inc,C=US’:
  Self-signed certificate encountered.

**Comment by JasonLG1979** [comment]
They may have changed their cert again. As soon as the problem trickles down to me I'll see what the cert has changed to this time. As far as the wget error you'll need to fire up your Google machine. The above command works just fine for me in Fedora and wget isn't a part of Pithos.
