### ISSUE TITLE
Ad support?

### ISSUE THREAD

**Issue by teldon** [pithos/pithos#563]
I know this was discussed a couple of years ago in #292 but the discussion was locked and never reopened. Was just curious if there's been anything new related to this or not. Me personally, I would like to at least HAVE the option to listen to ads or not.

**Comment by JasonLG1979** [comment]
Well eventually we plan on moving to the new API. The work has started but I've been slacking lately. Anyway, the new API is a lot different when it comes to ads. A lot of the ads are video based and I don't personally plan on adding video support just for ads. If I can find a way to just do audio ads maybe in the distant future but it would be the last thing I worry about.

**Comment by teldon** [comment]
Alright, thanks for answering my question.
