### ISSUE TITLE
IndexError: tuple index out of range

### ISSUE THREAD

**Issue by dln949** [pithos/pithos#564]
Often - but not always, I have not been able to recognize the pattern - I get an error message from Pithos, here is what is reported at the end of the Pithos error log:  

```
Traceback:
 Traceback (most recent call last):
   File "/usr/lib/python3.5/site-packages/pithos/plugins/dbus_util/GioNotify.py", line 155, in on_Notify_finish
     self._replace_id = self.call_finish(result).unpack()[0]
 IndexError: tuple index out of range
```
I am running Pithos 1.3.1 on Ubuntu 17.10 (Xorg).  

What does this error mean?  What causes it?  How to I correct it?  

Thanks.

**Comment by TingPing** [comment]
Update to 1.4.1: https://beta.flathub.org/apps/details/io.github.Pithos
