### ISSUE TITLE
Cannot verify PGP signature

### ISSUE THREAD

**Issue by cmcjacob** [pithos/pithos#566]
==> Verifying source file signatures with gpg...
    pithos-1.4.1.tar.xz ... FAILED (unknown public key B3C7CE210DE76DFC)
==> ERROR: One or more PGP signatures could not be verified!

Installing from Arch Linux.  Tried via pacman and pacaur.  This is a shame because you are the only good native script for pandora.  I won't even proceed to manually install, even though I can - because this is a serious issue.  Fix your goddamn pgp keys or continue to potentially lose users of your product.

**Comment by TingPing** [comment]
You have to import the key yourself: https://wiki.archlinux.org/index.php/Makepkg#Signature_checking

`gpg --recv-keys B3C7CE210DE76DFC` should do.

**Comment by cmcjacob** [comment]
I imported the key using your command, which occurred without error. However installing still incurs the original issue.  Maybe it's one of the "or more" keys I don't know about?  Still looking into this..

**Comment by cmcjacob** [comment]
I had to run this command prior to importing my key: `gpg --full-gen-key`
Afterwards, TinyPing's recommendation worked.  Closing as non issue.
