### ISSUE TITLE
But the STATS!!!!

### ISSUE THREAD

**Issue by ConWrite** [pithos/pithos#567]
Hello, longtime listener, first time, uh poster... maybe, can't keep track of these things.

Anywho, short story long, Last.fm Scrobbling no worky ;-(

Uninstalled, cleared stuff, reinstalled, resync'd with Last.fm, all that jazz.

Still using Version 1.1.1-2 -- most recent in Ubuntu shopping bag (that's my icon at least).

Flatpack is too snobby for the themes I use.

[/Late night Gibberish]

**Comment by pixelherodev** [comment]
1.1.1 is, well, *extremely* outdated. I suggest upgrading to 1.4.1 before doing anything else.

**Comment by pixelherodev** [comment]
You're on Ubuntu, so if you don't want to use flatpak, you can do the following:

Run `sudo apt install git meson`, then `git clone https://github.com/pithos/pithos`, `cd pithos`, `mkdir build`, `cd build`, `meson`, `ninja`, `sudo ninja install`

**Comment by JasonLG1979** [comment]
@ConWrite -

> Still using Version 1.1.1-2 -- most recent in Ubuntu shopping bag (that's my icon at least).

We don't control the version packaged in the default Ubuntu repos.

> Anywho, short story long, Last.fm Scrobbling no worky ;-(

We also don't support ancient versions. Basically only the current most stable and git master is supported. (ATM git master is only 1 trivial commit ahead of the latest stable.)

> Flatpack is too snobby for the themes I use.

I don't know what theme you use but it is possible to install a good many themes in Flatpak.

 @pixelherodev, they would also need to make sure to install all of the dependencies. See the wiki page for instructions to [install from source](https://github.com/pithos/pithos/wiki/Installing-from-Source).

**Comment by pixelherodev** [comment]
True, I’m just used to already having all the deps – my bad.

**Comment by JasonLG1979** [comment]
> True, I’m just used to already having all the deps – my bad.

For the most part if you're already running on the GNOME desktop (and maybe other GTK based DE's?) you'll more than likely have all of them with the exception of maybe codecs but generally that's one of the 1st thing most people install. ```python3-pylast``` would be the main thing missing though in this case. It's not a hard dependency as Pithos will still work, but it is required for Last.fm Scrobbling.

**Comment by ConWrite** [comment]
Did a little digging.

https://launchpad.net/~jasonlevigray3/+archive/ubuntu/unofficial-pithos-dev/+packages

pithos_1.3.1-1ppa1~xenial0_all.deb

I know it's not the latest and all of that but it's working just fine at the moment for me, scrobbling and all, so I'm good. :-)
