### ISSUE TITLE
I'm building a Pandora client for Android, and I'm trying to get a feedback ID

### ISSUE THREAD

**Issue by hacker1024** [pithos/pithos#571]
My issue is weird. I'm writing this here because the same Pandora API call seems to give different results in this app and in my one.

In Pithos, the feedback ID for a song is found in the response of the `station.addFeedback` api method. The response of the method looks like this:
```
{
    "stat": "ok",
    "result": {
        "totalThumbsDown": 4,
        "stationPersonalizationPercent": 57,
        "dateCreated": {
            "date": 9,
            "day": 3,
            "hours": 6,
            "minutes": 3,
            "month": 6,
            "seconds": 56,
            "time": 1404911036840,
            "timezoneOffset": 420,
            "year": 114
        },
        "albumArtUrl": "http://cont-sv5-2.pandora.com/images/public/amz/2/2/9/5/094632175922_130W_130H.jpg",
        "musicToken": "23234b0abdbeb37d",
        "songName": "Nothing Compares 2 U",
        "artistName": "Sinead O'Connor",
        "totalThumbsUp": 20,
        "feedbackId": "21955050420286614",
        "isPositive": false
    }
}
```

In my app, the response is this:
```
{
    "stat": "ok"
}
```

As you can see, no data other than the status code is received.

The only difference I can think of between my request and Pithos's is that I use the iPhone partner login, and Pithos uses the Android partner login. The problem is, when I get a partner login, on requesting the station playlist, I get an error 1003. What's going on?

**Comment by JasonLG1979** [comment]
If you're writing a new client you shouldn't use the crusty JSON API. You should use the newer REST API.

**Comment by JasonLG1979** [comment]
In any case this is not a valid Pithos bug.
