### ISSUE TITLE
The preferences window can be destroyed with the right click menu

### ISSUE THREAD

**Issue by JasonLG1979** [pithos/pithos#573]
Clicking on "Close" in the preferences window's right click menu deletes the window. After that it's gone ofc, to get it back you have to restart Pithos.

I'm pretty sure it's just a matter of adding this to PreferencesPithosDialog.py:

```python
self.connect('delete-event', lambda *ignore: self.hide_on_delete())
```

**Comment by TingPing** [comment]
Sounds reasonable. May want to also call `self.settings.revert()` like cancel does.

**Comment by JasonLG1979** [comment]
Agreed. Any way to close the prefs that isn't clicking Apply should be considered a cancel IMHO.

**Comment by JasonLG1979** [comment]
So this should do it then?

```python
self.connect('delete-event', lambda *ignore: self.settings.revert() or self.hide_on_delete())
```

It's a bit of lambda abuse since ```self.settings.revert()``` doesn't return anything ```self.hide_on_delete()``` will also be called.

**Comment by TingPing** [comment]
I'd prefer you just make it a full function.
