### ISSUE TITLE
Stuck with version 1.1.2

### ISSUE THREAD

**Issue by dooberdoober** [pithos/pithos#576]
Github releases shows 1.4.1 
I cant seem to install 1.4.1
I am running Lubuntu Bionic Beaver.
Is 1.4.1 only available on ubuntu?

Thanks for any assistance

**Comment by TingPing** [comment]
Sadly it looks like Ubuntus package doesn't have a maintainer. We recommend [Flatpak](https://flatpak.org) for installation:

```sh
sudo apt install flatpak/bionic-backports
flatpak install https://flathub.org/repo/appstream/io.github.Pithos.flatpakref
# May require restart for first installation
```

**Comment by dooberdoober** [comment]
Awesome. Thanks for such a rapid reply!
I am now enjoying 1.4.1
