### ISSUE TITLE
1.4.2

### ISSUE THREAD

**Issue by JasonLG1979** [pithos/pithos#582]
Are there any outstanding bugs you need fixed or cleanups that need done before 1.4.2? If so give me a list and I'll whittle away at it.

**Comment by TingPing** [comment]
One thing that I wanted to test is how Pithos behaves in GNOME 3.32 which removed the appmenu. I know in headerbar apps it puts the menu there automatically but since we don't have a headerbar do we just grow a menubar? If so maybe we want to get ahead of that and add a menu button.

It isn't necessarily a blocker but I think its something important to get released before 3.32.

**Comment by TingPing** [comment]
Also a minor detail but next release will be `1.5.0` since this some major behavior breakage and an API break in the MPRIS bus name.

**Comment by JasonLG1979** [comment]
We could just move to having a header bar?

**Comment by ForLoveOfCats** [comment]
Please don't move Pithos to using a HeaderBar. HeaderBars look and function terribly outside Gnome Shell. Of course while Pithos bills itself as a Gnome app many people (such as myself) use Pithos outside the Gnome ecosystem. I cannot quantify this number but with Gnome Shell usage only about 27% according to GoL user statistics (possibly incomplete but can give a good idea) the number of people who use Pithos in other DE's is likely very high comparatively speaking.


Source of DE usage: https://www.gamingonlinux.com/users/statistics

**Comment by TingPing** [comment]
> We could just move to having a header bar?

That might be part of the larger total UI redesign someday. For now I just want to ensure the menu is accessable which can be as simple as adding it to the toolbar.

> Please don't move Pithos to using a HeaderBar. HeaderBars look and function terribly outside Gnome Shell.

AFAIK they function in all major WMs. Looks are subjective but only on KDE is it particularly out of place IMO (especially with the shadow problem still).

Headerbars are going to be the design going forward. It would be possible to support two interface styles but I don't think that really makes sense given the manpower.

**Comment by JasonLG1979** [comment]
@TingPing I also wouldn't mind getting rid of secret service for the creds. A while back you were talking about just using a plain text file with the proper read/write permissions and how it would just about as secure as how GNOME uses the keyring.

**Comment by TingPing** [comment]
> @TingPing I also wouldn't mind getting rid of secret service for the creds. A while back you were talking about just using a plain text file with the proper read/write permissions and how it would just about as secure as how GNOME uses the keyring.

So a few things changed in this area:

- Somebody was working on libsecret to make it sandboxable by storing it locally: https://gitlab.gnome.org/GNOME/libsecret/merge_requests/6
- GLib is working on making settings sandoxable by storing it locally: https://gitlab.gnome.org/GNOME/glib/tree/settings-portal

So our options would be:

- Store our own custom file locally
- Wait for GLib to get that and just put it in GSettings
- Wait for Libsecret to be safer

**Comment by JasonLG1979** [comment]
I'm kinda in favor of storing our custom file locally. Do flatpak apps not have a safe place to store files inside the sandbox. I'm unsure how permissions would work in that case? Would the Pithos flatpak be the owner of the file?

**Comment by TingPing** [comment]
> Do flatpak apps not have a safe place to store files inside the sandbox. I'm unsure how permissions would work in that case? Would the Pithos flatpak be the owner of the file?

It is identical to a normal application. So it relies on filesystem permissions only (private from other users but not other apps) *but* ideally other apps are also Flatpaks and do not have filesystem access.

**Comment by JasonLG1979** [comment]
It would make sense from a sandboxing standpoint for an app to be able to have it's own little bit of storage totally separated and segregated wouldn't it?

**Comment by JasonLG1979** [comment]
Especially for an app like Pithos that doesn't need filesystem access except to store stuff in tmp and theoretically store a creds file.

**Comment by JasonLG1979** [comment]
Having a separate tmp for each flatpak app at least seems like basic security to me?

**Comment by TingPing** [comment]
> My concern is that apps are given access to the filesystem when they really don't need it and apps can read each other's stuff.

A lot of flatpaks do sadly have this permission, and in that specific case it would be worse than libsecret (which requires a specific dbus permission few have).

**Comment by JasonLG1979** [comment]
People are stupid and lazy I guess. IMHO permission should start at nothing a be granted on a need to have basis. But sadly I guess most devs think the opposite because it's easier to just open a huge hole...

**Comment by TingPing** [comment]
> IMHO permission should start at nothing a be granted on a need to have basis.

That is how it works. But a lot of applications need random directory access or are using toolkits that don't support portals.

**Comment by JasonLG1979** [comment]
> That is how it works. But a lot of applications need random directory access or are using toolkits that don't support portals.

Yep, I am NOT the flatpak expert. But you are and we(mostly you,lol!!!) can make Pithos as confined as possible.

**Comment by JasonLG1979** [comment]
Does Flathub audit app permissions?

**Comment by JasonLG1979** [comment]
> a lot of applications need random directory access

Is there no way to open up just what is needed in a granular way?

**Comment by TingPing** [comment]
> Does Flathub audit app permissions?

We are pretty lax but do request the minimal possible.

> Is there no way to open up just what is needed in a granular way?

You can open single files securely but it requires a Gtk3 or Qt5 application (that both use specific file chooser apis). So a lot of apps don't fit in that or need to open directories not files.

**Comment by JasonLG1979** [comment]
You'd think you'd be able specify specific paths?

**Comment by JasonLG1979** [comment]
We grow at least one "Pithos" menu on DE's that don't support app menus in the panel. (pretty much everyone except GNOME).

**Comment by JasonLG1979** [comment]
There's always ```Gtk.Application.prefers_app_menu()```

**Comment by TingPing** [comment]
I'm guessing on 3.32 that will still return true, it just renders in a different spot.

**Comment by JasonLG1979** [comment]
> I'm guessing on 3.32 that will still return true, it just renders in a different spot.

How knows yet? Anyway what do you say about a menu button. It's affords us the ability and opportunity to be consistent across all DE's?

**Comment by TingPing** [comment]
Somebody could install Fedora Rawhide in a VM. Yes a menu button would be good.

**Comment by JasonLG1979** [comment]
By "Somebody" you mean me ofc,lol!!!

**Comment by TingPing** [comment]
Heh, if we intend to move to a button anyway it doesn't really matter but indeed I wasn't planning on it :P

**Comment by JasonLG1979** [comment]
The button hedges our bet. The question then becomes would we loose any menu magic with our own menu button and what icon do we use for said button?

**Comment by JasonLG1979** [comment]
I'm more of a fan of the gear icon myself, but if the rest of GNOME is using ```open-menu-symbolic``` hamburger it is then,lol!!!
