### ISSUE TITLE
http.client.UnknownProtocol: HTTP/2.0

### ISSUE THREAD

**Issue by kexul** [pithos/pithos#586]
When proxy is used, I can login but no station is showed, the error showed in terminal is 'http.client.UnknownProtocol: HTTP/2.0'

**Comment by TingPing** [comment]
Sounds like the proxy you use is configured to only use http 2 and blocks http 1.x?

**Comment by kexul** [comment]
Could you please help me debug this? the proxy tool I'm using is attached.
[u1807a.zip](https://github.com/pithos/pithos/files/2783597/u1807a.zip)

**Comment by TingPing** [comment]
I don't know why you expect anything to come from uploading a random binary blob. If its a well known proxy they will have documentation, if not I question why somebody would use it.

Anyway it has nothing to do with this application.

**Comment by kexul** [comment]
I'm so sorry if it bothered you.
