### ISSUE TITLE
Dialog "Codec installation successful" but received same error

### ISSUE THREAD

**Issue by scottkosty** [pithos/pithos#589]
I'm on Ubuntu 19.04.

When installing Pithos from the Git repository (i.e., not from the Ubuntu archives), I was able to open Pithos and set it up correctly. After logging into my account, I received a dialog saying "Codec installation successful" and "The required codec was installed, please restart Pithos." but restarting just led to the same message.

These were the messages on the terminal:
```
ERROR - pithos:on_gst_error:1101 - Gstreamer error: gst-core-error-quark: Your GStreamer installation is missing a plug-in. (12), gsturidecodebin.c(988): no_more_pads_full (): /GstPlayBin:player/GstURIDecodeBin:uridecodebin0:
no suitable plugins found:
gstdecodebin2.c(4679): gst_decode_bin_expose (): /GstPlayBin:player/GstURIDecodeBin:uridecodebin0/GstDecodeBin:decodebin0:
no suitable plugins found:
Missing decoder: MPEG-4 AAC (audio/mpeg, mpegversion=(int)4, framed=(boolean)true, stream-format=(string)raw, level=(string)1, base-profile=(string)lc, profile=(string)lc, codec_data=(buffer)139056e5a0, rate=(int)22050, channels=(int)2)
, 12
ERROR - pithos:on_gst_error:1101 - Gstreamer error: gst-stream-error-quark: Internal data stream error. (1), gstbasesrc.c(3072): gst_base_src_loop (): /GstPlayBin:player/GstURIDecodeBin:uridecodebin0/GstSoupHTTPSrc:source:
streaming stopped, reason not-linked (-1), 1
** Message: 03:12:41.498: PackageKit: xid = 0
** Message: 03:12:41.498: PackageKit: desktop_id = (null)
** Message: 03:12:41.499: PackageKit: Codec nice name: MPEG-4 AAC decoder
** Message: 03:12:41.499: PackageKit: ignoring field named level
** Message: 03:12:41.499: PackageKit: ignoring field named base-profile
** Message: 03:12:41.499: PackageKit: ignoring field named profile
** Message: 03:12:41.499: PackageKit: field is: mpegversion, type: gint
** Message: 03:12:41.499: PackageKit: structure: gstreamer1(decoder-audio/mpeg)(mpegversion=4)()(64bit)
```

It was easy to run `apt-cache show pithos` and just install all the packages in the "Depends" category, and then everything worked. Specifically, I installed the following:
```
gstreamer1.0-plugins-good, gstreamer1.0-plugins-bad, python3-pkg-resources, python3-gi, python3-gi-cairo, gir1.2-gtk-3.0, gir1.2-gstreamer-1.0, gir1.2-gst-plugins-base-1.0
```

Thus, the fix was easy. However, I report here just in case it is desired to make it a little more user-friendly. The dialog suggests the problem is fixed when from what I can tell it is not.

**Comment by JasonLG1979** [comment]
The dependencies are listed in the wiki Installing from Source - Getting Dependencies - [Debian (Ubuntu)](https://github.com/pithos/pithos/wiki/Installing-from-Source#debian-ubuntu)

Specifically the 2nd line for the GStreamer dependencies.

In the future though ```apt-cache show pithos``` will show you the the dependencies of the Pithos package in the repo which is WAY out of date. It will NOT show you the dependencies of the source installed version of Pithos. Please refer to the wiki for a list of dependencies when installing from source as dependencies may change.

**Comment by scottkosty** [comment]
@JasonLG1979 thanks for the quick reply! Perhaps I shouldn't have added that extra stuff about the dependencies. My main question is whether it makes sense to change the dialog. The dialog currently says "The required codec was installed, please restart Pithos.", but that does not seem correct to me. When I restart, I get the same dialog. Or is your point "if you don't install the dependencies, all bets are off"? If so, let's keep this ticket closed.

Thanks for your time and work on Pithos.

**Comment by JasonLG1979** [comment]
@scottkosty that message is in response to a (supposedly) successful install of codecs.

https://github.com/pithos/pithos/blob/522f02e303c3762b2c1a81a001e7000055521a94/pithos/pithos.py#L1085

If Gstreamer is returning a success result there's really not much we can do about that.

Generally yes, when installing an application from source is it absolutely up to you to make sure to install all the required dependencies especially since they are listed in the wiki.

**Comment by JasonLG1979** [comment]
@TingPing We could probably do this better though?

  https://github.com/exaile/exaile/blob/8fb0ebb4ea108792d38e2b8ad355b27d70e1d246/xl/player/gst/missing_plugin.py

**Comment by scottkosty** [comment]
@JasonLG1979 OK thanks for taking a look.
