### ISSUE TITLE
SSL Certificate Error

### ISSUE THREAD

**Issue by 8bg** [pithos/pithos#591]
Same as issue 562, however the solution listed doesn't work for me:

> For arch, this worked for me
> `sudo wget https://www.geotrust.com/resources/root_certificates/certificates/GeoTrust_Primary_CA.pem -P /etc/ca-certificates/trust-source/anchors/ && sudo trust extract-compat`
> 
> This is from a comment in #251, linked above, modified for the correct cert.

I am encountering this problem now on Ubuntu 19.04, but the above commands give an error:

ERROR: cannot verify www.geotrust.com's certificate, issued by ‘CN=DigiCert SHA2 Extended Validation Server CA,OU=www.digicert.com,O=DigiCert Inc,C=US’:
  Self-signed certificate encountered.

_Originally posted by @8bg in https://github.com/pithos/pithos/issues/562#issuecomment-516425956_

**Comment by JasonLG1979** [comment]
Again. Try Googling "wget Self-signed certificate error".

This might be helpful:

https://security.stackexchange.com/questions/194709/wget-cannot-securely-connect-to-web-archive-self-signed-certificate-encountered

The problem from what I understand as mentioned in the other SSL Certificate Error issues is that your system for some reason or another does not trust the Cert presented by Pandora. This distrust seems to also extend to wget.

I can be of no further help really because 1. Pithos worked just fine even before I tested the wget command. 2. The given command works just fine for me. 3. If any cert changes have happened they have not effected me yet.

**Comment by 8bg** [comment]
Thank you for taking time to respond. I've tested every fix I can find after exhaustive searches, to no avail. I know it's something specific to my config, as Pithos works fine in a fresh VM. Just can't seem to resolve. 

My system seems to communicate OK with Pandora from web: 

`$ curl --verbose https://www.pandora.com`

gives

`Connected to www.pandora.com (2620:106:e003:f00e::63) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*   CAfile: none
  CApath: /etc/ssl/certs
} [5 bytes data]
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
} [512 bytes data]
* TLSv1.3 (IN), TLS handshake, Server hello (2):
{ [96 bytes data]
* TLSv1.2 (IN), TLS handshake, Certificate (11):
{ [2876 bytes data]
* TLSv1.2 (IN), TLS handshake, Server key exchange (12):
{ [333 bytes data]
* TLSv1.2 (IN), TLS handshake, Server finished (14):
{ [4 bytes data]
* TLSv1.2 (OUT), TLS handshake, Client key exchange (16):
} [70 bytes data]
* TLSv1.2 (OUT), TLS change cipher, Change cipher spec (1):
} [1 bytes data]
* TLSv1.2 (OUT), TLS handshake, Finished (20):
} [16 bytes data]
* TLSv1.2 (IN), TLS handshake, Finished (20):
{ [16 bytes data]
* SSL connection using TLSv1.2 / ECDHE-RSA-AES256-GCM-SHA384
* ALPN, server accepted to use h2
* Server certificate:
*  subject: C=US; ST=California; L=Oakland; O=Pandora Media, Inc.; OU=operations; CN=*.pandora.com
*  start date: Mar 14 00:00:00 2019 GMT
*  expire date: Jun 12 12:00:00 2021 GMT
*  subjectAltName: host "www.pandora.com" matched cert's "*.pandora.com"
*  issuer: C=US; O=DigiCert Inc; OU=www.digicert.com; CN=GeoTrust TLS RSA CA G1
*  SSL certificate verify ok.
`
I will keep searching and trying. For now I can use the web Pandora, but I miss Pithos!

**Comment by 8bg** [comment]
After some recent system updates, Pithos is once again working...
