### ISSUE TITLE
Notification Icon always shows up after reboot on XFCE

### ISSUE THREAD

**Issue by blurrred** [pithos/pithos#594]
The icon that shows up in the notification tray will always be present after a reboot. It will go away properly if the setting is disabled until a reboot occurs. After a reboot, the icon reappears and must be disabled once again in order for it to disappear.

This is present on Linux Mint XFCE but not Linux Mint Cinnamon.

**Comment by TingPing** [comment]
What version and how did you install it?

**Comment by blurrred** [comment]
I am using version 1.1.2.
I believe I got it from Linux Mint's software manager, so it's probably the
default that is in the Ubuntu 18.04 repositories.

**Comment by JasonLG1979** [comment]
> I am using version 1.1.2. I believe I got it from Linux Mint's software manager, so it's probably the default that is in the Ubuntu 18.04 repositories.

1.1.2 is old and no longer supported. Try the latest flatpak from flathub and see if the issue is still present.
