### ISSUE TITLE
<Return> to select top result of search

### ISSUE THREAD

**Issue by scottkosty** [pithos/pithos#597]
Alternatively, perhaps <Return> could only do something if there is only one station in the results.

This might be related to #561 (although I haven't checked if I can reproduce that one) in the sense that it has to do with <Return>.

**Comment by scottkosty** [comment]
If there is agreement on the desired behavior and a patch would be considered, let me know. I might work on this when I have time.

**Comment by TingPing** [comment]
Sounds good to me :+1:

Step one is to make hitting enter in the list change to the selected station, then we just need to consider how the search entry manipulates that selection and activate it on enter there also.

**Comment by scottkosty** [comment]
Sounds good! I probably won't get to this for a while, but I'm sure it will keep scratching me so I hope to get to it eventually.

**Comment by tylerthetiger** [comment]
I've added in [PR#628](https://github.com/pithos/pithos/pull/628) which should resolve this.
It does not address issue #561.
