### ISSUE TITLE
No Longer Working Through VPN

### ISSUE THREAD

**Issue by fjrider** [pithos/pithos#598]
May not be an actual Pithos issue, just reporting my condition for feedback.

Love the Pithos app.  Works great for me on Linux Mint 19.2.
Usually have PIA VPN running at all times on this machine.
Up until a few days ago I could still connect to Pandora and Pithos through VPN without issue.
A few days ago Pithos stopped working through the VPN.
I assume this is the Pandora service at Pandora.com blocking the VPN connection, not a Pithos issue, but is there any suggestions here for mitigation?
I also tried the split tunnel VPN instructions here https://www.privateinternetaccess.com/helpdesk/kb/articles/split-tunnel-app-examples
I tried to exclude /lib/bin/pithos and Pithos still can not connect to Pandora.

Thanks in advance for any advice, best regards.

**Comment by TingPing** [comment]
I will just agree its probably Pandora blocking VPNs. PIA is a big VPN so they probably blocked every IP they own.

**Comment by steelingbox** [comment]
If you are connected anywhere other than the USA you're going to be blocked.
