### ISSUE TITLE
Request: Listen to Stations A, X, & M

### ISSUE THREAD

**Issue by BeaverTek** [pithos/pithos#601]
I don't know if it's possible, but it'd be great to select a few stations and have it play those. Maybe it could be done by automatically switching to a different random station within the selection after a range of time / song count.*
Maybe there could be a setting somewhere to change how soon a different station gets played. 

My reasoning: I have 20+ artists in every station I created and sometimes I just want to listen to my 10 different metal, hardcore, and metal stations for a great variety but I can't "shuffle all" because that'll mix in the classic rock+country station, ambient and other junk. 

* keep in mind that progressive and doom metal metal songs regularly surpass 10 minutes; but punk, grindcore, etc songs tend to be under two minutes.

**Comment by TingPing** [comment]
I'm just going to preemptively close this. The bug tracker does not need to be a log of all designs users possibly want. I also don't believe this design really fits into the Pandora API's design.

**Comment by BeaverTek** [comment]
Sorry. Some other projects want everything in their code repository so there's a record of it beyond IRC.
Figured this was mostly a tweak to an existing feature.
