### ISSUE TITLE
Request: Offline Listening for Paid Subscribers

### ISSUE THREAD

**Issue by BeaverTek** [pithos/pithos#602]
It'd be great to have an "offline mode". Ultimately it should list only the stations that have songs saved. It'd also be nice to have some way to see a list of songs are saved and a way to toggle whether or not we want the station to be available without Internet connectivity and how much storage to allocate for each station & total and, if possible, where the songs are saved. i.e. if someone's only got a 30GB ~/ but multi-TB storage drive.

Again, this should very much only be possible for paid users as Plus & Premium subscribers are paying for exactly this functionality and I'm sure there are others that feel they should be able to listen to their radio without whatever analytics & tracking are being done with the official application.

**Comment by TingPing** [comment]
This is a scary proposition, so while Pandora's mobile app does provide this functionality its important to remember that this isn't official and if looks like we expose easy ways to aid in piracy that probably won't end well.

Now even if we did expose this option we have no way of reasonably downloading stations up front, they will simply ban the client the second it requests a handful of playlists under a minute.

**Comment by JasonLG1979** [comment]
With the current API that we use it's not even possible.

As @TingPing mentioned as soon as you request more then a couple playlists in a short period of time you're going to get temporarily banned.

The big sticker though is caching songs. That's a big No, No. So far Pandora has basically ignored us for what ever reason. We would like to keep it that way.

**Comment by TingPing** [comment]
I'll just close this as its not planned.
