### ISSUE TITLE
Stations not opening

### ISSUE THREAD

**Issue by trisailing** [pithos/pithos#603]
version 1.5.0
When selecting stations in the menu under the 3 lines. it will not open. The other menu iteams work.
This occurs in Linuxmint 19.2 and 19.3 cinnamon edition.
Error is below from debug.
Traceback (most recent call last):
  File "/app/share/pithos/pithos/application.py", line 191, in stations_cb
    self.window.show_stations()
  File "/app/share/pithos/pithos/pithos.py", line 1446, in show_stations
    self.stations_dlg = StationsDialog.StationsDialog(self, transient_for=self)
  File "/app/share/pithos/pithos/StationsDialog.py", line 55, in __init__
    self.modelsortable = Gtk.TreeModelSort.sort_new_with_model(self.modelfilter)
AttributeError: type object 'TreeModelSort' has no attribute 'sort_new_with_model'

**Comment by JasonLG1979** [comment]
Yep, same problem here.

It should be `Gtk.TreeModelSort.new_with_model`

**Comment by trisailing** [comment]
I put the updated pithos.py file in put now I have a syntax error.
Traceback (most recent call last):
  File "/app/bin/pithos", line 44, in <module>
    from pithos import application
  File "/app/share/pithos/pithos/application.py", line 24, in <module>
    from .pithos import PithosWindow
  File "/app/share/pithos/pithos/pithos.py", line 7
    <!DOCTYPE html>
    ^
SyntaxError: invalid syntax


Is it not completed?

**Comment by JasonLG1979** [comment]
You just copy and pasted the file? Don't do that. If you'd like to test build from source correctly. Although your mileage may vary. I'm not sure if everything is compatible with Mint 19/Ubuntu 18.04?

Your best bet is to wait for a point release and install the flatpak.

**Comment by trisailing** [comment]
Yep that's what I did. Ok Just let me know.
Thanks for the quick reply.

**Comment by JasonLG1979** [comment]
I'll sniff around and see if I can't find any other bugs and then maybe @TingPing will do a point relase.

**Comment by trisailing** [comment]
Ok. Will keep a look out.

**Comment by TingPing** [comment]
@JasonLG1979 Sure I can do a release soon, let me know when you're ready for oen.

**Comment by trisailing** [comment]
ready.

**Comment by JasonLG1979** [comment]
@TingPing I think that the new PR's I have in should do it.
