### ISSUE TITLE
Error thrown any time the volume is changed

### ISSUE THREAD

**Issue by RyanNerd** [pithos/pithos#609]
```
ERROR - pithos:on_gst_error:1104 - Gstreamer error: gst-resource-error-quark: pa_stream_writable_size() failed: Connection terminated (1), pulsesink.c(1752): gst_pulseringbuffer_commit (): /GstPlayBin:player/GstPlaySink:playsink/GstBin:abin/GstBin:bin0/GstAutoAudioSink:audiosink/GstPulseSink:audiosink-actual-sink-pulse, 1
```
Linux Mint 19.3 (Cinnamon) 
Pulseaudio 11.1

This happens every time I adjust the volume. Pithos skips the current song and shows it is playing the next song (however it is silent). I have to restart Pithos to restore the sound.

I went so far as to build Pithos from source and ran it locally so I could capture the error message.

**Comment by RyanNerd** [comment]
This may be a Pulseaudio issue and not Pithos (see https://github.com/mopidy/mopidy/issues/1503 and https://ubuntuforums.org/showthread.php?t=1487019) But none of the solutions there seem to work (removing `gstreamer0.10-pulseaudio` when it isn't installed in the first place or installing **all** gst* which I am unwilling to do).
Any help with this issue is appreciated.

**Comment by JasonLG1979** [comment]
What version of Pithos? The version in the Ubuntu repos is ancient and no longer supported.

`gstreamer1.0-plugins-good gstreamer1.0-plugins-bad` should do the trick as far as what Pithos needs to work, although `apt` in Mint may be configured recommended dependencies at least once upon a that was the case?

**Comment by RyanNerd** [comment]
> What version of Pithos? The version in the Ubuntu repos is ancient and no longer supported.
> 
> `gstreamer1.0-plugins-good gstreamer1.0-plugins-bad` should do the trick as far as what Pithos needs to work, although `apt` in Mint may be configured not to install recommended dependencies at least once upon a that was the case?

I built from source off the master branch yesterday - - so the most recent version.

**Comment by JasonLG1979** [comment]
> I built from source off the master branch yesterday - - so the most recent version.

Did you make sure that apt in Mint is installing the recommend and/or suggested dependencies?

**Comment by RyanNerd** [comment]
> > I built from source off the master branch yesterday - - so the most recent version.
> 
> Did you make sure that apt in Mint is installing the recommend and/or suggested dependencies?

The dependencies you mention `gstreamer1.0-plugins-good gstreamer1.0-plugins-bad` are already installed. As part of building from source I installed all [recommended dependencies](https://github.com/pithos/pithos/wiki/Installing-from-Source#debian-ubuntu)
I honestly think this is a Pulseaudio issue -- but thanks for your help anyway.

**Comment by JasonLG1979** [comment]
Ok I'm closing the issue then.
