### ISSUE TITLE
Pithos oddity - losing stations

### ISSUE THREAD

**Issue by Matt832** [pithos/pithos#610]
Been using Pithos for many years, have a number of favorite stations on Pandora.  Had been playing one for some time then all of a sudden I get Quick Mix, look for station, it's no longer in the list.  Go to Pandora and it's there.  Refresh stations still not there.

I have both flatpack and 1.1.2 installed, both do the same.  Just started happening in the last day or so.

**Comment by TingPing** [comment]
> Just started happening in the last day or so.

This would imply its a server issue. Worst case they broke their API but that seems unlikely.

**Comment by whattheserver** [comment]
I can confirm this issue. See the station in Android app and in web browser but cannot find it it in Pithos or Xbox one Pandora app.  

I have a theory though. The station missing was a very old station. I have went and edited the station slightly and added a description and then it showed back up in Pithos. Maybe you can try doing that @Matt832

**Comment by Matt832** [comment]
I wish that was the case, I went in and created a new station, only to find it missing too.  I create a station in Pithos and it plays for a while then switches over to "Quick Mix".  I've even edited QM to include the newly created station only to come back and see it gone again.  i also considered that I had too many stations, and deleted a number of them, no difference.

I have both the flatpack and v.1.1.2 installed on my Linux mint computer, got to say I like the functionality of v1.1.2 better - lets me edit the Quick Mix selection and add a station - even though it disappears.

**Comment by whattheserver** [comment]
You are right. It happened again to me midshift earlier was jamming to Disturbed radio. Then all of sudden im listening to quickmix random slow songs.

Don't have enough information to deduce the pattern to when this happens sadly.

might have to just wrap this in a pyqt5 webgineview or page mini app from now on.

Speaking of which looks like that actually works really nice lol. 
![image](https://user-images.githubusercontent.com/1596188/77916467-1c498680-7267-11ea-95bc-2c29d27c9ed0.png)
![image](https://user-images.githubusercontent.com/1596188/77916491-25d2ee80-7267-11ea-86c0-3f677fe230b1.png)
![image](https://user-images.githubusercontent.com/1596188/77916515-2e2b2980-7267-11ea-8e63-7b225f21eb4a.png)

code if you know python and wanted lightweight widget based on the webpage view. It is also resizable too :)

```
from PySide2.QtCore import QObject, QUrl
from PySide2.QtWebEngineWidgets import QWebEngineView, QWebEnginePage, QWebEngineSettings
from PySide2.QtWidgets import QApplication, QWidget
import sys



# print(data_dir)


class Handler(QObject):
    def __init__(self, *args, **kwargs):
        super(Handler, self).__init__(*args, **kwargs)



class WebEnginePage(QWebEnginePage):
    def __init__(self, *args, **kwargs):
        super(WebEnginePage, self).__init__(*args, **kwargs)



if __name__ == "__main__":
    # Set up the main application
    #app = QApplication([])
    app = QApplication(sys.argv)

    # Use a webengine view
    view = QWebEngineView()
    #view.resize(500, 200)
    view.settings().globalSettings().setAttribute(QWebEngineSettings.LocalStorageEnabled, True)
    # view.settings().globalSettings().setAttribute(QWebEngineSettings.JavascriptCanAccessClipboard, True)
    # view.settings().globalSettings().setAttribute(QWebEngineSettings.JavascriptCanPaste, True)
    # view.settings().globalSettings().setAttribute(QWebEngineSettings.LocalContentCanAccessFileUrls, True)
    # view.settings().globalSettings().setAttribute(QWebEngineSettings.JavascriptCanOpenWindows, True)
    # view.settings().globalSettings().setAttribute(QWebEngineSettings.LocalContentCanAccessRemoteUrls, True)
    # view.settings().globalSettings().setAttribute(QWebEngineSettings.AllowWindowActivationFromJavaScript,
    #                                               True)

    # Use a custom page
    page = QWebEnginePage()
    view.setPage(page)

    # Finally, load our file in the view
    # url = QUrl.fromLocalFile(f"{data_dir}/index.html")
    url = QUrl("https://www.pandora.com/")
    view.load(url)
    view.show()

    app.exec_()
```

**Comment by Matt832** [comment]
Might give the player linked a try.  Question - Will it play unattended?  With Pithos I run it 24/7 as whole house audio due to my tinnitus.

**Comment by whattheserver** [comment]
It has for me so far without issues for the 4 hours straight. Going to be using it for my shift here tonight and I'll get a 8-10hr nonstop test. 

Sent from Nine
________________________________

**Comment by PromyLOPh** [comment]
Sounds alot like https://github.com/PromyLOPh/pianobar/issues/693 which I just fixed.

**Comment by TingPing** [comment]
@PromyLOPh Thanks for the hint!
