### ISSUE TITLE
"Stations" dialog is inaccessible.

### ISSUE THREAD

**Issue by patrick-brian-mooney** [pithos/pithos#615]
Trying to open the Stations dialog box from the main menu does nothing. If I run Pithos from a terminal, then try to open the Stations dialog, I get a Python traceback:

```
13:42:14 patrick@laptop working$ flatpak run io.github.Pithos
Traceback (most recent call last):
  File "/app/share/pithos/pithos/application.py", line 191, in stations_cb
    self.window.show_stations()
  File "/app/share/pithos/pithos/pithos.py", line 1446, in show_stations
    self.stations_dlg = StationsDialog.StationsDialog(self, transient_for=self)
  File "/app/share/pithos/pithos/StationsDialog.py", line 55, in __init__
    self.modelsortable = Gtk.TreeModelSort.sort_new_with_model(self.modelfilter)
AttributeError: type object 'TreeModelSort' has no attribute 'sort_new_with_model
```

Pithos 1.5.0, installed via Flatpak. Just ran `flatpack update`; problem is still occurring with the most recent version available from the flatpak source. Linux Mint 19.3 x64.

**Comment by TingPing** [comment]
This was fixed in d9c0f397d8e0ec4c5987026262c49fa35c5391a8 but hasn't made it to a release yet.

**Comment by patrick-brian-mooney** [comment]
Many thanks! Is there a workaround in the meanwhile? Not being able to edit station settings is a big restriction in functionality.

**Comment by TingPing** [comment]
I updated the flatpak with these fixes, will be out in a few hours.

**Comment by patrick-brian-mooney** [comment]
Thank you so much!

**Comment by neoh4x0r** [comment]
@TingPing it depends on the version of GTK.

I had to revert the change in d9c0f397d8e0ec4c5987026262c49fa35c5391a8 to use **sort_new_with_model**

```
Traceback (most recent call last):
  File "/usr/local/share/pithos/pithos/application.py", line 193, in stations_cb
    self.window.show_stations()
  File "/usr/local/share/pithos/pithos/pithos.py", line 1449, in show_stations
    self.stations_dlg = StationsDialog.StationsDialog(self, transient_for=self)
  File "/usr/local/share/pithos/pithos/StationsDialog.py", line 55, in __init__
    self.modelsortable = Gtk.TreeModelSort.new_with_model(self.modelfilter)
AttributeError: type object 'TreeModelSort' has no attribute 'new_with_model'
```

Debian GNU/Linux 9 (stretch) / libgtk / 3.22.11

**Comment by TingPing** [comment]
At a glance the annotations for GTK have not changed. *Maybe* something in pygobject or gobject-introspection changed but that seems odd.

Eitherway we can add an attempt to use both versions. Could you open a new issue for this?
