### ISSUE TITLE
Only some Playback/Media controls are working

### ISSUE THREAD

**Issue by aarona** [pithos/pithos#620]
Version: 1.1.2

I can turn the volume up and down and mute but I cannot pause/play or skip a track with the `>>|` key (my `F11` key) on my laptop.

**Comment by TingPing** [comment]
What desktop?

**Comment by aarona** [comment]
Sorry. Ubuntu 20.04

**Comment by TingPing** [comment]
Well it works fine here on GNOME but might be worth updating from that old version: https://flathub.org/apps/details/io.github.Pithos

**Comment by aarona** [comment]
I installed it using snap and there doesn't seem to be the newest version available through synaptic either. Not sure why this is. I'll close this as I assume its working on a newer version. I'm sure flatpak is cool, but I'd rather not have to install yet another package management tool just to get these features working. Thank for looking into this.
