### ISSUE TITLE
Flatpak/flathub: Support/use the secrets service portal

### ISSUE THREAD

**Issue by dkogias** [pithos/pithos#621]
This may be already supported, in which case please accept apologies about the noise.  I don't know flatpak enough to deciper this so I thought I'd ask:

I tried to install from flathub and got:
```
$ flatpak install --user flathub io.github.Pithos
Looking for matches…
Required runtime for io.github.Pithos/x86_64/stable (runtime/org.gnome.Platform/x86_64/3.34) found in remote flathub
Do you want to install it? [Y/n]: 

io.github.Pithos permissions:
    ipc                   network      fallback-x11      pulseaudio      wayland      x11
    dbus access [1]

    [1] org.freedesktop.secrets, org.gnome.SettingsDaemon.MediaKeys, org.kde.StatusNotifierWatcher,
        org.mate.SettingsDaemon


        ID                                  Branch          Op          Remote           Download
 1.     org.gnome.Platform.Locale           3.34            i           flathub          < 322.2 MB (partial)
 2.     org.gnome.Platform                  3.34            i           flathub          < 320.4 MB
 3.     io.github.Pithos                    stable          i           flathub          < 536.5 kB

Proceed with these changes to the user installation? [Y/n]: n
```

`org.freedesktop.secrets` gives me pause so I declined the install.  Reading [about the secrets proxy portal](https://opensource.com/article/19/11/secrets-management-flatpak-applications) that was recently added to flatpak, I'm trying to understand:  Is Pithos still requiring full access to my secrets service because it depends on the GNOME 3.34 runtime?  The article I linked to mentions

> The necessary patches are (currently) only available in the Git repositories of the relevant components (xdg-desktop-portal, gnome-keyring, and libsecret). They will be included in the next releases leading up to GNOME 3.36.

FWIW this is all on a Fedora 32 workstation.

**Comment by TingPing** [comment]
Yeah we need to update the runtime, the bigger problem is I think it would just be broken on old hosts.

**Comment by BrookeDot** [comment]
On Ubuntu 20.04 I'm getting a warning that the Runtime 3.34 is now at end of life. Pithos is the last flatpak package I use which is on 3.34

``` 
$ flatpak update
Looking for updates…
Info: org.gnome.Platform is end-of-life, with reason: The GNOME 3.34 runtime is no longer supported as of 14th August 2020. Please ask your application developer to migrate to a supported platform.
Info: org.gnome.Platform.Locale is end-of-life, with reason: The GNOME 3.34 runtime is no longer supported as of 14th August 2020. Please ask your application developer to migrate to a supported platform.
```

**Comment by dkogias** [comment]
Looks like runtime has been updated to 40 on flathub: https://github.com/flathub/io.github.Pithos/commit/41155ad21b2b3774d979852548ead7e52129bc9d

but running pithos with:

```
[Session Bus Policy]
org.freedesktop.secrets=none
```

still results in an error on startup about the secrets service not being available.  So I assume there are code changes needed too?

**Comment by TingPing** [comment]
>  So I assume there are code changes needed too?

It shouldn't. `libsecret` is supposed to detect if its in flatpak and has talk permissions. If not use a local database.

Maybe try deleting that line entirely instead of `none`?

That said I haven't looked into this.

**Comment by dkogias** [comment]
That line was the result of `flatpak override --user --no-talk-name=org.freedesktop.secrets io.github.Pithos`.

After clearing that with `flatpak override --user --reset io.github.Pithos`, `Pithos` starts normally.  But it accesses the secrets service just like before, not through the portal; this is from the host:

![Screenshot from 2021-04-17 14-04-47](https://user-images.githubusercontent.com/428200/115126846-f6cd0f00-9f86-11eb-92f8-e73fedbfc3e5.png)

and if I lock the login keychain (where that secret was created), trying to start `Pithos` will prompt the GNOME keyring service on the host to ask me for the login keyring password.  I also verified that the host-side entry does contain the pandora password.

I was instead expecting to see a "global" flatpak secret created on the host side.

**Comment by TingPing** [comment]
> I was instead expecting to see a "global" flatpak secret created on the host side.

How it is supposed to work is that the secret is private entirely in the flatpak. Nothing is stored on the host.

**Comment by TingPing** [comment]
I investigated this and `gnome-keyring` is just broken. Its implementation of this portal doesn't work.

See also: https://gitlab.gnome.org/GNOME/gnome-keyring/-/issues/61

**Comment by dimitris-personal** [comment]
I noticed version 1.6.0 has been published on flathub.  I installed it on my Fedora 36 system.  Its flatpak permissions no longer mention `org.freedesktop.secrets`, but it still required me to unlock the host-side login keyring before the app could start.  Subsequently I see that it did access and store the password in a secret there.

**Comment by TingPing** [comment]
As of 1.6.0 we do use the secrets portal. When inside of flatpak we do not store any keys, or have read access, in the host keystore.

The actual keys will be stored in `~/.var/app/io.github.Pithos/data/keyrings/default.keyring` and you can use the [Key Rack](https://flathub.org/apps/details/app.drey.KeyRack) application to see/edit these.
