### ISSUE TITLE
No quickmix

### ISSUE THREAD

**Issue by jam01** [pithos/pithos#627]
For some reason I no longer have a Quickmix option in my stations
![image](https://user-images.githubusercontent.com/10093076/91067984-378fa680-e5f9-11ea-8052-4929863ee042.png)

Also I don't have a Preferences menu either. 

I'm on 1.4.1-8.fc31 from Fedora's rpmfusion-free

**Comment by TingPing** [comment]
> Also I don't have a Preferences menu either.

Update to 1.5.0 for that. Easiest method: https://flathub.org/apps/details/io.github.Pithos

The QuickMix not showing up would just mean Pandora isn't returning it to us for some reason.

**Comment by jam01** [comment]
Will try, thanks.

**Comment by jam01** [comment]
Updating to Fedora 32 brought back Quickmix, still no preferences found anywhere but CTRL P works so I'll live with it.

PS If you guys setup a sponsor page I'd be happy to send something :)

**Comment by TingPing** [comment]
> PS If you guys setup a sponsor page I'd be happy to send something :)

For now both @JasonLG1979 and I have it enabled on our accounts. (Can't enable it on the Pithos org atm and then we just have to figure out a split anyway)

**Comment by jam01** [comment]
:pray:
