### ISSUE TITLE
1.5.1  Selecting "Stations" in menu does nothing

### ISSUE THREAD

**Issue by assmblyreq** [pithos/pithos#640]
No error, no action performed.

Pandora 1.5.1, Debian 10, Gnome 3.30.2

**Comment by TingPing** [comment]
Is anything printed if you run `pithos` in the terminal?

**Comment by assmblyreq** [comment]
(pithos:6332): Gdk-CRITICAL **: 17:16:41.645: gdk_window_thaw_toplevel_updates: assertion 'window->update_and_descendants_freeze_count > 0' failed

**Comment by assmblyreq** [comment]
Is this caused by Jason Gray's modification for issue #603? (TreeModelSort.new_with_model isn't a defined attribute?)

**Comment by TingPing** [comment]
`new_with_model()` is correct, but its possible the wrong name is required for outdated systems (pygobject, or gtk potentially, being outdated).
