### ISSUE TITLE
Use as library instructions

### ISSUE THREAD

**Issue by sean-abbott** [pithos/pithos#645]
I'm trying to find an easy way to grab favorites from pandora to match to my local library to create plex playlists. If it's not too much trouble, it would be lovely if you could create a simple howto for using this a a library; particiuarly setting up credentials using only a user-name and password and then being able to call functions without using the GUI.

I admit, I'm being lazy and did not delve intot he code to see how easy it would be. So apologies for that, and I get it if this is closed rapidly. :-)

**Comment by TingPing** [comment]
We don't really support or expect people to use it as a library.

However you are free to read the source: https://github.com/pithos/pithos/tree/master/pithos/pandora
