### ISSUE TITLE
Pithos for android

### ISSUE THREAD

**Issue by drmmr109** [pithos/pithos#647]
This might have been brought up before or there might be legal issues but can an app be created to install pithos on android?

**Comment by TingPing** [comment]
No the toolkit used has no android support so it would be a new app basically.

**Comment by drmmr109** [comment]
Thanks anyway. Figured it couldn't hurt to ask.

It's hard to make predictions.... Especially about the future.. 

    On Sunday, March 21, 2021, 1:49:21 PM EDT, Patrick ***@***.***> wrote:  
 
 


No the toolkit used has no android support so it would be a new app basically.
