### ISSUE TITLE
shortcut for change station? 

### ISSUE THREAD

**Issue by brotherJ4mes** [pithos/pithos#648]
I'm curious if there's possibly a (hidden) shortcut to change station.  

I've noticed that once the drop down menu has focus (via a mouse click), typing a string will narrow down my existing stations and then arrow keys + enter will start playing the desired station.  (i.e. it seems like it's very nearly possible to change station with only the keyboard but I just can't get the focus on the station drop down without the mouse)

I noticed that there's at least one shortcut--ctrl+s for "manage stations", which doesn't appear in the shortcut help menu so I'm wondering if maybe there's also one for change station that I just haven't found.  If there isn't one would it be possible to implement?

**Comment by tylerthetiger** [comment]
I don't see any current shortcuts defined for opening stations dialog box.

I added in PR #649 to use ctrl+r to toggle stations popover/dialog, hopefully that will work for you.  Improving the keyboard-only navigation is something that could be improved, so feel free to call out any other improvements you'd like to see.
