### ISSUE TITLE
Key source

### ISSUE THREAD

**Issue by 89z** [pithos/pithos#662]
I am trying to find the source of this key:

https://github.com/pithos/pithos/blob/77c48c6061f3f63085a6385bb6c5b2d7865fc5db/pithos/pandora/data.py#L7

added here:

https://github.com/pithos/pithos/commit/d0af266a801d5ac10f25234e487352ffcb79ca48

**Comment by TingPing** [comment]
It was extracted from the Android client AFAIK. I don't really know the process for doing that though.

**Comment by 89z** [comment]
I didnt find it in the latest APK. I ran it though AndroGuard, including all classes (5 million LOC). I guess it could be heavily obfuscated. I might try just looking at the Smali instead, or maybe old APK. Also I thought about using a Frida hook, but I dont have much experience with that. If you know anyone that might have knowledge about how the key was aquired, it would be appreciated. I dont like using "magic key", without knowledge of how it was found.

**Comment by 89z** [comment]
Found it:

~~~java
com\pandora\constants\PandoraConstants.java
8:    public static final byte[] b = "6#26FRL$ZWD".getBytes(Charset.defaultCharset());
~~~

https://github.com/skylot/jadx
