### ISSUE TITLE
Remove or rename notification Icon?

### ISSUE THREAD

**Issue by scottkosty** [pithos/pithos#663]
From what I understand (b04290ca), it is expected that there is no right-click menu on the "notification icon" anymore due to necessary changes. I wonder if some users will be confused by this. I'm actually not sure having an icon with no right-click menu is useful, but perhaps some people like to just use it as a "button" to show the Pithos window? In that case, would it make sense to rename it to something like "System tray button (no right-click menu)" ? It's a long name but the clarity might be worth it.

Thanks a lot for your continued work on Pithos!

**Comment by scottkosty** [comment]
Would it be possible to leave the old notification icon plugin available as "notification icon (deprecated)" for one release?

**Comment by TingPing** [comment]
AppIndicator was removed for a possible GTK4 release, however that won't happen soon so it could return.  Also dbusmenu-gtk4 now exists so the new solution can have a menu.

**Comment by scottkosty** [comment]
Thanks for the quick reply! Good to know that a menu is possible.

**Comment by TingPing** [comment]
I've restored the menu feature.

I do agree it should probably be renamed but for now I'll just close this.

**Comment by scottkosty** [comment]
Sounds good, thanks for looking into that!
