### ISSUE TITLE
SSL: CERTIFICATE_VERIFY_FAILED

### ISSUE THREAD

**Issue by kalekundert** [pithos/pithos#664]
Starting just a few minutes ago, I get the following network error whenever I run pithos:

    [SSL: CETRIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1108)

I've seen that this problem has come up in the past, and may be due to changes made by pandora to their certificates: #251, #562.

Here are some relevant version numbers for my system:
- arch linux
- pithos 1.5.1
- openssl 1.1.1.m

Here is the result of using openssl to directly connect to `tuner.pandora.com:443`:
```
$ openssl s_client -connect tuner.pandora.com:443
CONNECTED(00000003)
depth=0 C = US, ST = California, L = Oakland, O = "Pandora Media, LLC", CN = tuner.pandora.com
verify error:num=20:unable to get local issuer certificate
verify return:1
depth=0 C = US, ST = California, L = Oakland, O = "Pandora Media, LLC", CN = tuner.pandora.com
verify error:num=21:unable to verify the first certificate
verify return:1
depth=0 C = US, ST = California, L = Oakland, O = "Pandora Media, LLC", CN = tuner.pandora.com
verify return:1
---
Certificate chain
 0 s:C = US, ST = California, L = Oakland, O = "Pandora Media, LLC", CN = tuner.pandora.com
   i:C = US, O = DigiCert Inc, OU = www.digicert.com, CN = GeoTrust RSA CA 2018
---
Server certificate
-----BEGIN CERTIFICATE-----
MIIGUTCCBTmgAwIBAgIQB6zneD6CGD1dhHJTqWSDAjANBgkqhkiG9w0BAQsFADBe
MQswCQYDVQQGEwJVUzEVMBMGA1UEChMMRGlnaUNlcnQgSW5jMRkwFwYDVQQLExB3
d3cuZGlnaWNlcnQuY29tMR0wGwYDVQQDExRHZW9UcnVzdCBSU0EgQ0EgMjAxODAe
Fw0yMTAxMDUwMDAwMDBaFw0yMjAxMDQyMzU5NTlaMG0xCzAJBgNVBAYTAlVTMRMw
EQYDVQQIEwpDYWxpZm9ybmlhMRAwDgYDVQQHEwdPYWtsYW5kMRswGQYDVQQKExJQ
YW5kb3JhIE1lZGlhLCBMTEMxGjAYBgNVBAMTEXR1bmVyLnBhbmRvcmEuY29tMIIB
IjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAtWj+rCR0D3d8JyYS0EP8Zbrx
Cd6ky8goUBntU2A6pDzQwTT5b++gX3vHKUz2+X9IfXQRBIx1pZeaQZAUsNXKg2wV
Z3bYAuJcITAYSZFRebBwCqaiv+9MD9xYIqZz/u+nmL45qSVkaCXuPK1kIdjP2iPK
2FqpmRdVKwgAP9mQT5OqcjcOaAdS+oNL4TWHo/H76IChQjUP2vG/AsYqjPAi6PpQ
cufeo5NiPrjX303tbIdkXwwmnL6Q5ZscD+xZrTF/q0h8z67ydqHNRbP7uGMkWX9z
9CRf6Nro0E/8oWiud35FHu+K1F441Jzj2S6OEpYJ0IDq/gyquVMpAAi/t8BJDQID
AQABo4IC+jCCAvYwHwYDVR0jBBgwFoAUkFj/sJx1qFFUd7Ht8qNDFjiebMUwHQYD
VR0OBBYEFFXUXarKigSv1rUODpGNtt6FwvqTMGsGA1UdEQRkMGKCEXR1bmVyLnBh
bmRvcmEuY29tghxkZXZpY2UtdHVuZXItbmV3LnBhbmRvcmEuY29tghhkZXZpY2Ut
dHVuZXIucGFuZG9yYS5jb22CFXR1bmVyLW5ldy5wYW5kb3JhLmNvbTAOBgNVHQ8B
Af8EBAMCBaAwHQYDVR0lBBYwFAYIKwYBBQUHAwEGCCsGAQUFBwMCMD4GA1UdHwQ3
MDUwM6AxoC+GLWh0dHA6Ly9jZHAuZ2VvdHJ1c3QuY29tL0dlb1RydXN0UlNBQ0Ey
MDE4LmNybDBLBgNVHSAERDBCMDYGCWCGSAGG/WwBATApMCcGCCsGAQUFBwIBFhto
dHRwOi8vd3d3LmRpZ2ljZXJ0LmNvbS9DUFMwCAYGZ4EMAQICMHUGCCsGAQUFBwEB
BGkwZzAmBggrBgEFBQcwAYYaaHR0cDovL3N0YXR1cy5nZW90cnVzdC5jb20wPQYI
KwYBBQUHMAKGMWh0dHA6Ly9jYWNlcnRzLmdlb3RydXN0LmNvbS9HZW9UcnVzdFJT
QUNBMjAxOC5jcnQwDAYDVR0TAQH/BAIwADCCAQQGCisGAQQB1nkCBAIEgfUEgfIA
8AB2ACl5vvCeOTkh8FZzn2Old+W+V32cYAr4+U1dJlwlXceEAAABdtTIaDwAAAQD
AEcwRQIhAPMQAK2K0H43W407rGMR8Jj+WFafaqJT0QqFgwT4Tw/rAiBvqWB4IYA/
NgwfrhQmSJuHkz28feCkYaxhD9E1AVCtSAB2ACJFRQdZVSRWlj+hL/H3bYbgIyZj
rcBLf13Gg1xu4g8CAAABdtTIaJkAAAQDAEcwRQIhAMzEW6WhJjm7JtloM0vhYw73
CHhBsJRrjccIMaO3Rw4yAiBDlgyniam2anLx3UTFzlH8uuCW3zw+1Sa27SG05gZR
NjANBgkqhkiG9w0BAQsFAAOCAQEAENH/E95Tgqie2YvLWoJBOBi6ulyF2jGK85Qd
Fl8vxdwwFEyTij788YB8sKtR0mV5tJjLhndlyw1EmhsMcBYANtMVJJV8+azSWSg6
BuynjjAVCH9h0g+vsHP6zeTEaczZ8dCAItc5m3M19erskRX8V7ZaXDI+M0C3Vnfn
Jmg0Om3k0GebthaQD+6zFpfdOrgzVMP5/q5U8/JJJGCoabV68bIcDWtdqcwfgcI0
idLbJixQ8ak+WihiCRFtHqfLmPRpsriVCI8mui2byVJ2ZofuIaG/pnEomk72Kn2G
MYpo39tcEhE/lJ69O8B4u5xmHh0eqooKwNktyckidk1ONSZ1NA==
-----END CERTIFICATE-----
subject=C = US, ST = California, L = Oakland, O = "Pandora Media, LLC", CN = tuner.pandora.com

issuer=C = US, O = DigiCert Inc, OU = www.digicert.com, CN = GeoTrust RSA CA 2018

---
No client certificate CA names sent
Peer signing digest: SHA256
Peer signature type: RSA
Server Temp Key: ECDH, P-256, 256 bits
---
SSL handshake has read 2373 bytes and written 445 bytes
Verification error: unable to verify the first certificate
---
New, TLSv1.2, Cipher is ECDHE-RSA-AES256-GCM-SHA384
Server public key is 2048 bit
Secure Renegotiation IS supported
Compression: NONE
Expansion: NONE
No ALPN negotiated
SSL-Session:
    Protocol  : TLSv1.2
    Cipher    : ECDHE-RSA-AES256-GCM-SHA384
    Session-ID: 83CF2C73C05E1AB400144353B651B06F5AD5442F5C340AD2C2263754E13196E8
    Session-ID-ctx: 
    Master-Key: 9B7F44F6DBCEDEA3317AFF57D9439FA4029895D1FAABF9C7F008549E53D91ECD86B689C5A9F7F75460F99DA328C778D4
    PSK identity: None
    PSK identity hint: None
    SRP username: None
    TLS session ticket lifetime hint: 3600 (seconds)
    TLS session ticket:
    0000 - 46 e0 49 30 43 23 a7 83-c0 ca da 0b a4 c8 c7 f1   F.I0C#..........
    0010 - 7b da 92 ff b0 61 96 8a-72 00 e4 09 11 8e e0 51   {....a..r......Q
    0020 - 98 f3 ce 90 df b0 e9 15-1f 32 0f 74 11 c5 0a 0e   .........2.t....
    0030 - f6 3d 9f 93 d4 db 77 65-1d d4 ed ac c2 92 1c 18   .=....we........
    0040 - 57 df b3 c1 b0 13 c0 a6-29 40 b9 9b 9f 0d 88 a5   W.......)@......
    0050 - db 99 25 db d7 90 dd 37-e2 7d bc 36 5f e0 83 38   ..%....7.}.6_..8
    0060 - ad d0 8d c8 6d 4e 2f 43-b4 e7 86 9e c6 c7 d9 ec   ....mN/C........
    0070 - f4 4c bb c3 d4 39 cd 1a-0d 55 d8 59 af 8d 1b 9e   .L...9...U.Y....
    0080 - 0d 74 f8 c8 a4 fc b0 c6-64 13 88 c2 ef bd 93 29   .t......d......)
    0090 - 5d 2b 3a fe 13 ec 54 20-4c 2a d5 45 86 1f 3a 27   ]+:...T L*.E..:'
    00a0 - ed 3d e9 13 09 8d 48 7b-e0 cc d3 80 8d 07 8a 79   .=....H{.......y
    00b0 - 1b 4c 3f 81 a4 d8 73 cb-5e e5 82 7a 8b 7e 90 67   .L?...s.^..z.~.g
    00c0 - 4d db 60 bb 16 36 45 8e-0b a1 a8 5b ad a3 f7 10   M.`..6E....[....
    00d0 - da 6a 8d db eb 8a ca 78-fe a9 09 c0 0e b8 bc a6   .j.....x........
    00e0 - 13 19 ca 9d d0 35 29 3f-a0 75 a7 94 59 b7 35 86   .....5)?.u..Y.5.
    00f0 - 0b c2 49 d1 bf 14 96 2a-f2 6a 9a 00 ce ca 84 fe   ..I....*.j......

    Start Time: 1641253235
    Timeout   : 7200 (sec)
    Verify return code: 21 (unable to verify the first certificate)
    Extended master secret: yes
---
```

**Comment by fraggle00** [comment]
You aren't alone.  Mine died as well.  Running a Pi  with bullseye.  Quit right in the middle of a song, too!

pi@KO4BCN:~ $ openssl s_client -connect tuner.pandora.com:443
CONNECTED(00000003)
depth=0 C = US, ST = California, L = Oakland, O = "Pandora Media, LLC", CN = tuner.pandora.com
verify error:num=20:unable to get local issuer certificate
verify return:1
depth=0 C = US, ST = California, L = Oakland, O = "Pandora Media, LLC", CN = tuner.pandora.com
verify error:num=21:unable to verify the first certificate
verify return:1
depth=0 C = US, ST = California, L = Oakland, O = "Pandora Media, LLC", CN = tuner.pandora.com
verify return:1
---
Certificate chain
 0 s:C = US, ST = California, L = Oakland, O = "Pandora Media, LLC", CN = tuner.pandora.com
   i:C = US, O = DigiCert Inc, OU = www.digicert.com, CN = GeoTrust RSA CA 2018
---
Server certificate
-----BEGIN CERTIFICATE-----
MIIGUTCCBTmgAwIBAgIQB6zneD6CGD1dhHJTqWSDAjANBgkqhkiG9w0BAQsFADBe
MQswCQYDVQQGEwJVUzEVMBMGA1UEChMMRGlnaUNlcnQgSW5jMRkwFwYDVQQLExB3
d3cuZGlnaWNlcnQuY29tMR0wGwYDVQQDExRHZW9UcnVzdCBSU0EgQ0EgMjAxODAe
Fw0yMTAxMDUwMDAwMDBaFw0yMjAxMDQyMzU5NTlaMG0xCzAJBgNVBAYTAlVTMRMw
EQYDVQQIEwpDYWxpZm9ybmlhMRAwDgYDVQQHEwdPYWtsYW5kMRswGQYDVQQKExJQ
YW5kb3JhIE1lZGlhLCBMTEMxGjAYBgNVBAMTEXR1bmVyLnBhbmRvcmEuY29tMIIB
IjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAtWj+rCR0D3d8JyYS0EP8Zbrx
Cd6ky8goUBntU2A6pDzQwTT5b++gX3vHKUz2+X9IfXQRBIx1pZeaQZAUsNXKg2wV
Z3bYAuJcITAYSZFRebBwCqaiv+9MD9xYIqZz/u+nmL45qSVkaCXuPK1kIdjP2iPK
2FqpmRdVKwgAP9mQT5OqcjcOaAdS+oNL4TWHo/H76IChQjUP2vG/AsYqjPAi6PpQ
cufeo5NiPrjX303tbIdkXwwmnL6Q5ZscD+xZrTF/q0h8z67ydqHNRbP7uGMkWX9z
9CRf6Nro0E/8oWiud35FHu+K1F441Jzj2S6OEpYJ0IDq/gyquVMpAAi/t8BJDQID
AQABo4IC+jCCAvYwHwYDVR0jBBgwFoAUkFj/sJx1qFFUd7Ht8qNDFjiebMUwHQYD
VR0OBBYEFFXUXarKigSv1rUODpGNtt6FwvqTMGsGA1UdEQRkMGKCEXR1bmVyLnBh
bmRvcmEuY29tghxkZXZpY2UtdHVuZXItbmV3LnBhbmRvcmEuY29tghhkZXZpY2Ut
dHVuZXIucGFuZG9yYS5jb22CFXR1bmVyLW5ldy5wYW5kb3JhLmNvbTAOBgNVHQ8B
Af8EBAMCBaAwHQYDVR0lBBYwFAYIKwYBBQUHAwEGCCsGAQUFBwMCMD4GA1UdHwQ3
MDUwM6AxoC+GLWh0dHA6Ly9jZHAuZ2VvdHJ1c3QuY29tL0dlb1RydXN0UlNBQ0Ey
MDE4LmNybDBLBgNVHSAERDBCMDYGCWCGSAGG/WwBATApMCcGCCsGAQUFBwIBFhto
dHRwOi8vd3d3LmRpZ2ljZXJ0LmNvbS9DUFMwCAYGZ4EMAQICMHUGCCsGAQUFBwEB
BGkwZzAmBggrBgEFBQcwAYYaaHR0cDovL3N0YXR1cy5nZW90cnVzdC5jb20wPQYI
KwYBBQUHMAKGMWh0dHA6Ly9jYWNlcnRzLmdlb3RydXN0LmNvbS9HZW9UcnVzdFJT
QUNBMjAxOC5jcnQwDAYDVR0TAQH/BAIwADCCAQQGCisGAQQB1nkCBAIEgfUEgfIA
8AB2ACl5vvCeOTkh8FZzn2Old+W+V32cYAr4+U1dJlwlXceEAAABdtTIaDwAAAQD
AEcwRQIhAPMQAK2K0H43W407rGMR8Jj+WFafaqJT0QqFgwT4Tw/rAiBvqWB4IYA/
NgwfrhQmSJuHkz28feCkYaxhD9E1AVCtSAB2ACJFRQdZVSRWlj+hL/H3bYbgIyZj
rcBLf13Gg1xu4g8CAAABdtTIaJkAAAQDAEcwRQIhAMzEW6WhJjm7JtloM0vhYw73
CHhBsJRrjccIMaO3Rw4yAiBDlgyniam2anLx3UTFzlH8uuCW3zw+1Sa27SG05gZR
NjANBgkqhkiG9w0BAQsFAAOCAQEAENH/E95Tgqie2YvLWoJBOBi6ulyF2jGK85Qd
Fl8vxdwwFEyTij788YB8sKtR0mV5tJjLhndlyw1EmhsMcBYANtMVJJV8+azSWSg6
BuynjjAVCH9h0g+vsHP6zeTEaczZ8dCAItc5m3M19erskRX8V7ZaXDI+M0C3Vnfn
Jmg0Om3k0GebthaQD+6zFpfdOrgzVMP5/q5U8/JJJGCoabV68bIcDWtdqcwfgcI0
idLbJixQ8ak+WihiCRFtHqfLmPRpsriVCI8mui2byVJ2ZofuIaG/pnEomk72Kn2G
MYpo39tcEhE/lJ69O8B4u5xmHh0eqooKwNktyckidk1ONSZ1NA==
-----END CERTIFICATE-----
subject=C = US, ST = California, L = Oakland, O = "Pandora Media, LLC", CN = tuner.pandora.com

issuer=C = US, O = DigiCert Inc, OU = www.digicert.com, CN = GeoTrust RSA CA 2018

---
No client certificate CA names sent
Peer signing digest: SHA256
Peer signature type: RSA
Server Temp Key: ECDH, P-256, 256 bits
---
SSL handshake has read 2373 bytes and written 435 bytes
Verification error: unable to verify the first certificate
---
New, TLSv1.2, Cipher is ECDHE-RSA-AES256-GCM-SHA384
Server public key is 2048 bit
Secure Renegotiation IS supported
Compression: NONE
Expansion: NONE
No ALPN negotiated
SSL-Session:
    Protocol  : TLSv1.2
    Cipher    : ECDHE-RSA-AES256-GCM-SHA384
    Session-ID: D80CCDD13B2393DFF43BFDC18B71A28F72A7EEF6E735EB40F95B66C69A25C280
    Session-ID-ctx: 
    Master-Key: EEB67812790E08BADA07A26FC2708E87E95486BEC576F6A8E262EEB2B839C9BB65CC1E849804FFFF94028F494ABE84B4
    PSK identity: None
    PSK identity hint: None
    SRP username: None
    TLS session ticket lifetime hint: 3600 (seconds)
    TLS session ticket:
    0000 - 46 e0 49 30 43 23 a7 83-c0 ca da 0b a4 c8 c7 f1   F.I0C#..........
    0010 - 1b a7 b3 72 e8 6a a3 44-05 47 b7 43 dc bc fc ed   ...r.j.D.G.C....
    0020 - 15 e3 de 74 bf 55 b2 e6-26 d7 ec 30 f6 99 5e 5d   ...t.U..&..0..^]
    0030 - aa 54 5c f9 4c 88 b9 3b-3e 66 7c 46 e4 14 9d 64   .T\.L..;>f|F...d
    0040 - 10 42 a3 f0 c7 28 e8 9a-fb 73 41 e3 c5 8c 42 3d   .B...(...sA...B=
    0050 - a3 b8 e2 eb 25 0d 1d 5f-9a 83 e0 f1 bd 4b 05 e5   ....%.._.....K..
    0060 - aa 68 bd 3b 7a aa 45 d9-a4 a8 11 80 57 a0 d4 a0   .h.;z.E.....W...
    0070 - ac 25 8b 5c f3 87 66 51-c1 46 4c 00 31 8d 33 7c   .%.\..fQ.FL.1.3|
    0080 - 18 4c aa bb 72 37 d0 5f-d3 b7 24 29 0a ed 95 db   .L..r7._..$)....
    0090 - d6 5f 56 2a 8f fc 04 33-7e 86 c5 f3 8e d7 b2 e5   ._V*...3~.......
    00a0 - aa f2 54 48 1b 0b c4 cf-c9 9a e1 4f 18 8d 67 1d   ..TH.......O..g.
    00b0 - cd 22 df c6 e3 00 3a 95-d1 f7 fb 11 ca fe 4a d4   ."....:.......J.
    00c0 - e3 1b f2 06 b2 62 6f c5-52 5e 2d 46 a6 87 2f ee   .....bo.R^-F../.
    00d0 - 91 66 e1 bc 2d 97 ce e9-44 d7 b3 ff 70 73 9d 86   .f..-...D...ps..
    00e0 - 09 94 8f 3c b2 31 de a7-ba c2 19 18 3e 23 ee fe   ...<.1......>#..
    00f0 - 7d 16 3e 66 a3 2d 29 d1-39 e7 d5 ec fd 3b 7c 72   }.>f.-).9....;|r

    Start Time: 1641254610
    Timeout   : 7200 (sec)
    Verify return code: 21 (unable to verify the first certificate)
    Extended master secret: yes
---

**Comment by Lvl4Sword** [comment]
@kalekundert According to https://crt.sh/?q=tuner.pandora.com it's not a brand new certificate, so that's *probably* not it.

**Comment by pebkacs** [comment]
Looks like I'm not the only one.  Same problem here.  I was running v1.1.2 from Ubuntu's repositories, so I tried upgrading to v1.5.1 with FlatPak, but no difference.  I still get the same error.

**Comment by SicVolo** [comment]
The signing CA cert from digicert is expired or about to be expire depending on your timezone. They'll have to reissue their cert again from a non-expired CA. Wait till then or reconfigure your system to trust an expired CA cert (not recommended)

**Comment by wbraswell** [comment]
I am also experiencing this same issue with Pithos v1.1.1 in Xubuntu.

**Comment by SicVolo** [comment]
The SSL cert is set to expire on Jan 4 at midnight GMT, but your OS is ignoring the time and thinks it's already expired. https://crt.sh/?id=3950291266
You'd have to wait until they refresh the cert.

**Comment by kalekundert** [comment]
Sure enough, I just had to wait a few hours.  Hopefully everyone else with this problem has the same experience.  Thanks for taking the time to look into this!
