### ISSUE TITLE
How to install on Windows?

### ISSUE THREAD

**Issue by Mattrod01** [pithos/pithos#668]
I tried to install the last release of pithos-for-windows, however it refuses to work. I had noticed that the project states that upstream Pithos has basic windows support, so how would I install it? 

![image_2022-01-25_174203](https://user-images.githubusercontent.com/98431400/151071979-f87188b5-0f04-4382-af2d-064d9e35a629.png)

**Comment by TingPing** [comment]
Windows is not directly supported by this project. That readme is outdated now.

If you would like to use Pithos still the best way is probably to use the Linux version on Windows via WSL: https://docs.microsoft.com/en-us/windows/wsl/about

**Comment by Mattrod01** [comment]
Tried out WSL, but the farthest I could get was to have the application open, but it would give me an error of "You need to install a service such as gnome-keyring. Error: g-io-error-quark: Cannot autolaunch D-Bus without X11 $DISPLAY (0)" with the dbus part of the error shown on the pithos app. I installed gnome-keyring and also seahorse to try to fix it, but it still gives the same error. This was also after a long process of getting flatpak installed, as it required a work around to get it on WSL.

**Comment by TingPing** [comment]
Hmm, it should be doable to get working but yeah sorry it wasn't straightforward.

I'm just going to close this though as Windows just hasn't been a priority of the project and none of the developers intend on improving that situation, sorry.
