### ISSUE TITLE
Quick Mix gone

### ISSUE THREAD

**Issue by Matt832** [pithos/pithos#669]
I had 4 or 5 stations set in my Quick mix that play all the time. Today I found Pithos playing a random station and when I went to reset it to Quick Mix, I found stations to select but no option to play the mix. Just the other day I was thinking how perfect the mix I had selected was, now it's gone.

As a long term user that was one of my favorite options.  What happened?

**Comment by rqkeating** [comment]
Not only is it gone, you can't recreate it or make a new one either.

**Comment by darkgreen** [comment]
Yep ... I've lost the Mix option as well just recently (within a few days). 

Running Ubuntu Mate 21.10, Pithos 1.1.2. 

Thanks to all Pithos developers ... It's a really awesome app.

**Comment by rqkeating** [comment]
Started up Pithos today and Quick Mix is back.  Hmmmm.

**Comment by Matt832** [comment]
Same here, Mix is back.  Weird.

**Comment by TingPing** [comment]
This is all on the Pandora service. It gives the list of stations.
