### ISSUE TITLE
Cannot sign in to Pandora

### ISSUE THREAD

**Issue by dmtparker** [pithos/pithos#675]
Just tonight I had a new problem. When I open Pithos, it says "Logging in" then "Reconnecting" then a popup says that my username or password is invalid. Now neither have changed in years and I can log in to the Pandora web page just fine. What's up with this? Is it one more way Pandora is trying to block Pithos?

**Comment by TingPing** [comment]
Logging in with a free account works here.

Pandora servers just regularly seem to have issues like this. Always try again later.

**Comment by dmtparker** [comment]
You're right. Today it works. I was concerned because I couldn't log in with Pithos, but could from their website. Today either works.

**Comment by TingPing** [comment]
For future information, how https://pandora.com works is quite different to Pithos. This behaves more like other native applications such as the Android application or ones built into devices.
