### ISSUE TITLE
Cannot start the app. Returns app/io.github.pithos/x86_64/master not installed

### ISSUE THREAD

**Issue by MshmurdaM** [pithos/pithos#676]
When I run the flatpak run io.github.pithos, it returns app/io.github.pithos/x86_64/master not installed. When I run flatpak install flathub io.github.Pithos, it returns io.github.Pithos/x86_64/stable is already installed. How would I fix this, or install the master? Ubuntu 22.04 LTS on WLS 2, Windows 10.

**Comment by TingPing** [comment]
Are you running any commands with `sudo`?

**Comment by MshmurdaM** [comment]
Just following the instructions here https://github.com/pithos/pithos/wiki/Flatpak

**Comment by TingPing** [comment]
Odd.

What is the output of `flatpak list` to show installed packages.

**Comment by TheKrafter** [comment]
App IDs are case sensitive. In the launch command you supplied you're launching pithos with a lowercase p.
Try launching `io.github.Pithos`.

**Comment by Fil4ment** [comment]
I'm having the same issue. I've made sure to use correct case. No resolution?
