### ISSUE TITLE
After viewing song info on several songs then the song timer stops and Pithos fails after that to advance songs

### ISSUE THREAD

**Issue by rskunath** [pithos/pithos#682]
If you right click the song list to click on song info several times on different songs, at random, the song info always comes up, but now and then the song timer stops incrementing. When this happens the song will finish but Pithos won't advance to the next song in the list it just sits there in silence. Restarting Pithos gets it going again.

This is SuSE Tumbleweed and KDE. Pithos is a git clone from today, but the older 1.51 has this behavior as I tested that earlier too.

**Comment by bkw777** [comment]
Stops at the end of songs for me without touching anything.

Sometimnes more frequently than others. Today it's doing it on every single song. Using pianobar instead for now (no problems with the same login, paid account).

In another old, and for some reason closed issue even though it's clearly not fixed, it was guessed that it might be pulseaudio but I switched to pipewire a week or so ago and it didn't change. Problem has been the same for many months, maybe over a year. I don't use it every day so I can't say when it exactly started happening, but not at all recently.

**Comment by rskunath** [comment]
I can't replicate that behavior here.

I'm running Suse Tumbleweed and Pithos 1.5.1 (source built a while ago) 
and it's using PulseAudio and also the PulseAudio Equalizer. I have a 
Pandora Premium account so I am logged into Pandora.

I can't replicate the stopping after each song that you are seeing here. 
It just keeps rolling from one song right into the next song.

Rick Kunath

**Comment by sygibson** [comment]
I'm new to Pithos - so far, loving having a lightweight Pandora player for my Linux desktop.  As I play songs, they work for a while.  Then at some random point, the current playing song shows seconds count of 0:00, the player things it's still playing, but nothing plays.

If I hit the "next" advance button (>>|) then it (usually) will advance to the next song and start playing.  I know for certain it has done this on starting to play the next song.  I believe it has just plain stopped in the middle of some songs and the timer counter stops advancing.

Pressing "pause" and then "play" does not force it to restart playing the current song.  I have to advance to next song.  I see this problem several times a day.  I am using a paid Pandora Premium account.

**My environment:**

Pithos Version/install:
```
1.6.0-1.2 (installed from OpenSUSE Main OSS repo http://download.opensuse.org/tumbleweed/repo/oss/ ) 
```

Other Versions:
```
OpenSUSE Tumbleweed 20230424
PipeWire 0.3.69-2.1
Operating System: openSUSE Tumbleweed 20230424
KDE Plasma Version: 5.27.4
KDE Frameworks Version: 5.105.0
Qt Version: 5.15.9
Kernel Version: 6.2.12-1-default (64-bit)
Graphics Platform: X11

```

**Comment by rskunath** [comment]
I am seeing something similar. This is on the Tumbleweed distro provided 
version 1.60 and also on a source built git pull I did today (also 1.6). 
I am also a Premium subscriber.

It ran through 3 songs and then stopped after the third completed and 
did not play after that. I did not hit the forward arrow, unless I am 
wrong this tells Pandora something, like to play less of this or 
something, but I could be wrong.

I shut down Pithos and restarted it and it then played away for a while 
without stopping. This seems to be the way of it.

One thing I did run across when looking through reported issues on 
github today was the cache issue. I took a look and sure enough there 
were 5 directories of Pithos cached jpeg art. I deleted these and I'll 
see if that has any effect. The cache files are in ~/.cache/Pithos and a 
bunch of alpha random characters after the Pithos. You'll see them there.

There was some discussion about fixing this on github and I don't know 
if that was done and this that I had is leftovers or not. Also I don't 
know if it really has anything to do with our playback issue, but it 
seemed that you were looking at Info, so maybe. I wasn't doing anything 
but playing songs.

Rick Kunath

**Comment by rskunath** [comment]
After the cache deletion it ran for 6 songs and then stopped again. A 
restart got it going again. More songs were cued up waiting to be played 
but it never moved off the last one it played on to the next to be played.

So there is definitely something going on with the streaming.

Rick Kunath

**Comment by rskunath** [comment]
Thanks so much. This fixes the issue for me :)
