### ISSUE TITLE
Fresh Mint install.  Pithos fails with "No secret collection at path:......."

### ISSUE THREAD

**Issue by docter-tirrud** [pithos/pithos#684]
I *just* installed Linux Mint 21 and wanted to use Pithos (1.5.1) for Pandora.  When I launch Pithos , I get a dialog that says:
```
No such secret collection at path: /org/freedesktop/secrets/collection/login
You need to install a service such as gnome-keyring.
```
Except gnome-keyring is already installed.

I'm new to Linux, so be gentle with me.

**Comment by TingPing** [comment]
I don't really think its a Pithos issue and more a distro issue.

Anyway I've made a change that could behave differently if you want to install a test flatpak: https://github.com/pithos/pithos/actions/runs/3137703876

**Comment by docter-tirrud** [comment]
Fixed it!  Thank you for taking the time.

**Comment by TingPing** [comment]
I made a 1.6.0 release with this changed, will be on https://flathub.org today.
