### ISSUE TITLE
Pithos cache grows without bound

### ISSUE THREAD

**Issue by zaporter** [pithos/pithos#686]
## Problem
I'm a very long time pithos fan and I was just making a backup when I realized that: 
`du -hs ~/.var/app/io.github.Pithos/cache/tmp` returns 47Gib
`find -iname "*.jpeg" | wc -l` returns 275067
## Expected
Pithos should not grow the cache forever and should only cache a few Gib at most. Having more than a quarter million jpegs feels wrong. 

## Solution
I could just run `rm -rf` every few months with a crontab, however this behavior still feels like a bug. Would it be possible to add some kind of cache clearing algorithm? If you don't want to write this, I could do it if you tell me how you want it implemented.

P.S. I am a huge fan of yours, TingPing. Thank you for your work.

**Comment by TingPing** [comment]
@jarebear6expepjozn6rakjq5iczi3irqwphcvb Hey a PR for this would be good.

There is actually a second problem. The cache files are never actually read as a cache. The directory they go into changes each run.

I agree it should be a core feature. For now I wouldn't even include settings for it.

**Comment by go140point6** [comment]
This fix breaks running Pithos on Debian (Bullseye) tested with a Pi 4 (64bit OS) and Pi Zero W (32bit OS) when compiling from source.  I've never been very successful with Flatpak on the Pi, so get Pithos running from source.  Perhaps the version of the tempfile module needs to be updated in Bullseye, but to get Pithos v1.6.1 running I removed the "ignore_cleanup_errors=True" flag from pithos/pithos.py line 372:

self.tempdir = tempfile.TemporaryDirectory(prefix='pithos-', dir=tempdir_base, ignore_cleanup_errors=True)

That flag seems to be unknown to whatever version Bullseye is running.
