### ISSUE TITLE
RHEL-7 build dependencies

### ISSUE THREAD

**Issue by scottsideleau** [pithos/pithos#688]
For those that may be interested, I am documenting the following build dependencies for RHEL-7 hosts:

```
sudo yum install meson libappstream-glib-devel  \
  gstreamer1-libav gtk3 libsecret gnome-keyring \
  cairo-devel cairo-gobject-devel gobject-introspection-devel
```

NOTE-1: The [rpmfusion-free](https://rpmfusion.org/Configuration/) repository is still required.  [EPEL](https://docs.fedoraproject.org/en-US/epel/#_el7) is also needed.

`pip3 install pygobject gobject pgi`

NOTE-2: Tested with python3.7.15 on RHEL 7.9, which I installed using [scottsideleau/get-python-src](https://github.com/scottsideleau/get-python-src), but there are many alternatives.

NOTE-3: RHEL-7 users will need to manually fetch and install a [supported Python3](https://devguide.python.org/versions/#supported-versions) version.

**Comment by TingPing** [comment]
I added this to the wiki: https://github.com/pithos/pithos/wiki/Installing-from-Source#rhel-7
