### ISSUE TITLE
Plugins not working (Python 3.11)

### ISSUE THREAD

**Issue by rudism** [pithos/pithos#690]
Pithos seems to mostly work OK on my system (Void Linux) but the "Plugins" tab of preferences is empty, and plugin functionality is not working (specifically I wanted to get Mpris working so it would respond to media button controls). When I launch Pithos from the command line (here I am running from source, but this also happens when running Pithos 1.5.1 installed using the xbps package manager), it displays this error:

```
Traceback (most recent call last):
  File "/home/rudism/source/pithos/pithos/plugin.py", line 147, in on_got_bus
    plugin = plugins[name] = load_plugin(name, window, bus)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/rudism/source/pithos/pithos/plugin.py", line 101, in load_plugin
    module = __import__('pithos.plugins.' + name)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/rudism/source/pithos/pithos/plugins/mpris.py", line 66, in <module>
    class PithosMprisService(DBusServiceObject):
  File "/home/rudism/source/pithos/pithos/plugins/mpris.py", line 647, in PithosMprisService
    @dbus_method(MEDIA_PLAYER2_IFACE)
     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/rudism/source/pithos/pithos/plugins/dbus_util/DBusServiceObject.py", line 138, in decorator
    in_args = _create_arginfo_list(func, in_signature)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/rudism/source/pithos/pithos/plugins/dbus_util/DBusServiceObject.py", line 123, in _create_arginfo_list
    arg_names = inspect.getargspec(func).args
                ^^^^^^^^^^^^^^^^^^
AttributeError: module 'inspect' has no attribute 'getargspec'. Did you mean: 'getargs'?
```

A bit of googling seems to suggest it may be some kind of incompatibility with Python 3.11. Here's the version on my system:

```
❯ python --version
Python 3.11.1
```

**Comment by rudism** [comment]
Replacing that one call to `inspect.getargspec` in `pithos/plugins/dbus_util/DBusServiceObject.py` with `inspect.getfullargspec` clears that error and fixes the plugins on Python 3.11. I'm not sure what the implications of that are as far as backwards compatibility with older Python versions though.

**Comment by TingPing** [comment]
According to the documentation `inspect.getfullargspec()` isn't a new API.

If you want to open a PR I'll test it and merge it.

**Comment by rudism** [comment]
@TingPing thanks, I've created the PR  at #691

**Comment by vadim-cherepanov** [comment]
When this is going to be available in an official release? This is a serious bug affecting new installations on systems that are already updated to the new Python version (Arch Linux in my case). In particular, this bug prevents any plugins from loading, showing up and working (no system icon etc.). I can confirm that the change above resolves the issue.

**Comment by TingPing** [comment]
@vadim-cherepanov https://github.com/pithos/pithos/releases/tag/1.6.1

**Comment by vadim-cherepanov** [comment]
Wow, that was fast! Thanks. Now I wish someone would also update the AUR package. You are no longer its maintainer, are you? I remember you were at some point unless I am not mistaken.

**Comment by TingPing** [comment]
I was but no longer. You can click flag out of date on its page: https://aur.archlinux.org/packages/pithos
