### ISSUE TITLE
Shorter Tracks Labelled as Advertisements

### ISSUE THREAD

**Issue by TheKrafter** [pithos/pithos#693]
Several songs, all less than a minute, are reported as "Commercial Advertisement" in Pithos' UI (which they are not) but are reported correctly to MPRIS.
For example:
![Pithos Showing Track as a "Commercial Advertisement", but it is reported properly as the track that is being played to MPRIS](https://i.imgur.com/Bc7oAjE.png)

If pithos does not play any ads, why does it label some tracks as ads? Could this 'feature' be safely removed or is there a reason to keep it I am unaware of?

**Comment by TingPing** [comment]
At some point Pandora started playing ads just like regular songs. We only can guess if it is an ad at that point and the logic for that assumes anything shorter than 45 seconds is one.

https://github.com/pithos/pithos/blob/7eab10b11ee008cccffd35b673e289fe32fc2e67/pithos/pithos.py#LL1118C35-L1118C35

**Comment by TheKrafter** [comment]
Oh, weird. You're right, there's nothing we can really do about that then.
Unless we would check those shorter songs' artist against a list of known advertisers?? (which would probably be shorter than a list of all artists, but not sure how we would obtain such a list as this happens very rarely)

However, one thing of note -- never have I ever gotten a real ad in pithos. So maybe they discontinued doing it that way? If anyone has had a real ad like this then I'd love to hear from them.

**Comment by TingPing** [comment]
I'd probably prefer removing the logic than keeping a list.

I have no idea what Pandora does these days though.

**Comment by TheKrafter** [comment]
K, I've been using pithos for a solid 2 years now, and this has never been an actual ad. I'll make a PR soon and remove it then.
