### ISSUE TITLE
ERROR:root:fault code: 1001 INVALID_AUTH_TOKEN message: Invalid username and/or password

### ISSUE THREAD

**Issue by ksaye** [pithos/pithos#701]
Starting today, I started getting the error "pandora.pandora.PandoraAuthTokenInvalid".

I have been using the library for months, but just today the error startred.  Any chance Pandora has blocked this?

Sample code:

        Python 3.8.10 (default, May 26 2023, 14:05:08) 
        [GCC 9.4.0] on linux
        Type "help", "copyright", "credits" or "license" for more information.
        >>> from pandora import *
        >>> userName='k*****@saye.org'
        >>> passWord='M*******0'
        >>> client = pandora.data.client_keys[pandora.data.default_client_id]
        >>> Application = Pandora()
        >>> Application.connect(client=client, user=userName, password=passWord)
        ERROR:root:fault code: 1001 INVALID_AUTH_TOKEN message: Invalid username and/or password
        Traceback (most recent call last):
          File "<stdin>", line 1, in <module>
          File "/mnt/disk2/opt/music/pandora/pandora.py", line 306, in connect
            user = self.json_call('auth.userLogin', auth_args, https=True)
          File "/mnt/disk2/opt/music/pandora/pandora.py", line 240, in json_call
            raise PandoraAuthTokenInvalid(msg)
        pandora.pandora.PandoraAuthTokenInvalid
        >>> print(pandora.data.client_keys[pandora.data.default_client_id])
        {'deviceModel': 'android-generic', 'username': 'android', 'password': 'AC7IBG09A3DTSYM4R41UJWL07VLN8JI7', 'rpcUrl': '://tuner.pandora.com/services/json/?', 'encryptKey': '6#26FRL$ZWD', 'decryptKey': 'R=U!LH$O2B#', 'version': '5'}

**Comment by TingPing** [comment]
My free account login works, so I'd guess it is a temporary issue.

**Comment by ksaye** [comment]
I have tried 3 different accounts and all get the same message.

@TingPing  what pandora.data.default_client_id are you using?  does it match mine above?

**Comment by TingPing** [comment]
It is the same as yours, it hasn't changed in well over a decade.

**Comment by ksaye** [comment]
Ok, so when I tethered my device to my phone, it worked fine -- meaning either my IP is blacklisted or there is a network issue.
