### ISSUE TITLE
flathub.org version  is 1.6.0

### ISSUE THREAD

**Issue by henrythemouse** [pithos/pithos#702]
I noticed that the flathub.org version is 1.6.0. Not sure if this is a typo or 1.6.1 has not been posted there yet. 

When I install it and open the About dialog the version there is still 1.6.0

**Comment by TingPing** [comment]
Updated https://github.com/flathub/io.github.Pithos/commit/a9d86a4e4991592f64b726d503f459b752bdd74f

Was a very small difference.
