### ISSUE TITLE
new version 1.6  is ignoring dark theme system colors 

### ISSUE THREAD

**Issue by BigRobPage** [pithos/pithos#703]
The new version 1.6  is ignoring dark theme system colors, Going to see if it reproduces on the next system i upgrade. Running Linux Mint 21.3 Mate.

**Comment by TingPing** [comment]
Pithos is not involved one bit in theming.

I would guess you installed the Flatpak version? If so I wrote some documentation on how to fix theming issues: https://blog.tingping.se/2023/04/20/Themes-and-Flatpak.html

**Comment by rjsmith899** [comment]
This I would guess you installed the Flatpak version? If so I wrote some documentation on how to fix theming issues: https://blog.tingping.se/2023/04/20/Themes-and-Flatpak.html that TingPing Post does not work. I want to get dark theme in pithos.
