### ISSUE TITLE
Can't save credentials with flatpak and KDE6

### ISSUE THREAD

**Issue by Erfboom** [pithos/pithos#707]
I've read on here that the flatpak version of Pithos is supposed to save credentials to `~/.var/app/io.github.Pithos/data/keyrings/`, however, regardless if I open Pithos using `flatpak --system` or `flatpak --user`, I type in the password and it won't save to that directory.

Using Flatseal I then try to give it talk permissions to `org.freedesktop.secrets`, but that seems to be depreciated(?) as the flatpak is not supposed to talk to anything outside of its immediate directory as a proper sandbox.

Using the native application built for Opensuse, the same issue occurs. I have gnome-keyring (seahorse), alongside kwallet6, which I understand is the preferred keyring manager. I open up seahorse, unlock the existing wallet with the existing Pithos credentials, try Pithos again, no dice. 

I then disabled the KDEWallet system altogether thinking there might be a problem with both gnome and kde, but still no go.

Not sure where to go from here to have either application be able to access the passwords that already existed in the system. I updated my DE from kde5 to kde6 and with it the wallet, so maybe that has something to do with it?

**Comment by Erfboom** [comment]
Might be my wallet system is busted. I'll close this once I confirm.

**Comment by Erfboom** [comment]
Updating my system and doing a reboot fixed the native application not being able to access KWallet. However, the flatpak version remains the same.

**Comment by TingPing** [comment]
Unfortunately `xdg-desktop-portal` depends on `gnome-keyring`.

KWallet could in theory implement `org.freedesktop.impl.portal.Secret` but it doesn't currently.

**Comment by TingPing** [comment]
> Using Flatseal I then try to give it talk permissions to org.freedesktop.secrets, but that seems to be depreciated(?) as the flatpak is not supposed to talk to anything outside of its immediate directory as a proper sandbox.

Adding this permission *should* bypass the portal and work fine. It is insecure but... oh well.

**Comment by Erfboom** [comment]
It did for a while, but it no longer does since the KDE update.

**Comment by Erfboom** [comment]
Found a fix here: https://github.com/pithos/pithos/issues/696

1. Download seahorse
2. Create a new Keyring and call it `login`
3. Close out of seahorse
4. Re-open it, unlock the keyring
5. Open Pithos and enter your credentials.

You should now see the passwords be entered into seahorse successfully. I chose default blowfish encryption.

Not sure if Pithos is expecting something that doesn't exist, or if the keyring in seahorse is incompatible with pithos until it's recreated.

**Comment by Erfboom** [comment]
the above fix will indeed fix the pithos password issue, but it will then break everything else. kdewallet disappears when you create a new keyring. everything else needs kdewallet, pithos needs login.

upon reboot, kdewallet will remake itself after you unlock the wallet and the keyring login will disappear.

**Comment by TingPing** [comment]
> Not sure if Pithos is expecting something that doesn't exist, or if the keyring in seahorse is incompatible with pithos until it's recreated.

FWIW Pithos isn't really doing anything unique. This is all handled by the libsecret library/gnome-keyring daemon.

**Comment by Erfboom** [comment]
Right but that is currently not working with KDE. Not saying it's Pithos
that broke, but on two different systems with KDE6, the flatpack can't
create an encrypted credential in KDE Wallet.

Up until recently, the distribution package could make a password, but now
it can't create nor read the KDE wallet even if it's unlocked.

Creating a new keyring fixes this problem, but then things like wifi won't
be able to save credentials in the keyring Pithos likes.

So is it a break in the gnome keyring daemon as it talks to KDE? Is it KDE
and the permissions set on kdewallet tripping the gnome keyring up?

**Comment by TingPing** [comment]
> Up until recently, the distribution package could make a password, but now
it can't create nor read the KDE wallet even if it's unlocked.

AFAICT KDE 5.97.0 added `org.freedesktop.secrets` support to KWallet. So that is likely what introduced this issue.

Whether the bug is in KWallet or libsecret I cannot say.

**Comment by pebkacs** [comment]
For what it's worth, I appear to be having the same issue here since upgrading from Kubuntu 22.04 to 24.04.

```
Operating System: Kubuntu 24.04
KDE Plasma Version: 5.27.11
KDE Frameworks Version: 5.115.0
Qt Version: 5.15.13
Kernel Version: 6.8.0-45-generic (64-bit)
Graphics Platform: X11
```
