### ISSUE TITLE
FYI: Update to 1.6.2 might require a settings reset (no stations displayed, possible login issue).

### ISSUE THREAD

**Issue by neoh4x0r** [pithos/pithos#710]
I  recently updated from 1.6.1 (791a99c9fcaf208d090f37a859b0d48f35d5e9ff) to 1.6.2 (0c5ca80c67ed18d292827f7582e2a9c935d50bea) -- I had not logged in or used pithos for a bit between those commits.

The update was needed because (791a99c9fcaf208d090f37a859b0d48f35d5e9ff) gave me a **Network Error**, but after updating (to 0c5ca80c67ed18d292827f7582e2a9c935d50bea) no stations were displayed and it didn't seem like it was even trying to login to pandora.

After a bunch of trial and error, I ended up using ```dconf-editor``` to rest the settings, recursively, under **/io/github/Pithos/**.

Naturally I had to go back and set my username, password, and other settings, but, the stations and everything were back to working as expected.

I'm not entirely sure of what issue the settings reset fixed (other than forcing a re-authentication).

**Comment by neoh4x0r** [comment]
> 1.6.2 didn't change anything related to settings or logins.

(While not strickly a 1.6.2 issue)....if there was a problem with the login token....I didn't receive any notice from pithos that an exception had occurred.

At the very least it should have asked for me to re-authenticate to pandora .

I could not reset the login information without doing a complete gio-settings reset, I saw no way in the preferences gui to refresh the login information, ie. get a new token).

**Comment by TingPing** [comment]
> I could not reset the login information without doing a complete gio-settings reset, I saw no way in the preferences gui to refresh the login information (other than changing user/pass, but thy had not changed).

The setting stored in Gio is just your email. The email is then the key to look up your password. If the contents of that field are correct, well then there was nothing to change.

**Comment by TingPing** [comment]
Anyway closing this as inactionable. Weird issue with the keyring :shrug:.
