### ISSUE TITLE
Dark Theme Flatpak

### ISSUE THREAD

**Issue by rjsmith899** [pithos/pithos#711]
The Flatpak for Pithos needs a dark theme. Please add this in the next version.

**Comment by TingPing** [comment]
Pithos just respects your set gtk3 theme.

Some info on how to set that https://blog.tingping.se/2023/04/20/Themes-and-Flatpak.html

**Comment by rjsmith899** [comment]
I've located the Linux PPA for ubuntuhandbook1/apps, and it works perfectly with the dark theme system. I have no doubt that this is the best option for me, so I'll be using this PPA moving forward. I expect you to continue producing and maintaining the PPA package because it's the superior choice.
