### ISSUE TITLE
Gnome 45 runtime warnings

### ISSUE THREAD

**Issue by TravellerNL** [pithos/pithos#716]
The following warning pops up when updating Pop!_OS (Ubuntu 22.04.1) for quite some time now:

Info: runtime org.gnome.Platform branch 45 is end-of-life, with reason:
   The GNOME 45 runtime is no longer supported as of September 18, 2024. Please ask your application developer to migrate to a supported platform.
Info: applications using this runtime:  io.github.Pithos

Therefore dear developers, as it the terminal has spoken...
Please migrate to a supported platform!

Using Pithos 1.6.2

**Comment by brandonlichtenwalner** [comment]
I am receiving the exact same warning during a `flatpak update` on Fedora Silverblue 41, also using Pithos 1.6.2 from Flathub. And see the following in Gnome Software:
![image](https://github.com/user-attachments/assets/a6352e73-228a-4e06-a0bf-dc74fc1b911e)
![image](https://github.com/user-attachments/assets/0b8af467-60db-493b-95a3-c73dce7c345e)

**Comment by TingPing** [comment]
Updated.
