### ISSUE TITLE
Pithos stops playing after an indiscriminate period of time

### ISSUE THREAD

**Issue by Techspectre** [pithos/pithos#85]
The player remains open but the music stops playing and won't continue playing until you change the channel. Sometimes happens after a day or two days, sometimes happens after two hours. No rhyme or reason to it. Brought the issue up on #pithos at freenode, determined it's a login expiration issue. Is there a way we can get the client to auto re-login? 

Here is the output:

http://pastebin.com/x0xDg1fV

As a temporary solution I employed crontab and had it execute "killall pithos && pithos" on an hourly basis, and that works because it forces the re-login, but that solution has suddenly stopped working and crontab is no longer killing pithos so I'd like to see if we can find the real problem.

**Comment by gregsheremeta** [comment]
We haven't seen other reports of login timeout issues. We did just fix a deadlock bug, #94 .

Please reopen if you have further issues.
