### ISSUE TITLE
python-keybinder dependency missing for < 1.0.0

### ISSUE THREAD

**Issue by psycho23** [pithos/pithos#92]
In versions 0.3.17-1 (saucy) (from regular Ubuntu repositories)
and 0.3.18-4~gitdf24f17 (from PPA)
I get this error: ERROR:root:Could not bind media keys
and the media keys on my laptop don't function.

What do I do?!

I'm using 64-bit OS.

I actually have two keyboards. One is the laptop that does have media keys. One is USB, which doesn't have media keys.

**Comment by gregsheremeta** [comment]
We're not going to support 0.3.18, so closing. Please upgrade to the latest release. Thanks!
