### ISSUE TITLE
Application menu takes up extra space on most desktops

### ISSUE THREAD

**Issue by MarkLodato** [pithos/pithos#95]
On any window manager other than Gnome 3 or Unity, the new GTK3 "Pithos" menu takes up an extra line and is really space inefficient.  Please bring back the old gear icon for non-Gnome-3 WMs.  (If I used Gnome 3 or Unity, I'd still prefer the gear to having to find the menu in the upper left, but I don't actually use those WMs so I don't really care about them.)

![pithos_1 0 0_menu](https://cloud.githubusercontent.com/assets/58860/2874003/ac9ca022-d3cc-11e3-828a-abb8f1721ddd.png)

**Comment by TingPing** [comment]
This menu no longer exists.
