### ISSUE TITLE
Missing dependencies Ubuntu 14.04 PPA

### ISSUE THREAD

**Issue by JasonLG1979** [pithos/pithos#98]
It may not be an issue with every other derivative as the missing dependencies may already be installed, but in Kubuntu 14.04 if you install from the PPA there will be no icons in the main window or album covers.

The missing packages are:
python3-gi-cairo (needed to show album covers)
gnome-icon-theme-symbolic (needed for icons)

**Comment by gregsheremeta** [comment]
Fixed in https://github.com/gregsheremeta/pithos-debian-package/commit/333c4ab5baad39981a0c7c3b512716237ec0e1b7
